### ISSUE TITLE
What sparked your interest in Angular?

### ISSUE THREAD

**Issue by Stephn-R** [kentcdodds/ama#10]
Also, do you still contribute to the AngularJS project?

**Comment by kentcdodds** [comment]
Originally, it was my work at Domo (discussed in #1). Specifically, when @geddski and @aaronfrost came on and encouraged us to use Angular, that's when I got into it. Dave Geddes gave us a quick demo using his [ng-workshop](https://github.com/geddski/ng-workshop) repo (which I have [forked](https://github.com/kentcdodds/ng-workshop) and [used](https://www.youtube.com/watch?v=GmVUw_Efi_M) [several](https://github.com/kentcdodds/talks#intro-to-angularjs-1) [times](https://github.com/kentcdodds/talks#intro-to-angularjs)). I was young and wowed by the two-way data binding and declarative style (though I had no idea what declarative meant at the time... and sort of still don't). Once we decided to move from backbone to Angular, I went all in (for more info, see #1).

As for contributing to the Angular project, you can find all my contributions [here](https://github.com/angular/angular.js/issues?utf8=%E2%9C%93&q=kentcdodds+). (Specifically, all my commits [here](https://github.com/angular/angular.js/commits?author=kentcdodds)). For a while, I did this thing called [#angularissueoftheday](https://twitter.com/kentcdodds/status/591627180834066432). I should pick that back up again. I help where I can, but I wouldn't consider myself a major contributor to the core project.

I should note that contributing to Angular doesn't have to be contributing code. Find out more in this Angular Air episode: [Contributing to Angular](https://www.youtube.com/watch?v=GOjeLhL0Uy4)

**Comment by kentcdodds** [comment]
Thanks for the question!

**Comment by Stephn-R** [comment]
Awesome! Thanks for the insight @kentcdodds. :smile:
