### ISSUE TITLE
What is your favorite temple?

### ISSUE THREAD

**Issue by joeeames** [kentcdodds/ama#101]

**Comment by kentcdodds** [comment]
Definitely [Mount Timpanogos](https://www.lds.org/church/temples/mount-timpanogos-utah). It's where I was married and sealed forever and stuff :-)

![mount-timpanogos-utah-808x480-cwd_436f96b6](https://cloud.githubusercontent.com/assets/1500684/14325523/f2994e4c-fbe6-11e5-9438-0f6851d20dc9.jpg)

**Comment by joeeames** [comment]
I was almost married in there, but ended up doing it in Portland instead.
