### ISSUE TITLE
Trump or Hilary?

### ISSUE THREAD

**Issue by joeeames** [kentcdodds/ama#102]

**Comment by kentcdodds** [comment]
Neither. If that's the lineup, I think I'll not vote or write someone in or something. Totally crazy we may actually have to pick between those two. This is the best our country has to offer by way of leaders? No way. Our system's messed up!

![muppets-annoyed-vwI4mYEHP8k0w](https://camo.githubusercontent.com/7cee9008ec760e118f64065692c7b639e735196d/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f767749346d59454850386b30772f67697068792e676966)
