### ISSUE TITLE
What are your thoughts on JS fatigue?

### ISSUE THREAD

**Issue by joeeames** [kentcdodds/ama#105]

**Comment by kentcdodds** [comment]
Hey @joeeames,
I'm fatigued by hearing/talking about fatigue! Haha, but in all seriousness I understand where people are coming from. I'm not bothered by all the choices, but I can understand that for people who just want to get things done the choices are frustrating. Though I think JS fatigue is more than just choices, but also tool immaturity. I think that in the coming year or two we'll see our tools mature and people can stop complaining (hopefully).

Though, the fact is that things are moving fast in this space and I love it. I love having tons of choices and opportunities to contribute. It keeps me motivated :-)

If people are frustrated by living on the edge, they can step away for a moment. I hear `jsp`s still work as well as they always have ;) JKJKJK! I know it's not that simple :-)

Anyway, there are some random thoughts for you.
