### ISSUE TITLE
Poe, Finn, Rey or Kylo Ren?

### ISSUE THREAD

**Issue by joeeames** [kentcdodds/ama#106]

**Comment by kentcdodds** [comment]
Hey @joeeames,
I'm a terrible person. I haven't seen it. As much as I love Star Wars, a few years ago I put a hard rule on myself that I wont watch PG-13 movies. It's not that I trust the MPAA rating system, but by watching PG-13 movies, I have about 50% chance that I'll see something inappropriate (violence, language, nudity, etc.). Whereas if I limit myself to PG movies I only have a ~90% chance of that. These are, of course, made up numbers, but I think you get the idea.

I hear that Rey totally kicked Kylo's trash in the movie though, so I'd have to go with Rey :-)
