### ISSUE TITLE
What hardware/software do you use for recording your egghead.io lessons?

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/ama#107]
Yeah, I know... I'm asking myself a question... Kinda weird. But people have asked me this verbally so I just decided to answer it here :-)

**Comment by kentcdodds** [comment]
Here's the hardware (in order of connection):

1. [Heil PR-40 Dynamic Studio Recording Microphone](http://amzn.com/B000SOYOTQ)
2. [Heil Sound HB-1 Steel Microphone Boom](http://amzn.com/B004PJ414I)
3. [Rapco Horizon N1M1-15 Stage Series M1 Microphone Cable Neutrik Connectors](http://amzn.com/B003Y580QY)
4. [DBX 286s Microphone Pre-amp Processor](http://amzn.com/B004LWH79A)
5. [Mackie Onyx Blackjack 2x2 USB Recording Interface](http://amzn.com/B003VZG550)

For recording software, I just use [Screenflow](https://www.telestream.net/screenflow/) from telestream. I really like it a lot. Some other egghead instructors use [Adobe Premier](http://www.adobe.com/products/premiere.html) which I'm sure is good (I used it years ago in a [past life](https://www.youtube.com/watch?v=KTjNhpUWe_s)).

This stuff works really well for me. Here's a picture of my nobs on the pre-amp and interface:

![img_20160411_141643](https://cloud.githubusercontent.com/assets/1500684/14441146/a38e5686-fff0-11e5-8214-9f362ebbaf52.jpg)

![img_20160411_141700](https://cloud.githubusercontent.com/assets/1500684/14441147/a4f5a7fe-fff0-11e5-93dc-acc04fb786dc.jpg)

To be perfectly honest, I have no idea, but it sounds pretty good when I do it like this. I just copied @tylermcginnis.

I hope this is helpful to someone!

**Comment by kentcdodds** [comment]
Also, I recommend you give this article a look: https://egghead.io/articles/recording-a-great-coding-screencast

**Comment by kentcdodds** [comment]
You may also want to checkout a Screencast that I made about creating screencasts :-) http://kcd.im/screencasting

**Comment by kentcdodds** [comment]
There's also now an official course on Egghead about this too: https://egghead.io/courses/record-badass-screencasts-for-egghead-io

**Comment by bradydowling** [comment]
Making my way through all these resources right now 👍 

> Also, I recommend you give this article by @johnlindquist a look: https://egghead.io/articles/recording-a-great-coding-screencast

There's a link in there to https://instructor.egghead.io/ which looks like it's deprecated.

**Comment by kentcdodds** [comment]
Here's an update on my setup. I've removed the pre-amp because I don't think it was helping. And instead got a [Cloud Microphones CL-1 Cloudlifter 1-channel Mic Activator](http://a.co/jjW33EF).

It's great and much simpler.

![mvimg_20180214_152808](https://user-images.githubusercontent.com/1500684/36231616-e70e6bc6-119b-11e8-9da8-19604874cf13.jpg)

**Comment by tylermcginnis** [comment]
I removed the preamp about 6 months ago as well 😂

**Comment by kentcdodds** [comment]
I should add to this that I livestream using open source software called [OBS](https://obsproject.com/). There are a million youtube videos explaining how to use this software. Good luck!
