### ISSUE TITLE
Is Twitter down for you too???

### ISSUE THREAD

**Issue by BarryThePenguin** [kentcdodds/ama#108]
At 3:00 am Thursday, (UTC)

![screencapture-twitter-com-1460602885355](https://cloud.githubusercontent.com/assets/1351912/14515873/1f85054e-0241-11e6-97e6-6c8e34c13f1a.png)

**Comment by kentcdodds** [comment]
Yes!!!

![screenshot_20160413-210404](https://cloud.githubusercontent.com/assets/1500684/14515915/593c1998-01bb-11e6-9eaa-2757d74b5706.png)

**Comment by BarryThePenguin** [comment]
The Internet is so quiet! I didn't know what to do so I opened this issue 😭

I needed to tell sombody
