### ISSUE TITLE
When is there a need for a react application to use flux/redux etc?

### ISSUE THREAD

**Issue by spylefkaditis** [kentcdodds/ama#109]
Is there anything wrong with fetching data directly from componentDidMount and saving it to the state if that data isn't being shared amongst different components?
For example if a view simply lists a list of users, and that list isn't shown anywhere else in the app, is there a need to save it to a store?

**Comment by kentcdodds** [comment]
Hi @spylefkaditis!

Thanks for the questions! It's interesting that there was [a twitter thread](https://twitter.com/dan_abramov/status/725089243836588032) about this just today! Here are some of my takeaways:

- `state` is not evil
- `redux` is awesome, but not necessary for all applications
- Fetching data directly from `componentDidMount` is fine, caching is [easy](https://twitter.com/ryanflorence/status/725065972000894976)

> For example if a view simply lists a list of users, and that list isn't shown anywhere else in the app, is there a need to save it to a store?

So, you definitely get a lot of benefits by using `redux` to hold ALL of your state, but it also can be a bit of overkill. One of the benefits is how easy it is to debug. I've experienced this first hand. It's really nice to have all state transformations in a single place.

> "The secret to building large apps is never build large apps. Break your applications into small pieces. Then, assemble those testable, bite-sized pieces into your big application" -Justin Meyer

When you build something with a single global Redux store, it's pretty much impossible to break your application into small pieces. Everything is now dependant on this single source of truth for data. This is beneficial in many ways, but it comes with tradeoffs.

I hope this is helpful! Good luck!
