### ISSUE TITLE
How do I get into giving talks?

### ISSUE THREAD

**Issue by SomeKittens** [kentcdodds/ama#11]
So far, I've given a lot of private lectures at a bootcamp and one public talk that was fairly well-received.  I want to give more.  Wat do?

Should I start off making more local meetup connections and applying to conferences when I've got a handful of meetup talks under my belt?

How much of a talk do you write out before submitting the proposal?  The outline?  Slides?  Everything?

How do you find RFS?  What rejection rate should I expect?

**Comment by kentcdodds** [comment]
> Should I start off making more local meetup connections and applying to conferences when I've got a handful of meetup talks under my belt?

Yes: speak at meetups often. Most of [my talks](https://github.com/kentcdodds/talks) are [at meetups](https://github.com/kentcdodds/talks#meetup-talks). I've made relationships with the organizers of local meetups and they know that I'm happy to give a talk at the drop of a hat (which I did for [my last talk](https://github.com/kentcdodds/talks#es6-webpack-karma-and-code-coverage)). This puts a lot of pressure on me to keep track of what I'm learning and figure out ways to take that and make a talk about of it.

I'd definitely make sure you feel comfortable talking in front of people. But if you do already, there's no reason you can't just apply to conferences. Just write up a good proposal (or several) and submit. There's no harm in that. Then, if you're selected, prepare like crazy so it's awesome and a good experience for everyone.

> How much of a talk do you write out before submitting the proposal? The outline? Slides? Everything?

It depends on the talk. Some talks I propose for conferences I have given a time or two (like [this one](https://github.com/kentcdodds/talks#intro-to-angularjs)), while others I have little to no experience with (like [this one](https://github.com/kentcdodds/talks#using-reactjs-with-existing-angularjs-codebase), but make sure that you at least know it's possible). If it's something I'm interested in and think I can pull off, then I propose it. If I get selected, then I work really hard to make it amazing.

> How do you find RFS? What rejection rate should I expect?

About a year ago, I was looking for good ways to know of conferences looking for speakers. I found a few good resources: [@calltospeakers](https://twitter.com/calltospeakers), [@devcfp](https://twitter.com/devcfp), [Lanyard JavaScript Conferences calendar](http://lanyrd.com/topics/javascript/javascript.ics) (just go out a few months). Also, ping people on twitter and ask them what conferences they like to go to/speak at. You could look at my talks repo for a list of the ones I've gone to/spoken at.

Thanks for the question! Good luck on your talks!

**Comment by kentcdodds** [comment]
Oh, by the way, this talk by @r00k totally changed my speaking style

[How to Talk to Developers](https://youtu.be/l9JXH7JPjR4)

**Comment by douglas-mason** [comment]
That talk is really cool.  Thanks for sharing!
