### ISSUE TITLE
Configuring Aurelia Skeleton Navigation (ES6/Webpack) project for Code Coverage

### ISSUE THREAD

**Issue by mattduffield** [kentcdodds/ama#112]
Hi Kent, 

I have seen several of your presentations and I was wondering if you would mind helping me getting an Aurelia sample configured for code coverage?

Here is the link to the repo for the Skeleton Navigation project.  I have tried but so far I have not been successful with the sample repo to get code coverage working.

https://github.com/aurelia/skeleton-navigation

The only one I am interested in is:  skeleton-es2016-webpack

Thanks in advanced and if you are too busy I understand,

Matt

**Comment by kentcdodds** [comment]
Hi @mattduffield!

Thanks for the question. I should start by stating that I've never used Aurelia. But I'm assuming that you could probably learn lots of what you need from [this project](https://github.com/kentcdodds/es6-todomvc) I've used for [my es6 workshop](http://slides.com/kentcdodds/es6-workshop).

Specifically, check out the fact that the [`.babelrc`](https://github.com/kentcdodds/es6-todomvc/blob/0c1b0afe31bad4713c51f6485cd616730e4ede8b/.babelrc#L3-L9) uses [`babel-plugin-__coverage__`](https://npmjs.com/package/babel-plugin-__coverage__) and we're setting `NODE_ENV=test` in [the `test` script](https://github.com/kentcdodds/es6-todomvc/blob/0c1b0afe31bad4713c51f6485cd616730e4ede8b/package.json#L32)

Good luck!
