### ISSUE TITLE
Mastering DataStructures and Algorithms for a JS programmer.

### ISSUE THREAD

**Issue by atishaybaid** [kentcdodds/ama#114]
Should a web javascript programmer consider mastering the data-structures such as linked-list,trees,maps,graphs etc. and having a good command over algorithms. Will these be useful in career advancements?
And is JavaScript appropriate language for implementing algorithms,or we should consider some language as c/c++?

**Comment by kentcdodds** [comment]
Hey @atishaybaid!
Thanks for the question! I should preface my answer by saying that I have very limited experience/exposure to classical Computer Science Data Structures and Algorithms. I took a few CS classes in college, but graduated in Information Systems where I focused more on actually building things.

So I think that sort of answers it from my perspective. I'm sure that I could be a more effective programmer with that knowledge, but I'm not sure I'm missing out.

> Will these be useful in career advancements?

I recently interviewed at Facebook and they didn't ask me a single question about these types of things. What I got was stuff like: "Write `debounce`" and "How would you build/architect a pinterest-type layout?" I feel like most places are learning that practical interviews are better.

> Is JavaScript appropriate language for implementing algorithms,or we should consider some language as c/c++?

I would expect that it'd be an interesting exercise to implement these kinds of things in JavaScript. I don't think that you'd be limited by the language to learn this kind of stuff. :+1:

Thanks for the question!
