### ISSUE TITLE
Do you have (or know of) a comprehensive list of JavaScript/Develope/Front-end Conferences?

### ISSUE THREAD

**Issue by DavidWells** [kentcdodds/ama#115]
Was just watching your talk from ForwardJS. 

Great stuff as per usual!

At [the 26minute mark](https://youtu.be/-qPh6I2hfjw?t=26m25s) you mention a couple places to look for JS conferences.

You wouldn't happen to have a list of these conferences handy would you?

Many thanks
David

**Comment by kentcdodds** [comment]
Hey @DavidWells!

Thanks for the question. I actually answered it inside [this question](https://github.com/kentcdodds/ama/issues/11) a while back. The list is:

- [@calltospeakers](https://twitter.com/calltospeakers)
- [@devcfp](https://twitter.com/devcfp)
- [@CallbackWomen](https://twitter.com/CallbackWomen)
- [Lanyard JavaScript Conferences calendar](http://lanyrd.com/topics/javascript/javascript.ics) (just go out a few months)

Also, if you're interested, [javascriptair.com/deals](https://javascriptair.com/deals) has a few conferences on there with some sweet discounts :-)

Good luck!

**Comment by kentcdodds** [comment]
Here are two more resources:

- [The Weekly CFP](http://theweeklycfp.com/)
- [prigara/javascript-conferences](https://github.com/prigara/javascript-conferences)

**Comment by DavidWells** [comment]
Also see: https://github.com/coryhouse/speaker-starter-kit#how-do-i-find-out-about-cfps-calls-for-presenters
