### ISSUE TITLE
Front end tools and http2

### ISSUE THREAD

**Issue by brenoc** [kentcdodds/ama#116]
Hey, I was wondering what's your opinion on the front-end tools today, like webpack and browserify.

I feel like they are not evolving to the http2 paradigm, since bundling everything (or using require.ensure) is not preferable in this scenario.

The question is: why do you think the community is not watching or not developing solutions to substitute module bundlers or pushing SystemJS forward in favor of http2?

**Comment by kentcdodds** [comment]
Hi @brenoc! Thanks for the question. I think that @iam-peekay addresses this really well in [her blogpost](https://medium.freecodecamp.com/javascript-modules-part-2-module-bundling-5020383cf306#.8smjuvmst) (look for the section about `HTTP/2` :smile:). I agree with her 100%. I'll probably be using a bundler for many years to come.

**Comment by brenoc** [comment]
That's a great read. Thanks!
