### ISSUE TITLE
JS on the side

### ISSUE THREAD

**Issue by neomaxzero** [kentcdodds/ama#117]
First of all, thank you very much for your javascriptair project. I found it incredible awesome while going  work or so. 
I found my self having a hard time learning JS on my own. I think having a tutor would really make a difference. The problem is that i am not sourrounded of JS devs (Yet). Would you recommend me to keep trying on my own? or how can I achieve a boost in my learning experience while having just time after works?

Thanks in advance!

**Comment by kentcdodds** [comment]
Hi @neomaxzero!
Thanks for the question. It's actually similar to what I answered [here](https://github.com/kentcdodds/ama/issues/89). Let me know if you have anything more specific that I don't answer there :-)
