### ISSUE TITLE
How do you setup automatic linting, builds, etc for PRs on your open source projects?

### ISSUE THREAD

**Issue by DevanB** [kentcdodds/ama#118]
Hey!

I've been perusing around, and haven't found anything you have written about how you setup your open source repositories. More specifically, I'm curious how you handle when an individual submits a PR and you do a build (run tests), any linting, any other tasks, and display the results.

A list of resources would be great, or I'm even patient enough to wait on a blog post :)

Keep up the great work Kent!
-Devan

**Comment by kentcdodds** [comment]
Hey @DevanB!
Thanks for the question! I've actually documented the whole process fairly comprehensively in my Egghead.io course: [How to Write an Open Source JavaScript Library](https://egghead.io/series/how-to-write-an-open-source-javascript-library). It's totally free and pretty accessible. Let me know if you have any questions that doesn't answer :-)
