### ISSUE TITLE
How do I get community feedback or find a mentor?

### ISSUE THREAD

**Issue by marcusnielsen** [kentcdodds/ama#119]
Hi Kent,
First of all, I think I gave you some hasty written feedback on one of your presentations. Thinking back I think the way I wrote the feedback came of in a bad way. I'm very sorry if it did!

My question is about getting help from the community. I feel like it's really hard to get mentorship and help on personal projects. I've gotten one person to get some good feedback on the RxJS-part, but otherwise it's just hard to get responses from Gitter chats and such.

So here's my project: https://github.com/marcusnielsen/reserve

It's a medium-sized 3-part project. I'm using RxJS heavily, React on the frontend, ported from node-tap to Ava, included some services such as Travis-ci and Coveralls (not yet up again after refactor though).

But i feel like I might need to restructure the project to make it easier to grasp.

So my question is in two parts: How do I make my project more accessible for others? And how do I get more feedback from the developer community or find a mentor for specific issues?

**Comment by kentcdodds** [comment]
Hi @marcusnielsen!

Thanks for the question and cool project. :smile: Have you seen [this talk](http://kcd.im/1st-pr-video)? I talk about how you can make your project easier for new user users. I'm also preparing to give a talk called ["Managing an Open Source Project"](https://github.com/kentcdodds/talks/tree/7640c2657beb7cf7eec684f534bd0e6979d293c7#managing-an-open-source-project) at [SpaceCityJS](http://spacecity.codes/) this month which I think could answer your question directly. [Here's a practice run](https://youtu.be/jKI1Kj5VXqE).

Let me know what you think and if you have any more questions!

**Comment by marcusnielsen** [comment]
Wow, that SpaceCityJS talk was awesome!
I really got good material, and will try to boost my project up a level. Still though... I guess I'm just worried as a beginner intrapreneur that I'm not seeing the whole problem and might miss what direction would be good for a project like this. But I think time will tell, and the journey will be the goal for ReServe until I find more handson 2-way mentorship.

Just this feedback from you makes a lot of difference! <3
