### ISSUE TITLE
Greatest tip for programmers looking to make an impact

### ISSUE THREAD

**Issue by Stephn-R** [kentcdodds/ama#12]
What would you tell a junior dev who is trying to aspire to become great. Like perhaps a Dev Advocate, a speaker, or anything.

**Comment by kentcdodds** [comment]
I remember talking with @geddski and @aaronfrost when I was at Domo about how much I wanted to be the best. They are both a great inspiration to me. They both encouraged me to just "keep doing what you're doing."

What I was/am doing was/is coding, a lot. I build projects and libraries whenever I want to solve a problem. Once I build something in a project, I try to find things in the project I can extract into a standalone library. I use that library to try out new tools (like grunt, gulp, webpack, etc.). Always learning and trying new things is good. Try to identify the things you want to go deep in on (like I have done with Angular and webpack). Avoid being a jack of all trades, master of none, but expose yourself to as much as you find interesting.

I have also forced myself into conversations with more experienced developers wherever I work (earlier on, I was mostly just a listener). I'm not afraid to ask questions and get into architecture/design conversations and talk about best patterns and practices. Lots of those conversations I had were with @jargv, @jinxidoru, @peanav, @iammerrick, @joeeames, @lund0n, and @mzabriskie. These developers are way cool and it was a pleasure to work with them all.

If you're on a smaller team or something and don't work with a lot of amazing developers you can have conversations like this with, then I highly recommend getting active on Twitter, GitHub, StackOverflow, IRC, Gitter, and Slack. These are fantastic places with some really smart people you can learn from.

Also, check out what I say about getting into speaking in #11. Getting into speaking is a great thing to do :-)

Finally, I was what you might call a "junior dev" just a year ago. In this industry, things are changing so rapidly that there's plenty of room for fresh blood. Don't put yourself in a box. Don't let others put you in a box. [You don't need a badge to be awesome](https://www.youtube.com/watch?v=hYXEuQZMLSM).

---

A word of caution. Don't give up having meaningful relationships to become "the best." No success outside the walls of your home and family is worth failing at those relationships. Find a balance, and you'll be much happier.
