### ISSUE TITLE
How do you find your gifs?

### ISSUE THREAD

**Issue by jfmengels** [kentcdodds/ama#121]
(Man, so surprised nobody asked the question yet)

Do you have any tips on finding gifs? I know you love them, and I find it pretty effective to welcome people who submit issues/PRs (among other uses).
Thanks in advance :)

**Comment by kentcdodds** [comment]
Haha!
It's not too hard thanks to @DrewML's amazing [GifHub](https://github.com/DrewML/GifHub):

https://chrome.google.com/webstore/detail/gifhub/lponagpckglibniamicamklhfkoebpeb?hl=en

![shaun-the-sheep-movie-not-my-gif-2016-oscar-nominations-tIeCLkB8geYtW](https://camo.githubusercontent.com/09b6d44863f23bed3630cd8017c214c5d7844b97/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f744965434c6b423867655974572f67697068792e676966>)

**Comment by jfmengels** [comment]
![youngertv-younger-hilary-duff-sutton-foster-26AHPsUxd2N1bjPsQ](https://camo.githubusercontent.com/67ba3cda959a3d567d5b248e144b95357e0fe74c/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f323641485073557864324e31626a5073512f67697068792e676966>)
