### ISSUE TITLE
Mocking 3rd party propriatary API for JavaScript Unittesting

### ISSUE THREAD

**Issue by con-ssc** [kentcdodds/ama#122]
How can I mock a 3rd party API that has a nested structure? I'm working with MS Dynamics Crm a lot and I want to test the so called form scripts before I deploy them. All mocking frameworks for JavaScript only handle 2 levels of objects but I have calls like
 ```javascript
Xrm.Page.getAttribute("name").getValue();
```
I tried sinonjs and testdoublejs as well. I was told if I try that I would violate the rule of demeter, But I cannot change the API.

**Comment by kentcdodds** [comment]
Hi @con-ssc,
I'm super sorry that it's taken me forever to get to you on your questions. I just lost track of them and whenever I remembered I didn't have time to give you an answer.

For your specific example, I'd need more information about how your testing environment is set up. But in general, I'd normally recommend using [`sinon`](http://npm.im/sinon) (as you indicated) or [`proxyquire`](http://npm.im/proxyquire).

You might also consider wrapping that third-party API in your own utility function. Then use that throughout your code and you can stub out your implementation in your tests. This is a pretty good practice normally anyway.

Good luck!
