### ISSUE TITLE
What is your opinion on the so called SoftwareCraftmanShip?

### ISSUE THREAD

**Issue by con-ssc** [kentcdodds/ama#124]
What is your opinion on the so called SoftwareCraftmanShip? I already saw that someone was asking for resources or mentor on how to learn React if I recall correctly. What do think about those ideals?

**Comment by kentcdodds** [comment]
Hey @con-ssc,
Let me make sure I understand your question. By "SoftwareCraftmanShip" do you mean ["Software craftsmanship"](https://en.wikipedia.org/wiki/Software_craftsmanship)? Or are you referring to something in particular?

If you're referring to the concept of craftsmanship as a software developer then I think it's important. I spend a great deal of my time learning and developing my craft. I think it helps me build more maintainable/testable/functional systems. I think this is an important part of software development.

Let me know if you meant something else entirely :-)
