### ISSUE TITLE
Javascript Interfaces

### ISSUE THREAD

**Issue by gh-amistry** [kentcdodds/ama#126]
Hi Ken, I was reading up on the factory design pattern in [Pro JavaScript Design Patterns] (http://www.amazon.com/Pro-JavaScript-Design-Patterns-Object-Oriented/dp/159059908X), and in it, the author makes extensive use of an interface as part of its implementation. What do you think about interfaces and their use (creation, emulation, etc.) in JavaScript?

Thanks!

**Comment by kentcdodds** [comment]
Hi @gh-amistry! Thanks for the question,

To be honest, I've never used interfaces in JavaScript. And I remember seeing Java codebases that had interfaces with a single implementation and I never quite understood what the value of the interface was in that scenario. It seems to be overkill to me.

In TypeScript, I know that you can define interfaces and get compile-time errors which could definitely be helpful. But in raw JavaScript I don't even know how you'd create an interface... I suppose you could do run-time checking, but I don't really see the value there...

Good luck!

**Comment by marcusnielsen** [comment]
(I hope I'm not trespassing here, but just wanted to add my fanboy view of interfaces.)

I would say that anything that describes the usage of an API/object/function/thing is a "contract" between a consumer and a provider. That can be formalized explicitly. I would then call it an interface.

A normal way to provide interfaces for me in JS code is like in this component: https://github.com/marcusnielsen/reserve/blob/master/common/src/components/connection/index.js

Note that the only file in that directory to import/require any external modules is the index.js. That provides an explicit contract/interface of what modules it depends on. So if you copy and paste that folder and do npm install on rxjs and react, you know you have everything you need to use the code.

Also, both the exported object (a factory called create), and the create function return objects with just keys and no inline code. This is to make it easier for you to note what the public API will look like without cluttering the API with implementation details. This will lessen the cognitive load for contributors scanning through your code.

Another use case I had when using angular with less (css-precompiler), was that I had a variable-file that converted global variables into component variables. By gathering those global variables in one place, it's much easier to refactor your global less-code and know what it impacts than if the globals were spread out all over the component.

Consider using interfaces as a pretty wrapped box that makes a contributor go: "Oh, how lovely" before even knowing what's inside :-)

**Comment by kentcdodds** [comment]
Hey @marcusnielsen,
I think that there may be a difference in our interpretation of the word `interface`. I was thinking more traditionally with Java/TypeScript. I'm a big fan of having explicit interfaces as you describe :-)

**Comment by gh-amistry** [comment]
@kentcdodds I think what @marcusnielsen describes is what I was referring to. In Java, it's very explicit; you have an `interface` files that `implement` classes. In JavaScript, it's not explicit and needs to be emulated. It's definitely useful, in my opinion. I'm just wondering how common it's used in practice. Thanks!

**Comment by kentcdodds** [comment]
Great. Glad to find us all on the same page now :-) I'd say what we're talking about is a pretty common practice. Many libraries and utilities that I've seen do this.

As for enforcing that something conforms to an interface, that's less common. But React's `propTypes` allows you to do this with your components and [`webpack-validator`](http://npm.im/webpack-validator) does this for your webpack config. Unless you can use ESLint or TypeScript/Flow, you'll have to do run-time checking.

**Comment by marcusnielsen** [comment]
Words; Many of them are confusing. Too few of them, and it gets even more confusing! :-)
