### ISSUE TITLE
Angular Formly with SQL Server back-end

### ISSUE THREAD

**Issue by KermitCoder** [kentcdodds/ama#129]
Hi Kent,

I am new to Angular-Formly but have been given the green light at my company to go ahead and start learning/developing CRUD forms that use SQL Server 2012 tables, stored procs, etc. Can you please direct me to a good walkthrough or example on this? In the meantime I am installing Angular 1 and planning on moving forward with replacing our current ASP.NET 4.5 web forms with the Angular forms.

Thanks in advance,
Bruce

**Comment by kentcdodds** [comment]
Hi @KermitCoder,
Thanks for the question. In general, angular-formly will only be concerned with a small slice of the entire thing you're trying to accomplish. For that slice, I recommend you check out the resources at http://learn.angular-formly.com

Good luck!
