### ISSUE TITLE
Build process + minified files

### ISSUE THREAD

**Issue by dbabaioff** [kentcdodds/ama#131]
I have a big JavaScript project which uses a lot of different libraries like jquery, angular, lodash, ...
On our dev environment we use the uncompressed version of those libraries and for production we minify using uglifyJs with the compress and mangle  options. After some time I compared the minifed version of these libraries we generate and the minified version from the vendors (like jquery angular), and from the vendors are smaller. 
From your experience should we keep 2 versions of the libraries one minified (production) and one not (dev) and the build script only include those or the build should minify? I'm asking because I assume each library have custom options for minification based on the library, and my options are general for all the libraries which probably the size will be bigger

Thanks!

**Comment by kentcdodds** [comment]
Hi @dbabaioff! Thanks for the question!

Here's my take on it: avoid pre-optimization. Do whatever is simplest first, then measure, then optimize. My guess is that the difference between your minified version of these libraries and their own minified versions is fairly minimal (no pun intended). I'm surprised there's a difference at all to be honest.

But in any case, complexity comes with a cost and you need to make sure that you're outweighing that cost with benefit. So before you add complexity, make sure that the benefit is worth it.

Right now you can pretty well measure the difference it would make (in bytes), and as I said, I'm assuming that difference is fairly small. So I would recommend not adding any complexity to your build system to compensate for such a small difference.

I hope that's helpful! Good luck!
