### ISSUE TITLE
Getting good with design a product/website

### ISSUE THREAD

**Issue by vgvenkat** [kentcdodds/ama#134]
Hi Kent,

I have followed your course through egghead and on twitter, much appreciation. I am a web developer, I am competent in building things in code from specs, psd/ sketch files. When I try to come up with my own design for web apps I want to build with colors, typography, font size, deciding which element should go where, adding interaction animations I hit roadblocks. I spend hours coming up with something which I would have coded in just 10 mins if I had the design given to me.

How do you approach designing your own products when you have good coding chops but not much design?

**Comment by kentcdodds** [comment]
Hi @vgvenkat!

I'm in the same boat as you! I'm pretty good at taking a design spec and making it a reality with the web, but coming up with one myself is a nightmare (I mean, just look at [my website](https://kentcdodds.com)  !)

So, how do I approach designing my own products? I generally just use an existing CSS framework like Bootstrap or something. I'm just not a good designer. It's really too bad.

Sorry that's not very helpful!

**Comment by vgvenkat** [comment]
Hi @kentcdodds 

Thanks for the reply. I have been thinking about this for some time time now and have learnt it is ok if my designs suck. I will probably learn some more design and iterate on it.

Here is a [youtube video](https://www.youtube.com/watch?v=IalgBQQKROU) of [Travis neilson](https://twitter.com/travisneilson) speaking on this topic. He also puts out amazing content 👌

**Comment by marcusnielsen** [comment]
@vgvenkat I used https://bootswatch.com/ a lot for small/internal projects. You can then try out different look and feels as long as you conform to bootstrap styled css. You can even do a dropdown menu and change the theme on the fly if you want to.
