### ISSUE TITLE
Angular or React

### ISSUE THREAD

**Issue by anirudh-modi** [kentcdodds/ama#135]
Hi,
I am a beginner JS developer, still trying to understand JS properly, however, I want to keep myself updated and want to learn a framework, however, I am confused in between angular and react what should I learn? 
So it will be very helpful, if you can give some pointers. 
And lastly, a huge thumbs up for helping out the beginners like me. Really inspires and motivates,to take a step towards contributing to the community and become a better developer.
Thanks,
Anirudh

**Comment by kentcdodds** [comment]
Hi @anirudh-modi!
Thanks for your question. The frontend world can be pretty overwhelming for sure! So much to learn and try to consume. So I get this kind of a question quite a bit. I think the answer to [this question](https://github.com/kentcdodds/ama/issues/89) should help you out. Specifically for your question though, I personally prefer React over Angular. But I would say you should try to follow the Hello World example from the docs for both projects and pick the one that makes the most sense to you. I should also say that I wouldn't recommend learning Angular 1. If you want to do Angular, try Angular 2.

Good luck! Let me know if you have any follow-up questions.

**Comment by anirudh-modi** [comment]
Thanks for the response.

**Comment by anirudh-modi** [comment]
I have earlier went through your talks and the answer which you have linked. I really feel motivated to do contribute towards open source.

When can we expect react30 to be on air? :)

**Comment by kentcdodds** [comment]
Should be really soon! Waiting for the iTunes feed to be approved before the official announcement, but you might be interested in: http://react30.podbean.com/ and https://www.youtube.com/channel/UCnyD10-edZmVsplCrF9eA6Q :-)

**Comment by anirudh-modi** [comment]
Awesome!
Thanks for early link :D
