### ISSUE TITLE
How do you style child element with Aphrodite based on parent's pseudo state? 

### ISSUE THREAD

**Issue by Dajust** [kentcdodds/ama#136]
@kentcdodds Great work on Aphrodite! I'm totally sold to  Aphrodite by the ability to

> "Supports pseudo-selectors like :hover, :active, etc. without needing to store hover or active state in components."

 I often style my child element based on the parent's  pseudo state? For example, to display  say a "Delete" button that was hidden on a given item. I usually do...

Using pure CSS:
```
.myItem:hover .delete-button {
  display: inline-block;
}
```
Or SASS

```
.myItem{
  &:hover{
   .delete-button{
      display: inline-block;
   }
  }
}
```

So when you hover over `.myItem` the `.delete-btton` shows up. Please, Is there a way to accomplish similar stuff on Aphrodite? 

Thanks again for Aphrodite!

BTW. I'm just arriving to the SPA world using React as landing point. Any other styling tips would be more than welcomed.

**Comment by kentcdodds** [comment]
Hi @Dajust!
Thanks for your question. First, just to be clear, I didn't create aphrodite and I'm not a part of Khan Academy. I'm just a happy user of the library :-)

As for your question, it's actually a [known issue](https://github.com/Khan/aphrodite/issues/10) that's got [an interesting workaround](https://github.com/Khan/aphrodite/issues/10#issuecomment-151932496) and is being [worked on](https://github.com/Khan/aphrodite/pull/61).

I hope that's helpful! Also, welcome to the wonderful world of SPAs!
