### ISSUE TITLE
What are your thoughts on TDD?

### ISSUE THREAD

**Issue by angular-tools** [kentcdodds/ama#137]
Hi,

Love your work, esp angular formly! I do have a question for you about TDD. How important do you think TDD is to Javascript and other development in general? I want to know **your own personal opinion about it**. Do you enjoy it? 

P.S. I hardly ever see any popular repos on Github that have less than 90% code coverage and I've been trying to write test driven code for sometime now but I often lose interest in a few days and start writing what comes naturally. The projects I determine not to write without TDD I never finish because I find TDD esp hard in the later parts of the project where everything is coming together like Database, Sockets, etc. In the end I'm usually skimping on writing tests because mocking classes, using spies, etc is just too much burden. Is there a way around it? Will I get the hang of it if I keep powering through and not write any code without writing tests first?

Thanks for your thoughts and guidance,

Regards,
San

**Comment by kentcdodds** [comment]
I thought it easiest to answer your question with my voice: https://www.briefs.fm/3-minutes-with-kent/29

Let me know if you have further questions :D
