### ISSUE TITLE
How about Open-sourcing from the beginning  ?

### ISSUE THREAD

**Issue by hanu412** [kentcdodds/ama#138]
Hey Kent --

I would want to know if there is any project which has been open-sourced and developed from the scratch in open? I see lot of projects on github. I love many of them for their amazing work like angular-formly.  I want to contribute and so I forked many of the projects. Once I start looking at the code, more often than not I end up thinking -"Ah, this project is awesome and no one needs to do anything about it". 

The result is I end up contributing nothing. This doesn't mean I don't want to contribute. My question here is "Is there any project which is going to start in open so I can join the discussion right from day-1/week-1 before the dev starts and I can help in dev." I hope my question is clear now.

**Comment by kentcdodds** [comment]
Hey @hanu412,
Thanks for your question. So it's really common for projects to start out as just a repo on GitHub and be discussed by people trying to solve a common problem. Often this is just one person or several from the same team. It'd probably be hard for you to find a project that's in the design phases without being among the people trying to solve the specific problem.

But you don't have to start at the design phase to make a difference in a project. I didn't actually create angular-formly. I started contributing to the existing project and got so involved that it was given to me (and now I'm looking to pass the torch on to someone else). There are a TON of projects that need work and improvements on them. It doesn't take too long after looking at at [Help Wanted](https://libraries.io/help-wanted) and [First Pull Request](https://libraries.io/first-pull-request) issues to see there's a lot of opportunity out there to contribute.

I'd also recommend you give [this article](http://kcd.im/what-oss) a read.

Good luck!
