### ISSUE TITLE
Aphrodite vs. Radium

### ISSUE THREAD

**Issue by alexbooker** [kentcdodds/ama#139]
Hi, Kent

I've seen you advocating Aphrodite on Twitter and noticed you're using it for [**the JavaScript Air site**](https://github.com/javascriptair/site)

Just wondering what drew you to Aphrodite over it's competitors (most notably [**Radium**](https://github.com/FormidableLabs/radium))

I have a small amount of exposure to both and they **seem** to accomplish same thing but Radium is more mature

Thanks

[**P.S. I hope you're having a nice trip, mate :smile:**](https://medium.com/@kentcdodds/kent-ooo-out-of-the-office-cf21a630ea60#.3b2iwkqwj)

**Comment by kentcdodds** [comment]
Hey @alexbooker!
Here's your answer! https://www.briefs.fm/3-minutes-with-kent/28

Let me know if you have more questions :-)
