### ISSUE TITLE
Wanted some feedback on my mini-project.

### ISSUE THREAD

**Issue by nirajpandkar** [kentcdodds/ama#140]
I have been following you egghead.io series on "How to contribute to open source Javascript libraries".
And that has perhaps been a lifechanger. Thank you for the knowledge :+1: 

This is my project - https://github.com/nirajpandkar/thought-of-the-day
**Question**: 1. Could you suggest me any **improvements/features/tweaks**?
2. How do I get my repo **recognized** and get people care and **contribute** to the project?

**Comment by kentcdodds** [comment]
Hey @nirajpandkar!
Thanks for the question (and your patience :wink:).
The library looks great! For your first question, you might consider adding [a browser distribution file](https://egghead.io/lessons/javascript-add-a-browser-build-to-an-npm-module?course=how-to-write-an-open-source-javascript-library), other than that I think you're pretty much done.

For your second question, you might be interested in [this talk](https://github.com/kentcdodds/talks/tree/313ec718d5ef5159820e6502faebd34cd56633a3#managing-an-open-source-project) and [this talk](https://github.com/kentcdodds/talks/tree/313ec718d5ef5159820e6502faebd34cd56633a3#the-first-pull-request). Good luck!

**Comment by nirajpandkar** [comment]
Thanks for the links :+1:
