### ISSUE TITLE
What do you think about Inferno?

### ISSUE THREAD

**Issue by trueadm** [kentcdodds/ama#141]
Hey Kent,

I know you're a keen React user and you have played around with many view-layer libraries out there. I'd love to hear your thoughts regarding a library that I've been working on. It's called [Inferno](https://github.com/trueadm/inferno) and it's a React-like library with additional features (such as hooks) and a strong architectural change to make vastly faster DOM operations. 

I'm also a keen React user, but found that React simply wasn't quick enough when dealing with complex UIs on legacy mobile devices – which is a big problem in parts of the world where having iPhone 6S's is almost non-existent. It turned out that these optimisations are actually something that really every virtual DOM library should leverage and I'm keen to somehow port these back to React if/when the core team want them (I've reached out already and they seem interested).

Thanks a lot for your time :)

**Comment by kentcdodds** [comment]
Hi @trueadm,
I'm sorry it's taken me so long to get to your question. I think that my lack of response is indicative of my thoughts on Inferno though. To sum up. It looks interesting, but I haven't hit any issues with React to encourage me to look outside the solution. On top of that, React has a vibrant community which encourages me to stay.

Speed is cool, but for most of us, React is fast enough. I think the same could be said of Angular 2 and Ember. I can understand that you may have a special use case where React isn't fast enough. And I think it's awesome that you've built something to cater to your use case. But for the vast majority of us it's working great.

If some of the optimizations you've made could be back-ported to React that'd be awesome. Good luck with that!
