### ISSUE TITLE
Ava vs typescript

### ISSUE THREAD

**Issue by marcusnielsen** [kentcdodds/ama#142]
Hi!

So I've written some code with node-tap, and converted to Ava. That was a breeze!

But adding typescript didn't work that well. According to https://github.com/avajs/ava/blob/master/docs/recipes/typescript.md I need to precompile and then run ava (`tsc && ava`). That's a no-go for me.

I'm starting to write type-checking test-helpers that you can include in every unit-test to check the unit's children's type.

Is this something anyone has solved already? How do others test/ensure reoccurring object structures in their projects?

Have anyone used typescript with ava? Or should I just go with typescript and another test-runner like Ava but with typescript support?

### (Current snippet idea for reference)
```
const types = {
  function: 'function',
  object: 'Object'
}

function assertType({parentObject, typeString, strictEqual}) {
  Object.keys(parentObject).forEach(function onMapParentObjectKeys(key) {
    strictEqual(typeof parentObject[key], typeString)
  })
}

export default {
  assertType,
  types
}
```

**Comment by kentcdodds** [comment]
Hi @marcusnielsen,
Thanks for the question. Unfortunately I wont be much help yet. I have yet to write a single line of TypeScript, so I don't really know much about it. My guess is that if the recipe says to precompile, that's the best the community has available for now. I'm also guessing that improving that experience will be a bit lower on the priority for the AVA team. I'm not aware of test runners like AVA that have TypeScript support. Sorry, but on this one you're on your own :-(

**Comment by marcusnielsen** [comment]
It's not what I want to hear, but I've heard that enough times now from other people. I don't want to put "ts" in front of all my tools and be confined in typescript-land. I will make a small tool for structural type-checking instead.

Thanks as always Kent!
