### ISSUE TITLE
Feedback on a app and suggestions to learn JS in a proper way?

### ISSUE THREAD

**Issue by akashnimare** [kentcdodds/ama#143]
Any suggestions to improve this?
http://akashnimare.in/ReadAMA/
https://github.com/akashnimare/ReadAMA

I have recently switched from Python to JavaScript as my primary programming language. There are floods of suggestions about how to be good at JS. They are confusing. 
> It would be very helpful if you can share your thoughts on how to be good at JS (Node/ React) in a proper way. I know Egghead is awesome but I am tight on budget :sob: 

> How did you improve yourself as a JS developer?

BTW I loved your talk on zero to 60 on web development :)

**Comment by kentcdodds** [comment]
Hi @akashnimare,
Thanks for the question.

> Any suggestions to improve this?
> http://akashnimare.in/ReadAMA/
> https://github.com/akashnimare/ReadAMA

Looks cool. But to be perfectly honest I don't really see it as much better than just using GitHub issues. By using what you've built, I get a few neat features, but at the expense of many other more important features (like being able to comment for example).

As for thoughts on how to be good at JS, I think everything I have for you is in the [Zero to 60 talk](https://github.com/kentcdodds/talks/tree/42903fc1790a2572a6a248399eebf7f3143e451f#zero-to-60-in-software-development-how-to-jumpstart-your-career) you mentioned.

If you have any specific questions outside of what's covered in that, let me know. :-)

**Comment by akashnimare** [comment]
@kentcdodds thanks for the feedback. App is pretty basic :sob: . I read lot of amas and thus my motto was to build something which will create a nice and easier way to read and browse those issues. 

Just a follow up question -

> Have you ever joined any programming contests? What are your thoughts on programming stuffs like binary tree, dynamic programming etc?

**Comment by kentcdodds** [comment]
> I read lot of amas and thus my motto was to build something which will create a nice and easier way to read and browse those issues.

For your use case it looks like a solid app :-) Good work on it 😄 

> Have you ever joined any programming contests?

I used to work somewhere that did regular "Hack Nights" where we would work on stuff for a few hours. I totally loved it. It was a lot of fun. I think I liked being around people. I don't know if I would do a remote contest. Maybe... But I'm pretty darn busy these days.

> What are your thoughts on programming stuffs like binary tree, dynamic programming etc?

This is stuff that's interesting, but I haven't found too practical in my experience. ¯\\\_(ツ)_/¯

**Comment by akashnimare** [comment]
Haha, glad to know that :v:
