### ISSUE TITLE
How to make npm use production or dev build?

### ISSUE THREAD

**Issue by jamestwiggle** [kentcdodds/ama#149]
Hello @kentcdodds ,

- I'm wondering how to make npm use the `production` or `development` build based on the environment variables set by the developer using my library. I know `npm` provides in the `package.json` the `main` field where its the entry for my library, and on the field I have the entry for non-production build. How do you make this dynamic?

- How to make the `dist` folder of my library only be present when the user installs my project on npm? So that it builds the project for production and development at the time of installation from `npm`(or whenever is best)?

I'm new to open sourcing my work so these are things I haven't understood yet.

**Comment by kentcdodds** [comment]
Hi @jamestwiggle!
I don't have time right now to give you a full answer (will come back later), but in the mean time, I recommend you watch [this](http://kcd.im/write-oss) :+1:

**Comment by jamestwiggle** [comment]
@kentcdodds , 
You might not believe me but I watched this before I started writing my library 😅. That helped get me started. No worries, whenever possible you can squeeze in time to get back to me is great!

**Comment by kentcdodds** [comment]
Hello again @jamestwiggle,

> how to make npm use the production or development build based on the environment variables set by the developer using my library

There's no real set way to do this AFAIK. You could do it various ways. One thing you might try is in your `main` you could point to a file that is basically:

```javascript
if (process.env.NODE_ENV !== 'production') {
  module.exports = require('./production-stuff')
} else {
  module.exports = require('./dev-stuff')
}
```

There's no way to make your `main` dynamic. You could also publish two different packages with different `name` and `main` properties.

> How to make the dist folder of my library only be present when the user installs my project on npm?

I'm assuming you mean you want it present in the npm registry, but not in your git repository. This is simple. Use `.gitignore` to ignore `dist` and use `files` in the `package.json` to include `dist`. This is what I do in my course. (see [`package.json`](https://github.com/kentcdodds/starwars-names/blob/2a6ff78ec19338b6d018082ac64559ffe65d91bd/package.json#L30-L33) and [`.gitignore`](https://github.com/kentcdodds/starwars-names/blob/2a6ff78ec19338b6d018082ac64559ffe65d91bd/.gitignore#L3))

Good luck!
