### ISSUE TITLE
Why have you not created your own start up?

### ISSUE THREAD

**Issue by stevebluck** [kentcdodds/ama#15]
I'm always surprised to see top developers in full time employment. I always think "If I was that skilled, I'd build my own company/startup and become a gazillionaire!!"

**Comment by kentcdodds** [comment]
Hey @stevebluck. Thanks for asking.

I'm married, have two small children (and another on the way), and a home mortgage. Some of us are more risk averse (like me). I don't want to chance my ability to feed and shelter my family by creating my own startup that may or may not succeed. To me, my family is too important for even the potential gazillion dollars to be worth it.

So when I'm faced with an offer to work at a sweet new startup that's going to make billions, I have a threshold for my salary to make sure that my family is taken care of, even if the startup flops. I know that's not how you get rich, you get rich from risk. But I'm risk averse in favor of confidence and stability.

In fact, I just want to be happy, and money doesn't buy you happiness. In fact, it has done quite the opposite for many of the rich and famous in the world. I have no interest in becoming super wealthy. I just want to have enough to take care of my families needs (and some wants).

<sup>Though I wouldn't be opposed to striking it big with one of the startups I work for so I can be independently wealthy and work wherever I want with no thought to money (or just work on open source all the time). :-)</sup>
