### ISSUE TITLE
Approach to learn a framework

### ISSUE THREAD

**Issue by anirudh-modi** [kentcdodds/ama#151]
Hello kent,
When you moved from angular to react, or when you started angular itself, what was your approach to learn?
Apart from documentation, what approach, would you suggest which can help us learn any framework in the most effective way..
Thanks,
Anirudh

**Comment by kentcdodds** [comment]
Hello @anirudh-modi,
Thanks for the question. This one is kind of similar to #89. I learn a framework the same way I learn everything. I describe this process in my talk [Zero to 60 in software development: How to jumpstart your career](https://github.com/kentcdodds/talks/tree/42903fc1790a2572a6a248399eebf7f3143e451f#zero-to-60-in-software-development-how-to-jumpstart-your-career). Another thing you might look at is my blogpost [What open source project should I contribute to?](https://kcd.im/what-oss) Specifically the bit where I talk about how to familiarize yourself with the code.

Good luck!

**Comment by anirudh-modi** [comment]
Thanks for the reply 😃
