### ISSUE TITLE
Using Webpack for Production JavaScript Applications

### ISSUE THREAD

**Issue by zombiecodekill** [kentcdodds/ama#152]
Hi Kent,

I was excited to see your new egghead.io course Using Webpack for Production JavaScript Applications is available for free on egghead.

I am interested in writing up a review of it on zombiecodekill.com

The format would be similar to the one I did when I reviewed Joe Eames Webpack course 3 weeks ago
https://zombiecodekill.com/2016/06/02/webpack-fundamentals/

I'd just like to check that you're happy with this, and me using your photo on my blog?

Thanks

**Comment by kentcdodds** [comment]
Ha, responded [on](https://twitter.com/ZombieCodeKill/status/745873290334445569) [twitter](https://twitter.com/ZombieCodeKill/status/745873699853770752) :-)
