### ISSUE TITLE
Authentication with React and REST Calls

### ISSUE THREAD

**Issue by tetter36** [kentcdodds/ama#155]
Hey Kent,

I’ve been trying to add authentication to the application that I showed you a few weeks ago, but I’m at a loss for the best way to go about doing it and wanted to get your opinion. My app runs using REST calls and in order to make an authenticated callout I need an access token that’s provided by the server. However, it’s not a true SPA so I can’t store it in a redux store for retrieval because every time a new page is loaded, it pulls the page from the server. I have read conflicting things about whether or not to pass the access token as a parameter or save it to a cookie. I need the access token to pass as a parameter or header when making my calls to the server to get the data. Do you have any experience or opinion on this?

**Comment by kentcdodds** [comment]
Hey @tetter36!
Thanks for the question! So what I'd recommend is sticking the token in `localStorage` or `sessionStorage`. This approach works great if you're in a SPA. If it's server-rendered only, then you may need to use a cookie which would be fine. The problem with cookies is that the server and the client have to served on the same domain.

I talk about this a bit in [this talk](https://github.com/kentcdodds/talks/tree/42903fc1790a2572a6a248399eebf7f3143e451f#jwt-not-your-grandmas-cookies) I gave 2 years ago. It's still relevant! Good luck!

**Comment by tetter36** [comment]
Thanks for the response, and resource! I think this will solve my dilemma rather painlessly.

**Comment by brotzky** [comment]
@tetter36, `localStorage` or `sessionStorage` fail on iOS Safari private browsing and have plenty of issues on Firefox with extremely high privacy settings or private browsing. Just a heads up if you need solid support for you application.

**Comment by gaui** [comment]
Cookies can also very well be used in SPAs. When logging in, API sets a cookie in the response headers, which is then set automatically in the users browser. Then the cookie will be attached to request headers in all subsequential XHRs. When logging out, API responds with another cookie with a negative expiration, thus deleting the cookie from the users browser.
