### ISSUE TITLE
Webpack & Babel Config

### ISSUE THREAD

**Issue by konstantinpschera** [kentcdodds/ama#157]
Hey Kent,

I really like your new Webpack course on egghead and the little helper functions `ifProd`, `removeEmpty` and `addPlugin` which make my Webpack config super easy to read and universal. I really didn't like to write two configs for production and development. Your helper functions are just to easy :)

I would like to know if you have an idea how to simplify the problem with different babel configs. If I want to use a Webpack config with ES6 imports I need to rename my `webpack.config.js` to `webpack.config.babel.js` and I need a .babelrc file with the preset `babel-preset-es2015`. For Node it's good to use the preset `babel-preset-es2015-node`. For Webpack I need the preset `babel-preset-es2015-webpack` so I can use tree shaking. In conclusion I need 3 different Webpack presets for the different environmenst. If I now want to use some plugins I have to add them to all different babel configs and I have to update all of them if I need to change some plugin configs. Do you have a tip how to solve this "problem".

Konstantin

**Comment by kentcdodds** [comment]
Hi @konstantinpschera,
That's definitely an interesting problem. In that case you have a few options:

`1.` Specify your options where the config is being used

- In webpack's babel-loader, you can specify the babel config using the `query` property (see [the docs](https://github.com/babel/babel-loader)).
- For `webpack.config.babel.js` I'm not sure whether you can specify what config is used... So I think you'll have to use `.babelrc`
- For node, you're probably calling into babel somewhere to transpile that stuff and you can probably pass in options for what should be transpiled (for example, with the `cli` you can specify what config to use as a command line flag).

`2.` Use `env`

Read more about this [here](https://babeljs.io/docs/usage/babelrc/#env-option). This could solve it for you. You may want to use this in combo with [`cross-env`](http://npm.im/cross-env)

Other than that, I'm not sure how to solve your problem. Good luck!
