### ISSUE TITLE
Feedback after interview

### ISSUE THREAD

**Issue by anirudh-modi** [kentcdodds/ama#158]
Hello Kent,
I would like to know, is it a good habit to ask from the interviewer, about a feedback on how well one faired in a technical interview?
Thanks,
Anirudh Modi

**Comment by kentcdodds** [comment]
Hey @anirudh-modi,
I do this all the time. Sometimes they're surprised by the question, but I normally get helpful feedback. I think it also forces them to stop and really consider what you could have done to be better which is good. :+1:

**Comment by sapegin** [comment]
Another question is when to ask? I did that once or twice after I was rejected but haven’t receive any answer.

**Comment by anirudh-modi** [comment]
Thanks @kentcdodds for replying. 😃

**Comment by kentcdodds** [comment]
@sapegin, I actually will ask before my interviewer leaves the room! This is why it surprises them sometimes :-)

Often people get busy after the interview and are unwilling/unable to provide feedback a few days after the fact. Doing it right away is useful for this reason.
