### ISSUE TITLE
A question about the way you talk

### ISSUE THREAD

**Issue by corderophilosophy** [kentcdodds/ama#159]
TW: Slurs, various.

You use the word 'lame' a lot. It's in an egghead series ('Lame DOM Bindings'), and it's in many of your tweets. As a person with a physical disability, I find this very offensive (it genuinely makes me sad just about every time I see it. Genuinely ruins me for a couple of hours. I don't like that it does, but it does.). I'm wondering if you can answer the following: In the 90s and 00s, people my age used the word 'gay' in the way you use 'lame', e.g. "You won't refund my ticket, that's gay" "That DOM binding is gay". How do you see the difference between these two terms? I see no significant differences. One is a homophobic slur, the other is a (dis)abelist slur. Any thoughts?

**Comment by kentcdodds** [comment]
Hi @corderophilosophy,
You're absolutely correct. I think you know me well enough to know that I would never intentionally be offensive, impolite, or unkind. So I'm glad that you've spoken up to call my attention to something I do that I don't realize is having that effect.

> How do you see the difference between these two terms?

I find them to be equally offensive, and will strive to take the improper use of the word "lame" out of my vocabulary. Thank you for your patience with me as I overcome years of cultural influence on my speech.

Thanks again.

**Comment by goliney** [comment]
People nowadays fill themselves offended without a reason too often, in my opinion.

**Comment by kentcdodds** [comment]
@goliney, you've voiced the same thing that several people have mentioned on twitter. I've avoided engaging, but I'll just say this. Whether you believe that this specific case is one of those situations or not isn't something that I think we need to get into. It's pretty subjective anyway.

The fact of the matter is that my language has caused someone some grief. It's just a matter of me being more accurate in the phrases I use (objectively improving my speech) and I avoid unintentionally hurting someone's feelings or causing the grief that @corderophilosophy has described. Seems like an objective no-brainer.

**Comment by corderophilosophy** [comment]
Two quick things. Then I'll leave this discussion (at least here) behind.
1) How is my taking offense at a (dis)ableist term significantly different from your apparently taking offense at my being offended? What is the purpose of your noting that people get offended "without a reason," @goliney? If you're not a person with a disability, you've got not business telling me, or any other person with a disability, what is or isn't an appropriate object of offense. If you are a person with a disability, then shame on you for your lack of solidarity. 
2) Before you suggest that my offense was taken "without a reason", maybe you could explain why the reason I provided isn't a genuine reason. What's the difference between a (dis)ablelist slur and a racial slur, or a homophobic slur, or a sexist slur, or any other kind of slur?  I understand that perhaps this isn't the venue for this discussion, so please feel free reach out to me on Twitter (@corderophi678) if you'd like to talk about it.

**Comment by kentcdodds** [comment]
Let's move this conversation elsewhere. Thanks.
