### ISSUE TITLE
Advice for someone who is going to giving their first presentation at a developer conference?

### ISSUE THREAD

**Issue by RandomlyKnighted** [kentcdodds/ama#160]
As the title states, this will be my first time giving a talk at a developer conference. I've given a talk at a conference before but I kept going blank during the middle of the presentation. Do you have any advice for someone just starting out giving talks like these?

**Comment by kentcdodds** [comment]
Hi @RandomlyKnighted!
Thanks for the question. I think the most important thing for you to do to prepare is:

> **Practice, practice, practice**

Practice by yourself, practice at a meetup, practice with your friends. This will help you feel more confident with the content. I often practice a new talk 4 times before giving it. More if I feel less confident with it. I'll also elicit feedback from my friends by giving the talk to them or recording myself giving it and putting it up on YouTube.

After that, just remember that nobody in the audience is at your talk hoping you'll fail. They came to your talk and they're interested in hearing what you have to say. They're rooting for you.

Good luck!
