### ISSUE TITLE
wysiwyg editor

### ISSUE THREAD

**Issue by dbabaioff** [kentcdodds/ama#161]
Hi,
I'm looking for a very basic wysiwyg editor (with very basic functionality like bold, italic, link, ... and maybe support for emoji) - like the one github uses on the new issue page.
Do you have any good suggestions?

Thanks!

**Comment by kentcdodds** [comment]
Hey @dbabaioff!
I'm not familiar with wysiwyg editors, but I'll tell you the first place I would check is libraries.io:

https://libraries.io/search?platforms=NPM&q=wysiwyg+editor

And if I were doing something with an editor like that, I'd look into [draft.js](https://facebook.github.io/draft-js/). https://libraries.io/search?platforms=NPM&q=wysiwyg+editor+draftjs

Good luck!
