### ISSUE TITLE
Assess myself in Js

### ISSUE THREAD

**Issue by anirudh-modi** [kentcdodds/ama#162]
Hello Kent,

I would like to know do you have particular website or github repo, which you use, or any person can use if they want to assess themselves in Javascript? I already know a repo
> https://github.com/rmurphey/js-assessment

Just, want to anything more is out their or not.

Thanks,
Anirudh Modi

**Comment by kentcdodds** [comment]
Hi @anirudh-modi!
Sorry, I'm not aware of anything. If you're trying to gauge where you're at with JS though, you might try [exercism.io](http://exercism.io/). I've never personally used it, but it appears to be a pretty good resource to get feedback from people on coding challenges :+1:

**Comment by anirudh-modi** [comment]
@kentcdodds Thanks for the suggestion and your time.

**Comment by d3lm** [comment]
@anirudh-modi Try [codewars](https://www.codewars.com/). You'll get challanges (katas) from different levels of difficulties. Additionally, you can / must solve those challanges via TDD. If you like you can also create an allegiance if people have the same clan tag or you follow other warriors. I really like the idea and it's much fun to compete against others. Once you have finished a kata, you have access to other solutions to see how people have solved the problem.Codewars offers several programming languages and you can choose which ever you prefer (JS I suppose).

**Comment by anirudh-modi** [comment]
@d3lm seems like fun thing, challenges via TDD, Thanks for the link!

**Comment by d3lm** [comment]
@anirudh-modi Indeed. I have been using it to keep my Haskell skills alive. Been enjoying Haskell back in the days and its still fun. Codewars is the perfect place to just play around and practice.

**Comment by anirudh-modi** [comment]
I guess, the TDD challenges are making a difference, there are few other things also, where you solve the problem statement, but they lack the TDD concept!

**Comment by d3lm** [comment]
Indeed. Writing tests is very important IMO.
