### ISSUE TITLE
Algorithms

### ISSUE THREAD

**Issue by anirudh-modi** [kentcdodds/ama#163]
Hi Kent,
I wonder have you bumped into a real job use case, where you actually end up using the algorithms taught in colleges?
Which leads to second question, if we are not able to use it in practical scenarios, what benefits is it to learn them?

PS: Might seem a little weird, because I am yet to discover a scenario where I am yet to use an algorithm, can be because of the job.
Thanks,
Anirudh

**Comment by kentcdodds** [comment]
Hi @anirudh-modi!
This is a great question. I think that I answered it fairly well before here: https://github.com/kentcdodds/ama/issues/114#issuecomment-214945007

Let me know if you have further specific questions :-)

**Comment by anirudh-modi** [comment]
Thanks @kentcdodds for the answer!

**Comment by anirudh-modi** [comment]
http://www.thatjsdude.com/interview/linkedList.html

bumped into something interesting, so thought would share.

**Comment by ctrlplusb** [comment]
@anirudh-modi if you are interesting in picking up some algorithms knowledge I would checkout the [grokking algorithms title](https://www.manning.com/books/grokking-algorithms).  It's very approachable.  I think having some algorithms knowledge is useful when you approach performance issues around data structure selection.
