### ISSUE TITLE
Interview questions for a Frontend Engineer

### ISSUE THREAD

**Issue by d3lm** [kentcdodds/ama#164]
In another question I saw that you interviewed at Facebook and I would be interested in the types questions you had to answer. You mentioned that classic CS topics were not covered, however you were asked to give an architectural design for a pinterest-type layout. I am wondering if you have general advice, suggestions regarding technical interviews or any experience you could share with us? What do you think are the most important topics you must know as a Frontend Engineer?

Thanks in advance for your response!

**Comment by kentcdodds** [comment]
Hey @d3lm!
Thanks for the question 😄 For general advice, I'd say that you should focus on the fundamentals of the platform upon which you're building. If you're doing web stuff, whether you spend your time with Angular, Ember, or React, you should focus on learning JavaScript, HTML, CSS, the DOM APIs, and basics of HTTP.

Actually, I recommend checking out [this blogpost](https://medium.com/@djsmith42/what-web-framework-should-i-learn-a9285925ca1f) by @djsmith42 and [this one](http://jamison.dance/07-04-2016/how-to-learn-technical-things/) from @jergason. While you're at it, you should subscribe to [the podcast](https://twitter.com/softskillseng) which they insidentally co-host. It's fantastic.

If you have a solid grasp on the basics, it'll really help you with the complicated problems you're presented with on the job and in interviews 👍

**Comment by d3lm** [comment]
Thanks for your advice @kentcdodds :+1:
