### ISSUE TITLE
Question 😅

### ISSUE THREAD

**Issue by anirudh-modi** [kentcdodds/ama#165]
Hello,
The question might seems a little silly,
I would like to know have you asked Brendan Eich, any question on Twitter/email? 😅

**Comment by kentcdodds** [comment]
Hi!
Sure I have! He's quite approachable. I even had him on the first episode of JavaScript Air: [jsair.io/first](https://jsair.io/first).

**Comment by anirudh-modi** [comment]
Ya i have watched the first episode of JavaScript air... It was such a privilege to just hear his thoughts out!

If you remember, and if the question was not a personal one, can you share the question?😄

**Comment by anirudh-modi** [comment]
Thanks alot for making sure he was their in the first episode of JavaScript air!

**Comment by kentcdodds** [comment]
Sure, here's [the first one](https://twitter.com/kentcdodds/status/552026708455342080) I've asked him several [questions on Twitter](https://twitter.com/search?q=brendaneich%20from%3Akentcdodds&src=typd) and DM... Why are you asking?

**Comment by anirudh-modi** [comment]
I was just curious if it was related to JavaScript, and i could learn anything from it.. Apologies if it was a little odd or inappropriate..
