### ISSUE TITLE
Webpack mobile first

### ISSUE THREAD

**Issue by iGitScor** [kentcdodds/ama#169]
Hi Kent,

Thank you for giving us the possibility to ask you questions about multiple subjects
Mine is technical and specially about WebPack.

I've searched some loaders or plugins (like postcss one) to split a css file into several files based on media queries. After that I need to gzip them and then to upload them on a Amazon S3 bucket.

Do you think that is it a good idea, and have you already found a resource (article/course) about that ?

Thanks and sorry if that looks like support question

Sebastien

**Comment by kentcdodds** [comment]
Hi @iGitScor!

Your use case sounds interesting. I'm not aware of anything that'll do this for you out of the box and not aware of resources you could look up to find out.

Honestly, I'm not certain that's a fantastic idea. Based on the fact tha tyou're uploading them to an S3 bucket, I'm assuming you're building a SPA that's totally rendered on the client and not doing any server side rendering or serving of assets. I think I understand that your goal is to ship as little CSS as possible to the client.

I wonder if there are other things you could do to speed things up. One thing you might consider doing is using code splitting. So on the client, you'll determine what CSS the device needs and then make a request for the CSS you need for that client.

Code splitting is a bit of an advanced topic but maybe [this](https://egghead.io/lessons/tools-maintain-sane-file-sizes-with-webpack-code-splitting) will help a bit (assuming your an egghead.io subscriber). Good luck to you!
