### ISSUE TITLE
How to make sure the issue wont be closed by the time we are working on it?

### ISSUE THREAD

**Issue by shreya22** [kentcdodds/ama#170]
when we see an open issue, we work towards it. but there may be many more working on the same thing. so, is it like a matter of time, the one submitting fast as soon as its open will be considered first and may win..? ALso, sometimes on issue discussion I found comments like 'm taking this'. We shouldnt be touching those issues.. right? 
I want to know the work culture of opensource. It is no surprise that all the time we are working on the issue it might be closed by then. What is the right ethics is that case? If m taking over an issue, should i tell the community that m working on it? 
thanks :)

**Comment by kentcdodds** [comment]
Hi @shreya22,
Thanks for the question. Sorry it's taken so long to get to you. So I actually talk about this a bit in https://github.com/kentcdodds/ama/issues/110

Generally if you want to take an issue, mention in the comments that you want to implement it. If someone else implements it first, that wasn't kind, but you can't control people's actions :-/ Good luck!
