### ISSUE TITLE
How do you tame an event broadcast nightmare?

### ISSUE THREAD

**Issue by run-time** [kentcdodds/ama#171]
We have a massive Angular app with lot's of stuff on root scope as well as way too many watchers / events being broadcast.  (a.k.a. house of cards)

Can you point me to any tools (or video) which shows how to monitor and log events so I can see which ones are being called the most in succession?

Do you have a personal process you follow which helps reign in event chattiness while limiting the chance of things breaking?

Thanks for sharing your experience with the world and I look forward to your answer.

P.S. I absolutely love the [ng-stats](https://github.com/kentcdodds/ng-stats) visualization tool you made which helps me see where digest cycles could be reduced.

**Comment by kentcdodds** [comment]
Hi @run-time,
Thanks for the question. Unfortunately I don't really know of any good resources for you. It's been about 10 months since I last wrote any angular code and memory fades fast. Sorry. Good luck to you!
