### ISSUE TITLE
Deploying/Build process

### ISSUE THREAD

**Issue by dbabaioff** [kentcdodds/ama#174]
Hi Kent,
On our company we have a very big js application and currently we are using (for build/minify) babel for es6, uglify, less, htmlminifier, cleancss.
For the build system we are using a very old php script we wrote - this script is responsible for concatenating/es6/minifing/cleaning all the files - but we thinking to replace with something like gulp or webpack - to give us more flexibility and easy to maintain.
Today we have some problems/ and questions connected to the build process:
1 - We have a dev, staging and the live servers - based on your experience, where is the recommend place to build?
Let's say I'm pushing a specific git branch from the dev server to the staging server - should we run the build script on dev and deplay the final result to the staging server?
2 - Sometimes one of the minifiers fails - for example the htmlminifier with you have something like this: `<a href="javascript:"">link</a>` - with an extra quotes it's breaks - and we run this minifiers before pushing to the staging/production server - then we waste a lot of time trying to figure out what broke - should we use a CI for trying to build the assets on every commit or run periodically on different git branches?
3 -  A see a lot of people saying maybe to use a separate server for building the files - how this help to make the build process better? and what's should be the flow dev --> build server --> staging/production

Can you share you experiences? what did you use on your last job and what you use today on paypal? Did you use a separate build server? What was the flow to deploy/build files?

**Comment by kentcdodds** [comment]
Hi @dbabaioff,
Great questions! It was easiest for me to answer verbally, so [here you go](https://www.briefs.fm/3-minutes-with-kent/33)!
