### ISSUE TITLE
Podcast on reactjs? 

### ISSUE THREAD

**Issue by atishaybaid** [kentcdodds/ama#179]
Hi,
Could you suggest some podcast or episodes to follow on react,to get around with the community and best methods to follow.

**Comment by kentcdodds** [comment]
Hey @atishaybaid, check [this](https://react30.com/) out!

Also, I'd recommend searching for the term "React" on any of [my favorite podcasts](https://github.com/kentcdodds/ama/issues/17#issuecomment-184783607)
