### ISSUE TITLE
How do you architecture your React projects?

### ISSUE THREAD

**Issue by ValentinH** [kentcdodds/ama#180]
Hi Kent,

I'm coming from Angular and starting to learn React. I follow you for a while (only on Twitte don't worry 😄), and I know that you also come from Angular (I have used your Formly lib) and are also a React user now.

Coming from Angular, I organize my files by domain instead of my nature and it's the recommended way for quite a bit of time.

Now, in React, I'm surprised to see that most of the examples ([this one for instance](https://github.com/reactjs/redux/tree/master/examples/real-world)) organize their files by nature (Reducers, Actions, etc..) and would like to know if this what you are using as well. And if you could explain your thoughts on it. 😉 

I have found this article that advocates for organizing your files by domain in React: http://marmelab.com/blog/2015/12/17/react-directory-structure.html

Thanks by advance,
Valentin

**Comment by kentcdodds** [comment]
Hi @ValentinH!
Thanks for the question. I like what @mzabriskie and @ryanflorence came up with a while ago [here](https://gist.github.com/ryanflorence/daafb1e3cb8ad740b346). In fact, I even structured my Angular apps like this before and was really happy with it.

More generally, check this blogpost out: [What code comments can teach us about scaling a codebase](https://medium.com/@kentcdodds/what-code-comments-can-teach-us-about-scaling-a-codebase-90bbfad8d70d).

I hope this helps!

**Comment by ValentinH** [comment]
Yeap now I remembered your blog post. 

Actually, in first versions of Angular seed projects, they were separating their files per type (Services, Directives, etc..) but now they switched to the architecture I was calling "by domain" which is the one you explain in your article.

By default, I was going to do the same in my React app but was surprised to see all the React examples not doing that.

Thanks for your lighting.
