### ISSUE TITLE
Do you have any book recommendations for effective programming/software engineering practices? 

### ISSUE THREAD

**Issue by ChrisWcs** [kentcdodds/ama#181]
Hey Kent! My name is Christian. I am studying Computer Science at the University of Utah ( no worries I have plenty of respect for BYU :)  ). I still have about 2 years left.

I am interested in improving how I approach problems ( like test driven development ). I am sure that I will have classes later that will go over this kind of stuff. I am just interested in learning more now about how to approach problems, lay things out before hand, testing, stuff like that.

Would you have any book recommendations? Sorry I realize this isn't the most clear question...

Thanks,

Christian Hansen

**Comment by kentcdodds** [comment]
Hi @ChrisWcs!
Thanks for the question. No grudges against you for going to UofU... nobody's perfect ;-) jkjkjkjkjk

> I am interested in improving how I approach problems ( like test driven development ). I am sure that I will have classes later that will go over this kind of stuff.

I hope you're right, but I seriously doubt that your classes will teach you much about testing at all let alone patterns like TDD. Let me know if they do though! That'd be great!

To answer your question though, I'm afraid that I don't have a good list of book recommendations. I don't learn much from reading these days. Maybe I should! I recently gave a talk that kind of explains how I learn though that you might be interested in: [Zero to 60 in Software Development: How to Jumpstart your Career](https://github.com/kentcdodds/talks#zero-to-60-in-software-development-how-to-jumpstart-your-career).

I'll tweet this question and see if we can get some other good book recommendations from others though :) Thanks!

**Comment by jkup** [comment]
My usual recommendations are:

+ [Code Complete](https://www.amazon.com/Code-Complete-Practical-Handbook-Construction/dp/0735619670)
+ [Introductions to Algorithms](https://www.amazon.com/Introduction-Algorithms-3rd-MIT-Press/dp/0262033844)
+ [SICP](https://www.amazon.com/Structure-Interpretation-Computer-Programs-Engineering/dp/0262510871)
+ [The Mythical Man Month](https://www.amazon.com/Mythical-Man-Month-Software-Engineering-Anniversary/dp/0201835959)

**Comment by bdougie** [comment]
@ChrisWcs I was given this book as a recommendation when I first started programming. The examples are in Java, but very clear and understandable. [Test Driven Development by Example](https://www.amazon.com/Test-Driven-Development-Kent-Beck/dp/0321146530)

**Comment by amasad** [comment]
The book that had the most direct impact on my career from a practical point of view [The Pragmatic Programmer: From Journeyman to Master](https://www.amazon.com/Pragmatic-Programmer-Journeyman-Master/dp/020161622X).

Where in most books there is a bit of a gap between application and theory, this book is full of real world advice on both software project management, and concrete coding advice.

**Comment by Jero786** [comment]
@ChrisWcs  I learn a lot with Uncle bob, I seriously recommend  [clean coder](https://www.amazon.es/Clean-Coder-Conduct-Professional-Programmers/dp/0137081073) at level at level of t, and at level of  [Clean Code](https://www.amazon.es/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882)

**Comment by kentcdodds** [comment]
Should probably link to this as well: https://github.com/kentcdodds/ama/issues/17
