### ISSUE TITLE
Why there's no segmenation fault in JavaScript of how arrays are implemented

### ISSUE THREAD

**Issue by vitkarpov** [kentcdodds/ama#182]
In `C` or `C++` you're getting segmentation fault errors all the time, espessialy if you're a newbie.

```c++
int a[4];

// Nope, you can't do that! Compiler doesn't let you to corrupt someone else's memory
a[5] = 20;
```

In JavaScript you're not gonna see this. Arrays just grow infinitely like vectors in `C++`.

How do JavaScript engines actually implement arrays? The real question actually is about where can I find answers for a such low level stuff except of source code?

Thanks!

**Comment by kentcdodds** [comment]
Hey @vitkarpov! Thanks for the question and your confidence in my ability to know! I actually have no idea off the top of my head. But I'll bet I have some twitter followers who are more knowledgeable than I am who can help answer your question better :) I'll tweet this and see if anyone can give you some resources to learn about this :)

**Comment by xjamundx** [comment]
Check out http://mrale.ph/irhydra/2/ which will show you what's happening under the hood of v8 without having to read the source code dirctly.

**Comment by rgbkrk** [comment]
[JavaScript manages memory for you](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management). Your main pal (sometimes frenemy) is the garbage collector - you get to allocate all the Arrays and Objects you feel like.

As for why:

```
var x = [0]
x[20] = 'woo'
```

Allocates an array as:

```
[0, undefined × 19, 234]
```

Effectively, Arrays in JavaScript are sparse. An Array is a special kind of object that adjusts the length property when elements are added at properties with numeric names. [Stranger Things are in the spec](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf) but that's the story here!

**Comment by mraleph** [comment]
@vitkarpov if you are looking for C++ equivalents then it's easier to think about JavaScript arrays as something similar to `std::map<int32_t, JsObject*>`. Map's don't segfault when you access them "out-of-bounds" - they just expand bounds :)

Of course this comparison is a bit naive, because virtual machines use rather complicated representations under the hood in attempt to optimize access times - but it captures _semantics_ rather well.

**Comment by vitkarpov** [comment]
Guys, thanks to all of you!
