### ISSUE TITLE
How do you handling bundling dependencies?

### ISSUE THREAD

**Issue by marr** [kentcdodds/ama#183]
Hi Kent,
I see you have some experience with dependencies and npm. I am running into an issue where I have a module _mod_ and a project _app_. I want to create a bundle in _app_ which would have an entrypoint like:
```
import React from 'react'
import { render } from 'react-dom'
import Mod from 'mod'

render(<Mod />, document.getElementById('root'))
```
Relevant repos: [app](https://github.com/marr/app) [dep](https://github.com/marr/js-native-modules)

_mod_ exports a class which extends `React.Component`, using `export default` syntax. 

When I try to bundle _app_ and `open index.html`, there are console errors: `Error: Cannot find module 'moment'` even though its in _dep_.

**Comment by kentcdodds** [comment]
Hi @marr,
It looks like you're using gulp + browserify. I don't know too much about browserify, but I can tell you that Webpack has been able to serve all of my needs for the last year and a half and I totally love it. There are a ton of great resources here: [git.io/awesome-webpack](http://git.io/awesome-webpack).

I've personally done a LOT to teach people about how to use webpack. Here's one of those resources: [es6-todomvc](https://github.com/kentcdodds/es6-todomvc).
