### ISSUE TITLE
ava vs jest?

### ISSUE THREAD

**Issue by sibelius** [kentcdodds/ama#184]

**Comment by kentcdodds** [comment]
Hi @sibelius!
Thanks for the question. I literally just [answered this for my team](https://twitter.com/kentcdodds/status/771739696988729345) at the same time you asked this!

Here's what I wrote to them:

> in other news, I'm thinking of migrating us from AVA to Jest (rather than Mocha) for various reasons:
> 1. The testing API is actually fairly similar (so migration will be much less painful)
> 2. It also supports running tests in parallel, but also supports running tests in a single thread (like Mocha) so we can see which is actually faster and just go with that
> 3. It has amazing inter-op with webpack (so we wont have to do as much proxyquire stuff for webpack-specific module stuff)
> 4. It has great module mocking capabilities (but it's no longer enabled by default like it was before)
> 5. It has an incredibly awesome watch mode. Like, seriously, it's amazing. I'm not even joking. I figured putting enough words in here would indicate how cool it is, so I'll just keep talking about how great it is.
> 6. It has a feature called snapshot testing for React components which would take a bit of time to explain, but basically it means that we wont really need to write tests for our components and the tests that it generates for us will be more reliable/helpful.
> 7. I'm sure there are more reasons. I'm still investigating. Stay tuned! If you've used Jest in the past, just know that it's been improved BIG TIME in recent months, so give it another shot :slightly_smiling_face:

**Comment by pavelloz** [comment]
@kentcdodds looking back, in your opinion, AVA is still the way to go? :)

**Comment by kentcdodds** [comment]
Nope. Jest is amazing and that's what I'd recommend.

In fact, I'm wearing my jest shirt right now!

![15646792599768211730153955004683](https://user-images.githubusercontent.com/1500684/62312894-99a8c700-b44c-11e9-98ec-a0b96e975dcb.jpg)
