### ISSUE TITLE
Programming Help 

### ISSUE THREAD

**Issue by Myussuf23** [kentcdodds/ama#185]
Hi, Kent C. How are you?.
My friend, i am new to the programming world. i am struggling with some issues, since i fully started focusing on it back in January this year. so i want to get help from you. my problem is about "function return" and "function parameters".
so when to use function return and when not to use it. and when to use function parameters and when not to use them, and also when to use Arrays and objects and when not to use them.. please explain to me with real life analogy.
Thank you so much.

**Comment by vitkarpov** [comment]
Hi @Myussuf23,

I'm sure @kentcdodds don't mind if I'll try to explain this in my view.

So, basically function is a container of some instructions, in another words, you can _take some piece of your program and wrap in into a function_.

Any program has its input and output, right? So does function.

You can think about it as a [subroutine](https://en.wikipedia.org/wiki/Subroutine). It's not very correct definition in terms of computer science, as subprogram works independently from the main one, I mean there's no shared state. JavaScript functions do have access to some set of scopes except its own, but seems it doesn't matter in terms of this answer (hint: google closures).

Think about any algorithm. You always can write your intensions in a very straightforward way:

- create some variables
- fill it with some user input or default data
- make some computations
- print the result

At some point you understand that your program tends to get bigger and there're some logical parts that _needs to be wrapped into functions_, cause they have own input and output, just like the main program.

Writing programs in such manner absolutely necessary to make the code _testable_. If you have divided your complex logic into some relatively simple parts, functions, you can test each function independently. Now you sure that each part works as expected you can easily combine them to getting complex things done.

Also, such program could be easily modified (as in real life requirements tend to change), you can drop out and replace some functions. Moreover sometimes you can replace _only the code inside_ saving _the interface: what function gets and what it returns_. So the other parts of the program work the same, cause they don't need to know much about what happens inside some particular function, the only want to specify expected input and get expected output.

**Comment by Myussuf23** [comment]
Thanks @Viktor for your answer.
