### ISSUE TITLE
What is your opinion on multi paradigm?

### ISSUE THREAD

**Issue by claudiordgz** [kentcdodds/ama#187]
Paradigm wars are no different than language wars, and I had quite a few over the past months. Front end is standardizing towards a more component based code causing a lot of fights with how this should be done. 

What is your opinion on Functional vs Imperative? 

Whether your propose one or a multi paradigm approach, how do you recommend that a team should tackle it if most of them have their own individual strongholds on which paradigm to use?  

How would you reach for 'peace'?

**Comment by kentcdodds** [comment]
Hi @claudiordgz,
Thanks for the question.

> What is your opinion on Functional vs Imperative?

I prefer functional over imperative most of the time. I like the idea of breaking a bigger problem into smaller chunks. I feel like individual functions are easier to think about and test. I can compose a program in your brain easier when it's composed of small functions. You can come into a codebase and look at how the pieces work, then look at how those pieces are put together. It's much easier to see what's going on in that scenario. And when changes come in, it's easier for me to see what part of the composition changed and how it impacts the end result.

With imperative code you normally just have a big block of code and it's harder to break it into pieces and understand the pieces individually. Also, even though there may be separation initially (enforced by comments), as people come in and make changes, I think it's much easier for you to just put random code in random places which kind of breaks the separation and makes it difficult to maintain/understand the code.

As for using multiple paradigms in a single codebase... I like to lean to functional when I can. But sometimes imperative makes more sense. I don't think it's a very big issue honestly. In the functional world, all that really matters is that the API you're exposing is pure. It matters less what you're doing inside your black box to make things work. So I kind of just go with what makes the most sense. I try to be as practical as possible I guess...

> How would you reach for 'peace'?

Teaching and patience. Teach about the trade-offs you're making between the two styles and have patience if people don't like it. Functional programming is relatively new, so many people are still learning about it and there's a big barrier around familiarity you have to break down first. It'll take some time.

Good luck!

**Comment by claudiordgz** [comment]
Thanks!
