### ISSUE TITLE
What is your dev environment?

### ISSUE THREAD

**Issue by akashnimare** [kentcdodds/ama#188]
Editor/terminal setup, apps, extensions etc.

**Comment by kentcdodds** [comment]
Hi @akashnimare,
You can find out about my editor from #113. Pretty much everything else about my terminal setup you can find from [my dotfiles](https://github.com/kentcdodds/dotfiles). As for apps, here are a few that I use (in no specific order):

- [Euclid](http://euclidapp.com/)
- [Sip](http://sipapp.io/)
- [ScreenFlow](http://www.telestream.net/screenflow/)
- [Google Play Music Desktop Player](https://www.googleplaymusicdesktopplayer.com/)
- [BetterTouchTool](https://www.boastr.net/)
- [Alfred](https://www.alfredapp.com/)
- [DTerm](http://decimus.net/dterm)
- [Bartender](https://www.macbartender.com/)
- [RDM](https://github.com/avibrazil/RDM)
- [Itsycal](https://www.mowglii.com/itsycal/)
- [LICEcap](http://www.cockos.com/licecap/)
- [TextExpander](https://smilesoftware.com/textexpander)
- [Franz](http://meetfranz.com/)

I would use [HyperTerm](https://hyperterm.org/) except the last time I tried, it didn't handle [my emoji](https://github.com/kentcdodds/dotfiles/blob/master/.bash_profile#L23) very well.

Enjoy :)

**Comment by akashnimare** [comment]
@kentcdodds awesome. Thanks 🚀 .

**Comment by akashnimare** [comment]
@kentcdodds I have also written an article on my dev setup [here](https://medium.com/@meakaakka/my-dev-environment-16e87cd67f6f) 😎 .
