### ISSUE TITLE
Jsair on Stitcher

### ISSUE THREAD

**Issue by emrysr** [kentcdodds/ama#189]
I've got an android phone. Can I listen to js air on Stitcher ? It doesn't come up on the searches.

**Comment by kentcdodds** [comment]
I haven't submitted it to the Stitcher network. I'll try to get around to that sometime.

**Comment by emrysr** [comment]
Thanks. I'll keep trying

**Comment by kentcdodds** [comment]
Just submitted. Please reopen if you don't see it in a week.

**Comment by emrysr** [comment]
I'm sorry to hear that. thanks for all your work getting this far. 
Unfortunately all my other podcasts are on stitcher so I wont be moving to another app. At least I've been able to download the ones I've missed  before they're removed.  
Thanks again 👍
