### ISSUE TITLE
Where do you get all those funny UTF emoticons? (like ಠ_ರೃ and so on)

### ISSUE THREAD

**Issue by benoror** [kentcdodds/ama#19]

**Comment by kentcdodds** [comment]
I have a [Google Keep](https://keep.google.com) note with my favorites:

```
＼(＾O＾)／
ᕕ( ᐛ )ᕗ
♪┏(・o･)┛♪┗ ( ･o･) ┓♪
(ó ì_í)=óò=(ì_í ò)
d-_-b
(－‸ლ)
¯\_(ツ)_/¯
ᕙ(⇀‸↼‶)ᕗ
┬┴┬┴┤(･_├┬┴┬┴
~=[,,_,,]:3
ಠ_ಠ
ლ(ಠ益ಠლ)
[¬º-°]¬
ಠ_ರೃ
ʕ •́؈•̀)
(◞‸◟；)
(╯°□°)╯︵ ┻━┻
(~_~;)
┐('～`；)┌
```

I got most of these from [emojicons.com/](http://emojicons.com/) or [www.disapprovallook.com(http://www.disapprovallook.com/).

Commit messages are far more fun with emojicons and emoji 😎
