### ISSUE TITLE
In what cases it doesn't work?

### ISSUE THREAD

**Issue by litrain** [kentcdodds/ama#193]
I am new to ReactJS. 
So far as I know, if a site uses ReactJS, it will has at least one 'data-reactroot' attribute after rendering, is that true?
Why https://asciinema.org/   only has 'data-reactid'? 
And  https://www.fiverr.com/  neither has 'data-reactroot' nor 'data-reactid', how it comes? 
In what cases your detector doesn't work?

**Comment by kentcdodds** [comment]
I'm thinking that the reason is most likely the version of React those two sites are using. But I'm not certain the exact reason. Let me ask some people :)

**Comment by litrain** [comment]
Thank you very much!

**Comment by Foxhoundn** [comment]
This is because since React version 15.0 the library does not need the reactid to find the element as it has moved to mounting to dom using createElement - which returns the element reference - instead of directly setting innerHtml.

**Comment by litrain** [comment]
Yes, but that's about ‘data-reactid’, what I want to know is why 'data-reactroot' doesn't exist.
