### ISSUE TITLE
How do you listen to podcasts?

### ISSUE THREAD

**Issue by k15a** [kentcdodds/ama#195]
Something like:
- which app do you use?
- how fast do you listen?
- when do you listen to podcasts?

**Comment by kentcdodds** [comment]
Hi @k15a,
Thanks for the question!

I use [BeyondPod](http://beyondpod.mobi) (paid, though there's a free version) and I have no complaints. It's pretty great. I always listen at 2x speed. I listen whenever I know I'll be driving more than 2 minutes and when I'm cleaning the house alone. Sometimes when I'm mowing the lawn too. Oh, and when I fly (during the time that I'm not allowed to have my laptop out). And occasionally I'll also go on a walk to listen.

If you're curious what podcasts I listen to, I try to keep this updated: https://github.com/kentcdodds/ama/issues/17
