### ISSUE TITLE
es6-modules and System.import and functions in JSON

### ISSUE THREAD

**Issue by zoomclub** [kentcdodds/ama#196]
Thanks for your es6-modules repo, it has clarified many things for me.

I’ve also heard that it is possible to load a module dynamically via System.import based on a condition at runtime:

if (Math.random()) {
   System.import('some_module')
   .then(some_module => {
       // Use some_module
   })
}

Apparently this is part of the Module Loader API except information about this API is hard to find. I only found this:

https://stealjs.com/docs/System.import.html

If you might confirm that this actually works it would be greatly appreciated!

Another thing I would love to do is store ES6 modules on a NoSQL backend like RethinkDB Horizon and fetch them with a query. I suppose they could be stored as the value on key-value pairs in a JSON document. However, how would they be loaded? Could they just be passed to System.import or do I need to use the eval function?

There is also a API called JSONfn, is this a good solution for storing functions in JSON? The best option would be something that works with ES6 and does not involve unnecessary dependencies.

http://www.eslinstructor.net/jsonfn

**Comment by zoomclub** [comment]
This use with Webpack is also interesting: 

http://rc.vuejs.org/guide/components.html#Async-Components

**Comment by zoomclub** [comment]
Looks like a confirmation to me :)

http://blog.avenuecode.com/lazy-loading-es2015-modules-in-the-browser

**Comment by kentcdodds** [comment]
Hi @zoomclub,
Sorr it's taken a bit for me to respond! I'm glad that my es6-modules repo has been helpful to you!

So right now loading modules is not supported by any environment. That's something that's still being worked on. However using tools like Webpack enable you to author your code with modules and have them bundled. Specifically the `System.import` API is supported by Webpack 2 to enable async loading of modules. It works great and I've taught about it on Egghead.io [here](https://egghead.io/lessons/tools-maintain-sane-file-sizes-with-webpack-code-splitting?pl=webpack-from-kent-1955b36a).

You might also like to go through [my slides from Frontend Masters](slides.com/kentcdodds/webpack-deep-dive), specifically starting with [this one](http://slides.com/kentcdodds/webpack-deep-dive#/16) (hit the down arrow).

Good luck!
