### ISSUE TITLE
Getting up to speed on node

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/ama#197]
My friend just asked me this, and I'm not sure of the right resources to point him to. Anyone else know?

> 1. Do you know of any resources I might be able to get a hold of that might describe some of the best practices for using nodejs for creating microservices?
> 2. Are there any other good references that might help me get up to speed on node? That last time I used it was for my capstone. :)

Note: his capstone was ~2.5 years ago.

**Comment by MethyleneGaming** [comment]
https://github.com/mfornos/awesome-microservices usually when in doubt look for the associated "awesome" list for the tech/pattern you are looking for. Usually a good spot to start from

**Comment by kentcdodds** [comment]
I remember seeing a talk from Laurie Voss that I thought was helpful with regards to microservices: https://youtu.be/5yK3lx-PQV0

**Comment by RandomlyKnighted** [comment]
I learned node from the [NodeSchool](http://nodeschool.io/) tutorials. I like them as I could go at my own pace and I believe it gives a decent primer on the topic.

**Comment by kentcdodds** [comment]
Thanks for the tips everyone!
