### ISSUE TITLE
Top things to do in Utah to convince my spouse to move?

### ISSUE THREAD

**Issue by mattferderer** [kentcdodds/ama#198]
I'm looking for some personal experience & ideas that might convince someone to move their young family & non-techy wife from a typical mid-west town to Utah, besides the amazing tech scene. If we took a vacation there, where should I all take her to make her fall in love with Utah?

**Comment by kentcdodds** [comment]
Hi @mattferderer,

Oh! That's awesome that you want to move to Utah! It's a fantastic place to live. I love it here!

It really depends on what you and your wife are into. To be perfectly honest, my wife and I don't go out to do a ton. We're pretty simple. We have 3 children 4 years old and under, so lots of the fun things you can do don't really work super well for us (yet). We normally just hit up some parks or hang out with family at home.

But if you're looking to get out, there's a bunch of outdoorsy things to do in the mountains and in Southern Utah. There's also water and theme parks (not a six flags or anything, but still a fun family outing if they're into that kind of thing). There are quite a few places in Utah to get really great performing arts entertainment too. My wife and I like to go to the [Shakespeare Festival](http://www.bard.org/), [Tuacahn](https://www.tuacahn.org/Online/default.asp), or [Utah Festival - Opera & Musical Theater](http://www.utahfestival.org/index.php).

Another thing my wife and I like to do with our whole family is head over to [Thanksgiving Point](https://www.thanksgivingpoint.org/) which has fun family activities all year round.

There are fun sports things to do too. I'm not really into that kind of thing, but I know it's a thing around here.

I'm also not sure of all the cool places to go to in Salt Lake City. I don't hang out there very often. But I hear that people like it. There are great places to eat. It's definitely no San Francisco or anything. One place to definitely see is [Temple Square](http://www.templesquare.com/) (especially around [Christmas](http://www.templesquare.com/christmas/) time).

I'll ask my other Utah friends to chime in here with their perspective :) Good luck!

**Comment by djsmith42** [comment]
Local stuff that I like to do with my family in Utah:

- The museum of natural curiosity
- Hike to Donut Falls
- Walks around our local lake in Daybreak (a community in South Jordan)
- Visit the aquarium
- Summer activities at Snowbird resort
- Temple Square (amazing Christmas lights in December)
- Picnics in the local canyons (too many to name)
- Cascade springs
- The Alpine Loop (beautiful scenic drive)

Stuff you can drive to in a single day from here:

- Yellowstone  (5 hour drive)
- Arches national park (3 hour drive)
- Zion national park (3 hour drive)
- Capitol Reef national park (3 hour drive)
- Lava hot springs (2 hour drive)
- The Grand Canyon (12 hour drive)

About the community: There are many young families here, and lots of community events are geared towards families with kids. There are always fun things to do, in our experience. We've met so many people who we love, and our kids have made tons of friends here.

I also never wanted to live in Utah, but I ended up here after the dot com bust, and I have loved every year for 15 years. It's a great place to have a young family.

**Comment by mattferderer** [comment]
Thanks @kentcdodds & @djsmith42! Is any particular time of the year better than others? Looking at both your answers, it looks like there are plenty of activities all year long.

**Comment by kentcdodds** [comment]
> it looks like there are plenty of activities all year long

Yes. Rarely too hot or too cold to do fun stuff.

**Comment by djsmith42** [comment]
During the winter, we tend to do indoor stuff like the aquarium and museums. It gets cold, but rarely below 15 F. The kids and I love building snowmen and forts in the yard during the winter. We do it literally every year. We don't ski, but if you're into that, the skiing here is world famously good in the winter.

The nice thing about the summer is that, despite the temperatures of 95+, it's actually not super uncomfortable like it is in the midwest. The air is dry. And the temperature delta in the shade is significant. Also, when the sun sets, the air temperature drops 20-30 degrees. So the evenings are usually quite comfortable, which is nice. We sleep with the windows open all summer, except maybe 1 or 2 weeks in the hottest time.

The dry air is generally a huge pro in my book, but one downside is that you must use lotion, chapstick, and drink lots of water. More than you are probably used to. Also, we are at 4,000 feet above sea level, so there is less Oxygen in the air. It affects some people when they visit. I'm super sensitive to it, but my body has adapted.
