### ISSUE TITLE
Software development workflow consultancy

### ISSUE THREAD

**Issue by gauravsoni1** [kentcdodds/ama#199]
Hey Kent, Great articles on egghead.io. 

We are looking for a consultant who can explain and develop front-end development architecture for our company. i.e.: the process that is to be followed form specification to building to maintenance , all the tools that we should be using and adopting etc.

We want to develop a sort of open source dev environment / dev style in the company.

Our front-end development is done primarily on AngularJs.

Please let me know if you would be interested to work on this project.

We can arrange payment on hourly basis, the training / discussions would happen over Skype.

Best Regards,
Gaurav

**Comment by kentcdodds** [comment]
Hi @gauravsoni1,
Thank you so much for the invitation. I'm afraid that I wont be able to help you out though. I'm too busy to do that kind of work at the moment. Best of luck to you though!

**Comment by gauravsoni1** [comment]
@kentcdodds I understand, thanks anyways.
