### ISSUE TITLE
i sure could some help

### ISSUE THREAD

**Issue by themood54** [kentcdodds/ama#20]
Hello sir, you said you like to help and i sure could use some help. I am the owner of freelivecam2camgirls.com and it is a web site that helps people  sexy people become internet stars. I have been held back from opening the site for real for 3 months. Because it is crusial that on my site or application linking to my site I can run the youtube api. I need to do broadcast setup video upload, Well just about all the api ver3 options for you tube I can get. I have taken the samples ran it in eclispse using maven for the java and i get a clean no error command line program that works no place except on my computer. I try to get it into a wen app or service using many many techniqes but it always fails. I have also done the api in pythone, .php. java, and google app scripts but i cant get the last part everytime i get stuck. I really really need this. I i am just missing a tiny "doget line on app scripts and or a tiny bit of help on the java end. Can you please please help me?

**Comment by kentcdodds** [comment]
Based on the URL and your description of the website, I believe it is in opposition to my moral standards. So I'm not interested in helping to push that along. Perhaps I should add that as a guideline in the readme. I hope you find something more wholesome to do with your skills and abilities.

**Comment by themood54** [comment]
El 2015-07-12 11:51, Kent C. Dodds escribió:
> Closed #20 [1].
> 
> --
> Reply to this email directly or view it on GitHub [2].
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/kentcdodds/ama/issues/20
> [2] https://github.com/kentcdodds/ama/issues/20#event-353821261

you can't actually be making a living on the internet and be that 
biassed. My friend you need me more than i need you. Your school 
learnings have led you astray. You can write code better than I. But you 
have no idea how to make that ode make millions. My site if you had 
opened the page does not allow nudity or sex in any way. It's a internet 
youtube facebook star makers. it makes you famous. These are the things 
please i'm not being mean that the school does not teach you. You think 
you know what i'm talking about but you don't. I make millions online 
every year. Without writing more than ten lines of code. I am not being 
confrontational I am stating facts. You need me more than i need you. 
You did not even see the millions of dollars in the two lines of code 
you needed to write. It's ok not many do that's why i make the millions. 
Before you close me out unless make millions and barley work you should 
think about getting to know me. I didn't really need the help but i 
checked you out and your your good programmer and qualified in 
particular areas i need. But the hardest part is finding someone who is 
not so arrogant. because as far as the internet is concerned i know more 
than you. Yet I know nothing about the internet. don't judge on spell 
check i had to look stupid in the first email. I am actually quite 
proficient  with net beans eclipse google scripts and everyother 
fricking program or gadget online. each app I write gets between 3000 to 
10000 downloads a day just cause made it no matter what it is. yes easy 
to prove i'll show my my google dev console stats i'm on vacation in 
cancun it was all in spanish first so sorry if it's still a bit messy
Now just hear me out i want to work with you. But you actually said in 
your email that the number one topic and largest change that has ever 
happened on the internet was something you did not want to work in???

If you don't want to work with social stars and sponsors and youtube and 
facebook an live video interaction well you will need to find a new job 
this is the internet now.

So give it some thought correspond a bit you will be amazed to learn as 
i was the real internet.
