### ISSUE TITLE
ReactJS Components Performance Testing

### ISSUE THREAD

**Issue by QAInsights** [kentcdodds/ama#200]
Hi Kent,

Can you please share your inputs on how to performance test the ReactJS components? Thanks!

**Comment by kentcdodds** [comment]
Hi @QAInsights,
I haven't really had to do much consideration of performance with React. It's never been my bottleneck. You'll normally get your biggest bang for your buck focusing on reducing the amount of code you're sending to the browser.

However, I saw an interesting talk about this at React Rally: [Scaling React to Accelerate Life Science Research](https://youtu.be/Had9nU9N7-0) by @saifelse. Good luck!
