### ISSUE TITLE
Do you script your content?

### ISSUE THREAD

**Issue by felixsanz** [kentcdodds/ama#202]
I've watched you egghead videos and they're great, thanks for the content!. I also have a question for you.

For example in the **How to Write an Open Source JavaScript Library**, do you really have memorized everything, like istanbul commands, babel, travis, etc, or you use your general knowledge plus a script previously written for every individual video?

Your pace seems natural, like you really know everything in the course. I ask it because I have curiosity since I have trouble myself memorizing that many tool commands and workflows. It's just me? :stuck_out_tongue_closed_eyes: 

Thanks!

**Comment by vitkarpov** [comment]
Once my wife asked me the same question: how you can remember all "the commands" (she meant css props and values), there's a ton of them! It's not so hard when you're doing this all the time :)

**Comment by sapegin** [comment]
@vitkarpov I disagree! 😝  It’s very hard, at least for me. But the good thing: you don’t have to remember everything, it’s usually very easy to check the docs using Dash, StackOverflow or just Google.

**Comment by vitkarpov** [comment]
@sapegin Good point! Google helps a lot ;)

**Comment by felixsanz** [comment]
@vitkarpov Yes, but you don't setup istanbul 40 times a day, don't you? CSS, HTML, and programming languages is normal. I mean, I know how to create a function in JS or how to apply borders in CSS, because as you say, you repeat that task looooot of times. But setting up this tools is not repetive and most times you just copy/paste from another project, so you don't even type it more than once

**Comment by vitkarpov** [comment]
@felixsanz I agree. Seems, we found the real answer deductively, as you already said "script previously written for every individual video" :)

**Comment by felixsanz** [comment]
Well we don't know yet :P maybe he really knows that stuff by memory! After all, the courses require preparation so maybe he already mastered it and is not scripted!

**Comment by kentcdodds** [comment]
Hey friends! Sorry it's taken me awhile to get to this.

> do you really have memorized everything, like istanbul commands, babel, travis, etc, or you use your general knowledge plus a script previously written for every individual video?

It really depends. I really do know many of these tools really well. Preparing an egghead.io lesson takes a LOT of time. So I get really familiar with the process. I'm also pretty darn active in open source, so I have a lot of experience with these tools from that as well. Also, I often end up doing a few takes of the video, so I even get practice as I go.

Most of [my lessons](http://kcd.im/egghead) were recorded typing and talking at the same time. But sometimes I _do_ script what I _say_. In fact, for all of [my Jest lessons](http://kcd.im/egghead-jest), I recorded what I was going to say first and then played it back in my headphones and typed as I listened to myself talking, then synced it up later.

As for the _code_, I pretty much _always_ have that thought out and ready before hand. And I'll often have a git diff or the final result open on another screen that I can reference as I'm recording.

> Your pace seems natural, like you really know everything in the course.

Thank you! I really _do_ know what I'm talking about in the courses. My goal is to be as minimally distracting as possible so you can focus on learning and not get distracted by me making mistakes or something. So I re-record if I make mistakes or edit out little mistakes.

I'm glad that you're enjoying and learning from my stuff. That's my goal!
