### ISSUE TITLE
Advice on testing setup for UI development

### ISSUE THREAD

**Issue by vgvenkat** [kentcdodds/ama#203]
At work we are starting to implement a stricter testing process for web dev, previously we did not enforce policies as most of our team's work was concept spikes. I would like your advice on 

- Strict integration/unit testing /code coverage libraries and frameworks. 
- Sticking to js/css styleguides both in editor(mostly in sublime and atom) and build pipeline. 
- We are planning to support  FF/ IE 11 and Edge/ Chrome

We are in Angular 1.x and are moving to React/Redux and mainly do enterprise applications. Any advice on frameworks, how to get started on an enterprise level would be helpful. Mainly to help developers think in TDD ways.

**Comment by kentcdodds** [comment]
Hi @vgvenkat,
For Angular 1 apps, I recommend:
- Unit testing: [Karma](https://karma-runner.github.io), [mocha](https://mochajs.org/), [babel-plugin-__coverage__](https://github.com/dtinth/babel-plugin-__coverage__). [This might be helpful](https://youtu.be/P-1ZZkpEmQA) though don't use isparta, use `babel-plugin-__coverage__` instead.
- I'm not sure about css styleguides much, but for JS stuff, definitely use [ESLint](http://eslint.org/)

Your browser support looks typical.

Good luck to you!

**Comment by vgvenkat** [comment]
Hi @kentcdodds Thank you for the detailed reply, I guess I should have given more emphasis on the moving to react part. We are doing react now and not Angular 1 any more. Would all of these make sense in the React world?
