### ISSUE TITLE
Would like to get some feedback on my libraray

### ISSUE THREAD

**Issue by k15a** [kentcdodds/ama#204]
Hey Kent,

I'm following you for a while and totally love what you're doing.

I recently published a CSS in JS library. In my opinion it combines the best of styled-components and CSS Modules. It would mean a lot for me if you could provide me some feedback.

The library is released at https://github.com/k15a/sprayer and I created an example at https://github.com/k15a/react-sprayer-example which uses my library to style React components.

Thanks,
Konstantin

**Comment by kentcdodds** [comment]
Hi @k15a,
Thanks for reaching out to me. I gotta say that I'm not a huge fan of template strings for CSS (or HTML for that matter). I'd much rather just have everything be JavaScript. JavaScript can be linted, syntax highlighted, and it's a real programming language where I get a lot of power. I've pretty much settled on aphrodite for my CSS in JS solution, and until I reach some point that it's not serving me well enough, I'm going to keep using it.

Good luck though!
