### ISSUE TITLE
Least favoured programming language

### ISSUE THREAD

**Issue by CarlMungazi** [kentcdodds/ama#207]
Of all the programming languages you've used, which one do you dislike the most and why?

**Comment by kentcdodds** [comment]
Hi @CarlMungazi,
Thanks for the question! Hmmm... Honestly, I haven't had a lot of opportunity to code with other languages to be able to give solid reasons why I like or dislike them. I'm 99% a JavaScript developer.

However, in college, I did some C programming and I found it tedious. I'm really happy to not have to code in C and worry about pointers and such!

Thanks for the question!
