### ISSUE TITLE
How do you test with Aphrodite?

### ISSUE THREAD

**Issue by jkup** [kentcdodds/ama#210]
Hey Kent,

We're considering adoption of Aphrodite at Brave but one thing I've been wondering about is how to manage tests (specifically webdriver). Right now we use class selectors for all of our webdriver tests but since Aphrodite will generate class names we'll have to change up our approach.

Do you have any advice for how to handle this?

**Comment by kentcdodds** [comment]
Hi Jon!
Excellent question. Here's my take on it. Often you'll hear that one problem with classes that they're used improperly. You start out using them to style things, then you overload the purpose of your class name by querying your DOM for those classes to attach an event listener or something right? I think that querying the DOM for class names originally intended for styling for tests is the same kind of improper overloading. (Please forgive those last two sentences if they were confusing, my brain is shutting down).

Anyway, the way that I like to do testing when I need to query the DOM to find elements is by adding a `data-test` attribute to the element. It makes it very clear that this is used for testing purposes so I can avoid that overloading. This has the nice benefit of also letting future developers know that this element is used in testing and if you're making changes, don't forget to update the tests too.

So normally, I'll say: `data-test="some-sensible-identifier"`. This could be dynamic if it's in a list (like `data-test="some-item-32` where 32 is indicates it's the 32nd item in the list). Though that specific scenario is fairly easy to query for without the number.

I've done this in my unit and E2E tests and it's been pretty great for me :)

Good luck!

**Comment by kentcdodds** [comment]
Just a quick update on testing with CSS-in-JS: If you're using [`glamor`](https://github.com/threepointone/glamor) (my personal favorite now) and [`jest`](http://facebook.github.io/jest/) then you should really look into [`jest-glamor-react`](https://github.com/kentcdodds/jest-glamor-react). If you're using [`styled-components`](https://github.com/styled-components/styled-components) then checkout [`jest-styled-components`](https://github.com/styled-components/jest-styled-components). I don't see any reason you couldn't build a tool like these for other CSS-in-JS libraries. Definitely awesome.
