### ISSUE TITLE
Guide regarding motivating people to contribute to open source

### ISSUE THREAD

**Issue by mohuk** [kentcdodds/ama#211]
Hey

While following you on twitter, I have seen you as a big advocate of open source so I'd like some help on how can I motivate people in Pakistan to contribute to OSS. I am presenting in a local Google Developers event. If you have any idea or talk you can refer me to, that would be great.

cheers 😄

**Comment by kentcdodds** [comment]
Hi @mohuk,
Thanks for the question. Motivating people is hard thing to do in general. But I recently listened to an audiobook that talked about this in detail. It's called [Start with Why](http://www.audible.com/pd/Business/Start-with-Why-Audiobook/B004DJCZUW) and it's really interesting! [Here's a 20 minute TED talk](https://www.ted.com/talks/simon_sinek_how_great_leaders_inspire_action) (from the author) that summarizes the key points. I recommend giving that a read!

In addition to talking about the "why" of open source, I would try to identify the things that motivates the group and see how you could connect those motivations with results from contributing to open source. Things like:

- Giving back to the community
- Becoming a better coder
  - being exposed to other ideas
  - having your code reviewed by other people
- Getting recognized (can really help with employment)

There are many reasons to do it.

I hope that's helpful. Good luck!
