### ISSUE TITLE
Your new Webpack Workshop on Frontendmasters compared to your Webpack course on egghead

### ISSUE THREAD

**Issue by oliver41** [kentcdodds/ama#213]
Hello Kent, 

can you please explain in short where the difference is between your webpack course on egghead and now the Frontend deep dive workshop? And are they both on Webpack 2?

thanks
Oliver

**Comment by kentcdodds** [comment]
Hey @oliver41,
First off, both of these resources use Webpack 2. Much of the Frontend Masters workshop is the same as what I have on Egghead.io, however there are some updates and improvements especially with regards to hashing for long-term caching and there are some additional topics like Hot Module Replacement, debugging webpack with Chrome DevTools using `node --inspect`, using the Offline Plugin, and deploying the application to surge.sh.

I hope you enjoy it!

**Comment by kentcdodds** [comment]
Oh and by the way, the slides and associated github repo is a pretty valuable resource and also gives a good overview of the course, give that a look here: [kcd.im/webpack-workshop](http://kcd.im/webpack-workshop)

**Comment by kentcdodds** [comment]
Oh, and one other thing. The format of Egghead.io and Frontend Masters is very different. With Egghead.io, you're expected to already know why you want to use these features and you're coming to learn how. With Frontend Masters you get more of the why, the how, and a even a little bit more of an explanation. It really just depends on your learning style. For me, I generally prefer Egghead.io for my learning style. But often Frontend Masters can give you a little more info that can be helpful. I'm glad that I have access to both.
