### ISSUE TITLE
a little intimidated by open source 

### ISSUE THREAD

**Issue by shreab373** [kentcdodds/ama#214]
Hi, I'm Shreya, for the longest time i have been trying to get into open source and failed miserably and eventually given up. For the past few days i've read a lot of blogs which help a newcomer start contributing, but there always a gap between reading them actually pulling your first request, i'm familiar with C++, Java and Python, and implemented algorithms and solved problems in these languages on websites like codewars and hackerearth. but i havent done anything beyond this ie. i have never worked with any specific libraries except the standard ones, but i am interested in learning, what according to you should be my starting point? my fist contribution was nothing more than a correcting spelling errors, i am little intimidated by it at this moment.
thanks and regards.

**Comment by kentcdodds** [comment]
Hi @shreab373,
Thanks for the question. It's a pretty common one! It's common to feel a little intimidated.

If it makes you feel any better, [my first contribution](https://github.com/playframework/playframework/pull/616) was nothing more than correcting a spelling error too! You gotta start somewhere! And I find that the first PR is often the hardest, so great job with that!

So, one of the most challenging bits to getting into open source is knowing what project you should contribute to and how you can contribute for that. I wrote [What open source project should I contribute to?](http://kcd.im/what-oss) and created [How to Contribute to an Open Source Project on GitHub](http://kcd.im/pull-request). I think these two resources have been pretty helpful to many people and I invite you to give them a look.

Good luck!
