### ISSUE TITLE
Which knowledge i should prepare when I want to contribute to react project?

### ISSUE THREAD

**Issue by thaodt** [kentcdodds/ama#215]
Hi Kent, if I want to contribute to React project, could you recommend to me that i should prepare which knowledge?
I mean ES5 / 6 and anything else?

**Comment by vitkarpov** [comment]
Try to implement your own version of React (Virtual DOM ;)

**Comment by kentcdodds** [comment]
Hi @thaodt,
Thanks for the question! Could you clarify? Do you mean you want to contribute to [the React project](https://github.com/facebook/react) itself or to a project that uses React?

**Comment by thaodt** [comment]
Hi @kentcdodds , I mean I'd like to contribute to the React project. So could you please show me which knowledge I need to prepare so that I can achieve that?

**Comment by sashashakun** [comment]
I have a small [contribution](https://github.com/facebook/react/pull/6884) to ReactPerf. Really, only knowledge that i used was a twitter app for android usage🙂
Just read my feed and saw Dan Abramov's tweet about "good first contribution" opportunity.  You can start from good first bug label in react repository: https://github.com/facebook/react/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+bug%22

Just want to share some experience, hope it helps)

**Comment by kentcdodds** [comment]
Sorry it's taken me so long to get to this question.

There are actually several sections on [the React website](https://facebook.github.io/react/contributing/how-to-contribute.html) about contributing to react. I recommend you go give that a look.

<img width="155" alt="screen shot 2016-12-15 at 5 22 40 pm" src="https://cloud.githubusercontent.com/assets/1500684/21247233/30ce432c-c2eb-11e6-8cdb-898bfcd882c0.png">

As part of that, I had some tech chats with some of the React team about contributing to React that might be helpful:

- [Contributing to React JS](https://youtu.be/wUpPsEcGsg8?list=PLV5CVI1eNcJi8sor_aQ2AzOeQ3On3suOr)
- [React events in depth w/ Kent C. Dodds, Ben Alpert, & Dan Abramov](https://youtu.be/dRo_egw7tBc?list=PLV5CVI1eNcJi8sor_aQ2AzOeQ3On3suOr)

I hope that's helpful!
