### ISSUE TITLE
What tools helps you do open source and keep your sanity?

### ISSUE THREAD

**Issue by sapegin** [kentcdodds/ama#216]
Tests, linters, CI? What else? Any secret tips that makes life of an open source maintainer hundred times easier?

**Comment by kentcdodds** [comment]
Hi @sapegin,
This is a pretty big question. I answer much of it in my Egghead.io course ["How to Write an Open Source JavaScript Library"](http://kcd.im/write-oss), in my Frontend Masters workshop ["Writing an Open Source JavaScript Library"](http://kcd.im/fem-oss) (will be officially released this week I think, [here are the slides](http://kcd.im/oss-workshop)), and in my talk ["Managing an Open Source Project"](https://kentcdodds.com/talks/#managing-an-open-source-project) (which I basically give at the end of the Frontend Masters workshop).

A few changes from those though:

```diff
- ghooks
+ husky

- mocha and chai
+ jest
```

I hope this is helpful!
