### ISSUE TITLE
Are you LGBTQ+ inclusive, friendly and accepting?

### ISSUE THREAD

**Issue by istx25** [kentcdodds/ama#218]
Especially us trans folks.

**Comment by vitkarpov** [comment]
@istx25 , sorry for maybe personal/silly question (I'm from Russia and this problem, seems, hasn't come yet).

Does LGTB community face some issues with employers or have some troubles with clients as entrepreneurs? More accurate formulation may be "how much do such personal things relate to work life?".

**Comment by kentcdodds** [comment]
@istx25,
Thanks for the question! Yes I am. I try hard to make [my language](https://twitter.com/kentcdodds/status/766825287124340738) and actions inclusive everyone. I regret to say that as a kid I fell into the trap so common for kids at that time of unintentionally hurting individuals with my casual language and I'm working hard to stop that and encourage my children to be more inclusive, friendly, accepting, and thoughtful than I was. My kids are pretty young, but so far so good :)

Thank you for being part of the community!

P.S. Thanks again for the question, it reminded me that I've been meaning to add a [Code of Conduct](https://github.com/kentcdodds/ama/blob/master/CODE_OF_CONDUCT.md) on this repo :)

**Comment by istx25** [comment]
@vitkarpov,

Not a silly question but it definitely is a problem in Russia. I guess the government and media just aren't as open or cover the problems as much in Russia as foreign media outlets cover LGBTQ problems in Russia quite a lot. Peopl

A helpful table from [Wikipedia](https://en.wikipedia.org/wiki/LGBT_rights_in_Russia):

|   |  Notes  |
|---|---|
| Same-sex sexual activity legal  | ✅ Yes, since 27 May 1993  |
| Equal age of consent  | ✅ Yes, since 27 May 1993  |
| Freedom of expression  | ❌ Federal ban on distribution of "propaganda" for "non-traditional" relationships to under 18s; some regions have legislation banning "propaganda of homosexuality, bisexuality and/or transgenderism" |
| Anti-discrimination laws in employment | ❌ No |
| Anti-discrimination laws in the provision of goods and services | ❌ No |
| Anti-discrimination laws in all other areas (incl. indirect discrimination, hate speech) | ❌ No |
| Same-sex marriage(s)	| ❌ No |
| Recognition of same-sex couples | ❌ No |
| Commercial surrogacy for gay male couples | ❌ No |
| Adoption by single homosexuals in Russia or (in case of Russian children) in foreign countries that do not recognise same-sex marriage | ✅ Yes, no legal restrictions based on sexual orientation for single people to adopt. |
| Adoption of Russian children by single homosexuals or same-sex couples in foreign countries that do recognise same-sex marriage| ❌ No, illegal since 3 July 2013.
| Step-child adoption by same-sex couples	| ❌ No |
| Joint adoption by same-sex couples|	 ❌ No |
| Conversion therapy banned on minors| ❌ No |
| Gays allowed to serve openly in the military| ✅❌ Yes, gay people can serve in the military, however, there is an unofficial "Don't ask, don't tell" policy. |
| Right to change legal gender| ✅ Yes, since 15 November 1997. |
| MSMs allowed to donate blood|	✅ Yes, since 16 April 2008. |

And a law was passed that allows police to arrest and jail people _for public displays of non-heterosexual orientation or gender identity_. Source: https://www.hrw.org/news/2016/01/14/dispatches-jail-time-being-gay-russia

**Comment by istx25** [comment]
Thanks for your response, @kentcdodds! Glad to hear it.

**Comment by vitkarpov** [comment]
@istx25 yep, I get it. And is the situations not different in where you're from?

@kentcdodds according to words in your tweet, why "guys" isn't acceptable? I mean, if there're girls among them it's incorrect?

**Comment by istx25** [comment]
@vitkarpov: The situations are a lot better in [Canada](https://en.wikipedia.org/wiki/LGBT_rights_in_Canada) (where I'm from) and [Germany](https://en.wikipedia.org/wiki/LGBT_rights_in_Germany) (where I live). See the summary tables for both in comparison.

**Comment by kentcdodds** [comment]
@vitkarpov, the term "guys" is not gender-neutral. I try to avoid using gender-specific language when addressing groups of mixed gender. It's tough to break that habit, but it's a small price for me to pay to know that my language is more inclusive and welcoming.

**Comment by istx25** [comment]
@vitkarpov @kentcdodds: I'm going to chime in about the gendered language as well. Guys is still widely used in all of the countries we're from but it should be less accepted than it is. Guys is informally defined as "noun; a man." If the group is 100% male (identified) people then sure, there's no problem but when there's a mixed gender pool (both men and women) then it's problematic because you wouldn't say "hey girls" to a group of men and women. The men would be offended. Why? misogyny. Through socialization and society, men are taught that being compared a woman or called a woman is a bad thing. It's not your fault persay but more the people who raised this generation and the generation before that one that instilled these negative notions.

On top of that, I am a woman-leaning non-binary trans person. I identify more as a woman than as a man, but I primarily identify as neither. So in those cases, guys and girls to refer to a group isn't great or respecting our identities. So folks, y'all and other genderless/gender neutral expressions are better to reduce discomfort and show people you're more inclusive than others.
