### ISSUE TITLE
Where do you draw the line between snapshotting and not with Jest?

### ISSUE THREAD

**Issue by elderfo** [kentcdodds/ama#219]
I guess I am going to start by sharing my experience and see where the discussion goes.

I recently forked a project that had minimal tests. The ones it had were integration tests and even then, a few of them didn't work (they were old and not maintained as the API evolved). Being a new codebase, I knew I needed to get test coverage before I could go in there and start mucking with stuff. So I set off with Jest (my new fav.).

In reviewing code and writing tests, I found that a lot of the structures in the project were constant and/or were intended to have immutable state after construction. I handwriting quite a few tests on the immutable state, it was tedious and somewhat brittle (what if I add a prop?). These seemed like good candidates for snapshots. So I converted and composed the state tests as snapshots.

As I moved past the state test and into functional/unit testing, I started using snapshots and while I realize, the tests will be accurate (I mean the API does already do what it does), I was not learning about how things worked in the project. It felt like I was cheating.

Anyways, I would love to hear thoughts on this.

**Comment by kentcdodds** [comment]
Hi @elderfo!
This is a great question! And one that [I've had](https://twitter.com/kentcdodds/status/775818897098354688) myself. Actually, if you look through that thread I just linked to, you'll see that I find a pretty solid answer [here](https://twitter.com/kentcdodds/status/777985815854981121) in @benmccormick's blogpost entitled ["Testing with Jest Snapshots: First Impressions"](http://benmccormick.org/2016/09/19/testing-with-jest-snapshots-first-impressions/)

Specifically these lines:

> Classic assertion based tests are perfect for testing clearly defined behavior that is expected to remain relatively stable.

> Snapshot tests are great for testing less clearly defined behavior that may change often.

Great principle to go by. Just remember that snapshots are just another type of assertion that you just happen to create and update differently.

So for your specific case, I'd say that I've actually felt the same (like I was cheating). But honestly, I think that snapshot testing is great for your use case. You're uncertain what the output should be, so you just snapshot it all to make sure you don't change it as you're refactoring. As you do your refactor, you'll learn more about what the output should be and you can update the snapshots and you can also start to make classic assertions for the parts of the behavior that's more fixed and defined.

I hope this is helpful! Good luck!

**Comment by elderfo** [comment]
@kentcdodds, thanks for your comments! 

That is a very good article. I stumbled on to it about the time your were probably typing that. 🙂 

>Classic assertion based tests are perfect for testing clearly defined behavior that is expected to remain relatively stable.

I somewhat naturally landed on this by going picking a strategy and seeing what happens. The project had a few deeply nested control structures that really had to tested at a more granular level so they got classic assertions. Jest's code coverage really help shake that out. 

All in all, this was a fun experience!

**Comment by kentcdodds** [comment]
I was asked this again and answered with more detail in a 3 minute podcast: https://github.com/kentcdodds/ama/issues/275

**Comment by elderfo** [comment]
Thank you!
