### ISSUE TITLE
What are the plans for formly in Angular 2?

### ISSUE THREAD

**Issue by enzolamzo** [kentcdodds/ama#22]

**Comment by kentcdodds** [comment]
Tune in tomorrow to find out :-) https://plus.google.com/events/c5k02na22bq5k5ftg63bqpvtteo

**Comment by kentcdodds** [comment]
I talked about this in today's Angular Air episode:
http://bit.ly/ng-air-formly

Basically, I plan to make an angular2-formly which should have as minimally
breaking changes as possible. I have yet to try anything though, so stay
tuned!

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by enzolamzo** [comment]
Yes, I watched it! Great stuff. Thanks for the amazing job!
