### ISSUE TITLE
Working from home

### ISSUE THREAD

**Issue by elderfo** [kentcdodds/ama#223]
@kentcdodds, I see that you work from home. I am sure that helps with all your other ventures, not being tied to an office all the time. I look forward to being a remote employee again (starting in Jan 2017). Enough about me...

I have a few questions around working remote, how do you keep yourself from working non-stop? Do you work a set scedule, or do you break it up throughout the day?

I didn't realize PayPal allows remote work, I know there was a push a few years back in some larger corporations to reduce that (Yahoo and my former company LexisNexis reduced remote numbers). How large is PayPal's remote workforce? Is there any concern about job security being remote?

Thanks as always for everything you do.

**Comment by vitkarpov** [comment]
> I didn't realize PayPal allows remote work

Kent said once that it's an unique case :)

**Comment by kentcdodds** [comment]
Hi @elderfo,
Thanks for the questions :)

> how do you keep yourself from working non-stop?

It's not all that hard. I'm married and have three kids. I can't wait to see them at the end of the day :) Also, I have a lot of other side-projects I like to work on too. So as soon as the day of work is done, I'm excited to hangout with the family, and if I get a chance to code again, I'll work on my own stuff.

> Do you work a set schedule, or do you break it up throughout the day?

I work on a fairly normal schedule. I start at around 9:00ish AM, I take a lunch break (with my family) at around noon, and I wrap up at around 5:00ish PM.

> How large is PayPal's remote workforce?

I can't really speak officially about PayPal's remote workforce, but I can tell you that out of the ~8,600 people we have on slack, only about 10 are in the remote slack channel (that's not at all to say every remote employee is in that channel). As @vitkarpov mentioned, my case is fairly unique.

> Is there any concern about job security being remote?

If there is, it's only slightly. Remote work comes with some unique challenges. Your boss doesn't see you working hard in the office. It's easy to get left-out/overlooked in meetings, etc. But if you keep yourself vocal, review PRs, and contribute well, I don't think you have too much to fear.

Good luck!
