### ISSUE TITLE
What inspires you?

### ISSUE THREAD

**Issue by sholladay** [kentcdodds/ama#224]
You know, the reason you get up in the morning and do what you do. Could be in general or specifically about coding - whatever inspires you most.

And relatedly, what is your reaction / desired outcome from said inspiration?

**Comment by kentcdodds** [comment]
Hi @sholladay,
Thanks for reaching out to me! This is a great question that requires a good deal of introspection.

In thinking about it, I'm motivated by several things. But to really figure out the core of what motivates you, I think it's good to think of times when you've been in your lowest place and consider what it was that pulled you through and helped you back on your feet.

Despite my privilege, I've been in pretty low places in my past. And what's pulled me out of those situations has always been my faith in Jesus Christ and the knowledge that if I follow [His example](https://www.lds.org/general-conference/2009/10/our-perfect-example?lang=eng&_r=1) and emulate [His attributes](https://www.lds.org/youth/video/christlike-attributes?lang=eng), I'll be happy and ultimately live with my family (with whom I've been [sealed](https://www.lds.org/ensign/2011/09/the-sealing-ordinance-links-families-eternally?lang=eng) [in the temple](https://www.lds.org/church/temples/why-we-build-temples/what-happens-in-temples?lang=eng)) forever. That knowledge can get me through anything. I know that whatever happens to me or my family, all will be made right through the [Atonement of Jesus Christ](https://www.lds.org/topics/atonement-of-jesus-christ?lang=eng).

This faith actually motivates me to do much more than simply "be nice" and go to church. It influences every aspect of my life. I'm following [the Savior's teachings](https://www.lds.org/bible-videos/videos/the-parable-of-the-talents) and [example](https://www.lds.org/scriptures/nt/luke/2.52?lang=eng#51) when I work hard to improve my talents and keep myself productive. That includes the coding that I do. I'm inspired by the Savior's ability and focus on teaching. I'm inspired by His welcoming, respectful nature and love for everyone regardless of whether their background, beliefs, or actions are the same as mine.

And it's not just learning of Him and faith in Him either. I have actually seen His influence change people's hearts (my own included). I have seen (and performed) miracles in His name with [God's priesthood power](https://www.lds.org/topics/priesthood?lang=eng). Many of these have been incredibly personal and powerful experiences.

> And relatedly, what is your reaction / desired outcome from said inspiration?

My desired outcome from this inspiration is happiness. Happiness for myself, my wife and children, my brothers, sisters, and parents, my friends, and anyone with whom I interact. And not the fleeting happiness you feel when you hear a funny joke, but true and lasting happiness. Eternal happiness. And I firmly believe that while I can really only control this for myself, it most certainly can be mine if I follow my inspiration. My Lord and Savior, Jesus Christ.

Thanks for the question and opportunity for introspection :)
