### ISSUE TITLE
Couple of questions, react related.

### ISSUE THREAD

**Issue by luiskhernandez** [kentcdodds/ama#229]
If you were start a react app, and you know you will need change somethings in the webpack configuration. Would you still use create-app, or create the webpack setup from scratch?

What would you use for Form? redux-form? or something else?

I know more of the tools depends on the project, but according of your experience. What would you choose? Thanks.

**Comment by kentcdodds** [comment]
Hi @luiskhernandez,
Thanks for the questions.

> Would you still use create-app, or create the webpack setup from scratch?

If I knew I was going to change the config, I'd probably write it from scratch. I'm pretty comfortable with webpack. And I also like understanding all the decisions that were made when the code was written.

> What would you use for Form? redux-form? or something else?

I've yet to have a form-heavy application. So I don't know what the landscape of forms with React is like. Sorry.
