### ISSUE TITLE
Why people stress to use Immutable structures in javascript ?

### ISSUE THREAD

**Issue by annamalai-saro** [kentcdodds/ama#23]

**Comment by kentcdodds** [comment]
Immutability brings a ton of really awesome architectural improvements to JavaScript applications that makes it easier to reason about your application's state/data. It also comes with some major performance improvements. Here's a good overview: [Immutability in JavaScript](http://www.sitepoint.com/immutability-javascript/) by @cjohansen (creator of [Sinon.JS](https://github.com/cjohansen/Sinon.JS)). Here's how it's helping Angular 2: [CHANGE DETECTION IN ANGULAR 2](http://victorsavkin.com/post/110170125256/change-detection-in-angular-2) by @vsavkin. Also @jhusain was recently on [JavaScript Jabber](http://devchat.tv/js-jabber/168-jsj-the-future-of-javascript-with-jafar-husain) and talked a little bit about why Immutability is a great approach to building UIs.

**Comment by annamalai-saro** [comment]
Thanks !
