### ISSUE TITLE
How do you map node_modules/.bin?

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/ama#230]
@ericdfields [asked me](https://egghead.io/forums/1/topics/use-jest-s-interactive-watch-mode):

> Can you share how you mapped global `jest` to your local `node_modules/jest/bin/jest.js`?

This is in reference to what I say at the start of [this video](https://egghead.io/lessons/javascript-use-jest-s-interactive-watch-mode?pl=testing-javascript-with-jest-a36c4074) on Egghead.io.

[![jest-node_modules](https://cloud.githubusercontent.com/assets/1500684/20978396/00c95ca6-bc66-11e6-9d56-2a97f5682da0.png)](https://egghead.io/lessons/javascript-use-jest-s-interactive-watch-mode?pl=testing-javascript-with-jest-a36c4074)

I posted it here because this isn't the first time someone's asked me and I'd rather that this is the last time I answer :)

**Comment by kentcdodds** [comment]
I decided to answer in the form of a video/live stream here: https://www.youtube.com/watch?v=2WZ5iS_3Jgs

**Comment by ericdfields** [comment]
So helpful. Thank you!
