### ISSUE TITLE
Node.js API Documentation?

### ISSUE THREAD

**Issue by amandeepmittal** [kentcdodds/ama#234]
Hello Kent,

Wanted to ask you, do you document (REST) API for your Nodejs projects? If yes, then which tool do you use?

**Comment by kentcdodds** [comment]
Hey @amandeepmittal,
Thanks for the question. I haven't really faced this problem personally. Sorry :-/ Not sure where to direct you. Good luck!

**Comment by amandeepmittal** [comment]
Thank you for your time.
