### ISSUE TITLE
Kickstarting node.js for Alexa skill development

### ISSUE THREAD

**Issue by sangeethakp** [kentcdodds/ama#235]
Hi Kent!
I want to develop a skill for Amazon Echo, Alexa. Documentations and blogs over the Internet suggest me to go ahead with Node.js to do this. But I am not very proficient in JS and Node. I am a Java developer. What would be the best approach to approach this? I have heard that JS is Vast and trying to comprehend Node without understanding of JS is tough. Can you kindly shed some light on this?

Many thanks and a happy new year! :)

**Comment by kentcdodds** [comment]
Hey @sangeethakp!
Thanks for reaching out to me! I've never personally developed a skill for the Amazon Echo (though, something tells me that @djsmith42 would know a thing or two about it 😉). If what I've heard is true, Node is a great way to go to develop skills. So for getting your JS skills up, I can't recommend @getify's ["You Don't Know JS"](https://github.com/getify/You-Dont-Know-JS) series enough (free to read on GitHub). He's great at teaching JS and this is a great series. He's also got some great stuff on [Frontend Masters](https://frontendmasters.com/). It's pretty comprehensive! You may also find [my talk at ForwardJS](https://youtu.be/-qPh6I2hfjw) interesting.

One thing that I'd recommend you avoid is getting too caught up on JavaScript tooling. There's a LOT there and it's really useful. But for someone getting going, it can become overwhelming. Try to stick with normal JS until you really feel like you need tooling help.

Best of luck to you!
