### ISSUE TITLE
How to distribute a library with static assets?

### ISSUE THREAD

**Issue by gaastonsr** [kentcdodds/ama#239]
I'm building a library that uses some static assets. The library is then used into different applications.

How do I distribute my library and its assets, so that it's easy for the other applications to use it with its assets?

Thanks!

**Comment by kentcdodds** [comment]
Hey @gaastonsr,
Thanks for the question.

> How do I distribute my library and its assets

There are tons of ways to do this.

> so that it's easy for the other applications to use it with its assets

I'd say the easiest way I've found to do this is with webpack and its loaders. Especially if the assets are small, webpack can inline them (like turn small images into Base64 encoded strings) and then all people have to do is include your `bundle.js` file and that's it. If the files cannot be inlined then you'll be left with additional files in our output directory and people will just need to make those files available on their own servers (by copying the files over in some way).

Sharing assets can be a challenge if they can't be inlined. And there are many ways of doing this. I'm afraid I don't have any examples personally that I could point you to. Best of luck to you!
