### ISSUE TITLE
What are you Intellij hotkey settings and live templates?

### ISSUE THREAD

**Issue by ksrb** [kentcdodds/ama#24]
Hey watched some of your videos on [egghead](https://egghead.io/lessons/javascript-intro-to-webpack) and youtube and noticed you've got some interesting JS templates, any chance on sharing them :smiley: ?

**Comment by kentcdodds** [comment]
Fantastic question! I'm on vacation right now, but I'll get back to you next week.

**Comment by ksrb** [comment]
Cools thanks!

**Comment by kentcdodds** [comment]
Hi there! Sorry this has taken so long! Here are some resource for you:

- Some of my [live templates](https://www.jetbrains.com/webstorm/help/live-templates-2.html): https://gist.github.com/kentcdodds/f29f6b74055561aa9b76
- My dotfiles (for bash shortcuts and prettyness, etc.): https://github.com/kentcdodds/dotfiles
- My [WebStorm Settings](https://www.jetbrains.com/webstorm/help/exporting-and-importing-settings.html) (beware, there's a bit of customization in here. I recommend exporting yours first, just in case): https://drive.google.com/a/doddsfamily.us/file/d/0BxZDtibcRzVWTWpoQ1otOEV6c2c/view?usp=sharing

**Comment by ksrb** [comment]
No problem thanks!
