### ISSUE TITLE
What do you think about React license?

### ISSUE THREAD

**Issue by ValentinH** [kentcdodds/ama#240]
From what I can see from your tweets/talks/etc. you are a React user and also work for a big company, Paypal.

Is the React licence and all the stuff about patents (https://news.ycombinator.com/item?id=12108158 and https://github.com/facebook/react/issues/7293) something that could be a issue for you? What about Paypal?

Thanks by advance :)

**Comment by kentcdodds** [comment]
Hey @ValentinH,

Thanks for the question. The honest answer is that I haven't spent much time investigating it myself and I don't know whether PayPal's lawyers have looked into it (I imagine they have, but no idea). Could it be an issue for me or PayPal? I don't know. Hopefully not. In the meantime, I'm just going to enjoy coding up some sweet React stuff :)

Sorry if that's not really helpful :-/

**Comment by ValentinH** [comment]
Thanks for the answer! ;) 

Indeed, " enjoying coding up some sweet React stuff" looks good to me! ^^

I just wanted to ask since I've heard some companies that don't want to use React for this reason but I don't know if they are overreacting or not..

**Comment by marcusnielsen** [comment]
Reference: https://twitter.com/dan_abramov/status/766210972776337408 .
So basically, you are fine.
Also, I'd add a personal reflection that you have Preact and others as almost drop-in replacement fallbacks.
