### ISSUE TITLE
My Framework (on top of express.js)

### ISSUE THREAD

**Issue by bougarfaoui** [kentcdodds/ama#242]
Hello Mr.Kent,

I'm houcine [https://twitter.com/Bougarfaoui07](https://twitter.com/Bougarfaoui07) , firstly thank you for the good work secondly I'm working on a small framework in typescript and on top of express here is the repo link : 
[https://github.com/bougarfaoui/back](https://github.com/bougarfaoui/back)
It's my first repo and I like to know your opinion of my work and some advice, also I'have a problem with .d.ts files I don't  get the auto completion.

Thanks.

**Comment by kentcdodds** [comment]
Hi @bougarfaoui,
I haven't had a chance to really use it or anything, but actually I've got quite a bit of info on this kind of thing:

- [How to Write an Open Source JavaScript Library](https://egghead.io/courses/how-to-write-an-open-source-javascript-library) on [egghead.io](https://egghead.io)
- [Creating an Open Source Library](https://frontendmasters.com/courses/open-source/) on [Frontend Masters](https://frontendmasters.com)
- [Managing an Open Source Project](https://kentcdodds.com/talks/#managing-an-open-source-project) (so far the only recording is a practice run at a meetup, I'm sorry about that).

Actually that talk is probably the most relevant. If you have more questions after looking at that let me know!

Oh and about:

> I'have a problem with .d.ts files I don't get the auto completion.

I'm sorry, but I don't use TypeScript, so I don't know what would cause that. Good luck!
