### ISSUE TITLE
Piano Humidty System: y/n

### ISSUE THREAD

**Issue by edm00se** [kentcdodds/ama#244]
As I saw in relatively recent history on Twitter, you're a fellow baby grand piano owner. Did you invest in a humidity control system for it? If so, would you recommend it?

**Comment by kentcdodds** [comment]
Hey @edm00se,
Nope, I haven't invested in a humidity control system. Should I!? 😱

**Comment by edm00se** [comment]
I'm currently debating it. Listening to my wife play last night reminded me how out of tune it is and I had it tuned four months back. We get some significant humidity changes throughout winter, so the humidity control system would help keep it in tune regardless of the ambient humidity in the house.

I'll let you know if I invest in one.

**Comment by kentcdodds** [comment]
I'm in Utah, and I don't think the humidity changes a whole lot around here. I think I'll wait until it becomes a problem :)

**Comment by edm00se** [comment]
That's probably for the best; I don't think they're terribly cheap.
