### ISSUE TITLE
What helps you to always be so cutting edge?

### ISSUE THREAD

**Issue by calebcordry** [kentcdodds/ama#245]
I was just reading this article https://blog.flennik.com/the-fine-art-of-the-webpack-2-config-dc4d19d7f172#.e5julikus and noticed that you helped him refactor it. 

As someone fairly new to JS I am very interested in gaining expertise in the most efficient way possible. I am impressed with things like how you are able to know all the new webpack2 stuff for this article, considering how new it is. Not to mention the TC39, speaking, react stuff etc.

What do you think helps you stay on top of these things? Specifically were you just reading the webpack docs as soon as they were released? Or are there any tips you have to someone working hard to get on your level? 

Thanks in advance,
Caleb

**Comment by kentcdodds** [comment]
Hey @calebcordry!
Thanks for the question. It's a good one! I talk about it a little bit in my talk: ["Zero to 60 in software development: How to jumpstart your career"](https://kentcdodds.com/talks/#zero-to-60-in-software-development:-how-to-jumpstart-your-career) and in the answer to question #89.

> Specifically were you just reading the webpack docs as soon as they were released?

Actually yes! While Webpack 2 was still in beta (about a year ago or so), I was working on an [Egghead.io series](http://kcd.im/egghead-webpack) and [Frontend Masters course](http://kcd.im/fem-webpack) about Webpack 2. So I was staying pretty close to the changelog and [this gist](https://gist.github.com/sokra/27b24881210b56bbaff7) was really helpful! I've been using and teaching about Webpack for over two years now.

> any tips you have to someone working hard

My best tips I share in that talk I referenced above. I can't stress enough how valuable building and teaching has been to my personal learning. I never would have known as much as I do without doing those things.

Good luck to you Caleb!

**Comment by calebcordry** [comment]
Thank you!
