### ISSUE TITLE
Learning new tech/working on side projects

### ISSUE THREAD

**Issue by atishaybaid** [kentcdodds/ama#246]
What should be the correct approach to learn some new tech skill(web frontend)?

I always wanted to  learn by building  something as a side projec,t using the latest technologies.
The concern which i face is what should i build?And where can i get apis,designs etc for that project?
for example i wanted to dig deep into progressive web apps,so to build a pwa i needed some https supported apis,a design for the app,and then i could focus on developing the frontend using the progressive frontend technologies,but even after browsing a lot on google i didn't find any suitable open source api/design which i can use and focus on frontend stack rather on focusing about what i should build,what its design should be.

In general what is your approachwhen you want to learn something new such as progreesive web app.

**Comment by kentcdodds** [comment]
Hey @atishaybaid,
Thanks for the question! [Here's my answer](https://www.briefs.fm/3-minutes-with-kent/37) in 3 minute audio format!

**Comment by atishaybaid** [comment]
thanks for the answer.
