### ISSUE TITLE
Are you available for a day of consulting/discussion?

### ISSUE THREAD

**Issue by joelbdavis** [kentcdodds/ama#25]
I attended your Formly workshop at ng-conf 2015, have been following you on Twitter ever since, and have become a fan of your energetic, humble, thoughtful approach to things.

We are putting together an internal "unconference" to look for ways to improve our development development process. I think we would benefit greatly from getting an outside perspective on how somebody else is doing things (adding Webpack, transpiling, modules, etc. to our AngularJS project)

I know you have a full time job, but I can't think of anybody I'd rather spend a day discussing all things JS with.

**Comment by kentcdodds** [comment]
Wow, now that's quite high praise! Thank you! Looking at your avatar, I believe I remember talking with you while we were waiting in line for lunch (sorry if I got that wrong).

I might be interested in something like that. There's nothing I love more than chatting it up with people about JS. Feel free to email me at my github-listed email address :-)

**Comment by brutalcrozt** [comment]
@kentcdodds i already sent email. You may make new `gitter` for this dude?
i really glad if i can chase you level. I am you fans too.
i just know promise on javascript, and i don't know what things next i have to learn about javascript.
Can you see me the way dude, the path which i have to pass bit by bit? please?
i really waiting your answer.
Thanks :)
