### ISSUE TITLE
Most productive programming language

### ISSUE THREAD

**Issue by CarlMungazi** [kentcdodds/ama#251]
Which programming language are you most productive in? What is your favourite feature of that language?

**Comment by kentcdodds** [comment]
Hey @CarlMungazi,
Thanks for the question! I'm definitely most productive in JavaScript. I got my start in Java (see #1) but only spent a little time there. I've also done some Perl, Python, Ruby, PHP, and others, but only a tiny bit. I've spent WAY more time doing JavaScript and I love it.

My favorite feature of JavaScript is ... Hmmm... That's a really hard one! I'd have to say the fact that functions are first-class citizens in the language. That was one thing that took me a while to understand when I started (coming from Java), but once I got it, it opened a whole new world of possibilities. I'm very fond of closures in JavaScript and the fact that you can pass functions around just like anything else. Very cool feature :)

Thanks!
