### ISSUE TITLE
NPM Package Best Practices

### ISSUE THREAD

**Issue by ALeonard90** [kentcdodds/ama#253]
Hey Kent,

It's really cool that you have this AMA!  

I have been tasked to investigate npm package best practices for a side project at work and thought you'd be a good person to reach out to. Any insights/articles/talks you can share would be much appreciated.

Thanks for your help.

**Comment by kentcdodds** [comment]
Hey @ALeonard90!
Thanks for the question! Here are a few resources:

- [How to Write an Open Source JavaScript Library](https://egghead.io/courses/how-to-write-an-open-source-javascript-library) - by me on egghead.io (free)
- [Creating an Open Source JavaScript Library](https://frontendmasters.com/courses/open-source/) by me on Frontend Masters (subscribers only)
- [Open Source Guide](https://opensource.guide/) - amazing new resource!
- [Tips for making a CLI based tool with node](https://medium.com/@kentcdodds/tips-for-making-a-cli-based-tool-with-node-9903255c2a3b)

I hope that's helpful!

**Comment by ALeonard90** [comment]
All great resources. Thanks again, Kent. Hope you have a great rest of your week!

**Comment by sapegin** [comment]
Here’s one more:

* [Authoring Packages](https://survivejs.com/webpack/advanced-techniques/authoring-packages/) from SurviveJS.

**Comment by ALeonard90** [comment]
Thanks @sapegin
