### ISSUE TITLE
How do I feel like I'm ready?

### ISSUE THREAD

**Issue by Flex-Luthor** [kentcdodds/ama#255]
I just got my first engineering job offer out of a bootcamp. I'm excited but terrified. I feel like I don't know anything and would only be a hinderance. How do I prepare myself for my first gig? How do I feel ready or at least deserving of the job?

**Comment by kentcdodds** [comment]
Hi @Flex-Luthor!
Thanks for the question. And welcome to the industry! It's a great place. One of the things I love about this industry is how quickly you can get up to speed and start contributing. I'm not saying it's easy. And I'm about as privileged as you can get so my experience was likely not representative of the average person's experience. But I can say that there are a wealth of opportunities for you to start contributing.

As for feeling ready to contribute, you have to accept the fact that you don't know everything and you'll be slower at things than other more experienced developers. But the more experience you get the better you'll be. For me, I frontloaded my experience by spending a ton of time working on things, and finding places where I could contribute. Open source played a big role in this (learn more about how to do that [here](http://kcd.im/pull-request) and [here](https://opensource.guide/)). Teaching the things that I was learning also played a big role. You can learn more about my experience from my talk: ["Zero to 60 in Software Development: How to Jumpstart Your Career"](https://youtu.be/-qPh6I2hfjw)

I hope this is helpful! Best of luck to you!
