### ISSUE TITLE
How do I "manage" my learning?

### ISSUE THREAD

**Issue by schedutron** [kentcdodds/ama#257]
I'm a college student. I want to learn linear algebra. I want to learn quantum mechanics. I want to learn common data structures and algorithms. I want to learn about integrated circuits. I want to learn about writing quality research papers. I want to learn so much. All at the SAME TIME. How do I manage my time to learn all these things effectively? I am not able to focus enough (and equally) on all of my subjects. There's so much to learn. So much detail.

Speaking of detail, how should I learn a subject, in general? The instructors often suggest a book to "follow", but it's difficult, at least for me, to complete reading a 400 or 500 page book within a semester. Are the lectures and problem sets provided by instructors enough, without a book? Should I omit following books completely? And, if I do that, would I miss out details not covered in any standard series of lectures?

My hunger for advice is soaring.

**Comment by kentcdodds** [comment]
Hey @schedutron,
Thanks for the question! I've had similar issues! It really just about learning how to focus yourself on a particular subject. I generally try to learn things via practical experience. So try to find projects that can teach you about those things. As for the books instructors give... I just pretty much read as much as I needed to get by when I was in school. Now I don't really read books much. I don't learn well that way. I gave [a talk](https://kentcdodds.com/talks/#zero-to-60-in-software-development:-how-to-jumpstart-your-career) a while back that may be helpful to you as well.

Good luck! And have patience!
