### ISSUE TITLE
Use of external media in conference presentation

### ISSUE THREAD

**Issue by KevinKelchen** [kentcdodds/ama#259]
Hi Kent!

I was wondering if I could get your opinion on something. I would particularly value it as you're someone who's presented at conferences before and can appreciate my concern for being honest in my dealings with my fellow man and honoring and sustaining the law. This question is one that I will have to ultimately answer for myself, but I would appreciate your input!

In the past, I've given various workshops and presentations to our development team at work. Often I will put a slideshow together and include external media to enhance the experience of the audience.

Most of the time the images are procured from a Google search for a key term that relates to the topic. For example, on a slide about data synchronization I might perform a Google image search for "sync" and include a photo or artwork image that symbolizes syncing. It's also not grossly uncommon--being someone who does indeed have a sense of humor--to include a meme or still-shots from a movie or TV show. In attempt to give credit to my sources, the final slides of my presentation will include a several word description of the image/media resource used and a URL to the file location. Trying to find the IP owner and reaching out for permission of use is not something I would typically do given the practicality of it and from what's been ostensible in the number of meetup and conference presentations I've attended.

While my question is applicable regardless, I'm considering submitting a talk to a conference and have to more seriously think about this matter. I fear that my use of external media in this way may not--in some degree--be legally sound. Since this could have a significant impact on my presentation, I've been reticent to submit an abstract.

I would greatly appreciate your thoughts on this! Thanks a lot for your time--I know you're a busy person! :smiley:

Take care,

Kevin

**Comment by joeeames** [comment]
The actual legal aspects are more muddy than you think since there's fair use, parody, and excerpt laws. Also you're not getting paid so there's no worry of profiting off illegal use of others material. Also much work is produced and intended for redistribution, especially in the case of meme images. People want those used. They want the notoriety, not the money. In general i pay when i can and don't worry about the rest

**Comment by kentcdodds** [comment]
Hey @KevinKelchen,
Thanks for reaching out. And thanks @joeeames for pitching in with your great perspective as well! I pretty much don't have much to add honestly. I'm no lawyer and I don't understand copyright law. You're already doing a great thing by adding the references at the end of your slides. I'll sometimes put those at the bottom of the slide for the image. I think you're probably good with what you're doing. Good luck!
