### ISSUE TITLE
How to bundle multiple features in one release

### ISSUE THREAD

**Issue by felipe-gdr** [kentcdodds/ama#260]
Hi, Kent.

I am watching your series about creating an open source Javascript library. Great stuff!

From my understanding, whenever a commit containing the keyword title 'feat' is pushed, semantic-release will trigger a new major release both on GitHub and Npm. 

Now, assume I'm working on a new version that would contain, let's say, 5 new features. The last release version was 1.4.0, and I want this new version to be 1.5.0. A version bump take place every time I commit and push one of those 5 new features, right? 

Is there a way to hold on the release process until all the features from that versions are finished and pushed?

Cheers!
Felipe.

**Comment by kentcdodds** [comment]
Hey Felipe! Great question!
I'm actually working on that right now with [`cross-env`](https://github.com/kentcdodds/cross-env/pull/87). This is definitely a common use-case (especially with breaking changes) and it's very easy to solve. You simply make a branch (I call in `next`) then you make all pull requests to that branch. When you're ready to release you merge that branch to `master` and it all goes out at once.

I would recommend though that you reserve this for breaking changes. No need to complicate things. Just drop the emotional attachment  you have to releases and version numbers and things get so much simpler! This is a great talk on the subject: https://youtu.be/tc2UgG5L7WM

Good luck! I'm glad you enjoyed my Egghead stuff!

**Comment by felipe-gdr** [comment]
Hey, Kevin.

Nice tips. Thanks for referencing the youtube video as well ;-)

**Comment by vitkarpov** [comment]
> Now, assume I'm working on a new version that would contain, let's say, 5 new features. 
> When you're ready to release you merge that branch to master and it all goes out at once.

And what if one of this features isn't working well or I understood that users don't want it, how can I get it back? First, all the features was merge with the same merge-commit (from one branch), second, some changes was made on top of that feature, so I can't just drop it without passing regression tests again.
