### ISSUE TITLE
Limiting repeatSection rows

### ISSUE THREAD

**Issue by rahulbhaya** [kentcdodds/ama#263]
I want to know is there a repeatSection property that limits the number of Rows? Say I don't want more than 4 sections in the repeatSection.

**Comment by vitkarpov** [comment]
A super cool question with a lot of context 👍

**Comment by kentcdodds** [comment]
@vitkarpov, that sarcasm is not appreciated on my AMA. If you are going to engage, please do so in a way that respects the [code of conduct](https://github.com/kentcdodds/ama/blob/master/CODE_OF_CONDUCT.md). Thanks.

**Comment by kentcdodds** [comment]
Hi @rahulbhaya,
Thanks for the question! I believe you're talking about the angular-formly example for repeatSection. I don't do any support for that library anymore I'm afraid. It's been a long time since I've looked at anything there. Sorry I can't be of much help to you. Good luck!

**Comment by vitkarpov** [comment]
I'm so sorry, guys, didn't want to insult anyone. My bad. Will never happen
again!

пт, 21 апр. 2017 г. в 20:45, Kent C. Dodds <notifications@github.com>:
