### ISSUE TITLE
pnpm vs. yarn vs. npm@5

### ISSUE THREAD

**Issue by kutsan** [kentcdodds/ama#265]
Just a quick question. What's your thoughts about those three? Have you tried out?

**Comment by kentcdodds** [comment]
Hey @kutsan!
Thanks for the question. So I'm all over `yarn` from the time it was released. I LOVE it. It's super awesome. I never used pnpm. So I don't have much to say about that. I've been seeing tweets about `npm@5` and I'm getting really excited about it. It seems to solve all the problems I use yarn for and it _also_ is more ubiquitous for developers. So I've asked [this question](https://twitter.com/kentcdodds/status/860516174957690880) on twitter and we'll see what people say. But I think I may go back to npm@5. We'll see!

Thanks!

**Comment by kutsan** [comment]
You should at least try, to see how awesome pnpm is. That wasn't quite an answer what I expected but thanks for putting your time!

**Comment by TreTuna** [comment]
I'd like to know your opinion on this now that NPM@5 has been out for a bit. Have you gone back or sticking with Yarn?

**Comment by kentcdodds** [comment]
Good question @TreTuna! I'm kinda torn. I asked [this question](https://twitter.com/kentcdodds/status/860516174957690880) and got some interesting responses from folks. I really like yarn, but because I do a lot of stuff to collaborate with others (like open source and workshops), I think that I'm going to switch to npm@5 with `package-lock.json`. At work we never got `yarn` working quite right so now we've upgraded to npm@5 and we're loving it.

**Comment by v1adko** [comment]
I was surprised to hear that you don't use yarn. I've got an impression that it's somehow better or faster than npm. I can blame tweets like [this one](https://twitter.com/iamdevloper/status/917710714361602048) for ignorance, but in truth I simply believed the hype and didn't spend time actually trying both and comparing.

How do you switch your tooling so easily? I get very used to something and then some sort of xenophobia kicks in. Even though I don't regret switching to webstorm to vscode, mocha to jest and using tools like prettier, but the thing is that most of people (myself included) try new things once they reach some level of hype or admiration, but you seem to be ahead of the crowd, pushing and even creating cool things into the "general public" and I think it's amazing.

Is there a secret to how you do this?)

**Comment by kentcdodds** [comment]
Great question @v1adko. Could you open a new issue about it?

**Comment by v1adko** [comment]
Sure! Done. #327
