### ISSUE TITLE
testing JS Apps for frontEnd Masters

### ISSUE THREAD

**Issue by snehalp29** [kentcdodds/ama#266]
1) is it possible for you to show how to test angular apps also would love to see some angular 2 / 1 tests if its not too much to ask I know its just in 3 days?
2) can we include Jest with some kinda CI tools?
3) can you please demonstrate how to debug the tests in browser. console logs are fine but debugging in browser would be nice.

**Comment by kentcdodds** [comment]
Hi @snehalp29,
Thanks for the questions. Sorry that I didn't get to this before the workshop. But I'll answer some of these as best as I can with [the time I have](http://kcd.im/no-time) :smile:

1. I don't use Angular anymore, so I would definitely be the _wrong_ person to teach about testing Angular. Sorry
2. Jest can _definitely_ be run on CI. [The testing workshop](https://github.com/kentcdodds/testing-workshop) has [TravisCI](https://travis-ci.org/kentcdodds/testing-workshop) setup (even though it's timing out... that's not related to Jest though, all of my open source projects are using Jest these days and have Travis setup on them). And my work project is running Jest in Jenkins.
3. Debugging in the browser with Jest is actually kinda tricky right now. I'm not sure why it's still a bit of a problem. But I'm hoping [that'll](https://github.com/facebook/jest/issues/1652) be fixed soon. In my workshop I also use a tool called [Cypress](https://www.cypress.io/) which is SUPER awesome and allows you to debug your end-to-end tests in the browser (which is something you cannot do with traditional selenium tools). Very cool stuff!

I hope that helps!
