### ISSUE TITLE
How old are you?

### ISSUE THREAD

**Issue by stevemao** [kentcdodds/ama#27]

**Comment by kentcdodds** [comment]
I was born on October 18, 1988 (can't remember the exact time :baby:). The following code prints out my age in milliseconds:

```
new Date() - new Date(1988, 9, 18)
```

I just ran it and the output is: `845703451796`

If you want that in years...

```
(new Date() - new Date(1988, 9, 18))/1000/60/60/24/365.25
```

`26.798725278633356` There you go :-)

**Comment by olegafx** [comment]
It's a strange thing that it shows 26.806 for my birth date when I'm reading this. @kentcdodds you did a great job for the last 3 years. Thanks for your work and inspiration.
