### ISSUE TITLE
Building a unit test framework on top of an existing code base

### ISSUE THREAD

**Issue by jeremyrader** [kentcdodds/ama#271]
Hey Kent,

At my current place of employment I am working on an extremely large React application that has no existing unit tests in place. We have some end to end tests, but there is a certain limit to the extent we can test with these. What do you suggest as a method to increase testability in a project that doesn't have any unit tests built up? Do you believe that it is feasible to add unit tests so late in the game? If so, do you have any pointers? I've kind of gotten the sense that unit tests are more helpful in the beginning of a project. Thanks, Jeremy

**Comment by vitkarpov** [comment]
I've been in the same situation once. Eventually, I started to notice the same bugs over and over again in some components, that was a signal to make unit tests for them and refactor the logic under the hood.

It was so easy to reason about the question "why do we need to do this?" and nobody was against it. So, in my opinion, you just have to define "the hot spots" and cover them with tests, if something works good and never being changed, seems okay to leave it as is.

**Comment by kentcdodds** [comment]
Hi @jeremyrader!
I would _definitely_ recommend adding unit and integration tests to your project! And I recommend you use [Jest](https://facebook.github.io/jest/) to do so. I just gave [a workshop](https://kentcdodds.com/workshops/#testing-javascript-applications) recently about testing JavaScript applications that I think you'll really like :)

The nice thing about Jest is that you can really easily add it to an existing project. A good way to go about things is whenever you find a bug ask yourself whether you can prevent that bug happening again with the following tools in this order:

1. Adding Types (with Flow or TypeScript)
2. Adding Linting with ESLint ([custom ESLint rules are awesome](https://kentcdodds.com/workshops/#code-transformation-and-linting))
3. Unit tests
4. Integration Tests
5. End-to-End Tests

This is a great way to start building up new tests on your existing codebase. Good luck! Let us know how it goes :)
