### ISSUE TITLE
Would you recommend using Jest snapshots for *almost* everything?

### ISSUE THREAD

**Issue by ls-guillaume-lambert** [kentcdodds/ama#275]
This is regarding the tweet you've made here: https://twitter.com/kentcdodds/status/862343047258009604?refsrc=email&s=11

Questioning myself after reading this article: https://hackernoon.com/how-to-snapshot-test-everything-in-your-redux-app-with-jest-fde305ebedea

Thanks!

**Comment by kentcdodds** [comment]
Hi friends! So this is a pretty common question and I decided to give it justice by recording a short 3 minute podcast about it. You can listen to that [here](https://www.briefs.fm/3-minutes-with-kent/40) (subscribe: [itunes](itpc://www.briefs.fm/3-minutes-with-kent.xml) [rss](http://www.briefs.fm/3-minutes-with-kent.xml))

I hope that helps! Feel free to ask follow-up questions.

**Comment by marcusnielsen** [comment]
I use snapshots for testing state reducers/updaters. The benefit is that I can treat the entire state of a component as a unit. If someone changes the state-shape, all updater functions are affected. It might seems like overkill, but we added an `errors` prop to the state, which should be reset if we successfully load data. The snapshot asks the question: "are you sure that the entire state shape should look like `[xyz]` in this test?", which I think is a pretty good checklist to go through.

**Comment by blocka** [comment]
That would require you and everyone on your team to have in their head the knowledge of how the state is supposed to look, and rely on having all your developers being awake (this is the major problem with snapshots, actually).

I think it's much better to be able to have a computer verify this.

**Comment by kentcdodds** [comment]
I agree with @blocka. The bigger the snapshot, the less carefully it's reviewed. It's a trade-off. But if you can use another assertion to be more specific, or if you can snapshot a smaller portion then that's better IMO
