### ISSUE TITLE
Which setup for (automated) cross-browser testing?

### ISSUE THREAD

**Issue by ls-guillaume-lambert** [kentcdodds/ama#276]
Hi (again) Kent! 😄 

I know you are personally using Jest and Cypress as your stack for unit, integration & functional testing. What about running/automating tests in a cross-browser environment such as BrowserStack? Do you have recommendations or alternatives when needing automated cross-browser testing as well? Would you suggest having automated cross-browser testing at all for softwares today?

Thanks again for your time!

**Comment by kentcdodds** [comment]
Hi @ls-guillaume-lambert,
Thanks for the question. It's a great one.

To be clear, I actually don't use Cypress for work. And I don't do E2E tests for my side-projects (I've got nothing big/important enough to justify it).

Another thing to note is that Jest runs in Node, so you're not going to get any cross-browser confidence out of that.

Also, Cypress currently only supports Chrome for the time being.

So.... How do I ensure my confidence that my stuff isn't broken in other browsers? At work on my team, we're using [nemo](https://github.com/paypal/nemo) and will soon be using [SauceLabs](https://saucelabs.com/). I haven't been involved in that effort, so I can't speak much to that. I used SauceLabs with [Protractor](https://github.com/angular/protractor) at a previous company and we liked it pretty well.

Outside of that, I kinda feel the same way that the Cypress folks feel about cross-browser testing. Read more about that [here](https://github.com/cypress-io/cypress/issues/310).

Good luck!

**Comment by ls-guillaume-lambert** [comment]
Interesting, thanks for taking the time to answer again! I did think 

Have you heard about [Nightwatch](http://nightwatchjs.org/)? It does e2e & can connect to BrowserStack for Cross-Browser testing as well. Cypress has been on my radar for a while but Nightwatch also brings a lot to the table.

**Comment by kentcdodds** [comment]
Yeah, I think my team considered Nightwatch. Can't remember exactly why they decided to go with nemo instead. Because it's selenium-based, it still suffers from all the same selenium problems. @brian-mann explains these really well in [this talk](https://youtu.be/lK_ihqnQQEM).

**Comment by ls-guillaume-lambert** [comment]
Yes, it's true that getting rid of Selenium is something to consider. So basically what you are saying is that cross-browser testing should be done separately from e2e testing? If you could have an ideal setup of your choice at work, what would it be? Cypress for e2e and automated SauceLabs/BrowserStack tests?

Thanks for the talk link, will definitely watch this.

**Comment by kentcdodds** [comment]
> So basically what you are saying is that cross-browser testing should be done separately from e2e testing?

Separately or not at all. Really depends. But you could probably do most of your E2E tests with Cypress and a handful of cross-browser tests with other tools.

> If you could have an ideal setup of your choice at work, what would it be?

Oh man. We'd have an awesome pipeline for pull requests like this:

1. Pull request created
1. flow typecheck
1. Lint
1. Build
1. Deploy to a special isolated environment just for that PR
1. Unit Test
1. Integration Test
1. E2E test with Cypress

Then for our production branch (only one branch that's always releasable):

1. Pull request merged
1. flow typecheck
1. Lint
1. Unit Test
1. Integration Test
1. Build
1. E2E test with Cypress
1. Cross-browser selenium tests (only a handful of these and only really necessary for projects where it really matters, like mine at work)
1. Wait for a button to be pressed to release (or rollback to) this built version.

I actually built and had this at my last job. We used Protractor instead (Cypress wasn't a twinkle in my eye at the time), but it was the same basic idea and it was amazing. The nice thing about using Cypress is that you can be productive for most of your tests and catch 99% of the problems, then you have some poor soul write the selenium tests for the last 1% of cross-browser issues. This would be amazing.

**Comment by ls-guillaume-lambert** [comment]
Merci beaucoup! 👌

**Comment by ConAntonakos** [comment]
@ls-guillaume-lambert I'm also a user of Nightwatch, but it's becoming increasingly difficult to debug. I don't think I can test with async/await which I was hoping for. The API is very weird, and trying to follow test executions is not as clear. My tests have a bunch of `pauses` which isn't always reliable. Overall, I'm not super happy with the experience, and I'm looking for a way to fix this. I don't know if it's Cypress. I also found this Jest + Puppeteer setup: https://facebook.github.io/jest/docs/en/puppeteer.html

Any thoughts?

**Comment by ls-guillaume-lambert** [comment]
Have a look at [TestCafé](http://devexpress.github.io/testcafe/), Nightwatch we considered but didn’t used it in the end. TestCafé is what we are trying out and so far so good!

**Comment by kentcdodds** [comment]
> Also, I'm curious as to how Kent set up E2E tests via PRs. Do you just add commands in your CI script?

To be clear. I haven't actually set up the aforementioned system, this is my theoretical workflow. I had something similar to this at a previous job. It was a while ago, but the CI system we were using supported running tests in headless mode so we just used that...

Today, I'd just use Cypress and that works in headless mode as well. It's amazing.

Good luck.

**Comment by ConAntonakos** [comment]
Awesome. It's also really hopeful to see that Cypress was open sourced, so I might check it out now. TestCafe looks like an interesting choice as well. Thanks for your valued input, everyone!
