### ISSUE TITLE
What's your thoughts on fela ?

### ISSUE THREAD

**Issue by wcastand** [kentcdodds/ama#280]
Hi,

I saw a lot of people talking about css-in-js right now and why they choosed one or an other, etc

You created glamorous for/with paypal and explained some reason in a tweet or post ( i don't remember) but like every article about css-in-js, you didn't mention [fela](http://fela.js.org/). Is there a reason for that, because from what i can remember from your tweet, you wanted css object instead of string for example (fela does that), [este](https://github.com/este/este) event typed his fela css objects :)

So i wanted to know if you tried it ? And if you did, why you choose to not use it like the others css-in-js solutions and created glamorous :) ?

**Comment by kentcdodds** [comment]
Hi @wcastand,

Thanks for the question. I definitely evaluated `fela` before I built glamorous. IIRC, I didn't like the API a ton. I think it was that everything's a function. I have many CSS-in-JS objects that are totally static. I believe that was the biggest thing for me. Also, I just really like how simple glamor is. You import this function, call it, get a string back and apply that to something. No need to create a renderer, deal with presets, or anything. The simplicity won me over. Also the fact that most CSS-in-JS libs are fast enough, I can choose between them based on how I like the look of them. Also, I really like @threepointone :smile:

I hope that's helpful :)
