### ISSUE TITLE
e2e/integration test coverage for large javascript applications

### ISSUE THREAD

**Issue by fpereira1** [kentcdodds/ama#283]
Hi Kent, I see your polls on twitter from time to time. I was wondering if you had any info around how many e2e/integration tests people had in their projects and how long they took to run? I guess this will change a lot from project to project but I am interested to know about this. 

Also, thanks for making this available: [Testing JavaScript Applications Workshop (at PayPal)
](https://www.youtube.com/watch?v=DdqiXcYDv-8)

Looking forward to watch it

Thanks 🙂

**Comment by kentcdodds** [comment]
Hi @fpereira1!

That's a great question! I have no idea! But I made [a twitter poll thread](https://twitter.com/kentcdodds/status/883437114779738112) so we'll see what people say.

Mind you, my sample is biased toward developers who generally care about this kind of thing...

Good luck! Oh, and if you're interested, there's a professionally edited version of my testing workshop as a course on Frontend Masters now: ["Testing JavaScript Applications (feat. React and Redux)"](http://kcd.im/fem-testing)
