### ISSUE TITLE
Remote talk at PDXNode

### ISSUE THREAD

**Issue by obensource** [kentcdodds/ama#285]
Hi Kent!

Hope you're doing super great. I organize PDXNode (Portland's premier Node.js meetup) and it would be an honor to have you present remotely sometime this year. We meet every 2nd Thursday at 6:30PST, and you could begin ~7:30 or ~8:15MT. The topic is up to you (whatever you're really stoked on!).

We have a lot of seasoned folks, and people just getting started as well who're excited to explore. We also record all our talks now, so we can record a video stream via HDMI and it'll look great. :D

Thanks for being awesome, and let me know if this is something you might like to do (any month including this one–we have an open slot still for this Thursday). Cheers Kent!🍻

https://www.meetup.com/pdxnode/

**Comment by kentcdodds** [comment]
Hey @obensource!
I'm so sorry it's taken me so long to respond to you! Things have been very busy! I'm honored that you would invite me to speak at your meetup!

Looks like the meetup for this month is on the same day I'm speaking at [Open West](https://www.openwest.org), but next month I'm sure I could speak on something! What would you like to hear about? I have a [list of talks](https://kentcdodds.com/talks/) I could give, or I could also speak about anything else you're interested to hear. [My GitHub](https://github.com/kentcdodds) history is full of stuff that I'd love to talk about :smile:

Let me know! I'll go ahead and close this (for my own management reasons), but feel free to comment :smile:

**Comment by obensource** [comment]
Hey @kentcdodds! My apologies that time got away from me and I'm just now swinging back around to reply!

I'm so so stoked that you're open to speak at our meetup! Would you be available October 12th? If you're going to be in MDT at that time you would start around either 7:30pm or 8:15pm (your choice :)) 

For the talk, my general advice is that you choose whatever it is that you're *most excited* about to share with an audience of JS/Node devs, rather than to choose something or provide a directive and miss out on getting the most unfiltered/authentic you. Whatever it is that you can't stop thinking about, or have a huge passion for (in the JS universe)–that'd be awesome. :D 

Thanks again @kentcdodds! Really looking forward to making this happen! (Promise to communicate much more frequently about it ;)) Cheers! 🍻

**Comment by kentcdodds** [comment]
I think it'd be great to share my talk about building custom ESLint and Babel plugins. Would that be of interest?

I'd prefer to start at 8:15pm.

Here's a Title/Abstract:

Title: "Building custom Babel and ESLint plugins and codemods"
Abstract:

The Abstract Syntax Tree. It sounds a lot worse than it is. It’s actually quite simple and enables some powerful tools. BabelJS uses it to transform your code from ES.Next to ES5. ESLint uses it to lint your code. And with a knowledge of how it works, you can extend these and other tools to do some mind bustingly powerful things. Prepare to be amazed by ASTs!

**Comment by obensource** [comment]
@kentcdodds this is 100% perfect! Hooray! 🎉🎉🎉 

Rad! So super stoked to put this on the calendar! Thanks for working this out, I'm really excited to be in touch! 🙌

Thanks Kent! I'll touch base again as we get closer, and will see you on the Internet! 🍻

**Comment by kentcdodds** [comment]
Hi @obensource! Just checking in. Is this still happening? 😄

**Comment by obensource** [comment]
@kentcdodds definitely! Thanks for checking in! 🙌

Everything we talked about previously is still golden. We're super stoked! 🎉

**Comment by obensource** [comment]
Please let me know if you have any questions beforehand, we've been using talky.io for our remote presentations, but if you're more comfortable with another platform–we're totally open to whatever you prefer :)
