### ISSUE TITLE
About Advancing Skillset

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/ama#286]
I'm trying to aggregate various opinions and methods from different experts. If you have the time to respond, I would greatly appreciate it.

Currently, I would call myself an Intermediate programmer. I can pickup a new language/framework/library fairly quickly and use it by going through it's documentation. But I don't feel like I'm an expert yet. My closest skill to expert is probably JavaScript, but I'm looking to expand further. 

I've heard varying opinions on what it might mean to be an expert, for example there's the "10,000 hours/10 years" theory, which if true means I still need another 4 years (I've been programming professionally for 5-6). And I think there might be some truth to that. But I also think there is a real value in the method, so I'd like to learn from community leaders who are said to be experts (not just self-proclaimed, but actually claimed as such by others). 

Anyway,

What have you found over the years it the best way to improve your skills? What is it that truly helped you on the road to becoming an expert? This could be anything from daily routines, use of mentor-ship, reading, teaching, etc. I don't think (or expect) you to have a single answer. I'm just curious about which methods you think were the most important to your eventual expertise. 

thanks and best regards,
Anonymous

**Comment by sapegin** [comment]
10 years of experience haven’t really helped in my case. I still consider myself an average developer. I still can’t uderstand any Math and most complex computer science things. I couldn’t finish a single book on functional programming and design patterns (except Addy Osmani’s one).

But it have made me worry much less about that ;-) I’ve learned what kind of tasks I’m capable of and enjoy doing and try to choose my work based on that. Experience with many different things (frontend was very different 10 years ago) have made me much less opinionated. Every tool is good for something, it I think that something is terrible and useless — most likely I just don’t understand the use case. I’m trying to learn related things like design and writing to make myself more useful. 

Passion and persistence help a lot here ;-)

**Comment by vitkarpov** [comment]
In my opinion an expert is a rear person by definition, this fact literally
puts the title on him or her. For instance, there're a lot of people out
there who can write JavaScript and pretty good at it, but there're a few
people who can write JavaScript itself, I mean V8 for example.


пн, 12 июня 2017 г. в 21:01, Artem Sapegin <notifications@github.com>:

**Comment by kentcdodds** [comment]
Hi Anonymous :wink:

Thanks for the questions!

> What have you found over the years it the best way to improve your skills? What is it that truly helped you on the road to becoming an expert?

I talk about this in my talk ["Zero to 60 in Software Development: How to Jumpstart Your Career"](https://www.youtube.com/watch?v=-qPh6I2hfjw&list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf&index=16). And I've answered this question a few times (#89, #41, #167) 

Mostly it's just a matter of spending a ton of time doing it and sharing what you learn along the way. Good luck!
