### ISSUE TITLE
What skills have made the biggest impact on your programming?

### ISSUE THREAD

**Issue by titoesteves** [kentcdodds/ama#288]
What topics, skills, learnings, etc, would you say have made you a better and more confident developer? As a follow up, what topics, skills, learnings, would you give to someone who wants to become a better overall developer?

**Comment by vitkarpov** [comment]
I bet, it's ability to talk to other people :)

**Comment by kentcdodds** [comment]
Hi @titoesteves!

Thanks for the question. The biggest thing for me has been how to teach what I've learned to others. For me, that means giving talks and workshops, podcasting, and occasionally blogging. For you it might be something totally different. But that has honestly helped me more than anything else I can think of. When you're forced to teach something, it forces you to learn it really well. I talk about this a bit in my talk ["Zero to 60 in Software Development: How to Jumpstart Your Career
](https://www.youtube.com/watch?v=-qPh6I2hfjw&list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf&index=16). I hope that's helpful! Good luck to you!
