### ISSUE TITLE
Someone stole one of your Smiley Face videos you made 10 years ago and got 1 1/2 million views with it.

### ISSUE THREAD

**Issue by DashLt** [kentcdodds/ama#290]
[Your video.](https://www.youtube.com/watch?v=IiDQwQQsrL8)
[Stolen video.](https://www.youtube.com/watch?v=t6q5_7fVjEg)

**Comment by kentcdodds** [comment]
lol, nice. Thanks for sharing! That kinda-sorta made my day. Still feeling mixed emotions, but mostly hilarity.

If you wanna, you can give [my comment](https://www.youtube.com/watch?v=t6q5_7fVjEg&lc=z12txxa41yitsze3d23cyr1bml2ui15ba04) a :+1: Maybe it'll get to the top :)

**Comment by DashLt** [comment]
Unfortunately the link doesn't link to another comment. Glad I could make you laugh though!

**Comment by tomByrer** [comment]
It's a thing that people steal content & slap their own ads to it.
