### ISSUE TITLE
How to keep up with so many JS Frameworks/libraries?

### ISSUE THREAD

**Issue by nits41089** [kentcdodds/ama#291]
There are so many JS frameworks/libraries. By the time you master 1, 10 more are created. How do you keep up with all these?

**Comment by vitkarpov** [comment]
Podcasts. It's a good way to keep up, doesn't take lots of efforts, convenient and fun.

**Comment by sapegin** [comment]
The most productive solution: you don’t ;-)

There are new frameworks every day but very rarely there are that much better to justify learning and migration. React was the last in my opinion. So learn thing that don’t change that often: the language itself, design patterns, etc.

**Comment by luftywiranda13** [comment]
yeah you don't need to know/master every single thing. Use what makes you comfortable 😄

**Comment by kentcdodds** [comment]
Hi @nits41089,

I make a conscious decision to not learn them. I pretty much just do what @geddski says you should do in his blog post ["Deciding What Not To Learn"](http://gedd.ski/post/what-not-to-learn/). Solid stuff...

Then, when I decide what to learn, I try to learn it really well by studying about it, building with it, and teaching others what I learn. [This talk](https://youtu.be/-qPh6I2hfjw?list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf) includes a little bit about that process.

I hope that's helpful!
