### ISSUE TITLE
Does generator break the run-to-completion behavior of JavaScript

### ISSUE THREAD

**Issue by fengzilong** [kentcdodds/ama#294]
As suggested in title, does generator break the run-to-completion behavior of JavaScript ?

It puzzled me for several days, and I've searched a lot on the internet.

But the result looks more confusing

> [breaking-run-to-completion](https://github.com/getify/You-Dont-Know-JS/blob/master/async%20%26%20performance/ch4.md#breaking-run-to-completion)

> [preserve run to completion](http://2ality.com/2015/03/es6-generators.html)

Who is telling the truth ? or is it meanless seeking an answer for this?

Thanks in advance!

**Comment by kentcdodds** [comment]
Hi @fengzilong,

Thanks for the question. Honestly, I don't really think about that either way. It's not an area that I consider much in my programming. Also I don't really use generators 🙃 

Soooo....

> is it meanless seeking an answer for this?

Probably not... But I don't think I'll ever care to find the answer.

Sorry that's not all that helpful... Haha.
