### ISSUE TITLE
Help me (Kent) stay awake driving by calling my phone and talking tech

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/ama#295]
Family emergency came up and I'll be driving across the country to help someone out tomorrow and Sunday (I need to get a car somewhere, so I can't fly). **I'll be driving by myself** and I don't trust myself to stay awake driving 24ish hours in two days.

So I'm asking for your help!

I can't fall asleep when I'm actively in a conversation with someone about something I care about! Open Source, Testing, ES6, Soft Skills, whatever! That'll keep me awake really well. So **you can help me by calling me to chat**. You can ask me questions, I can ask you, and we can learn from each other! It'll be great!

If you want to participate, here's how things are going to work:

### 1. You subscribe to this issue

<img width="448" alt="click the subscribe button on the issue" src="https://user-images.githubusercontent.com/1500684/28737335-46384318-73ab-11e7-9320-a2a1f60dcbae.png">

### 2. I let you know when I'm accepting phone calls

Before I start driving, I'll comment on this issue saying that I'm ready to accept phone calls. You should get a notification. And you can call in at any time! Here's the info:

**Join the call: https://www.uberconference.com/kentcdodds**
**Optional dial in number: 401-283-5757**
**PIN: 19573**

(You can call from your phone or your computer)

I can have up to 10 people in at once, so I'm sure that'll be plenty :smile:

> Note: [The AMA code of conduct](https://github.com/kentcdodds/ama/blob/master/CODE_OF_CONDUCT.md) applies during the call. Let's all be nice and inclusive on this call :smile:

### 3. We start chatting!

We can talk about anything really. We'll just pretend we're at a conference hanging out talking tech. Or on one of my JavaScript Air shows :smile: We can talk about anything you all want to talk about. Whatever helps me stay awake, engaged, and alert while driving.

I'll be recording the call so I can put it up somewhere when we're done. That way more folks can get something out of whatever we talk about! Cool right!? (Don't worry, if you'd like me to cut something out of the call later, just ask me and I'll cut that out of the recording).

### 4. We wrap up

I may need to hang up to take a break or pull over or something. When that happens, I'll let you all know and we'll hang up. Then I'll comment on this issue saying I'm not taking calls anymore.

### 5. Start over again

When I'm ready to take more calls again, I'll comment again. Feel free to call in.

### 6. Repeat

We keep doing this until I'm done with all the driving. And I thank you from the bottom of my heart! ❤️ 

---

Let me know if you have any questions! And thank you so very much!

FYI. I'll be starting tomorrow at around 13:30 UTC and possible the same time the next day :)

Ideas of things to talk about if the conversation dies down:

1. Look at [my github](https://github.com/kentcdodds) history and ask me about anything on there.
2. Look at [my 3 minute podcast](https://www.briefs.fm/3-minutes-with-kent) and ask me about anything in there
3. Look at [JavaScript Air](https://javascriptair.com/) and ask me about any of those episodes
4. Ask me about any of my [Frontend Masters](https://frontendmasters.com/courses/) or [Egghead.io](https://egghead.io/instructors/kentcdodds) courses
5. Teach me something I don't know about! Reason, GraphQL, Serverless
6. CSS-in-JS
7. Inbox 0
8. Privilege Awareness
9. Really anything, I'm just making things up... :smile:

**Comment by kentcdodds** [comment]
Shoutout to @TheLarkInn for the idea!

**Comment by hawkins** [comment]
This is brilliant 🙌 drive safe!

**Comment by m13m** [comment]
can't wait i have to ask tons of question.

**Comment by Nargonath** [comment]
That's an awesome idea! Good luck with the trip.

**Comment by cacheflow** [comment]
Stay safe buddy!

**Comment by rouzbeh84** [comment]
This *IS* an awesome idea! Hopefully service stays strong haha

**Comment by kutsan** [comment]
Kent C. Dodds as a Service™. It'll be great.

**Comment by edm00se** [comment]
Above all, drive safe.

**Comment by abdulhannanali** [comment]
@kentcdodds I am going to ask you for an internship referral. Please :raised_hands:

**Comment by CompuIves** [comment]
Haha this is so cool! Certainly subscribing.

**Comment by kentcdodds** [comment]
Ok! We're on our way. Feel free to call in 😀

**Comment by callahad** [comment]
I think Kent lost his cell phone signal, but we're still chatting without him!

**Comment by callahad** [comment]
(To clarify, Kent is back now. He's hit some ~1-2 minute long dead spots, but nothing too bad)

**Comment by kentcdodds** [comment]
Getting back on in about 20 minutes...

**Comment by morioust** [comment]
The automated voice said "The conference has reached its maximum duration and will end in 1 min"...

**Comment by ajwhite** [comment]
Call back up and running!

**Comment by ajwhite** [comment]
Couple of us are dropping off, and Kent's started yawning, go keep him awake!

**Comment by senordelaflor** [comment]
I just joined twice but I don't hear anything. Anyone else having this problem?

**Comment by ajwhite** [comment]
I'm in Canada right now and I had to hop on my office VPN (in the US) to get in for some reason. Without my VPN i wouldn't hear anything and i'd see a popup on the top left saying it can't detect audio

**Comment by rouzbeh84** [comment]
just joined up, a few people on the call just chatting 👍

**Comment by senordelaflor** [comment]
@kentcdodds where did you go man? I hope you're staying awake 👍🏼

**Comment by keyvhinng** [comment]
This is so cool. This is to late to mention but I hope you are driving a Tesla. Autopilot would make your trip easier and save you some energy

**Comment by kentcdodds** [comment]
I wish! Haha. I'm wrapping up dinner now and I'm about to hit the road again. Started 10 hours ago and will be going about two or three before the night's over. Thanks everyone who's called in so far! It's really helped! Now I'm going to need more help than ever! Let's talk tech! I'll be on in a few minutes 😀

**Comment by jspraul** [comment]
Ask people to link anything they can in the conference chat, mostly for your own future reference.

If you can convince someone to "live tweet" hashtags there as well it will make the audio much easier to review later.

Drive safe.

**Comment by kentcdodds** [comment]
Thanks. I did ask folks to do that a bit, but not sure whether it happened. Also things were a bit tricky because we have a three hour time limit on recordings and I can only start recordings when I have internet access (which I often don't have on the road), but I'll do my best with what I can.

I'm just thrilled folks like this idea enough to call and chat. It's been fun!

While I'm here, we just decided we'll be skipping church tomorrow because we have time of driving to do. So we'll get started early (in 7.5 hours). So I'm going to sleep! Talk to you tomorrow!

**Comment by kentcdodds** [comment]
Whoops, plans just changed. We're going to split it up and drive a bit on Monday. That way we can make it to church and not drive so much. I'll ping you all here when I'm ready to chat 😀

**Comment by Raathigesh** [comment]
I was there listening for the most part and it was really fun. Glad that
this wild idea really worked out. Drive safe ☺️

**Comment by mujuni88** [comment]
It was fun talking to you Kent. I met some really cool people in the chat. Drive safe.

**Comment by ndelangen** [comment]
I'm just chillin, listening to the music 😂

**Comment by kentcdodds** [comment]
Thanks!

I think I'll jump on the conference call after church, but I went ahead and started it so folks can talk to each other if you wanna jump on :smile:

**Comment by kentcdodds** [comment]
I kinda feel like ["Aech"](http://readyplayerone.wikia.com/wiki/Aech) from Ready Player One. This conference call is my ["Basement"](http://readyplayerone.wikia.com/wiki/The_Basement) ;-) You're all welcome to come hang out so long as you're cool about it 😉

**Comment by ajwhite** [comment]
> Aech

This changes everything. I always thought it was literally **H** 🤦‍♂️ 

_I listened to the podcast_

**Comment by reznord** [comment]
> I'm just chillin, listening to the music

Worse part, you can't mute the music :P

**Comment by kentcdodds** [comment]
About ready to go!

**Comment by kentcdodds** [comment]
I'm on again!

**Comment by leggsimon** [comment]
Thanks for the chat earlier Kent, and others of course.

**Comment by siddharthkp** [comment]
> > I'm just chillin, listening to the music

> Worse part, you can't mute the music :P

I keep missing Kent, because I'm travelling too. But, I stick around for some time for the music. So good 😋

**Comment by kentcdodds** [comment]
We're packing up now. I'll probably be on the line in ~30 minutes or less

**Comment by kentcdodds** [comment]
I'm on 😀

**Comment by cavneb** [comment]
I'd love to chat with you whenever you'd be open

**Comment by reznord** [comment]
He is already online, you can join him at https://www.uberconference.com/kentcdodds

**Comment by jspraul** [comment]
Chatlog (including PayPal interviewing discussion I originally did in the Discord): https://gist.github.com/jspraul/a6d966e0719e4d082ac35ce586c088e0

**Comment by kentcdodds** [comment]
Wow! That's awesome @jspraul! Thank you very much!!! I'm hoping to get the recordings up somewhere eventually. Will ping in here when I do.

I just want to say thank you to everyone who joined in on the conversations. It was really enjoyable. I've never had so much fun driving by myself.

I do plan to do more calls like this in the future, though never as long. If I'm driving by myself more than a half hour or so, I'll probably just start up the call and tweet about it (so [follow me](https://twitter.com/kentcdodds) to see that).

Thanks again. It was great!

**Comment by abdulhannanali** [comment]
@kentcdodds Thank you for answering my Udacity Nanodegree, although I was in the call for a fair amount of time I couldn't just get my self to speak up. :sad: it was great to learn from amazing people there who were discussing everything from about Storybook to Jest. Love the conversations. <3 Would definitely love to speak with everyone till then I can work on my communication.

**Comment by ndelangen** [comment]
I had a great time too, got to speak to new people, and learn about new things.

**Comment by BrianSchroer** [comment]
In a few minutes, I’ll be starting a 5-hour drive to the Kansas City Developers Conference.

If anyone wants to call and ask me any questions, my areas of expertise are:

- Visual Basic 6 and "Classic ASP"
- Simpsons trivia
- Favorite pizza  toppings

Seriously, I had a great time this weekend, and may have learned more than I will at the conference.

At one point we discussed the frustration of working with other developers who didn't share your passion for software. Luckily, I have *one* colleague who didn't look at me like I was a loon when I told him about it, and knew why it was a big deal that I spent the weekend hanging out with KENT C DODDS! And NORBERT from STORYBOOK was there. And HENRY ZHU showed up!!

Thanks, all.

**Comment by BrianSchroer** [comment]
I apologize to those who didn't realize I was joking about calling me during my drive today. I guess deadpan humor doesn't come across well online. If you knew me, you would realize that I don't have much knowledge to share. :) Thanks for your friendliness, though!

**Comment by mxstbr** [comment]
This issue was featured on the GitHub Octoverse 2017 "Highlights of the last 12 months" page!!! https://octoverse.github.com/

<img width="652" alt="screen shot 2017-10-11 at 9 05 31 pm" src="https://user-images.githubusercontent.com/7525670/31460868-f99c11b2-aec7-11e7-9339-a70ecf5bee53.png">

**Comment by kentcdodds** [comment]
Well that's awesome! 😂  Thanks for letting me know @mxstbr!

Also, I'm uploading the recordings to Google Drive right now: https://drive.google.com/open?id=0BxZDtibcRzVWOXh4V1BIeU9YRE0

Thanks again everyone. This was a terrific experience that I'd like to repeat one day 😄

**Comment by sriharshakappala** [comment]
I came here from this https://octoverse.github.com/  Great work @kentcdodds :)

**Comment by blakeathomas** [comment]
Hey, just heard about this. Pretty cool. Great Job! @kentcdodds

**Comment by kentcdodds** [comment]
Hey friends 👋 
We're doing this again! https://github.com/kentcdodds/ama/issues/405
