### ISSUE TITLE
AST Resources

### ISSUE THREAD

**Issue by reznord** [kentcdodds/ama#297]
I'm looking for some resources for learning about ASTs. 

I've found @kentcdodds 's [video recording](https://www.youtube.com/watch?v=CFQBHy8RCpg) on Youtube.

Can anyone else suggest any other resources regarding ASTs?

**Comment by kentcdodds** [comment]
Hey @reznord :wave:

I list the best resources I'm aware of at the end of my blog post: [How writing custom Babel & ESLint plugins can increase productivity & improve user experience](https://medium.com/@kentcdodds/how-writing-custom-babel-and-eslint-plugins-can-increase-your-productivity-and-improve-user-fd6dd8076e26). Definitely [My course on Frontend Masters](https://frontendmasters.com/courses/linting-asts/) too :smile:

Good luck!

**Comment by reznord** [comment]
That blogpost is real gold! Amazing kent.

Thanks a ton 😄
