### ISSUE TITLE
Guidance to further improve my javascript skills so that i can contribute

### ISSUE THREAD

**Issue by nveenjain** [kentcdodds/ama#299]
Hey kent, I wanted to contribute to babel and other such huge projects. I've gone through babel-handbook too, but still I can't solve issues except for the ones with test cases. Adding to it, there are quite a lot of tools required by a single open source project (like babel uses flow, jest,etc.), when encountered by that code, I don't know how to tackle it (Don't know whether I can solve issues or not)? Will you please honor me by guiding me/suggesting me some source to improve skills required(for such huge projects). (Currently, I'm reading you don't know js). Any other book/path you would recommend? I'll be very grateful if you could guide me. Thanks.

**Comment by kentcdodds** [comment]
Hi @nveenjain :wave:

Thanks for the question! As I've said multiple times on this AMA, there's no shortcut to experience. You really just have to dive in and start messing around with stuff. It takes a lot of time. [The "You Don't Know JS" series](https://github.com/getify/You-Dont-Know-JS) is a fantastic resource to help you improve your JS knowledge. I don't read a whole lot (#17). For me it's really just a matter of jumping in and working with stuff. It can be really frustrating at first, but you'll get it with time.

If you haven't already, you might be interested in watching ["How to Contribute to an Open Source Project on GitHub"](http://kcd.im/pull-request).

Good luck!
