### ISSUE TITLE
What's your favorite part about programming?

### ISSUE THREAD

**Issue by sindresorhus** [kentcdodds/ama#3]

**Comment by kentcdodds** [comment]
I think my favorite part finding hard problems, and creating elegant solutions. There's just something about coming up with a fantastic solution to a hard problem. That gets me every time. I think I'm a bit of an architect implementor. I like developing solutions that have a huge impact on the overall product (or on multiple products via an open source library or tool).

I'm also a huge fan of the community around JavaScript. I may be a bit of a ham, but I really enjoy going to and speaking at conferences and sharing with others what they and I have learned from our experiences. That's super fun.
