### ISSUE TITLE
Using angular-formly

### ISSUE THREAD

**Issue by rihabesx** [kentcdodds/ama#30]
Hi Kent,

Thank you for all the work in angular-formly.
I have an existing angular application where I have used includes to dynamically build parts (chunks, i.e many fields each include) of a form spanning multiple tabs.

Now that I have decided to use formly, I am not seeing how I could implement a similar dynamic form parts. I thought about expressions per field but then I will have to repeat the same condition for each field in a form part.

I hope that I have made my question clear and I hope to hear from you soon.

By the way, I have seen your tabs example and that helps in constructing the form over many tabs. But as I said, I would like multiple dynamically added chunks of the form (multiple fields) to each tab and to show and hide. Once hidden, the validation should not take place on hidden or not rendered fields.

Thanks a lot.

**Comment by kentcdodds** [comment]
Hi @rihabesx,

Thanks for asking. The beauty of angular-formly is how easy it is to keep your code [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). If you take the bootstrap templates as an example, take a look at the [input type template](https://github.com/formly-js/angular-formly-templates-bootstrap/blob/master/src/types/input.js#L7). It's literally 58 inlined characters. But if you look at any example that uses this, you'll see that it can have validation, a label, and much more.

This is made possible by the [wrappers](https://github.com/formly-js/angular-formly-templates-bootstrap/blob/master/src/types/input.js#L8) it uses ([example](http://angular-formly.com/#/example/advanced/template-wrappers)). You [define a wrapper](http://docs.angular-formly.com/docs/formlyconfig#setwrapper), and then you can assign that to a field or a type. Learn more about this by watching either my [NG-NL Talk](http://docs.angular-formly.com/v6.23.7/docs/learn-angular-formly#ng-nl-talk) or my (more recent) [MidwestJS Talk](http://docs.angular-formly.com/v6.23.7/docs/learn-angular-formly#midwestjs-talk) giving a good overview of angular-formly.

> Once hidden, the validation should not take place on hidden or not rendered fields.

Yes, hidden fields do not take validation into account (there's a simple work-around to this, but the default is to have them not make an impact when they're not showing).

Good luck!
