### ISSUE TITLE
Career path

### ISSUE THREAD

**Issue by aileenvl** [kentcdodds/ama#300]
Hi Kent! Big fan of your work, knowledge and contribution to open source. Let me introduce myself, my name is Aileen. I’m a frontend developer self taught and I’ve only develop in JavaScript with frameworks like angularjs and backend with node I want to improve myself and become proficient JavaScript developer. I look forward for your advice if possible.

Want to ask what’s the best way to become proficient? And how to prove to recruiters your knowledge, meaning maybe contributing in open source and if so in what kind of way ? Or maybe having a personal web page? I mostly work in consulting companies so I can’t show my portafolio since is part of the job not to mention clients. Also should I learn another backend language such as java, c# , python? I’ve seen that some companies don’t take JavaScript as a serious programming language and it has sometimes made me lose some working opportunities. And finally I don’t have a good cs or algorithms knowledge since I don’t really have a cs degree ,how to get this knowledge of architecture of architecture or cs concepts and algorithms and should I care to know all of these? Thank so much for your time!🤗

**Comment by kentcdodds** [comment]
Hey @aileenvl! :wave:

Congratulations on being question #300! :tada:

Thank you so much for your questions!

> what’s the best way to become proficient?

I've said many times on this AMA that there's no shortcut to experience. It really takes a lot of time and energy. I talk about how I go about doing this in #89 :smile: I hope that helps answer your question.

> And how to prove to recruiters your knowledge [OSS? Website?]

I've found that developing relationships with other developers has proved to be a more effective way to get the jobs that I want than trying to impress recruiters. That said, having a solid contributing graph on GitHub is something that recruiters reference very often when they reach out to me. As an interviewer, a "weak" contribution graph on GitHub is something I don't hold against anyone. That said it is a great way for me to get to know the kinds of things that person is working on, so it makes it easier for me as an interviewer to see whether this person can bring the skills we need on the team.

[I have a very unimpressive website](https://kentcdodds.com/). Sadly, I'm afraid that not everyone could get away with something like that. I don't have to fight the bias so prevalent in our industry (I'm white, young, male, and heterosexual). I think that it'd be great for me to improve my website and only help me in the long run, but it's not something I've prioritized personally.

> Should I learn another backend language such as java, c# , python? I’ve seen that some companies don’t take JavaScript as a serious programming language and it has sometimes made me lose some working opportunities.

Any company not taking JavaScript seriously is making a serious error. I personally have focused all my time and attention on JavaScript and it's proved very well for me. I would definitely benefit from learning other languages, but I've chosen to hold off for now. I don't think that you would be in too much trouble focusing on JavaScript. There are lots of opportunities out there for JS devs. I guess this kind of depends on where you live, so if I were you I'd reach out to a few recruiters and ask them if they can provide you with any data about the skills needs in your area.

> And finally I don’t have a good cs or algorithms knowledge since I don’t really have a cs degree, how to get this knowledge of architecture of architecture or cs concepts and algorithms and should I care to know all of these? 

I also don't have a CS degree or algorithms knowledge! I think it's probably valuable to have an understanding of some of these things, and [James Kyle](https://twitter.com/thejameskyle) has some great material: ["Itsy Bitsy Data Structures"](https://github.com/thejameskyle/itsy-bitsy-data-structures) and ["The Super Tiny Compiler"](https://github.com/thejameskyle/the-super-tiny-compiler). I suggest looking into those. Also [Brian Holt](https://twitter.com/holtbt) has a great course on Frontend Masters (if you have a subscription to that) called [Four Semesters of Computer Science in 5 Hours](https://frontendmasters.com/courses/computer-science/) that I suggest you take a look at if you can.

I hope that's helpful! Good luck to you. And thanks again :tada:
