### ISSUE TITLE
How do I build a meaningful rapport with a remote team?

### ISSUE THREAD

**Issue by imavroukakis** [kentcdodds/ama#301]
I'll begin with something that @kentcdodds mentioned in conversation

> it's definitely a matter of finding happiness where you are 

Expanding on this, and in relation to the question, my assertion is that a primary source of happiness on the job is down to the personalities of the team, both blending _and_ standing out at the same. 

Given a remote team, that does not, or will not, cluster around a team chat medium, how do you build a) a meaningful rapport  and b) "convince" them of the merits of (a) without sounding like a cultist?

**Comment by kentcdodds** [comment]
Hi @imavroukakis,

Thanks for the question. That's a really tough one! What do you mean by "cluster around a team chat medium." You mean that there's no way to effectively communicate with your team? If that's the case then you need to communicate with the people who make decisions about that kind of thing. Probably management. Explain to them the challenges that you're facing and ask them to help you enforce a better communication mechanism so you all can do your jobs better.

I hope that helps!
