### ISSUE TITLE
How to push generated docs with semantic-release?

### ISSUE THREAD

**Issue by sudo-suhas** [kentcdodds/ama#303]
Hey Kent, I recently went through your egghead course and was able to set up semantic-release for a repo - [eslint-config-chatur](https://github.com/sudo-suhas/eslint-config-chatur). I also wanted to setup semantic-release for [elastic-builder](https://github.com/sudo-suhas/elastic-builder). However, I am stumped on one aspect and I haven't been able to find a good answer. Along with the release process, I also want to build documentation which is hosted here - https://elasric-builder.js.org/docs. How do I build and commit this? I use the master branch itself for this. I saw that you had written [publish-latest](https://github.com/kentcdodds/publish-latest) but it is now deprecated. I apologise for asking this question here rather than the semantic-release repo itself. But there seems to be less activity there.

**Comment by kentcdodds** [comment]
Hi @sudo-suhas,

Thanks for the question!

So I generally treat docs as an entirely separate process from my releases. There have been _some_ cases where I have hosted old versions of docs and had the docs versioned, but in those cases I still managed it separately. Often, if your docs are in the repo, then people can access the older versions of the docs by looking at the git tag on GitHub.

As for building the docs site, it really depends. Right now with glamorous, the docs website is even in a different repository, so it's all managed differently. If it's in the same repo, then I suggest you just include building the docs as part of the travis build (or whatever you're using for CI).

I hope that's helpful. Good luck!

**Comment by sudo-suhas** [comment]
Alright, thanks @kentcdodds!

**Comment by sudo-suhas** [comment]
Note for anybody else who might come across this, I used [`gh-pages`](https://www.npmjs.com/package/gh-pages) to solve this. Getting the right command was slightly tricky though.
See - https://github.com/sudo-suhas/elastic-builder/blob/4c454fd3c345ae7de09cd5ad27dcac9479a71cf6/.travis.yml#L29-L37

**Comment by kentcdodds** [comment]
I'm surprised I didn't mention [Netlify](https://www.netlify.com/) to you, but it's amazing and I highly suggest you try it out as well. I think you'll be pleased!

**Comment by sudo-suhas** [comment]
The [documentation](https://elastic-builder.js.org/docs/) is generated using [documentationjs](https://github.com/documentationjs/documentation) and it is better to do it after `semantic-release pre`. I am not sure netlify would fit into this workflow. Also, the domain is through [dns.js.org](https://github.com/js-org/dns.js.org) which needs github pages(I think).

**Comment by kentcdodds** [comment]
Gotcha
