### ISSUE TITLE
Thoughts on cleaner package.json file for published packages.

### ISSUE THREAD

**Issue by Jefiozie** [kentcdodds/ama#305]
Hi Kent, 

In the last couple of days I've been working on some internal npm packages.
One of the things I found out was that in my published "package.json"; I still had a lot of "extra" information that is not needed. For example the scripts tag or the dev-dependencies tag where still there.

What are your thought on making a more cleaner package.json file for published packages?

Thanks for your time looking, forward on your thoughts.

**Comment by kentcdodds** [comment]
Hi @Jefiozie,

Thanks for the question!

> What are your thought on making a more cleaner package.json file for published packages?

I personally don't really care about that, and I would suggest that you don't care either. It's so small it's not worth the effort. But if you're determined, one thing you could do is have a script that changes the package.json in a `prepublishOnly` script which changes the `package.json` file temporarily and then a `postpublish` which restores the original. That would be a way to solve the problem. But again, I don't recommend this. It's not worth the extra complexity. If it really mattered that much, npm would do something about it on their end :wink:

Good luck!
