### ISSUE TITLE
Side project idea validation

### ISSUE THREAD

**Issue by Raathigesh** [kentcdodds/ama#309]
Hey Kent,

If you have an idea for a side project which would take considerable effort to implement and if you are not quite sure how well it would be received, would you prefer to validate the idea first or would you go ahead implementing it and then see what happens?

Thanks,
Raathi

**Comment by kentcdodds** [comment]
Hi @Raathigesh!

Thanks for the question! I actually had an idea like this a while back! It's called "Bucket Streams" ([learn more about the bucket streams idea here](https://www.youtube.com/watch?v=7ID64AEbl-0)). I don't think it works anymore, but [here's the app](http://alpha.bucketstreams.com/).

When I was building this, I spent a LOT of time researching things trying to validate the idea. I think that was a good idea. I just didn't have the dedication to really take it all the way. It was for a school project and once I got credit, I found other things to distract me 😅
