### ISSUE TITLE
how would you approach minimizing the size and number of http calls of a Node/React/Webpack application w/ 50+ image assets.

### ISSUE THREAD

**Issue by talgoldfus** [kentcdodds/ama#311]
Hey Kent, 

How would you approach minimizing the size and the number of HTTP calls required to load 50+ image assets as well as 40+ icons (most of which are not font icons) in a Node/React/Webpack application?  Are CSS sprites still a thing?

Thanks in advance

**Comment by kentcdodds** [comment]
Hey @talgoldfus!

Actually, I've done very little of that kind of optimization myself. Most projects that required those kinds of optimizations already had them in place when I got on the project. We do use CSS sprites for some of it. For icons, I suggest SVGs as they'll scale better, they're smaller, and more accessible.

Sorry that's not quite as helpful as you were probably hoping. Good luck!
