### ISSUE TITLE
Build Tools For Massive Project. Send Help.

### ISSUE THREAD

**Issue by ryanvaness** [kentcdodds/ama#314]
Hello!

I'm currently working on a massive LAMP stack software, and I have been tasked to implement some front end build tools. Since its such a big project, there are tons of js and scss files.

I've done smaller projects using Webpack/Babel that only have one main js file; I'm just wondering if there's a way I can set it up for many js files.

I would appreciate any tips to guide me in the right direction.

Many thanks!

**Comment by kentcdodds** [comment]
Hey @ryanvaness!

Thanks for the question! One of webpack's strengths is bundling up many js/scss/etc. files together. I strongly recommend you check out @TheLarkInn's [webpack.academy](https://webpack.academy/). Also I have some content about webpack:

- [My webpack stuff on Egghead.io](http://kcd.im/egghead-webpack)
- [Webpack 2 Deep Dive on Frontend Masters](http://kcd.im/fem-webpack)

Good luck to you!

**Comment by ryanvaness** [comment]
Thanks for the resources! I have some homework to do now.

I suppose I have a follow up question then.

In a project like this, is it better to include one bundled js file that's potentially millions of lines long, or a separate bundled js file for each of the 100 or so pages?

**Comment by kentcdodds** [comment]
> is it better to include one bundled js file that's potentially millions of lines long, or a separate bundled js file for each of the 100 or so pages?

million lines long? Well, first off make sure that you're minifying your JavaScript. Secondly, you'll want to only include the code on the page that's needed for the page. You can do this with code splitting and/or having multiple entries with webpack. You'll come across these things as you research things!

Good luck!

**Comment by ryanvaness** [comment]
Interesting. I've never heard of code splitting. Sounds good to me!

> Well, first off make sure that you're minifying your JavaScript.

Should've seen that coming, haha.

Thanks a ton!
