### ISSUE TITLE
How to open my repo to other contributors?

### ISSUE THREAD

**Issue by mbowen13** [kentcdodds/ama#315]
I have a repo for an application I want to make open source because I can use the extra help. Is there a checklist to follow?

i.e.: How do I make it easy for other contributors to contribute? Should I deploy the master branch or have a deploy branch?

**Comment by kentcdodds** [comment]
Hey @mbowen13!

Have you had a chance to watch my course ["How to Write an Open Source JavaScript Library"](http://kcd.im/write-oss)? I think that could really help point you in the right direction. Also, you might enjoy my talk ["Managing an Open Source Project"](https://kentcdodds.com/talks/#managing-an-open-source-project).

Good luck!
