### ISSUE TITLE
Can we just use Prettier instead of a combo of ESLint + Prettier

### ISSUE THREAD

**Issue by alayek** [kentcdodds/ama#316]
Hi,

Recently I saw your tweet, that you have been using Prettier without ESLint. 

I have been working on a React project recently. And making Prettier work with ESLint can be challenging at times.

Are Prettier and its plugin ecosystem stable enough to completely replace ESLint? Are there any edge cases we should worry about?

**Comment by sapegin** [comment]
You can’t replace ESLint with Prettier (or at least you shouldn’t) — they solve very different problems. Prettier formats your code but ESLint helps you to write better code, prevents bugs and ensures best practices.

**Comment by kentcdodds** [comment]
Hi @alayek!

Yeah, @sapegin is correct, ESLint cannot be entirely replaced by prettier. I think that Nicholas C. Zakas‏ (creator of ESLint) [said it best](https://twitter.com/slicknet/status/877194938508656641):

> Prettier is not a replacement for ESLint. Prettier is a source code formatter. ESLint is a code quality tool.

<img width="633" alt="screen shot 2017-09-06 at 12 47 53 pm" src="https://user-images.githubusercontent.com/1500684/30128949-a078eca4-9301-11e7-99ba-6e5cf71bde75.png">

I'm slowly removing eslint stylistic rules from my setup and using prettier for formatting concerns (even though I created [`prettier-eslint`](https://github.com/prettier/prettier-eslint)). It's simplifying my life considerably :)

Good luck!
