### ISSUE TITLE
How to semantically release a beta package?

### ISSUE THREAD

**Issue by Apidcloud** [kentcdodds/ama#318]
Hello!

First of all, thanks for the egghead courses and articles. It really helped me get my head around all these packages (javascript world in general) and what not.

I have a question regarding semantic releases.
How can I release a package with different tags such as **beta**? You've taught the manual way and I get it, but I would like to be able to do the same automatically (i.e., semantic-release). Or rather, what's your method when you are releasing a non-ready version?

I have tried **--tag=beta** flag after npm publish, but I believe it's not really working as intended as npmjs doesn't show the release under that tag. It would also be nice to get that same tag under **github releases**.

Thanks for your time!

Edit:
Actually, the **beta tag** is working with npm. It shows up under `npm info package_name` **dist-tags**. I wonder if it's possible to accomplish the same thing in GitHub. 

I will ask the same question in https://github.com/semantic-release/semantic-release/issues/97

**Comment by kentcdodds** [comment]
Hi @Apidcloud!

Thanks for the question. So I've never tried to automate releases of `beta` or `next` tags. I find that I do it so infrequently that it's not really worth figuring out and configuring. So I'll just do it manually on my local machine.

Sorry that's not super helpful. Good luck!

**Comment by Apidcloud** [comment]
Thanks @kentcdodds! I ended up creating a PR to make pre-releases to GitHub: https://github.com/semantic-release/semantic-release/pull/457
