### ISSUE TITLE
What's your favorite place on earth and why?

### ISSUE THREAD

**Issue by arthurvr** [kentcdodds/ama#32]

**Comment by kentcdodds** [comment]
That's a big question! I live in American Fork, UT. I think right now, home is my favorite place on earth. I'm married and have two kids (one on the way). I really love spending time with them at home. I have a solid internet connection as well so I can code up a storm after the kids go to bed and my wife and I have had time or early in the morning. I feel safe and secure. I feel loved. There's no better place on earth for me than being at home.

Thanks for the question. It was a tough one!
