### ISSUE TITLE
Thoughts on 'toolboxes' and considerations when building my own 'kcd-scripts'

### ISSUE THREAD

**Issue by peterschussheim** [kentcdodds/ama#324]
Hey Kent,

Big fan of your work and want to thank you for the contributions to the JS/Node community.  This question stems from your `kcd-scripts` videos from Youtube and [Dan Abramov's FANTASTIC talk from Zeit World Berlin](https://www.youtube.com/watch?v=G39lKaONAlA).  Now that I am trying to word my question, I realize it is better split into two:

- In `kcd-scripts` you seem to be using `rollup` or `babel` as the build process.  I searched but couldn't find your comments on **WHY** you use `rollup` instead of `webpack` (I found a closed AMA where you talked about using `rollup` on one project).  Can you please expand more on your reasons for using `rollup` || `babel` || `webpack` and why your prefer one for a specific use case?

- After watching Dan's talk, I was inspired to start thinking about building my own toolbox.  I was reminded of `kcd-scripts` and realized that I should take a similar approach when building my own toolbox.  I guess what I am trying to ask here is for you to **share your design / use case considerations when you built `kcd-scripts` and paypal scripts** and any **tips you have that can help someone building a similar toolbox to narrow all the choices/tools to include or support.** 

Please let me know if this is not clear.  Looking forward to hearing from you.

Peter 👍

**Comment by kentcdodds** [comment]
Hi @peterschussheim!

I use babel when transpiling something that's only used in node, and rollup for things that will go to the browser. Though I could use rollup's cjs bundler to do node as well, I think that makes it harder for people to debug things in their `node_modules` directory. Regarding webpack vs rollup, [read this](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c).

I pretty much built kcd-scripts (and paypal-scripts) to satisfy my own needs. That's pretty much how I build all my software :) If you find yourself doing the same thing in multiple projects, then include it in your tool :smile:

Good luck!

**Comment by peterschussheim** [comment]
Thanks Kent! 👍
