### ISSUE TITLE
What's your stand on technological singularity?

### ISSUE THREAD

**Issue by v1adko** [kentcdodds/ama#325]
Hi Kent. 

After seeing advances of AI in the fairly recent past and all of the investments and acquisitions that tech giants are making, using AI to improve their services, actively betting on it, I have taken interest in the ideas of Singularity and advanced AI.

What is your take on this? Do you think that software developers will play a big role in this? Is it inevitable?

Do you know people who are actively working on AI programs at those big tech companies?
I would love to get more insights.

Thank you very much.

**Comment by kentcdodds** [comment]
Hi @v1adko!

I actually just answered this question 3 days ago :wink: https://github.com/kentcdodds/ama/issues/321

**Comment by v1adko** [comment]
Yes thank you, but that was more of a "will they replace us as developers" kind of question. I'm interested in weather you think it's inevitable (in our lifetime) and more of a will it be the last invention (basically recursive progress and self-improvement) and so on.

To generalise and simplify - what is your take on points in [this TED talk](https://www.youtube.com/watch?v=MnT1xgZgkpk)?

And do you know anyone who actively works on these systems, either within tech giants or even Open Source contributors to TensorFlow, DeepMind and the likes.

**Comment by kentcdodds** [comment]
I'll give that talk a look later. Thanks for clarifying :)

**Comment by kentcdodds** [comment]
It's an interesting talk for sure!

> Do you think that software developers will play a big role in this?

Software developers will most certainly play a big role in this, considering we can't build AI without software developers.

>  Is it inevitable?

I guess so. I'm sure _someone_ will work on it and make it a reality, even if we collectively decide it's a bad idea.

> Do you know people who are actively working on AI programs at those big tech companies?

I don't know anyone personally that I can think of...

> I'm interested in whether you think it's inevitable (in our lifetime) and more of a will it be the last invention (basically recursive progress and self-improvement) and so on.

In our lifetime? Hmmm... I don't know. I'm not familiar enough with the space to tell how close we are. But I have a feeling that [the millennium](https://www.lds.org/topics/millennium) will happen before we get a chance to make it as far as that guy was talking :wink: Then everything will change for the better anyway.

Thanks for the interesting talk!
