### ISSUE TITLE
Your video about testing

### ISSUE THREAD

**Issue by norbertpy** [kentcdodds/ama#326]
Hi Kent,

Thanks for all your contribution to open source world. I remember you had a short video about testing in general. It was about 8-10 minutes long and was like an overview of testing (unit, integration, e2e). It was at a conference (maybe ReactRally) and is fairly recent (few months ago). It was NOT specific to any tools or technologies and it was NOT a workshop. 

I cannot find it and I really need it. Can you help please?

**Comment by kentcdodds** [comment]
Sadly, O'Reilly has made it unlisted, so it's not easy to find. But I've linked to it on [my website](https://kentcdodds.com/talks/#what-we-can-learn-about-testing-from-the-wheel) and it's in [my Talks and workshops playlist](https://www.youtube.com/watch?v=Da9wfQ0frGA&feature=youtu.be&list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf).

Enjoy :)

**Comment by norbertpy** [comment]
Awesome. Thank you sir.
