### ISSUE TITLE
On being the first and fighting xenophobia

### ISSUE THREAD

**Issue by v1adko** [kentcdodds/ama#327]
In continuation to [my comment](https://github.com/kentcdodds/ama/issues/265#issuecomment-337163672) on #265.

>I was surprised to hear that you [don't use yarn](https://github.com/kentcdodds/kcd-scripts/issues/10#issuecomment-336515507). I've got an impression that it's somehow better or faster than npm. I can blame tweets like [this one](https://twitter.com/iamdevloper/status/917710714361602048) for ignorance, but in truth I simply believed the hype and didn't spend time actually trying both and comparing.
>
>How do you switch your tooling so easily? I get very used to something and then some sort of xenophobia kicks in. Even though I don't regret switching to webstorm to vscode, mocha to jest and using tools like prettier, but the thing is that most of people (myself included) try new things once they reach some level of hype or admiration, but you seem to be ahead of the crowd, pushing and even creating cool things into the "general public" and I think it's amazing.
>
>Is there a secret to how you do this?)

And yeah, as I've promised you on twitter, I started reading more of your AMA - it's great! 
Respect for [sharing knowledge](https://github.com/kentcdodds/ama/issues/277#issuecomment-302959724) so easily!

**Comment by kentcdodds** [comment]
Hi @v1adko!

I was locked out of my house for a few hours the other day so I recorded answers to a bunch of my AMA questions and put them up on [my 3 minute podcast](http://kcd.im/3-mins). [Here's your answer](https://www.briefs.fm/3-minutes-with-kent/52)!

**Comment by v1adko** [comment]
Nice. Thank you for the answer!
Kudos for the last name pronunciation btw, pretty good 👍
