### ISSUE TITLE
npm ecosystem and semver

### ISSUE THREAD

**Issue by danseethaler** [kentcdodds/ama#328]
Hey Kent!

I've published a few npm packages recently and also been working on upgrading to React@16 at work. I have some rapid fire questions about npm I'm hoping you can help with or at least point me in the right direction. Two of them I actually asked on SO but haven't had any feedback at all. Thanks so much for any thoughts in advance!

## Nested dependecy overhead
While upgrading to react@16 on the [foreman project](https://github.com/theforeman/foreman) I've been thinking about the structure of npm and how dependencies rely on other dependencies and on and on. Each of those dependencies sets a specific version range that it will work with. This whole scenario seems like it could really slow down the upgrade process if you've got a nested dependency that hasn't updated their package.json to support React@16 (or whatever you're moving to). If a package has a React peer dependency of 15.x will it use React@16 anyway? I realize it may break since it hasn't been tested but would it use it?

## Set the semver range as npm author
I just published my [first npm package](https://www.npmjs.com/package/dayone-to-md) on npm and I don’t understand how the semver range is specified.

When I install `react` I get `"react": "^15.6.1"` (with the caret) in my `package.json`. When I install `dayone-to-md` I get `"dayone-to-md": "0.0.2"`. I'm assuming as a package author I can do something to set the caret/tilde when a user installs my package. How would I accomplish that?

## Get patch updates with caret on npm package
The caret symbol (^) doesn't seem to include patch updates on `npm update`

After I published `v0.0.1` of my package I installed it in a local project and set the semver range to `^0.0.1`. I then bumped my packge version to `v0.0.2` and published to npm. When I run `npm outdated` I see 

```
Package       Current  Wanted  Latest  Location
dayone-to-md    0.0.1   0.0.1   0.0.2  test-dayone-to-md
```

indicating there is a higher latest version but my semver range doesn't want it.

If I change my semver range to `~0.0.1` and run `npm outdated` I see 

```
Package       Current  Wanted  Latest  Location
dayone-to-md    0.0.1   0.0.2   0.0.2  test-dayone-to-md
```

I would expect this second outcome to be the result when I use the `^` or the `~` since they both encompass the patch updates.

I read through the docs but I don't see anything that would explain this. Thanks for your help!

**Comment by kentcdodds** [comment]
Hi @danseethaler!

I was locked out of my house for a few hours the other day so I recorded answers to a bunch of my AMA questions and put them up on [my 3 minute podcast](http://kcd.im/3-mins). [Here's your answer](https://www.briefs.fm/3-minutes-with-kent/53)!

**Comment by danseethaler** [comment]
Ah this is great! Thanks @kentcdodds! The https://semver.npmjs.com/ site is pretty nifty 😀
