### ISSUE TITLE
Do you believe in extraterrestrial life?

### ISSUE THREAD

**Issue by robbbz** [kentcdodds/ama#33]

**Comment by kentcdodds** [comment]
Yes, I believe there are sentient beings on other planets. It's actually part of my religious beliefs that God created ["worlds without number"](https://www.lds.org/scriptures/pgp/moses/1.33#32). [Elder Neal A. Maxwell](https://en.wikipedia.org/wiki/Neal_A._Maxwell) (deceased member of [the quorum of the twelve apostles](https://www.lds.org/church/leaders/quorum-of-the-twelve-apostles?lang=eng)) said (https://youtu.be/DiTTUZqmZkw?t=1m45s):

> How many planets are there in the universe with people on them? We don't know. But, we are not alone in the universe. God is not the God of only one planet.

I truly believe this.

Whether I believe that we'll ever come across people on other planets is a bit of a different matter. I have no reason to believe one way or another (whether scripturally or from my church leaders), but I personally believe that it doesn't make sense for us to meet them before Christ comes again. I wouldn't be surprised if it happened after though.

Thanks for the question! Sorry it took so long for me to get to you! You asked this a few days after my third child was born :baby:. Things have been a little crazy around here!
