### ISSUE TITLE
Contribute to anything 

### ISSUE THREAD

**Issue by OsamaJandali** [kentcdodds/ama#330]
I have seen your your tweets about contributing to many web tools, so I had this question if I want to contribute and understand many web tools like for example webpack and bable what should I learn to do so knowing that I know javascript but not in a way to make me contribute nor understand the written code.

**Comment by kentcdodds** [comment]
Hi @OsamaJandali!

I was locked out of my house for a few hours the other day so I recorded answers to a bunch of my AMA questions and put them up on [my 3 minute podcast](http://kcd.im/3-mins). [Here's your answer](https://www.briefs.fm/3-minutes-with-kent/54)!

**Comment by OsamaJandali** [comment]
Thanks you for your response. It really helped me.
