### ISSUE TITLE
Babel-preset-env?

### ISSUE THREAD

**Issue by cuong-nguyen** [kentcdodds/ama#331]
Hi @kentcdodds, I am still getting my head around this new preset.

Because not all browsers support new feature of ES, if you want to use those features, you need babel preset to transpile it so browsers can understand them. At this point, I understand the purpose of preset like **es2015, es2016,...**

And gradually browsers adopt more new ES features, it's no point in transpile and send polyfills down to client anymore, that's why they introduce **babel-preset-env**

Here are my questions:

We have the option to specify the browsers we want to target, e.g.

`{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions", "safari >= 7"]
      }
    }]
  ]
}`

1/ How does babel know **which browser has what features** so it does not need to transpile those features?
2/ With above example, if users with **safari version 6** go to our website, functions might not work, right?
3/ What does **versions** imply, the major version (59, 60) or the minor/patch (59.0.1,...)?
4/ Adopting this new preset, we need to know for sure which browsers we support?

Thanks :)

**Comment by kentcdodds** [comment]
Hi @cuong-nguyen!

I was locked out of my house for a few hours the other day so I recorded answers to a bunch of my AMA questions and put them up on [my 3 minute podcast](http://kcd.im/3-mins). [Here's your answer](https://www.briefs.fm/3-minutes-with-kent/55)!

**Comment by cuong-nguyen** [comment]
Thanks @kentcdodds. That helps a lot.
