### ISSUE TITLE
React + Router

### ISSUE THREAD

**Issue by dbabaioff** [kentcdodds/ama#332]
Hey Kent,
I'm working on a new React project and I wanted to ask you about the router
1 - I understand you can use different router libraries with React - which router you recommend to use with React?
2 - If I need to save data specific to a url (page data) - for example - the scroll position, the page number of a feed, what would be the best place to store ? in a module? redux? router library?
3 - One of the requirements of our project is to implement a cache for the router - each page the user visit, we make some ajax requests to an API to load data for this page. If the user come back to the same page he was before, we should load right away and not make another request(s).
What would be the best way to implement this?

Thanks!

**Comment by kentcdodds** [comment]
Hi @dbabaioff!

I was locked out of my house for a few hours the other day so I recorded answers to a bunch of my AMA questions and put them up on [my 3 minute podcast](http://kcd.im/3-mins). [Here's your answer](https://www.briefs.fm/3-minutes-with-kent/56)!
