### ISSUE TITLE
Any tips about blogging?

### ISSUE THREAD

**Issue by Booligoosh** [kentcdodds/ama#333]
Hi Kent!
I've started a blog for beginner web developers (plain HTML, CSS and JS for the moment) which takes people though learning to code right from the ground up:

https://codetheweb.blog/

The problem is, not many people seem to be coming and most that do usually leave after less than a minute. I really put a lot of time and effort into these tutorials, and am wondering how to get more people to read and appreciate them (not spam people and annoy the internet). Ideally I do not want to spend any money on this eg. with ads.

Any ideas of how to get more readers and how to keep them engaged? Also, any general blogging feedback or advice would be appreciated. Thanks! 😸

**Comment by kentcdodds** [comment]
Hi @Booligoosh!

I was locked out of my house for a few hours the other day so I recorded answers to a bunch of my AMA questions and put them up on [my 3 minute podcast](http://kcd.im/3-mins). [Here's your answer](https://www.briefs.fm/3-minutes-with-kent/57)!

Good luck on your blog!

**Comment by Booligoosh** [comment]
@kentcdodds Thanks so much! You are really inspiring 😄  I never knew that CSS-Tricks started out so small, that's really awesome :)
