### ISSUE TITLE
Advice for an aspiring developer?

### ISSUE THREAD

**Issue by rileyskains** [kentcdodds/ama#334]
I am a pretty young developer, 22, who is not particularly talented, and I am currently in my senior year of college getting a degree in web development.

As I have been pursuing my degree, I cannot seem to keep myself motivated in pursuing a career as a developer. I am absolutely in love with the Internet and technology in general, and my primary goal in life is to be able to make an impact in other peoples' lives.

I am at my happiest when I am making other people happy, but I can't seem to find my niche in tech where I am doing something I enjoy while also helping other people. If I make something I enjoy, no one uses it. If I make things people use, I typically get stressed out and dislike the process.

The tech community can be a little intimidating, so reaching out is kind of scary for me. I never know if I'm going to say the wrong thing to the wrong person and ruin my chances at something that could have been great.

Are these the normal feelings for someone at this stage in my career? Can you think of another way I could positively contribute to the open source/web community in a less technical aspect? Should I keep pushing through? Or maybe you have a totally different approach?

Your time in reading this is greatly appreciated, and I hope you have a great day!

**Comment by kentcdodds** [comment]
Hi @rileyskains!

I was locked out of my house for a few hours the other day so I recorded answers to a bunch of my AMA questions and put them up on [my 3 minute podcast](http://kcd.im/3-mins). [Here's your answer](https://www.briefs.fm/3-minutes-with-kent/58)!
