### ISSUE TITLE
Getting More Into Testing

### ISSUE THREAD

**Issue by ankurkaushal** [kentcdodds/ama#336]
As someone who's late to the game, I have found unit tests / integration tests to be really useful & really make me confident about my code. Though one of the issues I have found myself to come across is I find myself choking whenever I try to write unit tests from scratch for my personal projects. Its not a problem however, when I write them for work. I guess reason being the framework for those tests is already laid out. 

I think I would attribute it to lack of proper knowledge of testing in JavaScript & was wondering if you would have any pointers as to how to could fill the gaps in my knowledge?

**Comment by kentcdodds** [comment]
Hi @ankurkaushal!

I was locked out of my house for a few hours the other day so I recorded answers to a bunch of my AMA questions and put them up on [my 3 minute podcast](http://kcd.im/3-mins). [Here's your answer](https://www.briefs.fm/3-minutes-with-kent/59)!

**Comment by ankurkaushal** [comment]
Thank you so much for taking time to answer my question @kentcdodds! :)
