### ISSUE TITLE
React Testing

### ISSUE THREAD

**Issue by ASJvine** [kentcdodds/ama#337]
Hi Kent,
I write you in order to see if you can do a code review in a React Component Test to check if I understood the logic to properly Test React Components. 

Below, you'll find the react component and its test (or in this [link](https://gist.github.com/ASJvine/cbc84d0579b2dbdfa1c6a0e3de292e34)), and attached a screenshots of the coverage summary and parts not covered (not 100% covered :S). 

I'd like to read you constructive criticism to keep improving, raise the coverage of the parts that I do not know how to test. Maybe you could give some tips to understand where to define the test limits, or where a test of component A finishes to let test of component B starts (sometimes is not really clear on my mind).

![coverage](https://user-images.githubusercontent.com/15228714/32692342-9b21b058-c716-11e7-87fb-001a4f67cd91.png)
![not_covered0](https://user-images.githubusercontent.com/15228714/32692343-9b3aab26-c716-11e7-833d-4529f356943f.png)
![not_covered1](https://user-images.githubusercontent.com/15228714/32692344-9b538a24-c716-11e7-91f8-2a11f188b23b.png)
![not_covered2](https://user-images.githubusercontent.com/15228714/32692345-9b6b7882-c716-11e7-981a-335abc4a6815.png)

**Comment by ASJvine** [comment]
**CollectionsView.test.js**

`import React from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
import FontAwesome from 'react-fontawesome';
import Select from "react-select";

import Animationer from './Animationer';
import RenderItemList from './RenderItemList';
import SearcherBar from './SearcherBar';
import Loading from './Loading';
import AddCollection from '../Containers/AddCollection';
import Trad from '../Containers/Trad';
import ListFilter from '../Containers/ListFilter';

import './Styles/ItemsView.scss';

class CollectionsView extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            showPopup: false,
            isLoadedList: props.collection && props.collection.items ? true : false,    //list loading,
            orderByValue: props.savedFilters.orderByValue || null,
            hideFilters: true,
        };
    }

    componentWillReceiveProps(nextProps){
        if ( nextProps.collection && nextProps.collection.items ) {
            this.setState({ isLoadedList : true});
        }
    }

    componentWillUnmount() {
        const { orderByValue, selectedMarket } = this.state;
        this.props.saveFilters({ orderByValue, selectedMarket});
    }

    applySorterFilter(orderByValue) {
        const { cleanFilters } = this.state;
        this.props.cleanCollections();
        this.setState({ orderByValue, isLoadedList: false, }, () => {
            const fetchOptions = {start: 0, textToSearch: this.props.searchValue, sorter: orderByValue, cleanLeftFilters: cleanFilters};
            this.props.fetchCollectionItems(fetchOptions);
        });
    }

    showPopup(editCollectionID) {
        this.editCollectionID = editCollectionID ? editCollectionID : null;
        this.setState({showPopup : !this.state.showPopup});
    }

    hidePopupEditCollection() {
        this.setState({showPopup: false });
    }

    applyLeftFilters(filters) {
        this.props.cleanCollections();
        const { rawFilters, cleanFilters } = filters;
        this.setState({isLoadedList: false, rawLeftFilters: rawFilters, cleanLeftFilters: cleanFilters }, () => {
            const fetchOptions = {
                start: 0,
                textToSearch: this.props.searchValue,
                //idsMarket: [...selectedMarket],
                //sorter: orderByValue,
                //liveTranslationLang: langTranslate,
                filters: cleanFilters
            };
            this.props.fetchCollectionItems(fetchOptions);
        });
    }

    renderCollectionFilters() {
        if (this.state.hideFilters) {
            return <div className="show-filters-btn" onClick={()=> {this.setState({hideFilters: !this.state.hideFilters}); }}>
                <span className="filter-icon"></span>
            </div>;
        }
        return (
            <ListFilter
                initFilters={this.state.rawLeftFilters}
                onClose={()=>{this.setState({hideFilters: !this.state.hideFilters});}}
                onApplyFilters={this.applyLeftFilters.bind(this)}
                ingredientFilter={true}
                productFilter={true}
                needLanguageFilter={true}
                needRecipeCountFilter={true}
                needInternalSharing={true}
                needCollectionsTagsFilter={true}
                />
        );
    }

    fetchNewItems() {
        let { orderByValue, cleanFilters } = this.state;
        const { items } = this.props.collection;
        const fetchOptions = {start: items.length, textToSearch: this.props.searchValue, sorter: orderByValue, cleanLeftFilters: cleanFilters};
        this.props.fetchCollectionItems(fetchOptions);
    }

    renderFullCollections() {
        const { numResults, items } = this.props.collection;
        if(!items) {
            return null;
        }
        const hasMoreElements = items.length < parseInt(numResults);

        return (
            <RenderItemList
                listType='collections'
                isStrechView={!this.state.hideFilters}
                list={items}
                fetchNewItems={this.fetchNewItems.bind(this)}
                hasMoreElements={hasMoreElements}
                renderItemListClass={this.state.showPopup ? 'no-scroll' : ''}
                onClickEditCollection={(editCollectionID)=>{ this.showPopup(editCollectionID); }}/>
        );
    }

    render() {
        let count = this.props.collection ? this.props.collection.numResults : null;
        return (
            <span id="searcher-items-component">
                <section className="main-filter-bar-container">
                    <div className="quick-actions">
                        <div className="quick-action">
                            {/* <span className="filter-text"><Trad name="translated" /></span> */}
                            {/* <span className={this.state.isTranslateOn ? 'toggle-on' : 'toggle-off'} onClick={this.toggleTranslation.bind(this)}></span> */}
                        </div>
                        <div className="quick-action quick-action-long">
                            {/* <MarketsFilter applyMarketFilter={this.applyMarketFilter.bind(this)} /> */}
                        </div>
                        <div className="quick-action">
                            <Trad name="collections"/>: <span className="count-text">{count}</span>
                        </div>
                        <div className="quick-action quick-action-long">
                            <span className="select-container">
                                <Select name="order-by" options={this.props.sorterList} value={this.state.orderByValue} searchable={false} clearable={true}
                                    className="select-order-by" valueKey="sortBy" labelKey="label"
                                    onChange={selected => { this.applySorterFilter(selected); }} />
                            </span>
                        </div>
                    </div>
                </section>

                <section className="list-background" style={{'minHeight': '300px'}}>
                    <span className="main-view-container">
                        { this.renderCollectionFilters() }
                        { !this.state.isLoadedList ? <Loading strechLoading={true} mainClass="loading-list"/> : this.renderFullCollections()}
                    </span>
                </section>

                {!this.props.searchValue ?
                    <span className="add-collection" onClick={()=>{this.showPopup();}}>
                        <FontAwesome name='plus' size="2x"/>
                    </span> : null }

                <Animationer animationType='fade' >
                    {this.state.showPopup ? <AddCollection hidePopup={this.hidePopupEditCollection.bind(this)} editCollectionID={this.editCollectionID} /> : null}
                </Animationer>
            </span>
        );
    }
}

CollectionsView.propTypes = {
    searchValue: PropTypes.string,
    collection: PropTypes.object,
    sorterList: PropTypes.array,
    cleanCollections: PropTypes.func,
    fetchCollectionItems: PropTypes.func,
    saveFilters: PropTypes.func
};

export default CollectionsView;`

**Comment by ASJvine** [comment]
**CollectionsView.test.js**

`import React from 'react';
import { shallow } from 'enzyme';

import CollectionsView from '../../src/Components/CollectionsView';
import RenderItemList from '../../src/Components/RenderItemList';
import Loading from '../../src/Components/Loading';
import ListFilter from '../../src/Containers/ListFilter';

import collection from '../fixtures/collection';
import sorterList from '../fixtures/sorterList';

function shallowCollectionsView(props = {}) {
    const propsToUse = {
        cleanCollections() {},
        fetchCollectionItems() {},
        saveFilters() {},
        collection: collection,
        savedFilters: {},
        sorterList: sorterList,
        ...props,
    };
    return shallow(<CollectionsView {...propsToUse} />);
}

describe('<CollectionsView /> test', () => {

    test('<CollectionsView />  exists', () => {
        const saveFilters = jest.fn(),
            wrapper = shallowCollectionsView({saveFilters});

        expect(wrapper.find('#searcher-items-component')).toHaveLength(1);
        expect(wrapper.find(RenderItemList).length).toBe(1);
        expect(wrapper.find(Loading).length).toBe(0);

        wrapper.unmount();

        expect(saveFilters).toHaveBeenCalledTimes(1);

    });

    test('<CollectionsView />  willReceiveProps without items (then the loading appears)', () => {
        const wrapper = shallowCollectionsView({collection: {numResults: 50, items: undefined}});

        expect(wrapper.find('.main-view-container')).toHaveLength(1);
        expect(wrapper.find(RenderItemList).length).toBe(0);
        expect(wrapper.find(Loading).length).toBe(1);
    });

    test('<CollectionsView />  willReceiveProps without items but the list is loaded', () => {
        const wrapper = shallowCollectionsView({collection: {numResults: 50, items: undefined}});
        wrapper.setState({isLoadedList: true});

        expect(wrapper.find(RenderItemList).length).toBe(0);
        expect(wrapper.find(Loading).length).toBe(0);
    });

    test('<CollectionsView />  willReceiveProps ', () => {
        const wrapper = shallowCollectionsView({collection: {}});

        expect(wrapper.state().isLoadedList).toBeFalsy();
        expect(wrapper.find('#searcher-items-component')).toHaveLength(1);

        wrapper.setProps({collection: collection});

        expect(wrapper.state().isLoadedList).toBeTruthy();
    });

    test('<CollectionsView />  simulate addCollection', () => {
        const wrapper = shallowCollectionsView();

        expect(wrapper.state().showPopup).toBe(false);

        wrapper.find('.add-collection').simulate('click');

        expect(wrapper.state().showPopup).toBe(true);
    });

    test('<CollectionsView />  simulate edit Collection', () => {
        const wrapper = shallowCollectionsView();

        expect(wrapper.state().showPopup).toBe(false);

        wrapper.instance().showPopup(12);

        expect(wrapper.state().showPopup).toBe(true);

        wrapper.instance().hidePopupEditCollection();

        expect(wrapper.state().showPopup).toBe(false);
    });

    test('<CollectionsView />  load more elements (like scrolling)', () => {
        const fetchCollectionItems = jest.fn(),
            wrapper = shallowCollectionsView({fetchCollectionItems});

        expect(wrapper.find(RenderItemList).props().fetchNewItems).toBeTruthy();

        wrapper.instance().fetchNewItems();

        expect(fetchCollectionItems).toHaveBeenCalledTimes(1);

    });



    test('<CollectionsView />  simulate sorter filter (orderByValue)', () => {
        const wrapper = shallowCollectionsView();

        expect(wrapper.state().orderByValue).toBe(null);

        wrapper.find('.select-order-by').simulate('change','Newest');

        expect(wrapper.find('.select-order-by').props().value).toBe('Newest');
        expect(wrapper.state().orderByValue).toBe('Newest');
    });

    test('<CollectionsView />  show left filters', () => {
        const wrapper = shallowCollectionsView();

        expect(wrapper.state().hideFilters).toBe(true);

        wrapper.find('.show-filters-btn').simulate('click');

        expect(wrapper.state().hideFilters).toBe(false);

        //TODO Close then the filters display
        // console.log('WOW', wrapper.find(ListFilter).props().onClose);

    });

    test('<CollectionsView />  simulate left filter ()', () => {

        const filters = {rawFilters: {}, cleanFilters: {} },
            cleanCollections = jest.fn(),
            fetchCollectionItems = jest.fn(),
            wrapper = shallowCollectionsView({ cleanCollections, fetchCollectionItems });

        wrapper.instance().applyLeftFilters({filters});

        expect(cleanCollections).toHaveBeenCalledTimes(1);
    });


});`

**Comment by kentcdodds** [comment]
Hey @ASJvine!

So I have a lot of thoughts about testing React. So many that I couldn't get them all down in text, so [I recorded a video](https://www.youtube.com/watch?v=gJMYMnyA7ZE&index=1&list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf) of me analyzing your testing code and making suggestions! I hope it's helpful! Good luck!

**Comment by ASJvine** [comment]
Thanks a million for your tremendously useful video. I wrote down every tip and I'm gonna apply it!
