### ISSUE TITLE
Do you wish for Global Peace?

### ISSUE THREAD

**Issue by atiglobe** [kentcdodds/ama#339]
We are a small international collective [Libereria](http://libereria.com) we dream that global peace is possible. We’re creating a web App for realize wishes with the aim of realizing Global Peace. But we need to increment our group with more web programming skilled partecipants. 

Have you ever dream about a Globe where Human being Realize to live without any war?

At the moment we need to make this form work, you can see it here:

http://taratam.org/globalpeace.html 

Repositories 
https://github.com/turrandott/TaratamPage

Would you like to contribute to the creation of the Wish Realizer?

**Comment by kentcdodds** [comment]
Hi @atiglobe,

Yes, I do wish for global peace. I believe that the best way to contribute to world peace is by following Jesus Christ and encouraging those around you by your example to do the same.

Also, I believe that there will soon be a day where Jesus Christ will return again to the Earth and begin what we call [the Millennium](https://www.lds.org/topics/millennium?lang=eng) where He will rule over a world of peace.

---

Tangent aside, I'm afraid that [I'm currently stretched too thin](http://kcd.im/no-time) and I'm unable to contribute to every worthy cause that I hear about (though I do try). Good luck on your web app though!
