### ISSUE TITLE
re first-timers-only: second- and millionth-timers

### ISSUE THREAD

**Issue by Kwpolska** [kentcdodds/ama#34]
Regarding [the first-timers-only issues](https://medium.com/@kentcdodds/first-timers-only-78281ea47455), how would you react to the following people sending a PR:
* a second-timer?  (it’s their 2nd OSS contribution)
* an experienced person, who heard about your project 5 minutes ago?  They *are* a first-timer in some regard…

Would you accept it, or scold the person (which is a very bad experience and an awful PR move)?

**Comment by kentcdodds** [comment]
Good question. I've thought about this a bit. I certainly wouldn't scold them. That's for sure. If it's a second-timer, third-timer, or even tenth-timer, I'd probably accept the contribution if nobody else has expressed interest. If a true first-timer has expressed interest, then I'd probably thank them for the contribution and give them positive, constructive feedback.

For an experienced person who'd just heard of the project, I'd direct them to the `up-for-grabs` issues which is available to people who want to contribute.

As I describe in my blogpost, sometimes I have to ask my daughter to not respond to a question to give my younger son a chance to answer and learn. That's the idea behind `first-timers-only`. I intentionally make the implementation super easy (and describe step-by-step what to do). If someone who's experienced just goes in and does it, they sort-of ruin the experience for someone who's trying it out for the first time.

But I would never scold anyone for contributing. I would only scold someone for not following the `CODE_OF_CONDUCT.md` in the project (but I'd try to do so nicely).

Thanks for the question!

**Comment by Kwpolska** [comment]
Thanks for the quick answer, and please carry on helping beginners!
