### ISSUE TITLE
Keeping tests _more_ resilient

### ISSUE THREAD

**Issue by blocka** [kentcdodds/ama#347]
In your wonderful blog post, https://blog.kentcdodds.com/making-your-ui-tests-resilient-to-change-d37a6ee37269, you demonstrated how using a feature marker can help keeps your tests from breaking when the designer decides to change something.

So we have an input in our component and we add a data-* attribute:

```html
<input data-test="input">
```

Now you designer comes a long and creates a nice component to replace this

```js
const FancyInput = () => (<div>
   <input />
</div>)
```
he's nice enought to leave you data attribute in

```html
<FancyInput data-test="input" />
```

but your test is now broken as you're referencing a div, not an input.

**Comment by kentcdodds** [comment]
Hi @blocka!

So [I researched this a little bit](https://twitter.com/kentcdodds/status/949331458488860673) (yes, twitter is the new StackOverflow) and found [an answer](https://twitter.com/kentcdodds/status/949339902893871104) that isn't terrible. [Here's an example repo](https://github.com/kentcdodds/enzyme-sel). And here's the code to save you a click:

```javascript
// sets up JSDOM and configures enzyme with React 16
require('./irrelevant-setup')

const React = require('React')
const {mount} = require('enzyme')

// a composite component that forwards all props to a DOM component
function MyButton(props) {
  return React.createElement('button', props)
}

// create an element out of the composite component
// and pass data-test which will be forwarded on to the underlying button
const element = React.createElement(
  MyButton,
  {'data-test': 'button'},
  'Click Me'
)
const wrapper = mount(element)

wrapper
  .find('[data-test="button"]')
  // right now we have a wrapper with two things:
  //   1. MyButton composite component instance
  //   2. button DOM component
  // If we tried to run `.simulate` on that, we'd get the following error:
  // Error: Method “simulate” is only meant to be run on a single node. 2 found instead.
  //
  // So we have to simulate the click on only one of them. We could just do .first()
  // but I prefer to simulate events (and in general only work with) DOM components
  // in my tests, so instead we can use .hostNodes() to filter out only the DOM components
  .hostNodes()
  // now the wrapper only has the button DOM component and we can simulate the click
  .simulate('click')
```

I hope that's helpful.

Thanks for reminding me, I need to update the blog post with this!

**Comment by blocka** [comment]
Thanks! I actually followed that discussion on twitter and was wondering if that was answering my question!
