### ISSUE TITLE
Using proptypes on a function component

### ISSUE THREAD

**Issue by Maamun** [kentcdodds/ama#348]
Hey Kent,

i started watching your egghead's beginner's guide to react and i really can't thank you enough for that, but i'm actually struggling at the video number 5 and i thought that you could maybe help understand this issue, i really can't figure out how `firstName(props, propName, componentName)` works without being invokated !
how it comes that the componentName returns `SayHello` ?
is it a default property in every component ?

**Comment by kentcdodds** [comment]
Hi @Maamun!

> I really can't figure out how firstName(props, propName, componentName) works without being invokated

React actually calls that function for you when it renders your component. So you don't need to call it yourself.

> how it comes that the componentName returns `SayHello` ? is it a default property in every component ?

Here's what happens:

```javascript
function SayHello() {
  // code
}

console.log(SayHello.name === 'SayHello')
```

Execute that in your JavaScript console and you'll see that console.log logs out `true`. So React simply uses the `name` property on your function! That's not a React thing, that's just a JavaScript thing. Every function has a `name` property (if it's not an anonymous function). Cool right?
