### ISSUE TITLE
Task analysis before jumping into writing the code

### ISSUE THREAD

**Issue by 3sanket3** [kentcdodds/ama#350]
Hi Kent,

I am looking for some tips on how you approach the task before writing the code. Means mostly we guys take pen and paper do some abstract analysis and start writing the code. Then while coding, sometimes we come across a situation, where we think, we are still lacking or problem with info/concept/approach (due to improper or partial analysis).

So, how do you handle it, and best practices or tips you have to share?

Also, I don't have any experience with bigger companies,  I think they must have set up some practices for their employees for the same. Please share if you have some idea of that as well.

Happy new year. Keep Inspiring!

Thanks.

**Comment by kentcdodds** [comment]
Hi @3sanket3!

Thanks for the question! I'm actually pretty bad at planning things out before I code. If something's complex enough, I'll generally try to write a simple implementation of what I'm thinking. I plan to throw away all the code, but doing it helps me solidify the assumptions that I'm making about things. If it's a big system that I'm trying to design out, then I need to talk it over with some people. Sometimes we'll draw out something, but honestly designing big systems is not something I do all that often. I'm not aware of any established practices at PayPal for doing this either. There probably are some, but I'm not aware of them 🤷‍♂️ 

Sorry I'm not all that helpful 😅 

Good luck!

**Comment by 3sanket3** [comment]
Thanks Kent for your time. Actually, the reply is helpful. It clears out my mind saying, it's a general issue common to even the experts ;-) So I should not get disappointed and should continue working on it. It will keep improving with the experience. 

Regards.
