### ISSUE TITLE
Tips for Working in Open Source as an Enterprise Developer?

### ISSUE THREAD

**Issue by Aghassi** [kentcdodds/ama#351]
While I know we work at different companies, I was curious if you had any tips or pointers for people looking to open source when working in Enterprise. I know the rules can be different at scale, and wanted to know if you had any tips regarding things like navigating licensing with Legal when it came to open sourcing projects. I understand the specifics may differ from company to company, but any overall pointers would be greatly appreciated. Thank you again for your time!

**Comment by kentcdodds** [comment]
Hi @Aghassi!

Thanks for the question. Hmmm... Tips?

1. Make sure that your management supports your interest in open source. If they don't, then come up with a plan for how you can help them understand the value of open source.
2. Make sure that you aren't legally prevented from contributing to open source on the job. Some companies disallow their employees from contributing to open source while on the clock (or even off the clock). These are the kinds of companies that you'll never find me working for :wink:
3. When you bump into a problem in a package that you use at work and you need something fixed or would like an improved experience/documentation in a certain area, just do the work. I don't even ask. I just do it. It's part of my job to deliver what I'm being asked to deliver and I don't care where the code needs to go for me to do that.
4. If you can see that something you're working on could be open sourced, talk to your manager about it. Express your desire to open source what you're working on and then talk to the legal team at your company to make sure that you're covering all of your bases before open sourcing it. Then go for it!

You might find [this talk](https://kentcdodds.com/talks/#managing-an-open-source-project) helpful.

Good luck!
