### ISSUE TITLE
Would love to see similar tutorials/intro into Jest similar to "Writing tests from scratch for the first time"

### ISSUE THREAD

**Issue by yeongsheng-tan** [kentcdodds/ama#352]
Heyya Kent,

I'd like to thank you and congratulate you on a great piece of work at https://blog.kentcdodds.com/but-really-what-is-a-javascript-test-46fe5f3fad77.

I'm new to JS, and your courses on React and the above, really helped eased me into the ecosystem.

Having ended https://blog.kentcdodds.com/but-really-what-is-a-javascript-test-46fe5f3fad77 on the note with Jest, I was wondering, if you'd be doing more similar pieces to better understand Jest, especially the dark magic/world of mocking in JS world (I come primarily from Ruby and Java background). And how Jest compares to Mocha + Sinon.

Please keep up the good work. Awesome stuff learning from your great posts and podcasts/RSS.

**Comment by kentcdodds** [comment]
Hi @yeongsheng-tan!

I'm so glad you like my blog post and courses on React! I post about what I'm working on or common questions that I get. Pretty much whatever I want to. But if you're not subscribed to [my newsletter](http://kcd.im/news) then I suggest you jump on that. That's where my blog posts come from after all :)

Actually, [last week's newsletter](https://tinyletter.com/kentcdodds/letters/spelunking-in-node-modules) was about some aspect of Jest. I'll be publishing that to my blog next week. I'm not certain whether I'll write any other blog posts to "demystify" Jest any further. There's so much to write about and I only have so much time.

Thanks again. Good luck!
