### ISSUE TITLE
Building standalone libraries to learn

### ISSUE THREAD

**Issue by oyin-k** [kentcdodds/ama#353]
Hello @kentcdodds i'm just starting out in software development and i want to increase my chances of being the best i can be in this industry that's why i chose OSS to both learn and contribute to the community. I read one of your answers here about how you build standalone libraries from projects you have built. Can you help out how i can do this too and break things down for more understanding thank you..

**Comment by kentcdodds** [comment]
Hi @oyin-k! :wave:

You might appreciate [this talk](https://kentcdodds.com/talks/#how-to-open-source-your-stuff) where I basically talk about just that. You may also like [this talk](https://kentcdodds.com/talks/#managing-an-open-source-project) where I talk about managing open source projects and [this free egghead.io course](http://kcd.im/write-oss) where I teach how to write an open source library.

Good luck!

**Comment by veeranatarajan** [comment]
Inspired your commitment towards AMA's here. I was looking for answer to this question. After 30mins it was gone from Open issue list. Surprised :1st_place_medal: @kentcdodds 

#inspired #motivation.

:handshake:
