### ISSUE TITLE
How does your job let the developers fix what's not broken (e.g. upgrade dependencies)?

### ISSUE THREAD

**Issue by sompylasar** [kentcdodds/ama#354]
Hi Kent, from your recent email "Spelunking in node_modules 👷" (not yet a blog post so cannot link to it):

> This last week I started work again after over a month away. What's the first thing you do when you get back from that long away? Why, upgrade dependencies of course!

I'm curious how does your job let the developers fix what's not broken? If everything works with older dependencies and may break with the newer, how do they let you spend time to upgrade and then spend more time to fix what's broken after that? How do you explain the time spent?

Thank you.

**Comment by kentcdodds** [comment]
Hi @sompylasar!

Thanks for the question! So basically we've been able to establish the value of staying current with management. If you don't keep your dependencies up to date, then when you _need_ to upgrade for security or really-helpful-new-feature reasons it becomes _very_ difficult. It's much easier to just keep things up to date, even if it means that you have to spend a little bit of time every now and then keeping things updated.

That said, this is why I'm working on `paypal-scripts`. Every team is working on keeping the same tools up to date. It'll be really nice when we can differ all upgrade "pains" to a single project and all other projects can simply bump their version of a single dependency. [My most recent newsletter](https://tinyletter.com/kentcdodds/letters/concerning-toolkits) (will be a blog post in two weeks) discusses this in more depth :)

I hope that's helpful!
