### ISSUE TITLE
what program do you prefer to use to compress your scss files into css?

### ISSUE THREAD

**Issue by alohavolha** [kentcdodds/ama#36]
I currently use prepros but it is very buggy and I am also just getting familiar with sass. Eventually I would like to switch to a different program. What are your go-to tools?
Thank you

**Comment by kentcdodds** [comment]
Hi,
Thanks for the question! I actually don't do write sass. But if I did I would probably use the [webpack](webpack.github.io) [sass-loader](https://github.com/jtangelder/sass-loader) which uses [node-sass](https://github.com/sass/node-sass) to compile the source code. If you're interested in learning about webpack, I recommend you checkout [this egghead.io playlist](https://egghead.io/playlists/learning-webpack)

Good luck!

**Comment by alohavolha** [comment]
Cool, thank you. 
Sorry, gotta reopen this request: have one more question to follow your answer: I have notice that a lot of developers are not using sass. Is there a reason why you don't write in sass?

**Comment by kentcdodds** [comment]
I wrote in sass when I worked at Domo. It was good. I personally enjoy writing css using Stylus or Postcss more than sass. Though I don't have a huge preference. I don't really enjoy using less though. Not as many features and a little quirky syntax for stuff.
