### ISSUE TITLE
Redux or New Context API

### ISSUE THREAD

**Issue by muazu** [kentcdodds/ama#361]
Hello Kent
In your most recent newsletter you covered the topic of the New Context API.  One of the things you said was that perhaps people would not feel the need to reach so soon for Redux  or other state management tools.  

I was wondering if you could please expand on this a little and I wanted to ask your opinion , in regards to the new context API, is there EVEN a need for Redux any more? I’m about to kick off a project which is a good candidate for Redux, decent size and many components that need to share state and data. I was trying to understand if I should go for Redux or prop drill and refactor once the new context API comes available?

**Comment by kentcdodds** [comment]
Hey @muazu!

I was actually thinking of this question when I wrote this: ["Application State Management"](https://blog.kentcdodds.com/application-state-management-66de608ccb24).

Let me know what you think :)
