### ISSUE TITLE
Error handling experience in JavaScript applications 

### ISSUE THREAD

**Issue by NaviMarella** [kentcdodds/ama#362]
How do we handle error handling....is it really a good approach to show error page to the user or allow user to work on broken UI

**Comment by NaviMarella** [comment]
How do we handle error handling....is it really a good approach to show error page to the user or allow user to work on broken UI

**Comment by kentcdodds** [comment]
Hi @NaviMarella,

That's a pretty specific question and will have a different answer based on the use case. In general though I'd either show an error page if the error is pretty critical, or just show a localized error by the broken component if that component isn't key to the rest of the page.

Good luck!
