### ISSUE TITLE
Recommend UI Framework for React

### ISSUE THREAD

**Issue by cuong-nguyen** [kentcdodds/ama#363]
Hi Kent,

I am thinking to choose one React UI framework and apply it to our company project so that we can focus more on JS coding part. But there are a ton out there, have you used or experienced with any frameworks that you can recommend?

I am looking for extensibility, easy to use/read

Thanks,
Chris

**Comment by kentcdodds** [comment]
Hi @cuong-nguyen! :wave:

I've never used a React UI framework enough to be a good judge. Sorry :-( Material UI looks interesting FWIW.
