### ISSUE TITLE
Does a degree worth it in web development?

### ISSUE THREAD

**Issue by stevenandersonz** [kentcdodds/ama#365]
I grew up in Bolivia far away from the US, until 2017 I was doing college there, my major was System Engineering but I did not finish because I realize that I was learning a lot more by myself than what my teachers taught me. So I move to the US looking for a better education, but it is very expensive far away from my budget, but I'm really interested in Front End, I take the React Nanodegree from Udacity and I just fall in love with React, now I'm looking forward to a career in this field, do you think that the best option is going to college, or take individual courses and learning by doing my own projects?

**Comment by kentcdodds** [comment]
Hey @stevenandersonz,

Just in case you missed it, I answered that mostly here: https://github.com/kentcdodds/ama/issues/306

Feel free to ask me follow-up questions if you're interested.
