### ISSUE TITLE
How do you manage focus/clicks/any client event? [React]

### ISSUE THREAD

**Issue by EmaSuriano** [kentcdodds/ama#366]
Hi Kent,

In the project that I'm working right now, we have to provide a way to the user so he can navigate the screen, by focusing or clicking on components with shortcuts (the shortcut problem is solved for now). I've been reading and searching for how is the "React" way to do this and I found something like this.

``` javascript
import React, { Component } from 'react';

export default class App extends Component {
  render() {
    return (
      <div>
        <button onClick={() => this.input.focus()}>focus input</button>
        <input type="input" ref={x => (this.input = x)} />
      </div>
    );
  }
}
```
I found this solution of defining a ref and accessing to a function of it like an anti-pattern on React because the parent has to know which methods the children has inside.

My question is: Have you ever had to deal with this kind of problem? If so, which approach did you use?

Thanks,
Emanuel

**Comment by kentcdodds** [comment]
Hi @EmaSuriano,

What you have there is exactly what I would do to allow a button to focus an input. I can't think of why this would be an anti-pattern in React, this is literally the way to do it. Perhaps you could write an abstraction to hide away that implementation detail, but I fear that you'd come away with something more complicated anyway.

Good luck!
