### ISSUE TITLE
Is there a "best practice" for handle user modifiable values when creating a react component with a render prop?

### ISSUE THREAD

**Issue by rigobauer** [kentcdodds/ama#367]
Hi, Kent!

First of all, thank you for all the work that you do for the community. I'll try to give back as much as I can...

Now mainly because of you and Michael Jackson I am a render props believer ;), and I have this doubt. When designing a component that uses a render prop, you normally have some values that you want the user to be able to modify and finally affect the internal behavior of the component. I know and use the concept of controlled/uncontrolled components for a regular component, but when you have a render prop, It seems to me that the user is going to always modify that values from outside the component, so I don't know if it makes sense to set that values as state properties or just use them directly as component props.

As I see it, there're to main ways to handle this:

1. Set those values as component props, and when the user change it from the outside do whatever you have to do inside of `componentWillReceiveProps` (compared what prop has change, etc). I'm actually doing it this way, but something I don't like is that the state of the component doesn't show me the full state information, so I feel like I'm loosing the declarative approach a little bit.

2. Set those values as state properties of the component and when the user change a prop externally, modify the associated state value. What I don't like about this is that I feel like I'm doing double work, because I'm just passing the prop value to the state property to end up doing the same thing.

I'm not sure if my doubt is clear, so let me finish with an easy example: a `Counter` component that just counts and show the current value, with a prop to set the interval time (mseconds until showing the next number) and with a render prop. I mean, this idea...

```js
<Counter
  interval={2000}
  render={(props, state) =>
    <div>{state.count}</div>
  }
/>
``` 
Of course, internally it will have a setInterval, lifecycle functions, etc. In the end, we want the user to be able to modify the interval value so the counter will automatically go faster or slower. My doubt is if there's a "better" way to handle that `interval` value internally. My two options:

1. I just use `this.props.interval` internally and when user change the value, I use `componentWillReceiveProps` to delete the interval and create a new one with the new speed. That's my current approach, but what bothers me is that looking at the component state I can't know the current speed, so I feel like I'm missing something.
2. I set a state.interval that initially equals to `this.props.interval`, and when user change the value I use `componentWillReceiveProps` to update the state value, and then `componentDidUpdate` to remove and recreate the interval whit the new state value. With this, the state shows me the current speed, but I feel like I'm doing unnecessary work passing that info, because nobody is going to modify that `this.state.interval`internally.

I's just a basic idea that can get as complex as you want depending of the amount/type of props, the complexity of the internal state, etc. I don't know if I'm being able to explain my doubt, but if you finally have time for this question and but need more info, please let me know.

Kind regards
Alberto

**Comment by rigobauer** [comment]
Mmm... I've been doing some research and reading more about the "props as state" issue, and it looks to me that the second approach is not a good one. In the end, you ended up having to do more work to maintain that synchronization, and can be a pain in the ass if as the component gets bigger and more complex.

About the fact that the component won't show all the state info, I've been thinking... Maybe it makes sense, because in the case of a render prop that values doesn't really "belong" to the component, but to the one calling the component. That's the one that establish and handle that values, and it will probably have a state with those values to allow changing them dynamically. In the end, that's the whole point of using a render prop, allow the user to control that values to interact with whatever it's  decided to render.

Mmm... maybe I'm answered my own question... but anyway, I'd love to know what do you think....

**Comment by kentcdodds** [comment]
Hi @rigobauer,

Yes, I was going to say that option 2 is not a good one. Synchronizing props and state is never fun. Option 1 is what I do.

> what bothers me is that looking at the component state I can't know the current speed, so I feel like I'm missing something.

I'm not sure I understand what you mean by this. When the prop is provided you get the state from `this.props`, not `this.state`.

I actually built [`react-toggled`](https://github.com/kentcdodds/react-toggled) as a way to show a simple example of some patterns that I use in `downshift`. This pattern of controlled components is actually one such pattern. Hopefully it's helpful to you!

Good luck!
