### ISSUE TITLE
Using mutation testing to measure test quality

### ISSUE THREAD

**Issue by simondel** [kentcdodds/ama#368]
What are your thoughts on using mutation testing to measure test quality?

**For people reading this that are unfamiliar with mutation testing:**
Mutation testing is a technique to measure the quality of unit tests by changing your source code and testing if that results in a failing test (which it should, since your logic was changed). An example of such a *'mutation'* could be changing `if(a > b)` into `if(a < b)`. If all your tests still pass after this change, you probably don't have proper tests for this piece of code.

> But code coverage also measures test quality!

Code coverage measures if code gets executed. It doesn't test if your code actually works. It doesn't guard you from tests with disabled asserts. Code usually contains bugs and since tests are also made of code, they are also prone to containing bugs. 

As an example, this piece of code may *seem* to be tested properly if you look at the code coverage:
![image](https://user-images.githubusercontent.com/4221997/36065751-8b903940-0e9f-11e8-84dd-7b40c90818be.png)
But if you [look at the mutation test result](https://stryker-mutator.github.io/stryker-html-reporter/process/MutationTestExecutor.ts.html), it's all red:
![image](https://user-images.githubusercontent.com/4221997/36065763-a8e1ac18-0e9f-11e8-9fdb-3771de33afdd.png)
The mutation testing framework was able to remove all code inside this function and none of the tests failed.

**Comment by kentcdodds** [comment]
Hey @simondel!

I've heard of mutation testing, but never actually done it. I love the idea a lot and think it's probably something I should look into. You described the benefits of mutation testing over the code coverage metric well... Another metric I would like to have is "data coverage." Specifically, do I cover this function when it's called with any combination of data? I think that would be really useful as well.

Good luck!
