### ISSUE TITLE
For someone who aspires to teach others / host workshops, how do they establish credibility to reach there?

### ISSUE THREAD

**Issue by sudarshang** [kentcdodds/ama#369]
From the twitter [thread](https://twitter.com/siddharthkp/status/963060073244348416)

**Comment by kentcdodds** [comment]
Hi @sudarshang! I'm sure @siddharthkp would be interested in the answer to this question as well :)

So I get this kind of question a lot. So much that I made a talk all about it: [Zero to 60 in Software Development: How to Jumpstart Your Career](https://www.youtube.com/watch?v=-qPh6I2hfjw&list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf). I also talk about it generally in my blog post I published today: [Increase your marketability](https://blog.kentcdodds.com/increase-your-marketability-ced1cb315d18).

It takes a lot of thoughtful work and giving things away for free/getting a following. Good luck!
