### ISSUE TITLE
What is the book you suggested for maintainable code

### ISSUE THREAD

**Issue by ultrox** [kentcdodds/ama#371]
You mention that you was reading a lot of books when you where intern at **USAA San Antonio**, one of those was about "maintainable code".

You mention maintainable code at #132, which is no related.

Can you please share your though/**suggestion about organizing and maintaining bigger code libraires**, and what was that book you read while [walking here](https://youtu.be/-qPh6I2hfjw?t=309)

PS I got it, its [maintainable javascript](http://shop.oreilly.com/product/0636920025245.do) by grate [Nikolas Zakas](http://github.com/nzakas), but still I would like to hear _how to go about learning pattern and maintainable code_, especially in **context** of building stuff with tech you are not that good at.

**Comment by kentcdodds** [comment]
Hi @ultrox!

Yep, you found it!

To answer your question:

> how to go about learning pattern and maintainable code, especially in context of building stuff with tech you are not that good at.

For me it's just doing it a lot and developing an intuition for what will be hard to understand in the future. Going back to old code that I wrote a long time ago really helps reveal problems to me as well.

As far as building stuff with tech I'm not good at, I just build a lot of stuff with it until I become good. I follow [my learning process](https://blog.kentcdodds.com/solidifying-what-you-learn-6650258c84be) and get better and better at that tech.

I hope that's helpful. Good luck!
