### ISSUE TITLE
What are the main technologies you use / like / want to learn?

### ISSUE THREAD

**Issue by adtm** [kentcdodds/ama#373]
I wonder, what would be the technologies you would like to learn more broadly: AWS / Serverless / maybe something other?

Also, what are your current stack preferences? 

Thanks! 🍰

**Comment by kentcdodds** [comment]
Hi @adtm!

Right now my stack preference is Express and React. That's pretty much it. I use libraries when I need them. I prefer spending time on the frontend. I don't care too much for server-side stuff (though I love working in node on tools). I definitely want to learn Reason (and Reason-React) eventually. I want to learn GraphQL (mostly using, not implementing). I think serverless is cool, but I don't really care to get into it myself. I'd rather use some service that makes it easy for me to spin up a server quickly and they can use that tech if they want to. I don't really care.

Good luck!
