### ISSUE TITLE
Getting started with React Native

### ISSUE THREAD

**Issue by sangeethaKP** [kentcdodds/ama#374]
Hi Kent, can you kindly point me to resources on how to systematically get started with React Native? Assume I have super basic knowledge of Javascript. Thanks a bunch! :)

**Comment by kentcdodds** [comment]
Hi @sangeethaKP!

I'm afraid that I don't know very much about React Native. I'd start with [the official docs](https://facebook.github.io/react-native/docs/getting-started.html), then I'd look at [expo](https://docs.expo.io/versions/latest/index.html), and [snack.expo.io](https://snack.expo.io/).

Also, if you're new to React, definitely spend some time learning that. I have a free course for you here: ["The Beginner's Guide to ReactJS"](https://egghead.io/courses/the-beginner-s-guide-to-reactjs).

Good luck!

**Comment by sangeethaKP** [comment]
Thanks Kent! :)
