### ISSUE TITLE
What are your thoughts on my Smalldux library?

### ISSUE THREAD

**Issue by zaguini** [kentcdodds/ama#376]
Hey, Kent!

I've built a simple `react-redux` implementation using the fresh `Context API` that comes bundled with React 16.3.

I want you to take a look at it [@smalldux](https://github.com/zaguini/smalldux) and share your opinions, thoughts and advices. It would be of great value!

Of cours, it's just a small project with learning purposes, so don't take it as a production-ready one, haha. Oh, and ignore `combineReducers` function -- it's just a "placeholder" (as listed in TODO section in the Readme).

Thanks in advance!

**Comment by kentcdodds** [comment]
Hi @zaguini!

Thanks for the question. I'm honestly not sure I'm the right person to ask though. I don't spend a whole lot of time with redux personally. You should probably reach out to other people in the community and you'll get a better response.

Sorry I can't be much help here. Good luck!

**Comment by zaguini** [comment]
Ok. And what about that one? https://github.com/zaguini/react-native-tree-view

**Comment by kentcdodds** [comment]
Sorry, I'm still the wrong person to ask. I don't do much with react native... :-/
