### ISSUE TITLE
Curious what keyboard and mouse you use?

### ISSUE THREAD

**Issue by lonelydatum** [kentcdodds/ama#379]

**Comment by kentcdodds** [comment]
Hi @lonelydatum,

I just use the official [Mac Bluetooth Keyboard](http://a.co/1cv1Stv) and the [Mac Bluetooth Trackpad](http://a.co/8tyFZfQ)

Nothing all that special. I tried a Microsoft Sculpt for a while but it started repeating keys and all sorts of other weird things and I didn't like it enough to get a replacement.
