### ISSUE TITLE
Mastering javascript dom/dom api

### ISSUE THREAD

**Issue by atishaybaid** [kentcdodds/ama#38]
Hi,

Could you suggest some project/repositories to master javascript dom,eventing,js performance.
I thought of creating a event bus,but was not sure how to proceed.
I would be helpful for me if you could share some good resources.

**Comment by kentcdodds** [comment]
That's a great question, but I don't think I have any good projects or repositories to share. I'll open this up to anyone else who would like to answer...

**Comment by tylermcginnis** [comment]
Not sure what your experience level is, but here are some resources I can personally vouch for. 

[THIS](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/constructing-the-object-model?hl=en) is really good for understanding the DOM/CSSOM -> Render Tree -> Layout -> Paint process browsers take as well as perf stuff.

[You Might Not Need jQuery](http://youmightnotneedjquery.com/) is great for learning the most used DOM API methods (regardless of their role in jQuery).

And [THIS](http://www.html5rocks.com/en/tutorials/internals/howbrowserswork/) article is another great article in terms of what the browser does internally.

**Comment by kentcdodds** [comment]
Thanks @tylermcginnis! Big +1 to the "Constructing the Object Model." Really cleared up some things for me. I reference "You Might Not Need jQuery" frequently. Never seen "How Browsers Work" before, should give that a look!

**Comment by atishaybaid** [comment]
Thanks for sharing the articles.
Would be going through them to deepen my understanding of Dom/APIs
On 8 Oct 2015 00:52, "Kent C. Dodds" <notifications@github.com> wrote:
>
> Thanks @tylermcginnis! Big +1 to the "Constructing the Object Model."
Really cleared up some things for me. I reference "You Might Not Need
jQuery" frequently. Never seen "How Browsers Work" before, should give that
a look!

**Comment by atishaybaid** [comment]
@tylermcginnis could you share something to master dom/js eventing and js performance.

**Comment by tylermcginnis** [comment]
Event Loop -> https://vimeo.com/96425312
Performance, I'd say the first link I shared above should work (unless you already have knowledge of DomContentLoaded vs Load and async script loading, etc).

**Comment by atishaybaid** [comment]
thanks.
it was a great talk on js event loop.

**Comment by kentcdodds** [comment]
Thanks for asking your question. I think I forgot to close it
