### ISSUE TITLE
Does React & Angular co-exists in an application?  

### ISSUE THREAD

**Issue by tonysk** [kentcdodds/ama#380]
I have React and Redux and Angular (with Redux). Is it a good practice to build an application with both React and Angular? What if I need to migrate my application from React/Angular to VueJS/any future JS, where I don’t want to do complete RE-write?

**Comment by kentcdodds** [comment]
Hi @tonysk,

So I gave [a talk](https://www.youtube.com/watch?v=AiE4ajXh7dY&index=30&list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf) about using React in an Angular 1 application so maybe that'll show you some ideas (it was quite a while ago). The nice thing about React is that it can fit in anywhere with whatever else you have happening.

My co-worker @jamischarles gave a talk a while back called ["Migrating Safely to React"](https://www.youtube.com/watch?v=sXDZBxbRRag) that you might find helpful as well.

Good luck!

**Comment by jamischarles** [comment]
@tonysk I'd suggest watching this talk https://www.youtube.com/watch?v=mrtwImsEq5s but in a nutshell:
1) If you currently have 2 frameworks, I'd find a way to phase one out. The added complexity and page weight is going to be detrimental.
2) Use as much vanilla JS as possible (for your business logic), as this makes migrating much much easier (see the talk)

After watching the talk feel free to ping me on twitter (same handle) if you have any more questions.

**Comment by tonysk** [comment]
Hey KC & Jami, I was referring to micro frontend, meaning having micro apps (eg: React, Angular, Vue) in an application. What’s your thoughts on building micro frontend? Even in mobile (Swift & Java)? am not sure micro frontend are proven methods? 

https://micro-frontends.org
https://medium.com/@tomsoderlund/micro-frontends-a-microservice-approach-to-front-end-web-development-f325ebdadc16

**Comment by jamischarles** [comment]
I haven’t heard that term yet. If you want to use vanilla or same framework
for each that is one thing. At work we have a node backend app that houses
2 React SPAs.

Personally I’d recommend against using different frameworks unless you have
a good reason to. The big downside is your team is now forced to learn both
frameworks which is a pain and doesn’t scale well across teams.

**Comment by kentcdodds** [comment]
I agree with Jamis 👍

**Comment by tonysk** [comment]
Yea, got you. So the idea of having micro frontend is, instead of building big frontend SPA, we could built small micro apps (or widgets) which includes end-to-end (UI+Business logic) and plug it anywhere. What do you think about micro apps for mobile or web?
