### ISSUE TITLE
Whats your Testing approach like❓

### ISSUE THREAD

**Issue by deadcoder0904** [kentcdodds/ama#381]
Hi Kent 👋

I read your blog post `Write Tests. Not too many. Mostly Integration` & was wondering how do you start with Tests. Like first Unit Test, then Integration & then E2E or some other way❓

Also, do you follow TDD❓

What are your steps as I'm planning to write more tests from now on❓

Also what is the use of Unit & Integration if I use E2E as I'm basically building a web app & the way I used to test things manually was through the browser like E2E & not calling function with params like Unit or Integration❓

**Comment by kentcdodds** [comment]
Hi @deadcoder0904!

For anyone wondering, here's a link to that blog post: http://kcd.im/write-tests

> how do you start with Tests. Like first Unit Test, then Integration & then E2E or some other way❓ Also, do you follow TDD❓

There's no science to it. I write the test that makes sense for what I'm writing.

- E2E: after finishing a whole feature
- Integration: _normally_ after finishing the set of components for a feature
- Unit: _sometimes_ I use TDD here, but normally it's test as I build the unit

> What are your steps as I'm planning to write more tests from now on❓

My steps? I think it's important to make sure you have a testing framework configured and ready to go. Write a few tests for existing components and find areas where you could make simple testing utilities for your codebase, then make those easy to import from other tests. Then integrate testing into your workflow while building stuff.

> Also what is the use of Unit & Integration if I use E2E as I'm basically building a web app & the way I used to test things manually was through the browser like E2E & not calling function with params like Unit or Integration❓

Every level of testing comes with benefits and trade-offs. Give my talk ["What we can learn about testing from the wheel"](https://youtu.be/Da9wfQ0frGA?list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf) a watch. Also, watch the my talk ["Write tests. Not too many. Mostly integration."](https://www.youtube.com/watch?list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf&v=Fha2bVoC8SE) where I justify several of the forms of testing.

Good luck!
