### ISSUE TITLE
Building Websites

### ISSUE THREAD

**Issue by chadelofson** [kentcdodds/ama#384]
Hey Kent,

I have been starting to play with react a little more in the past month.  I took both the React and Redux class with Wesbos and I will be reviewing your course on egghead.   Can you build a business site with React and React Router without redux?

One site I am making has an App root component with state information.  I would like to pass some of that state information to the components in the routes, but I think I would have to have state at each React Page component.

The other thought I have is to have a multi-page node.js website with react components.

**Comment by kentcdodds** [comment]
Hi @chadelofson,

I rarely ever use redux actually. I wrote about how I prefer to manage state on my blog: [Application State Management](https://blog.kentcdodds.com/application-state-management-66de608ccb24). Hopefully that's helpful to you.

Good luck!
