### ISSUE TITLE
Render props as children

### ISSUE THREAD

**Issue by singletoncoding** [kentcdodds/ama#386]
In your talk [5 Patterns to make your React Components more useful](https://www.youtube.com/watch?v=Jlj8mVaDrb4) you show using render props as children instead of using a specifically named prop.  Could you explain why you chose children over the regular prop?

**Comment by kentcdodds** [comment]
Hi @singletoncoding! Yeah, sorry I know the audio from that was pretty bad. So here are a few reasons I prefer calling my render prop `children` over `render`:

1. I like the way it looks
2. You can't have more props after the render prop. If you use a regular named prop then the length of the render prop could obscure other props further down below which could lead to some confusion.
3. It's what the new context API uses and I like cohesion.
4. When you look at the React tree in dev tools what the render prop renders is a child of the component you're using so it makes sense to put it there.

I hope that helps. Thanks!

**Comment by singletoncoding** [comment]
Sorry to dredge this back up, but could you further clarify point 2?  Based on what I am reading[1], it looks like you can have multiple render props.  Perhaps I'm missing something?

[1] - https://reactjs.org/docs/render-props.html#using-props-other-than-render

**Comment by kentcdodds** [comment]
Yep, you can have any number of props that render. In that situation the render function of the component does more than just call a single function but has some logic or perhaps even some additional react elements that it renders in addition to calling your functions. In those cases, having named render props is preferable to differentiate them.
