### ISSUE TITLE
What's your take on BDD?

### ISSUE THREAD

**Issue by riddla** [kentcdodds/ama#387]
Hi Kent,
I'm curious if you ever did try BDD?
Like in “speccing” out requirements together with different team members – product owners, stakeholders, UX and design people? Resulting in a common understanding of the given business domain, it's problems and uses cases and/or a living documentation? Taking it a step further would be driving automated unit/integration/e2e tests from a tool like Cucumber?

Thank you,
Volker

**Comment by kentcdodds** [comment]
Hi @riddla!

Thanks for the question. I like the idea conceptually and I've done it in the past with some success. But any pure BDD-style tests have inevitably led to pretty confusing tests in my experience. But to be perfectly honest, my experience with BDD has been fairly limited, so I don't know if my experience is a typical one in this regard.

Sorry that's not all the helpful. Good luck!
