### ISSUE TITLE
Your opinion about UNSTATED

### ISSUE THREAD

**Issue by venikman** [kentcdodds/ama#388]
https://github.com/jamiebuilds/unstated .

**Comment by jkinzel-r7** [comment]
@venikman -- He actually talked about this yesterday after the advanced react patterns workshop at Front End Masters. They use unstated at PayPal and he thinks it is an awesome first step into state management. IIRC he said his approach is usually:  React Component State > Unstated > Redux.

**Comment by venikman** [comment]
@jkinzel-r7 I think with Unstated we could not use Redux. Hm I would like to see more real(prodcution) projects based on Unstated.

**Comment by jkinzel-r7** [comment]
Sorry I meant to imply that would be a progression of usage. Start with normal component state, when you feel the pain of limitations move to Unstated, and then if you feel pain there, move to Redux. It would require potential refactoring of the application.

**Comment by kentcdodds** [comment]
I love Unstated. We're using it on a project I'm helping with at PayPal and it's fantastic. I have a blog post about this actually [Application State Management](https://blog.kentcdodds.com/the-state-reducer-pattern--b40316cfac57).

There's actually no reason you shouldn't be able to use unstated with redux as well. Though I wouldn't recommend storing the same state in both.

Good luck!
