### ISSUE TITLE
Looking to make contribution to react-testing-library

### ISSUE THREAD

**Issue by suhailnaw** [kentcdodds/ama#389]
Do you have any work you need done on your react-testing-library?  I'm looking to make my first open source contribution on a React related project and your super lightweight testing library seems awesome!  Do you have any plans to edit it or ideas for new features?

**Comment by kentcdodds** [comment]
Hi @suhailnaw!

In [my most recent newsletter](https://buttondown.email/kentcdodds/archive/11b78095-a41f-4b79-a025-3a6e615c7cd1) I talk about this a little bit:

> You contribute best to something you use regularly

Normally the ideas for contributions come naturally when you're using a project regularly.

Another thing you can do if there's a specific project you'd just like to make contributions to [is "watch" the repo](https://help.github.com/articles/watching-and-unwatching-repositories/).

For example, if you had been watching the react-testing-library you would have seen this pop up: https://github.com/kentcdodds/react-testing-library/issues/65

Following along the discussion there's an opportunity to contribute a `rerender` utility method that should be a pretty straightforward contribution.

Feel free to make that contribution. Thanks!

**Comment by kentcdodds** [comment]
I've left that issue open for you to implement and gave some specific instructions. Good luck!
