### ISSUE TITLE
What is your opinion on ES6 classes?

### ISSUE THREAD

**Issue by mayankchd** [kentcdodds/ama#39]
I have recently seen some JS developers advocating against using ES6 classes . <a href="https://github.com/joshburgess/not-awesome-es6-classes">There</a> is also a git repo about this. What is your view on this ..

**Comment by kentcdodds** [comment]
There are several reasons that I don't like using ES6 classes. The repo you linked was interesting and reflects some of my feelings on them. I prefer object composition over inheritance and I think that classes enable/encourage inheritance. I also really like what I've come to call [Newspaper Code Structure](https://medium.com/@kentcdodds/newspaper-code-structure-8b4616af9539) which I think makes code really readable, but is impossible to do with classes.

Angular 2 is adopting classes big time. I'm not a fan of this at all. This is one of the few things about Angular 2 that I'm not excited about and it gets me more excited about React.

**Comment by mayankchd** [comment]
Thanks , i like your tutorials a lot .

**Comment by kentcdodds** [comment]
Thanks! And thank you for the question!

**Comment by tannerlinsley** [comment]
I have also found es6 to be a step backwards for good code organization.  It's a shame that we can just hoist functions to a class haha.

**Comment by killswitch** [comment]
Why not both inheritance and composition? In PHP we had traits, which helped add common functionality to many classes. We would often extend classes that made sense, for example:

```php
class Animal {
  private $type;
  
  public function __construct ($type) {
    $this->type = $type;
  }
}

trait Walks {
  public function walk() {
    return $this-> name . "the " . $this->type . " walks.";
  }
}

class Bear extends Animal {
  use Walks;
  
  public function __construct ($name) {
    parent::__construct('bear');
  }

  public function growls () {
    return $this->name . "the " . $this->type . " growls.";
  }
}

class Human extends Animal {
  use Walks;

  public function __construct ($name) {
    parent::__construct('human');
  }

  public function speaks () {
    return $this->name . " the " . $this->type . " speaks.";
  }
}

$bubba = new Bear('Bubba');
echo $bubba->growls(); // Bubba the bear growls.
echo $bubba->walks(); // Bubba the bear walks.

$josh = new Human('Josh');
echo $josh->speaks(); // Josh the human speaks.
echo $josh->walks(); // Josh the human walks.
```

With this `Human` and `Bear` are children of `Animal` and both can `walk()` but only `Bear` can `growl()` and `Human` can `speak()`.

Same can be done in JavaScript:

```javascript
class Animal {
  constructor (type) {
    this.type = type
  }
}

function Walks () {
  return `${this.type} walks.`
}

class Bear extends Animal {
  construct (name) {
    super('bear')
    this.name = name
  }

  growls () {
    return `${this.name} the ${this.type} growls.`
  }
}

class Human extends Animal {
  constructor (name) {
    super('human')
    this.name = name
  }

  speaks () {
    return `${this.name} the ${this.type} speaks.`
  }
}

extend(Bear, { walks })
extend(Human, { walks })

const bubba = new Bear('Bubba')
console.log(bubba.growls()) // Bubba the bear growls.
console.log(bubba.walks()) // Bubba the bear walks.

const josh = new Human('Josh')
console.log(josh.speaks()) // Josh the human speaks.
console.log(josh.walks()) // Josh the human walks.
```

Now you're getting the benefits of both. While I understand the argument against ES2015 classes because of way too deep of inheritance, when used properly they are beneficial, and you can do both.

**Comment by kentcdodds** [comment]
I see your point. Thanks for sharing. However I feel like I could accomplish all of that using **only** composition and don't really see any benefits of inheritance at all. And by focusing on composition I don't need to worry about the problems with too deep inheritance because I'm not doing it :)

**Comment by killswitch** [comment]
True, I consider it something as a developer I need to be conscious of.
