### ISSUE TITLE
What's it like working at PayPal?

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/ama#390]
I got these questions from someone on Twitter who would like to remain anonymous:

> How mentorship / individual career growth is handled? 
> 
> How collaborative is the work? 
> 
> Do you like it? 
> 
> As an individual eng do you get much say in what / how something is built? 
> 
> How is the stack divided up for engs? Ex are all engs full stack or is it front end / back end?
> 
> Also how they ensure collaboration happens in a remote environment

**Comment by kentcdodds** [comment]
I decided to record my answer via audio: https://www.briefs.fm/3-minutes-with-kent/60

Good luck!

**Comment by joeycozza** [comment]
"What's it like working at Paypal"
>I should start off by saying that I work at home, I've been working at Paypal for 2 1/2 years at home in Utah. I've actually only been into the office like a dozen times or so in the past 2 1/2 years. So take my experience with a grain of salt I guess. 

"How is mentorship/individual career growth handled"? 
>Yeah, I think I'm going to miss out a little bit being remote and all. I don't think there is a specific program for this, but we do have internal training for sure that I'm always getting emails about. And I also do training for paypal employees. Often its like I'll go into the office in San Jose and do training for anybody that wants to come. And there is definitely budgets for going to conferences and things like that. As far as mentorship, I think when you're a new dev, like there's nothing official and maybe other teams do things differently, but we pretty much just all help each other, there's nothing official there.

"How collaborative is the work"? 
>I would say its pretty collaborative. In the office it is an open office, which has goods and mostly bads, but yeah I feel like there is a lot of collaboration between teams, so pretty collaborative I guess.

"Do you like it"?
>Yes, I absolutely love Paypal. It is by far my longest tenure at any company. I love it at Paypal, and I'm not planning on making any change anytime soon.

"As an individual engineer do you get to say much about how something is built?"
>Yeah, I do have to convince my teammates. Now I'm doing more like tooling related stuff. This paypal-scripts thing you can find on my blog I talk about it in a couple blogposts. So yeah, I have a lot more say about how that is built. Even as an individual contributor engineer on a product team, I definitely felt like I had a lot to say. I was able to decide or able to convince the team on testing frameworks and ui libraries and stuff.

"How is the stack divided"?
>There is a frontend and backend. Most engineers that like, on my team we had frontend and backend together but it was all considered kind of frontend. It used to be server rendered stuff so it was a lot of node.

"How do you ensure collaboration happens in a remote environment"? 
>It is kind of my job. That's my responsibility, most of Paypal isn't remote friendly.

**Comment by kentcdodds** [comment]
Thanks you @joeycozza!

**Comment by joeycozza** [comment]
No problem. I had a few lulls at work and decided to do something other than read more online articles.

Also, if you wanted to add the transcribed label to this one https://github.com/kentcdodds/ama/issues/393 that would really help my impulse to have a 100% completion rate. :)

**Comment by kentcdodds** [comment]
Done! Also I added you as a collaborator in case you want to add labels yourself :) Thank you!
