### ISSUE TITLE
Creating a video (gif) quickly

### ISSUE THREAD

**Issue by ruffle1986** [kentcdodds/ama#392]
Hello Kent,

I'm hoping that you're doing alright. 

I'm really curious about what your approach is to quickly create a small size video to show a bug or an unexpected behaviour in the application to another person. 

Thank you in advance! 

Cheers! ✌️

**Comment by kentcdodds** [comment]
Hi @ruffle1986,

I use [Kap](https://getkap.co/). It's really awesome :)

**Comment by ruffle1986** [comment]
Indeed, it really is! Thanks! 🙏

**Comment by ultrox** [comment]
@kentcdodds regarding kap, can you edit video quickly, like deleting some parts, or/and annotate?

**Comment by kentcdodds** [comment]
It's not quite that capable. You can trim the start and end and export to various formats and resolutions.
