### ISSUE TITLE
Have you considered 'not coding' as a career?

### ISSUE THREAD

**Issue by aputhin** [kentcdodds/ama#393]
Hi Kent! Hope everything's going well.

Do you expect/would like to be a software engineer for your whole life/career? Have you ever thought about pursuing other related career paths or activities, like coaching or management roles (a.k.a. moving away from code)? 

I've been thinking about these lately regarding my own career path and thought it would be nice to check on other people's ideas on the subject as well. :)

**Comment by kentcdodds** [comment]
Hi @aputhin!

I decided to answer this question via audio: https://www.briefs.fm/3-minutes-with-kent/62

Good luck!

**Comment by joeycozza** [comment]
Side note: I left off the intro in the audio answer that introduces the question.

Audio Transcription:
```"I've certainly considered it. I've thought about what it would be like if I went into management. About a year ago I was the team lead on a product team here at Paypal and I did a pretty terrible job at it. I do care about people and I want them to be successful in their careers and stuff, but I just...I dunno, I just prefer to code. Maybe one day I'll be good at it and I'll want to get more involved in that area of software development but right now I can't see myself not coding or teaching people how to code better. I think its a great career path, so if that's something you're interested in then definitely go and do that. You can make a bigger impact on a lot more people in that way, but yeah,I just prefer to code myself. I think it's a lot more fun. Good luck!"```

**Comment by kentcdodds** [comment]
Thank you so much @joeycozza!
