### ISSUE TITLE
Flexible Compound Component Pattern (with Redux)

### ISSUE THREAD

**Issue by DalerAsrorov** [kentcdodds/ama#394]
Hi Kent, I am watching the *React Patterns* course in Frontend Masters, great stuff! I was wondering if it's possible to implement components with compound pattern using redux instead of the new React context API. What do you think about it?

**Comment by kentcdodds** [comment]
Hi @DalerAsrorov,

Is it possible? Definitely. Would I recommend it? No. Definitely not. I can't imagine a collection of compound components growing to such complexity that they need something like redux to simplify things. All that redux would do would make the components more complex than necessary.

Good luck!
