### ISSUE TITLE
AVA

### ISSUE THREAD

**Issue by rimatla** [kentcdodds/ama#395]
Hi Kent,

I haven't encountered many online tutorials except your youtube workshop talking about AVA. 
Nowadays Jest is widely chosen as the testing framework of choice to go alongside React apps.

- Having worked with both AVA & Jest, how do they compare to each other **today**?
- Do you know where else I'd find more content covering AVA?

**Comment by kentcdodds** [comment]
Hi @rimatla!

I decided to answer this question via audio: https://www.briefs.fm/3-minutes-with-kent/63

Good luck!

P.S. here's the referenced blog post: https://blog.kentcdodds.com/migrating-to-jest-881f75366e7e

**Comment by rimatla** [comment]
Thank you so much @kentcdodds
