### ISSUE TITLE
Do you prefer CSS modules or styled components?

### ISSUE THREAD

**Issue by zaguini** [kentcdodds/ama#396]
The title is pretty self-explanatory, btw.

I know you're involved in the styled components project, but that's one thing that came into my mind.

Which one is better?
What are the advantages and disadvantages of one method over another?
Are styled components extracted to a CSS file or are the styles inlined and repeated in the final bundle? What are the gains in performance?

**Comment by kentcdodds** [comment]
Hi @zaguini!

I decided to answer this question via audio: https://www.briefs.fm/3-minutes-with-kent/61

Good luck!
