### ISSUE TITLE
Best ways/patterns to split app into components

### ISSUE THREAD

**Issue by glaszczyk** [kentcdodds/ama#399]
Hello,
I would like to ask what is best approach when splitting app into components. I always struggle with this part. How specialized/universal should components be?

Thank you.

**Comment by kentcdodds** [comment]
Hi @glaszczyk!

I answered this question in my newsletter today: https://buttondown.email/kentcdodds/archive/ebc5ac2c-07bf-4e07-8a2b-fe131fe573e0

Here's a copy/paste of the whole thing:

---

# When to break up a component into multiple components

_At what point does it make sense to break a single component into multiple components?_

**[Advanced React Component Patterns Course in Portland next week!](https://workshop.me/2018-07-advanced-react?a=kent)**

Hey friends, one quick thing before this newsletter, I'm giving [a live and in person workshop in Portland](https://workshop.me/2018-07-advanced-react?a=kent) next week right before [ChainReact](https://infinite.red/ChainReactConf).  Ask your boss if they'll pay for you to go get better at React. They probably would love for you to attend this workshop :) We'll be going over:

- Use the Compound Components Pattern to write React components that implicitly share state while giving rendering flexibility to the user
- Share code and enhance your components with the Higher Order Components Pattern
- Give full rendering power to users with the Render Props Pattern
- Improve the render prop API with the Prop Collections and Prop Getters Patterns
- Provide total logic control with the Controlled Props and State Reducer Patterns
- Take advantage of React’s Context API to share state throughout the application with the Provider Pattern

Ok, now on to our newsletter!

---

Did you know that you could write any React Application as a single React Component? There's absolutely nothing technically stopping React from putting your entire application into one giant component. You'd have a HUGE `render` method, a TON of instance methods, a LOT of state, and you'd probably need every lifecycle hook (with the exception of `shouldComponentUpdate` (it should always update!) and `componentWillMount` (it will never unmount!)).

If you tried this though you'd face a few problems:

1. Performance would probably suffer: Every state change results in a re-render of the entire application.
2. Code sharing/reusability would be... not easy.
3. State would be a challenge: Knowing which pieces of state and event handlers went with what parts of JSX would make your head hurt 😬 and lead to some hard to track down bugs 🐜
4. Testing would be 100% integration: [Not necessarily an altogether bad thing](http://kcd.im/write-tests), but it would be pretty tough to test edge cases and keep things isolated to the parts that you're trying to test, so maintaining those tests would be a challenge.
5. Working together on the codebase with multiple engineers would just be terrible. Can you imagine the git diffs and merge conflicts?!
6. Using third party component libraries would be..... ummm... impossible? If we're writing everything as a single component third party libraries is at odds with that goal! And even if we allowed using third party components, what about HOCs like [react-emotion](https://emotion.sh/)? Not allowed!
7. Encapsulating imperative abstractions/APIs in a more declarative component API wouldn't be allowed either meaning that the imperative API would be littered throughout the lifecycle hooks of our one giant component, leading to harder to follow code.

These are the reasons that we write custom components. It allows us to solve these problems.

I've had a question on my AMA for a while: [Best ways/patterns to split app into components](https://github.com/kentcdodds/ama/issues/399). And this is my answer: "When you experience one of the problems above, that's when you break your component into multiple smaller components. NOT BEFORE." Breaking a single component into multiple components is what's called "abstraction." Abstraction is awesome, but [every abstraction comes with a cost](http://kcd.im/how-to-react), and you have to be aware of that cost and the benefits before you take the plunge

> ["Duplication is far cheaper than the wrong abstraction."](https://www.sandimetz.com/blog/2016/1/20/the-wrong-abstraction) - [Sandi Metz](https://twitter.com/sandimetz).

So I don't mind if my component's render method gets really long. Remember that JSX is just a bunch of JavaScript expressions using the declarative APIs given by components. Not a whole lot can go wrong with code like that and it's much easier to keep that render method as it is than breaking out things into a bunch of smaller components and start [Prop Drilling](http://kcd.im/prop-drilling) everywhere.

## Conclusion

So feel free to break up your components into smaller ones, but don't be afraid of a growing component until you start experiencing real problems. It's WAY easier to maintain it until it needs to be broken up than maintain a pre-mature abstraction. Good luck!

**Looking for a job? Looking for a developer? Check out my job board: [kcd.im/jobs](http://kcd.im/jobs)**

---

**Learn more about React from me**:

- **[Workshop.me](https://workshop.me/2018-07-advanced-react?a=kent) - I'm giving my Advanced Component Patterns workshop in person in Portland next week!!!!**
- [egghead.io (beginners)](http://kcd.im/beginner-react) - My Beginner's Guide to React absolutely *free* on egghead.io.
- [egghead.io (advanced)](http://kcd.im/advanced-react) - My Advanced React Component Patterns course available on egghead.io!
- [Frontend Masters](https://frontendmasters.com/courses/advanced-react-patterns/) - My Advanced React Patterns course in the form of a Workshop.
- [Workshop.me](https://workshop.me/2018-08-react-intro?a=kent) - I'm giving my Intro to React workshop in person in Salt Lake City in August!

**Things to not miss**:

- [DevTipsWithKent](http://kcd.im/devtips) - I have a daily livestream where I show off one thing that I learned recently or something people have been asking me about. The videos are live, brief, unscripted, and full of valuable info and tips. [Subscribe to my YouTube channel](http://kcd.im/youtube) and click the notification bell to be notified when I'm streaming :)
- [Learn React with Kent C. Dodds](https://www.youtube.com/watch?v=zthIUs2w_c8) - My livestream on [freeCodeCamp's YouTube channel](https://www.youtube.com/channel/UC8butISFwT-Wl7EV0hUK0BQ).

**Some tweets from this last week:**

> This is just so freaking cool: https://github.com/facebook/jest/pull/6380
> 
> Mad props to [@lucasazzola](https://twitter.com/lucasazzola) – [27 Jun 2018](https://twitter.com/kentcdodds/status/1012025903042519041)

<a href="https://github.com/facebook/jest/pull/6380"><img width="500" alt="screenshot of the tweet" src="https://user-images.githubusercontent.com/1297597/40886784-a430e130-6781-11e8-8a3e-b7fb0c9d88cc.gif" /></a>

> Friends, I'm telling you @fbjest is an incredible testing framework. Seriously so good. Give it a try if you haven't 💗 🃏 – [25 Jun 2018](https://twitter.com/kentcdodds/status/1011438296843497473)

> Font: http://Dank.sh  by @_philpl
> Theme: http://aka.ms/nightowl  by @sarah_edo
> 
> Shortening this tweet to http://kcd.im/mft  (my font/theme)
> 
> \+ other @code things: http://kcd.im/vscode  👌 – [27 Jun 2018](https://twitter.com/kentcdodds/status/1011999102492504064)

<a href="https://twitter.com/kentcdodds/status/1011999102492504064"><img width="500" alt="screenshot of the tweet" src="https://pbs.twimg.com/media/DgtXwVYV4AE_ajw.png" /></a>

> Phew, got 24 branches ready for my course on Configuring Jest in modern JavaScript web applications. 😌 
> 
> Now time to get recording! 😬 😆 – [30 Jun 2018](https://twitter.com/kentcdodds/status/1013266401216245761)

---

This week's blog post is  "[Test Isolation with React](https://blog.kentcdodds.com/6962d3f13d1f)". It's the published version of my newsletter from 2 weeks ago. If you thought it was good, go ahead and give it some claps (👏[x50](https://blog.kentcdodds.com/did-you-know-3079d5aec43b)) and [a retweet](https://twitter.com/kentcdodds/status/1013830327767220224):

<a href="https://twitter.com/kentcdodds/status/1013830327767220224"><img width="500" alt="screenshot of the tweet" src="https://i.imgur.com/iOIR4TT.png" /></a>

**Special thanks to my [sponsor Patreons](https://www.patreon.com/kentcdodds)**: [Hashnode](https://hashnode.com/?utm_source=kentcdodds)

_**P.S. If you like this, make sure to [subscribe](http://kcd.im/news), [follow me on twitter](https://twitter.com/kentcdodds), [buy me lunch](http://kcd.im/donate), [support me on patreon](http://kcd.im/patreon), and [share this with your friends](http://kcd.im/news) 😀**_

---

👋 Hi! I’m [Kent C. Dodds](https://kentcdodds.com/). I work at [PayPal](https://www.paypal.com/) as a full stack JavaScript engineer. I represent PayPal on [the TC39](https://github.com/tc39). I’m actively involved in the [open source community](https://github.com/kentcdodds). I’m an instructor on [egghead.io](https://egghead.io/instructors/kentcdodds), [Frontend Masters](https://frontendmasters.com/), and [Workshop.me](https://workshop.me/?a=kent). I’m also a [Google Developer Expert](https://developers.google.com/experts/people/kent-c-dodds). I’m happily married and the father of four kids. I like my family, code, JavaScript, and React.
