### ISSUE TITLE
Selfie

### ISSUE THREAD

**Issue by sindresorhus** [kentcdodds/ama#4]
To continue the tradition https://github.com/sindresorhus/ama/issues/75, https://github.com/passy/ama/issues/28, https://github.com/stephenplusplus/ama/issues/19.

**Comment by kentcdodds** [comment]
![1436186994826-1796254236](https://cloud.githubusercontent.com/assets/1500684/8522436/52373b6c-23ab-11e5-92c7-e1f421488bac.jpg)
