### ISSUE TITLE
What do you use to insert emoji characters

### ISSUE THREAD

**Issue by scotato** [kentcdodds/ama#40]
I noticed you inserting emoji into text in the Open Source JS library how to series, what are you using for that?

**Comment by kentcdodds** [comment]
Great question :smile: (👈 that's actually just [a github emoji](http://www.emoji-cheat-sheet.com/))

I'm just using the built-in mechanism for Macs . You can read up 📗 on that [here](http://www.imore.com/how-insert-emoji-text-os-x-yosemite). Basically just hit the <kbd>⌃</kbd> + <kbd>⌘</kbd> + <kbd>space</kbd> key combination and up pops the emoji chooser:

![Emoji Chooser](https://cloud.githubusercontent.com/assets/1500684/10635059/35d9f480-77b3-11e5-8a35-fe8f41a36b5b.png)

I find it makes commit messages more entertaining and expressive :laughing: 

If you really want to take it to the next level, check out [lolcommits](https://github.com/mroth/lolcommits) by @mroth :joy:

**Comment by scotato** [comment]
Very cool! Thank you!

**Comment by juristr** [comment]
@kentcdodds Wow!!! Cool, thx, I was always wondering what ppl use to write down emojis when on the computer. On the phone it's quite obvious, but I didn't know about the shortcut on OSX :smile: cool, thx!

**Comment by Dignifiedquire** [comment]
Soooo good!

**Comment by devrchancay** [comment]
:+1:  :runner: 

https://www.npmjs.com/package/emotsjs

**Comment by kentcdodds** [comment]
@devrchancay that's amazing. If I'm not mistaken, you built that following along with my [egghead.io series](https://egghead.io/series/how-to-write-an-open-source-javascript-library). It just looks remarkably similar to the lib I used for the series [starwars-names](npm.im/starwars-names). If so :+1: :clap: if not :+1: :clap:

**Comment by devrchancay** [comment]
I discovered , just after purchasing the subscription , use it in one of your examples please :clap:

**Comment by kentcdodds** [comment]
I might just do that!

On Mon, Oct 26, 2015, 9:20 PM Ramón Chancay Ortega <notifications@github.com>
wrote:

> I discovered , just after purchasing the subscription , use it in one of
> your examples please [image: :clap:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kentcdodds/ama/issues/40#issuecomment-151360595>.
>
-- 
- Kent C. Dodds <https://twitter.com/kentcdodds>
