### ISSUE TITLE
Please summarize your issues with Enzyme

### ISSUE THREAD

**Issue by josgraha** [kentcdodds/ama#402]
In your testing-react course you mentioned that you had a lot of issues with Enzyme.  Wondering if you could summarize them here?

**Comment by detrohutt** [comment]
For a short, inclomplete answer see [this tweet](https://twitter.com/kentcdodds/status/974278185540964352).

For a more complete answer, see the question `What about enzyme is "bloated with complexity and features" and "encourage poor testing practices"?` at [the FAQ for react-testing-library](https://github.com/kentcdodds/react-testing-library/blob/master/README.md#faq).

For a live demonstration/explanation/reasoning of the differences between enzyme and react-testing-library see [this talk called "Confident React"](https://www.youtube.com/watch?time_continue=160&v=qXRPHRgcXJ0).

**Comment by kentcdodds** [comment]
Thanks @detrohutt! I do plan on writing a blog post about Shallow Rendering specifically eventually. Subscribe to my newsletter to get that in your inbox: http://kcd.im/news

**Comment by kentcdodds** [comment]
Here's the newsletter: https://buttondown.email/kentcdodds/archive/76ce5bb1-0681-490b-9e1e-62f27e5cfa4d
