### ISSUE TITLE
Help me (Kent) stay awake driving by calling my phone and talking tech (part 2)

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/ama#405]
Hey friends! Remember about a year ago when I drove by myself half way across the United States and asked you to help me stay awake? If you don't remember, read up about it here: #295. It was pretty sweet.

Whelp, I'll be driving by myself this weekend. Just making a special and short trip to my hometown and my family can't come due to logistical reasons.

My hometown is just about a 4 hour drive away, so it wont be nearly as long as last time, but I think we could still talk about a lot of fun stuff in that time!

So, just like last time, here are the things you should do if you want to participate in our conversation:

### 1. You subscribe to this issue

<img width="448" alt="click the subscribe button on the issue" src="https://user-images.githubusercontent.com/1500684/28737335-46384318-73ab-11e7-9320-a2a1f60dcbae.png">

### 2. I let you know when I'm accepting phone calls

**The trip is Saturday Afternoon and I'll return Sunday Morning**. I'll be leaving at around 11:00 AM Mountain Time on Saturday, and probably sometime around 10:15 AM Mountain Time on Sunday.

Before I start driving, I'll comment on this issue saying that I'm ready to accept phone calls. If you've subscribed, you should get a notification. And you can call in at any time! Here's the info:

**Join the call: https://www.uberconference.com/kentcdodds**
**Optional dial in number: 401-283-5757**
**PIN: 19573**

You can call from your phone or your computer.

> ⚠️ Note: Calling in reveals your phone number to all participants; using the web link does not

**Please do NOT call in until I comment**. Uberconference will send me a text about it and it's kinda annoying 😅 

I can have up to 10 people in at once (I think more can just listen in though), so I'm sure that'll be plenty :smile:

> Note: [The AMA code of conduct](https://github.com/kentcdodds/ama/blob/master/CODE_OF_CONDUCT.md) applies during the call. Let's all be nice and inclusive on this call :smile:

### 3. We start chatting!

We can talk about anything really. We'll just pretend we're at a conference hanging out talking tech. Or on one of my old [JavaScript Air](https://javascriptair.com) shows :smile: We can talk about anything you all want to talk about. Whatever helps me stay awake, engaged, and alert while driving.

I'll be recording the call so I can put it up somewhere when we're done. That way more folks can get something out of whatever we talk about! Cool right!? (Don't worry, if you'd like me to cut something out of the call later, just ask me and I'll cut that out of the recording).

### 4. We wrap up

I may need to hang up to take a break or pull over or something. When that happens, I'll let you all know. Last time even when I would hang up, folks would keep talking. That's totally cool. I'll just join back in when I'm finished.

---

Let me know if you have any questions! And thank you so very much!

Ideas of things to talk about if the conversation dies down:

1. Look at [my github](https://github.com/kentcdodds) history and ask me about anything on there.
2. Look at [my 3 minute podcast](https://www.briefs.fm/3-minutes-with-kent) and ask me about anything in there
3. Look at [JavaScript Air](https://javascriptair.com/) and ask me about any of those episodes
4. Ask me about any of my [Frontend Masters](https://frontendmasters.com/courses/) or [Egghead.io](https://egghead.io/instructors/kentcdodds) courses
5. Teach me something I don't know about! Reason, GraphQL, Serverless
6. Really anything, I'm just making things up... :smile:

**Comment by PierreAndreis** [comment]
In the last call, we could see other participants phone numbers, which was an issue for me.

Back then, discord didn't allow to limit a voice chat to 10 participants, but now does.
I suggest moving this conversation to discord?

**Comment by kentcdodds** [comment]
You can call in on the computer or via the uberconference app I think. I'm afraid I wont have time to investigate whether using discord would work for me (I'm not sure whether I'll have data on my phone on the whole drive).

**Comment by callahad** [comment]
Probably worth just adding a note next to the dial-in number along the lines of "(⚠️ Note: Calling in reveals your phone number to all participants; using the web link does not)"

**Comment by tannerlinsley** [comment]
This sounds like blast. 🙌

**Comment by dandigangi** [comment]
Subbed!!!

**Comment by kentcdodds** [comment]
Whoops! Thanks @jnielson94! Fixed!

**Comment by ajwhite** [comment]
Last time was fun! Lookin forward to it

**Comment by loanlaux** [comment]
I'm in!

**Comment by jeremyscatigna** [comment]
Sounds so cool I’m in !

**Comment by kentcdodds** [comment]
FYI, I updated the time I'm leaving. I'm probably leaving about two hours earlier than originally planned.

Chat later! :)

**Comment by gricard** [comment]
So 11am MST / 1pm EST?

**Comment by kentcdodds** [comment]
I'm calling in now!

**Comment by olstenlarck** [comment]
damn i can't join ;/

**Comment by kentcdodds** [comment]
I'm on my way home and ready to chat!

**Comment by marktnoonan** [comment]
Hey folks, I learned a lot in the chat and really appreciate you talking through some of the ideas I was curious about. The suggestions about Code Sandbox and a testing workflow were both hugely helpful, as was the discussion around pros and cons of adding a framework to a plain JS civic hacking project. It was also beneficial for me to just sit on some of the discussions around state, Redux, context etc. Thanks for setting it up Kent :)

**Comment by tannerlinsley** [comment]
I was also unable to attend. If anyone feels like they could summarize the
subjects talked about, I would love to hear about it!

**Comment by ritchieanesco** [comment]
Same. It would be great if someone can volunteer to document the discussion.

**Comment by marktnoonan** [comment]
Kent mentioned plans to upload the recordings, I'm sure he will update this thread when that happens.

**Comment by kentcdodds** [comment]
I'll be uploading the recording (audio only) to YouTube soon. It would be so cool if someone wants to make a table of contents for it when it's done!

**Comment by binarybaba** [comment]
Yup I'd do it.

**Comment by kentcdodds** [comment]
Cool! Thanks @binarybaba! Just post it here and I'll add it to the description.

This will take at least 2 hours to upload and probably some time to process, but when it's done it'll be here: https://www.youtube.com/watch?v=vVlcq3e1ooI

**Comment by binarybaba** [comment]
okay it's done. I tried to be a bit exhaustive. Sorry I took some more time.

1:00 - [Reason](https://reasonml.github.io/) with React
3:25 - Modules in Reason
9:18 - [React Native DOM](https://github.com/vincentriemer/react-native-dom) and [Vincent Riemer’s talk on Bridging React Native back to it's roots ReactEurope2018](https://www.youtube.com/watch?v=aOWIJ4Mgb2k)
20:06 [Metro](https://github.com/facebook/metro)
32:32 Satya from India’s cameo appearance.
34:10 Honest interviews with Kent: [Glamorous](https://github.com/paypal/glamorous) , [Downshift](https://github.com/paypal/downshift) and [cross-env](https://github.com/kentcdodds/cross-env).
52:22 [React Testing Library](https://github.com/kentcdodds/react-testing-library)
1:04:30 - [React DevTools](https://blog.kentcdodds.com/react-devtools-c2d56a901f37)
1:09:02 - Examples of real world React Projects repos with Testing?
1:15:54 - Angular/Vue vs React (feat. MobX/Redux)
1:20:51 - Managing complex UI in React
1:29:40 - Vue vs React Round 2
1:30:48 - What makes for good sustainable/managable React code?
1:32:37 - “We Kent reach Kent, guys”
1:34:05 - Kent came back.
1:39:50 - Vue on manageability of code
1:44:46 - How Kent reviews code.
1:54:24 - Render props and Decorators
1:59:07 - Kent looks at beautiful cows in a valley
2:00:24 - Views on Immutability of state
2:06:43 - Question: UI Composition
2:23:20 - About setState and how it _is_ asynchronous
2:30:00 - NangularJS
2:32:00 - PangularJS/Pongular vs React
2:36:52 - Hangular and Ember
2:37:51 - Async setState
2:44:39 - Opinions on React’s source code 
2:48:05 - DevTools with Angular vs React
2:53:15 - How Kent juggles between day job and contributions
2:59:51 - About Universal React components
3:07:09 - Good libraries to use with React on a real world app.
3:09:13 - Server side routing, client side routing and server side rendering

3:19:20 - Time travel debugging with Redux
3:29:00 - Pre-rendered components and sever side rendering
3:39:15 - How to deal with React interviews if you’re new to Redux
3:39:42 - Why use Redux
3:50:40 - Context API vs Redux
4:03:52 - Kent’s life at PayPal
4:09:50 - How to deal with deeply nested components
4:19:20 - Redux visited
4:20:50 - Framework or no?
4:31:39 - Why use React?
4:44:40 - Modern web development tooling
4:46:36 - Codesandbox.io
4:54:36 : Kent’s view on Javascript
4:59:53 : Kent’s thoughts on [CSSinJS](http://cssinjs.org/) and getting non-React guys unto speed
5:05:29 : Structuring Applications
5:09:58 : How to manage a lot of props in a component
5:35:09 : Testing with Cypress.io for authenticated routes 
5:46:45 : Data fetching in event handlers in React
5:49:09 : Context API and Redux
5:59:02: Kent’s take on GraphQL

**Comment by joshmanders** [comment]
Great work @binarybaba I copy and pasted your comment into the actual comments of the video so that we can easily just click the times to have it jump to each spot.

https://www.youtube.com/watch?v=vVlcq3e1ooI&lc=UgwtFbKpLaafTbipweZ4AaABAg

**Comment by antmdvs** [comment]
@binarybaba 

>1:59:07 - Kent looks at beautiful cows in a valley

LOL

**Comment by kentcdodds** [comment]
Thanks a ton!

**Comment by binarybaba** [comment]
Glad I could help guys! Please excuse me mocking angular. Im sorry I couldn't help it. TeeHee.
