### ISSUE TITLE
How did you display content of package.json in your terminal?

### ISSUE THREAD

**Issue by martinnov92** [kentcdodds/ama#408]
Hello Kent,

first I would like to thank you for amazing React Testing workshop and I would like to ask you, how did you display "script" part of your package.json file in terminal. I saw it in one of your videos, that you used the command `nr`. Can you please tell me how to do it? 😄 

Thank you very much.

**Comment by kentcdodds** [comment]
Hey @martinnov92!

I'm using [npm-quick-run](https://www.npmjs.com/package/npm-quick-run) by @bahmutov

I recorded a video about this and other things here: https://www.youtube.com/watch?v=zEM50eI4O9o&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

Thanks!

**Comment by martinnov92** [comment]
Thank you 😄
