### ISSUE TITLE
Optimal way to understand a piece of code

### ISSUE THREAD

**Issue by opmftw** [kentcdodds/ama#410]
Hi Kent, 
I think that most new developers have a phase, where they can get a lot of things to 'work', but they don't necessarily understand, how and why everything works. 

I am trying to figure out a way to shorten the so called 'magic phase' for myself and be more confident when writing or reading code. 

I started testing my django and react code like 3 days ago and I feel like I've made some improvements.

Could you give your opinion on **if testing is the best way to understand a piece of code** (even if it's a side project and you're not concerned about it breaking.)

Thank you for your time :)

**Comment by detrohutt** [comment]
Kent does mention testing and “breaking things” in his article [How I learn an Open Source Codebase](https://blog.kentcdodds.com/how-i-learn-an-open-source-codebase-e0a447edcac2). If this doesn’t answer your question let me know and I’ll reopen this!
