### ISSUE TITLE
Aspiring web-developer; Looking for direction.

### ISSUE THREAD

**Issue by elamahpla** [kentcdodds/ama#413]
I'm an aspiring web-developer and I want to eventually move into software engineering once I've been working for in the industry for a bit. My question is this: I primarily use React, as it's what really appeals to me. Should I, as an aspiring web-developer try to use something else? Or do you think React can fit my needs?

I ask because lately, I've been having doubts about myself. Not the typical imposter syndrome, but the doubt that I'm using the wrong technology to achieve my goal(s).

**Comment by hedgerh** [comment]
Hey @elamahpla, figured I could help you with this.

> Not the typical imposter syndrome, but the doubt that I'm using the wrong technology to achieve my goal(s).

When I first started, I didn't know what back-end language/framework would be most useful to learn professionally.  Is that how you feel?

If your goal is to get a job in web development, you definitely can't go wrong learning React.  There are tons of React jobs out there.  I've pretty much been working exclusively with React for the past 3 years on the front-end.

If you want to bounce some questions off me, my email is on my Github profile.

**Comment by elamahpla** [comment]
Hey thanks, @hedgerh I emailed you last week, just as a heads up

**Comment by joeybuczek** [comment]
Hey @elamahpla, 

As @hedgerh mentioned, knowing React isn't a bad thing for web development, but do make sure that you try to broaden your knowledge along the way. For example, starting with React, you could easily delve more into the JavaScript language itself (that alone will make you a better React developer), and from there it might spark other framework/language interests. 

To address the doubts surrounding accomplishment of your goals, that really comes down to the following:
1) Define your goals (writing them down makes a huge difference!)
2) Researching what tech is commonly used to meet project needs of those goals
3) Work towards them by learning + doing based on your research

Also, once you start working in the industry, you'll learn things on the job that can help you improve your goals and make decisions on what to do next.

Hope this helps!
