### ISSUE TITLE
Testing using Cypress.io

### ISSUE THREAD

**Issue by tmarnet** [kentcdodds/ama#415]
You've been talking a lot about Cypress lately.

Do you think Cypress could do the job on its own (unit, integration & e2e) or should I pair it with something like Jest/react-resting-library ?

If so, should I write my integration tests with Cypress or with Jest/react-resting-library ?

Thanks 😄

**Comment by tylerbhughes** [comment]
I looked at Cypress a while back for work. I got the impression it was suited more for end to end testing. I'd probably use it just for that and then use Jest/react-testing-library for my unit/integration tests.

**Comment by detrohutt** [comment]
@tmarnet Kent actually answered this same question [on Twitter](https://twitter.com/kentcdodds/status/1008050762759299075) just a few days ago. Here's his answer:

"I prefer using react-testing-library and jest for my integration tests and Cypress only for end-to-end test. See Cypress-testing-library"

**Comment by kentcdodds** [comment]
Bingo. In addition check out my recent YouTube videos for how to use react-testing-library + jest mocking to unit test as well 👌
