### ISSUE TITLE
Tracking of Javascript application

### ISSUE THREAD

**Issue by Bigandt** [kentcdodds/ama#417]
Hey Kent

How do you go around tracking how your users interact with your applications?
I have searched the web for this topic, but I can't find any good resources. Do you have some pointers on where to look?

And, I am building an ads platform for a publisher which interact with lots of server on the client side, and I would like to track the interaction of the servers.
How do I do this? Are there any best practices for implementing tracking scripts? And how do I store all this information on servers?
I am of course not asking for how to implement it, but more what kind of tools I should look into, and what topics I should read into.

Hope you would like to answer this question :)
I use your blogs and videos a lot - thanks!

**Comment by kentcdodds** [comment]
You might also consider Trackjs or sentry. I hear good things about them. I've very little experience in this area though.
