### ISSUE TITLE
What is the difference between babel-plugin-macros and babel-plugin-codegen?

### ISSUE THREAD

**Issue by karanjthakkar** [kentcdodds/ama#418]
Hey 👋🏻 Following up from [this Twitter thread](https://twitter.com/kentcdodds/status/1005098900162691072), I'm now more confused than ever about the difference between these two.

I was under the impression that babel-plugin-codegen (and [other macros](https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/macros.md)) are powered by babel-plugin-macros under the hood. But apparently that seems to be a misconception. 

For me, based on what the reading that I did:
- macros is a concept of code transformation
- babel-plugin-macros are an implementation of that concept and expose utility methods to build your own macros
- babel-plugin-codegen will use these utilities from babel-plugin-macros to provide a certain type of transformation

Could you please elaborate a bit more on what I'm missing or what I'm getting wrong? 🙂

**Comment by sibelius** [comment]
More one this https://twitter.com/sseraphini/status/1007057593238478849?s=21

**Comment by kentcdodds** [comment]
[Heres your answer](https://www.youtube.com/watch?v=1queadQ0048&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u)!

**Comment by sibelius** [comment]
code here https://github.com/kentcdodds/codegen-vs-preval-vs-macros

**Comment by karanjthakkar** [comment]
Thanks for taking the time to explain this, Kent!
