### ISSUE TITLE
Using vars (const) in the render function

### ISSUE THREAD

**Issue by giladl82** [kentcdodds/ama#420]
Hi I'm just in the middle of watching your talk  "Advanced react patterns" on frontendmasters. I love it!

When you talked about compound components, you said not to put vars inthe render method since it will cause for multiple renders.
I was wondering if I shouldn't use it at all? Is it bad practice?
for example: 
const isActive = this.props.isOk && this.props.isBlue

Thank you.

One other thing, when you talked about render props you said you prefer children over function. I found myself using a function when I've built a tree component and wanted to enable a way to defer the way you render the nodes and the leafs.
Just thought it is a nice example of using a function

**Comment by hedgerh** [comment]
Hey, noticed you hadn't received an answer yet, so thought I'd try to answer your question.

Are you sure he said defining vars in the render method would cause multiple renders?  That shouldn't be the case.  I imagine he said that the vars would be redefined on every render, maybe?  If you define vars inside the render method, or inside a stateless functional component, they'll be redefined on every re-render.

I don't think it's bad practice to do your example.  `const isActive = this.props.isOk && this.props.isBlue` makes it much clearer what that conditional is doing, and keeps your JSX clean.  I don't imagine it having any performance implications unless you're re-rendering thousands of the component a few times per second, maybe not even then.

However, you may want to avoid defining things in render when there are alternatives.  For example, don't define functions inside render.  Instead, make them methods on a class component, or define them outside of a stateless functional component and pass it the params it needs.
