### ISSUE TITLE
React composition vs inheritace

### ISSUE THREAD

**Issue by krvajal** [kentcdodds/ama#421]
Hi Kent,
I recently started working on a new project and found a very *interesting* piece of code but I think that is against the react way of doing things. I would like to prove that to my coworkers but I want to have strong arguments to justify the refactoring. 
Here it goes.

```js
class export default class AbstractModal extends Component {
   

    state = {
        shown: false,
    };
    open = () => {
        this.setState({shown: true});
    }
    close = () => {
   
        this.setState({shown: false});
    }

    render() {
        return (
            <Dialog show={this.state.shown} onHide={this.close} >
                {this.renderModal()}
            </Modal>
        );
    }
}
```
And a concrete example can be
```js
class ConcreteModal extends Component {
  
  	renderModal(){
		return <div> Modal content here </div>
	}
}
```
This is later on used like this
```js
class Page extend Component {
	modalInstance = ConcreteModal
	render(){
	
		<div>
		<button onClick={() => this.modalInstance.open()}> Open Modal</button>
		<button onClick={() => this.modalInstance.close()}> Close Modal</button>
			<this.modalInstance/>
		</div>
	}
}
```
What can you critisize of this code and how it could be improved ?

**Comment by hedgerh** [comment]
Yeah this is definitely a wonky approach.  I assume you meant that `ConcreteModal` extends `AbstractModal`?  This is not a pattern that's typically used in React.  If you want to add re-usable functionality to a component, you typically create a HOC or a render prop/render as child function type component.

You shouldn't need to take that approach with Modals, though.  Typically, the `shown` state and open/close methods for a modal live on the parent component that renders the Modal as a child.  The approach they've taken goes against the flow of React, at least in my mind.  Parents shouldn't have access to methods on their children like `open` and `close` and directly alter their child state.

```
const Modal = props => {
  return (
    <Dialog show={props.shown} onHide={props.close}>
      {props.children}
    </Dialog>
  );
}
```

```
const ConcreteModal = props => {
  return (
    <Modal {...props}>
      <div> Modal content here </div>
    </Modal>
  );
}
```

```
export default class Page extends Component {
  state = {
    shown: false
  }

  open = () => {
    this.setState({ shown: true })
  }

  close = () => {
    this.setState({ shown: false })
  }

  render() {
    return (
      <div>
        <button onClick={this.open}> Open Modal</button>
	<button onClick={this.close}> Close Modal</button>
	<ConcreteModal show={this.state.shown} onHide={this.close} />
      </div>
    );
  }
}
```

Similar pattern by React Modal:
https://github.com/reactjs/react-modal

**Comment by detrohutt** [comment]
@krvajal I'm closing this because I believe @hedgerh adequately answered your question. If this is not the case, let me know and I can reopen the issue. Thanks.
