### ISSUE TITLE
What learning subscription service is most worth my money?

### ISSUE THREAD

**Issue by ChapmanJeff** [kentcdodds/ama#422]
Hey Kent, I'm debating buying a membership to a learning service and I am wondering which one you recommend. Egghead.io, pluralsight, front-end masters, etc. I am a full stack developer but want to deepen my javascript/react skills in particular. Also what platform do you contribute to most?

Thanks, Jeff

**Comment by kentcdodds** [comment]
Hi @ChapmanJeff!

I contribute most to egghead.io and plan on keeping most of my contributions there. If you can only subscribe to one, I recommend that one be [egghead.io](https://egghead.io/pricing).

Good luck!
