### ISSUE TITLE
Testing a connected component by doing a provider or mocking the connect

### ISSUE THREAD

**Issue by mcrowder65** [kentcdodds/ama#429]
Hey Kent, Thanks for reading this question.. I have gotten *a lot* of jest help from you, and even attended one of your react trainings virtually!

I have recently started working on a React Native application, and so there are some subtle differences between React and React Native... specifically with testing.

In my previous project, when I would want to test a component that was wrapped via react-redux's connect method, I would just mount the component with Enzyme using `mount(MyComponent.WrappedComponent)`, and that would render the inner component.

Some people have said that in order to test the component in isolation, just export the component individually, and do the default export at the bottom

See:

```jsx
import React from "react";
// Export right here!!
export class MyComponent extends React.Component {
  render() {
    return (...)
  }
}

export default hocWrapper(MyComponent)

```
But i think this is a huge 🤦‍♂️.... Manipulating the source code to help test the component? That seems wrong to me for some reason...

A solution to test it could be, since most of the HOC wrappers utilize context, is to wrap the component in a Provider while testing, but then, you have to wrap the component in a Provider while testing... Which, all I want to do is to test the component in isolation!!

Another solution I found, was setting the static `displayName` property and exporting it and using `.find(displayNameValue)` with enzyme to find the component in the tree.. But this felt the same as just exporting the component. 

And then I realized that I could mock the actual hocWrapper function!!

So I created a `__mock__/node-module-library-name.js` file, and I just mocked the function so that it returns the original Component with absolutely no changes... This way, the component can be tested in isolation with no provider being wrapped, and no displayName or exporting the non-connected component.

I wanted to get your thoughts on this, if I am crazy, if you need more clarification on anything, please ask :) thanks man!!

**Comment by kentcdodds** [comment]
If you're going to test your component in isolation of the HOC, then your solution is superb. I personally don't have too much trouble with exporting the component for testing. But I generally will test the wrapped component as it is rather than attempting to side-step reality by making a mock or exporting the wrapped component. Checkout the [react-testing-library-examples](https://codesandbox.io/s/github/kentcdodds/react-testing-library-examples) for more on this.

Good luck!

**Comment by mcrowder65** [comment]
Thank you Kent!
