### ISSUE TITLE
What is your opinion on using Cypress for integration tests

### ISSUE THREAD

**Issue by rbrtsmith** [kentcdodds/ama#430]
Recently we've been spiking out the idea of writing our integration tests using Cypress - having all service call responses mocked out.
The idea was to allow us to deliver upcoming features much faster with tests that cover behaviours from a users perspective (In the browser).
We've found we'd be able to ship with confidence and easily refactor with the tests aiding that instead of hindering (Our older test suite hindered as much as it helped).

It seems that scalability hasn't been a big issue thus far due to the responses all being mocked — This also makes it super easy to setup certain scenarios like error handling etc. On top of this we've been able to partition the tests using Docker containers to allow suites to run in parallel.

So I'm starting to question how valuable is it to test React component trees directly Vs doing the integration level entirely in Cypress? I would still look to use Jest to test shared utility functions and those that warrant a unit-test.

My question is Kent, what is your opinion on this testing strategy.  Do you think it has merit and what would you say are the potential issues that could arise from this approach.

Thanks 😄

**Comment by kentcdodds** [comment]
Hi! I'm afraid I don't have time to give a super solid answer to all my open questions right now, so I just went through and answered all my AMA questions in the form of a video: https://www.youtube.com/watch?v=y23g8L8UtoQ&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

A few things that folks can do to help make things better for others reading the questions and answers:

1. Link to when I start answering the question. Add `&t=xxmxxs` to the end of the URL like this: https://www.youtube.com/watch?v=y23g8L8UtoQ&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u&t=2m5s
2. Comment with links I referenced
3. Summarize what I talk about

Thanks!

**Comment by detrohutt** [comment]
Answer starts at [21:00](https://youtu.be/y23g8L8UtoQ?t=21m).

Kent prefers Cypress for end-to-end tests but uses Jest for integration tests because he prefers the features it offers like better mocking capabilities, really fast watch mode and ability to run tests only for files that have changed.
