### ISSUE TITLE
Choosing source of Eslint rules 

### ISSUE THREAD

**Issue by nellysattari** [kentcdodds/ama#436]
Which extension would you recommend for Eslint rules to be extended!   

> Airbnb? Google? standard?

Is it just a matter of preference? or different characteristics?  

Thanks

**Comment by hedgerh** [comment]
Not Kent, but figured I could answer this one.  Preference, and whatever has the most useful rules in it to you.  I don't know the exact rules used in airbnb/google/standard, but the other day I found out Airbnb's has accessibility linting (jsx-a11y, I believe?).  Not sure if the others also have those rules.  If accessibility is important to you, that may be something to look for in a config.

My personal preference is to lean towards configs that mostly have rules that can be autofixed and requires as little thought as possible to get together.  You should check out [prettier](https://prettier.io/) if you haven't heard of it before.  It's an opinionated set of linting rules that are all autofixable.  Something like that with a few other rules like no unused vars, along with accessibility linting, would be ideal for me personally.

**Comment by nellysattari** [comment]
Great answer @hedgerh  appreciated. 
accessibility linting  is really interesting and I should to read more about it.

**Comment by hedgerh** [comment]
@nellysattari yeah.  i haven't had the chance to actually work with it yet.  going to set it up at work tomorrow as an extra tool in our accessibility workflow.

https://www.npmjs.com/package/eslint-plugin-jsx-a11y

**Comment by kentcdodds** [comment]
Hi! I'm afraid I don't have time to give a super solid answer to all my open questions right now, so I just went through and answered all my AMA questions in the form of a video: https://www.youtube.com/watch?v=y23g8L8UtoQ&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

A few things that folks can do to help make things better for others reading the questions and answers:

1. Link to when I start answering the question. Add `&t=xxmxxs` to the end of the URL like this: https://www.youtube.com/watch?v=y23g8L8UtoQ&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u&t=2m5s
2. Comment with links I referenced
3. Summarize what I talk about

Thanks!

**Comment by detrohutt** [comment]
Answer starts at [31:52](https://youtu.be/y23g8L8UtoQ?t=31m52s).

**Comment by nellysattari** [comment]
Appreciated @kentcdodds  you are amazing @detrohutt :)

**Comment by kentcdodds** [comment]
> you are amazing @detrohutt

I quite agree!

**Comment by detrohutt** [comment]
😊YOU TWO are awesome!
