### ISSUE TITLE
What do you use to take notes for work as well as personal tasks ?

### ISSUE THREAD

**Issue by smitthakkar1** [kentcdodds/ama#442]
I've been poor at taking study notes from childhood. But now I have started my first full-time job as a software engineer and I realized that it's very important to take notes of tasks that you need to do.

For e.g., during the meeting, someone assigns some task like follow up with someone or someone mentioned something which is important for you. Which tool/software do you use to take notes?

**Comment by kentcdodds** [comment]
Hi! I'm afraid I don't have time to give a super solid answer to all my open questions right now, so I just went through and answered all my AMA questions in the form of a video: https://www.youtube.com/watch?v=4Yq6PO0r-fU&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

A few things that folks can do to help make things better for others reading the questions and answers:

1. Link to when I start answering the question. Add `&t=xxmxxs` to the end of the URL like this: https://www.youtube.com/watch?v=4Yq6PO0r-fU&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u&t=2m5s
2. Comment with links I referenced
3. Summarize what I talk about

Thanks!
