### ISSUE TITLE
How do you measure personal growth?

### ISSUE THREAD

**Issue by siddharthkp** [kentcdodds/ama#443]
In the context of learning, building things, your personal goals, etc.

This is a question that I've been thinking about. Aaaand I wanted to get your views on it 😄

**Comment by kentcdodds** [comment]
Hi! I'm afraid I don't have time to give a super solid answer to all my open questions right now, so I just went through and answered all my AMA questions in the form of a video: https://www.youtube.com/watch?v=4Yq6PO0r-fU&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

A few things that folks can do to help make things better for others reading the questions and answers:

1. Link to when I start answering the question. Add `&t=xxmxxs` to the end of the URL like this: https://www.youtube.com/watch?v=4Yq6PO0r-fU&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u&t=2m5s
2. Comment with links I referenced
3. Summarize what I talk about

Thanks!

**Comment by ivosantiago** [comment]
https://youtu.be/4Yq6PO0r-fU?t=3m29s
