### ISSUE TITLE
Do you think HOC's are good use case for fetching data?

### ISSUE THREAD

**Issue by dadamssg** [kentcdodds/ama#445]
I have no control over the backend api on the app that i'm currently developing. Many of the same endpoints are used in multiple presentations(map, chart, table, etc). Many components I develop force me to request 10+ endpoints to get the required data.

We're using redux and redux-thunk. My container components ended up looking like this(but worse with more fetches): 

```jsx
class Dashboard extends Component {
  componentDidMount () {
    const {loginId, companyId} = this.props
    this.props.fetchTickets(loginId, companyId)
    this.props.fetchTasks(loginId, companyId)
    this.props.fetchOpportunities(loginId)
  }

  componentDidUpdate (prevProps) {
    if (!prevProps.loginId !== this.props.loginId) {
      this.props.fetchTickets(loginId, companyId)
      this.props.fetchTasks(loginId, companyId)
      this.props.fetchOpportunities(loginId)
    }
    if (!prevProps.companyId !== this.props.companyId) {
      this.props.fetchTickets(loginId, companyId)
      this.props.fetchTasks(loginId, companyId)
    }
  }
  render () {
    // put it all in a table
  }
}
```

I came up with a HOC that I think will be useful for eliminating some of the boilerplate for reusing the fetch code. It looks like this:

```js
import {compose} from 'redux'
import {connect} from 'react-redux'
import * as actions from '../redux/actions'
import {dashboardSelector} from '../redux/selectors' 
import Dashboard from './Dashboard'

const enhance = compose(
  connect(dashboardSelector),
  dispatchOnProps(
    props => actions.fetchTickets(props.loginId, props.companyId),
    {loginId: PropTypes.string, companyId: PropTypes.string}
  ),
  dispatchOnProps(
    props => actions.fetchTasks(props.loginId, props.companyId),
    {loginId: PropTypes.string, companyId: PropTypes.string}
  ),
  dispatchOnProps(
    props => actions.fetchOpportunities(props.loginId),
    {loginId: PropTypes.string}
  )
)

export default enhance(Dashboard)
```

The `dispatchOnProps` is the HOC that will fire that action on component mount and if any of the props it cares about changes(`loginId` and `companyId` in this example). 

I like this because it keeps the data fetching closer to where the `connect()`ing is happening and I can potentially reuse these as preconfigured HOCs.

```js
// src/redux/HOC
import * as actions from '../redux/actions'
import dispatchOnProps from './dispatchOnProps'

export const fetchTickets = dispatchOnProps(
  props => actions.fetchTickets(props.loginId, props.companyId),
  {loginId: PropTypes.string, companyId: PropTypes.string}
)

export const fetchTasks = dispatchOnProps(
  props => actions.fetchTasks(props.loginId, props.companyId),
  {loginId: PropTypes.string, companyId: PropTypes.string}
)

export const fetchOpportunities = dispatchOnProps(
  props => actions.fetchOpportunities(props.loginId),
  {loginId: PropTypes.string}
)

// elsewhere
import {compose} from 'redux'
import {connect} from 'react-redux'
import {dashboardSelector} from '../redux/selectors' 
import * as HOC from '../redux/HOC'
import Dashboard from './Dashboard'

const enhance = compose(
  connect(dashboardSelector),
  HOC.fetchTickets,
  HOC.fetchTasks,
  HOC.fetchOpportunities
)

export default enhance(Dashboard)
```

I'm scared to start implementing this pattern throughout our apps just because I've never seen it done before. It seems like a big departure from what is typical. That might just be because most devs have influence over their backends or maybe I'm just not looking hard enough.

Do you think this is a good way to cleanup/reuse fetch code or does this look like I'm going to be shooting myself in the foot? Thanks!

Source of [`dispatchOnProps`](https://gist.github.com/dadamssg/d8b500a05e13b16275483bd1ad3f1be4#file-dispatchonprops-jsx)

**Comment by kentcdodds** [comment]
Hi! I'm afraid I don't have time to give a super solid answer to all my open questions right now, so I just went through and answered all my AMA questions in the form of a video: https://www.youtube.com/watch?v=4Yq6PO0r-fU&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

A few things that folks can do to help make things better for others reading the questions and answers:

1. Link to when I start answering the question. Add `&t=xxmxxs` to the end of the URL like this: https://www.youtube.com/watch?v=4Yq6PO0r-fU&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u&t=2m5s
2. Comment with links I referenced
3. Summarize what I talk about

Thanks!
