### ISSUE TITLE
What is your opinion on testing Redux actions, reducers and selectors in isolation

### ISSUE THREAD

**Issue by rbrtsmith** [kentcdodds/ama#447]
Hi Kent 👋 

So there's been some ongoing debate on the back of a little [demo app](https://github.com/rbrtsmith/react-tdd) I've built that shows how you can test a Redux connected component and get full coverage + confidence without directly testing the reducers, actions or selectors.

I'm of the opinion that the fact you have selectors and actions - even redux existing is an implementation detail - the user does not care if your app uses Redux.  So shouldn't you tests be isolated (as much as possible) from this implementation detail.  It would also make it a smoother process if you were to move away from Redux onto something else… say React Apollo 🎉 

I get that when implementing TDD your tests can help you write these functions - but after the feature has been built I don't think these tests carry any value and should be deleted.

I also think if a selector for example is merging together multiple sections of state and doing a complex transformation of that data then having some tests against that may carry more value.

I'd like to get your thoughts on this.  Thanks!

**Comment by kentcdodds** [comment]
Hi @rbrtsmith!

I answered your question via DevTipsWithKent: https://www.youtube.com/watch?v=h7ukDItVN_o&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

In summary: I think you're right. This is what I recommend as well most of the time :+1:

**Comment by blocka** [comment]
In my opinion (which is of course just my opinion), redux is in a different ball game then react router, or even apollo.

I like to say there are two approaches to UI development, the top-down approach, where you start with the UI, and work backward. You're basically selling yourself into a UI library at this point. Building a React app, or a Vue app, etc. 

Then there's a bottom-up approach. You design your app around your business logic, and it's state. The actual UI library is not terribly important...it is just one way of expressing your state logically. When you use redux, this is the mode that you're in. If you started from the top and then decided to add redux in later, you _probably_ added it in to solve the "prop" drilling problem, and you're doing something wrong.

In top-down approach, it totally makes sense that you want to spend most of your time UI testing. "Doing what the user does". 

In the bottom-up approach, you are basically working with a state management library, and writing business logic. The _UI_ is the implementation detail. Therefore it makes more sense to spend more time writing tests against your business logic, most of which is going to be unit tests against pure functions, plus integration tests to make sure you've hooked up middleware correctly, and, finally, a few UI integration tests to make sure you've glued everything together (ie., passed in the correct actions and selectors to react-redux). Now you have solid business logic, and you can share this logic across different UI libraries (perhaps react + react native).

So to reiterate, in my opinion, if you are using redux (and using it as it is meant to be used), then it makes total sense to be testing these things in isolation.
