### ISSUE TITLE
what is the best and efficient approach to write css in react?

### ISSUE THREAD

**Issue by hamidpouladi** [kentcdodds/ama#450]
hi kent. thank you very much for sharing your valuable knowledge. my question is what is the best way to write css  in react components?

**Comment by kentcdodds** [comment]
Hi! I'm afraid I don't have time to give a super solid answer to all my open questions right now, so I just went through and answered all my AMA questions in the form of a video: https://www.youtube.com/watch?v=4Yq6PO0r-fU&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

A few things that folks can do to help make things better for others reading the questions and answers:

1. Link to when I start answering the question. Add `&t=xxmxxs` to the end of the URL like this: https://www.youtube.com/watch?v=4Yq6PO0r-fU&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u&t=2m5s
2. Comment with links I referenced
3. Summarize what I talk about

Thanks!

**Comment by jLouzado** [comment]
- Answer starts at [20:53](https://youtu.be/4Yq6PO0r-fU?t=20m53s)
- [emotion.sh](https://emotion.sh/)
