### ISSUE TITLE
Must have apps for programming or productivity in general

### ISSUE THREAD

**Issue by quietbits** [kentcdodds/ama#451]

**Comment by kentcdodds** [comment]
Hi! I'm afraid I don't have time to give a super solid answer to all my open questions right now, so I just went through and answered all my AMA questions in the form of a video: https://www.youtube.com/watch?v=4Yq6PO0r-fU&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

A few things that folks can do to help make things better for others reading the questions and answers:

1. Link to when I start answering the question. Add `&t=xxmxxs` to the end of the URL like this: https://www.youtube.com/watch?v=4Yq6PO0r-fU&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u&t=2m5s
2. Comment with links I referenced
3. Summarize what I talk about

Thanks!

**Comment by jakehansen** [comment]
The extension for managing other extensions is [Extension Manager](https://chrome.google.com/webstore/detail/extension-manager/gjldcdngmdknpinoemndlidpcabkggco?hl=en).

**Comment by kartik2406** [comment]
Link: https://youtu.be/4Yq6PO0r-fU?list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u&t=1444
