### ISSUE TITLE
I have created this React package. Any thoughts?

### ISSUE THREAD

**Issue by krzystof** [kentcdodds/ama#453]
Hi Kent,
I am sorry if this is not the kind of question you expect. But I have created a npm package to quickly scaffold a new React component with a bunch of tests (using your library).
It would be awesome to have your thoughts on this.
https://github.com/krzystof/stub-react-component
Thanks

**Comment by kentcdodds** [comment]
Hi! I'm afraid I don't have time to give a super solid answer to all my open questions right now, so I just went through and answered all my AMA questions in the form of a video: https://www.youtube.com/watch?v=4Yq6PO0r-fU&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

A few things that folks can do to help make things better for others reading the questions and answers:

1. Link to when I start answering the question. Add `&t=xxmxxs` to the end of the URL like this: https://www.youtube.com/watch?v=4Yq6PO0r-fU&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u&t=2m5s
2. Comment with links I referenced
3. Summarize what I talk about

Thanks!
