### ISSUE TITLE
What's your motivation for producing content?

### ISSUE THREAD

**Issue by CodingItWrong** [kentcdodds/ama#454]
If you don’t mind me asking, what’s your motivation for doing so much speaking and producing so much content? I’ve noticed that most folks doing so are either in devrel or are looking to start a teaching business. I don’t want to do either of those but I *am* trying to produce more content, because it’s helping folks and it’s content I wish existed. But I’m starting to wonder if I’m crazy trying to do it without it being a business! =]

**Comment by kentcdodds** [comment]
Hi! I'm afraid I don't have time to give a super solid answer to all my open questions right now, so I just went through and answered all my AMA questions in the form of a video: https://www.youtube.com/watch?v=4Yq6PO0r-fU&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

A few things that folks can do to help make things better for others reading the questions and answers:

1. Link to when I start answering the question. Add `&t=xxmxxs` to the end of the URL like this: https://www.youtube.com/watch?v=4Yq6PO0r-fU&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u&t=2m5s
2. Comment with links I referenced
3. Summarize what I talk about

Thanks!

**Comment by CodingItWrong** [comment]
Answer: https://youtu.be/4Yq6PO0r-fU?t=35m26s

tl;dw Kent said that he mainly creates content because it's fun and because it's how he learns best. (This parallels an earlier question where he said that the way he continues to learn is by building things and teaching about them.) He also said it's always possible he may start a teaching business in the future, in which case this prep would help.

Thanks for the answer, Kent!
