### ISSUE TITLE
How do motivate others to learn in your work projects?

### ISSUE THREAD

**Issue by adtm** [kentcdodds/ama#455]
This question is out of curiosity how can you motivate others to try more advanced techniques - f.e try various patterns, f.e: React patterns like `render-props` or `prop collection`. I understand that you can motivate doing it yourself and showing it others.

But usually, people do their own way and only when you say a comment take notice.

**Comment by kentcdodds** [comment]
Hi! I'm afraid I don't have time to give a super solid answer to all my open questions right now, so I just went through and answered all my AMA questions in the form of a video: https://www.youtube.com/watch?v=4Yq6PO0r-fU&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

A few things that folks can do to help make things better for others reading the questions and answers:

1. Link to when I start answering the question. Add `&t=xxmxxs` to the end of the URL like this: https://www.youtube.com/watch?v=4Yq6PO0r-fU&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u&t=2m5s
2. Comment with links I referenced
3. Summarize what I talk about

Thanks!
