### ISSUE TITLE
What makes you continue being a JavaScripter?

### ISSUE THREAD

**Issue by thelambdaparty** [kentcdodds/ama#46]
There are many other languages/technologies available for web/mobile/desktop development, but what about JavaScript makes you continue to invest your skills and time in it?

**Comment by kentcdodds** [comment]
Thanks for the question @thelambdaparty! As @brendaneich says: "Always bet on JavaScript." JavaScript may not be around for my entire lifetime, but right now it is the most ubiquitous language out there and it's the first one that I've managed to learn to the level I have. JavaScript is extremely approachable and I just really enjoy developing in JavaScript despite [its flaws/weirdness](https://www.destroyallsoftware.com/talks/wat).

At the same time, I'm really looking forward to what [Web Assembly](http://www.2ality.com/2015/06/web-assembly.html) could mean for the web platform. I'm also really excited about [Elm](http://elm-lang.org/) (a compile-to-js language) by @evancz. Going to the first [Elm meetup](http://www.meetup.com/Utah-Elm-Users/) here in Utah in December and I'm super stoked about it (even re-listened to [the JavaScript Jabber episode](https://devchat.tv/js-jabber/175-jsj-elm-with-evan-czaplicki-and-richard-feldman) yesterday).

In the end, I'm married and have three kids. We're a happy family and we all like to eat. So we eat JavaScript for breakfast, lunch, and dinner. So long as JavaScript will bring home the bacon better than anything else I can do, I'll keep learning and developing JavaScript :D

Thanks again for the question! Also, don't forget that [JavaScript Air](http://javascriptair.com/) starts soon :D Tune in December 9th!
