### ISSUE TITLE
Could you please speak at React Summit 2018 happening in Nigeria?

### ISSUE THREAD

**Issue by innocentamadi** [kentcdodds/ama#460]
I (and several other of my colleagues) have been through your course on Advanced Design Patterns with React in frontendmasters.com. We would love it if you could hold a talk about it.

![](React Summit 2018) is a community driven event aimed at bringing together frontend developers who use React/Javascript or are hoping to learn more about it so as to foster deep, valuable discussions around what’s new, what’s possible and best practices.

The conference expects about 600 developers in attendance and is scheduled to hold on the 19th and 20th of October. It is organized by Facebook Developer Circles Lagos and is completely free for attendees.

We understand it might be too late to ask you to be here physically. A call-in on zoom is equally effective (as we have found with talks from Sarah Drasner, Brian Holt, etc in our latest @concatenteconf).

I'll be happy to answer any questions you might have. Thank you

**Comment by kentcdodds** [comment]
Hi @innocentamadi! Thank you so much for reaching out to me!

I thought that concatenateconf was awesome and I'd be honored to take part in the React Summit! You're correct that it wont be possible for me to attend in person, but I would be happy to join the conference remotely! Count me in! Please email me any details: kent@doddsfamily.us

Thanks again! I'm honored :)
