### ISSUE TITLE
Another one with a Library :P (Render props, Context API, and a lot of Thanks)

### ISSUE THREAD

**Issue by Thram** [kentcdodds/ama#463]
Hey Kent, big fan here,
I've been following you for a while through egghead and the newsletter. 
I learned a lot thanks to you and your awesome content. I really appreciate it.
Two of those things were the `Render props pattern` and the new `Context API`, and I love them both. 
I've been experimenting with them since, in some projects.
A couple of days ago I saw you mentioning, in one of your videos (I think it was a DevTip),[@reactions/component](https://www.npmjs.com/package/@reactions/component) and I really liked the idea. I also read your newsletter about Application State Management and I ended up mixing both ideas in a library.

I think is the type of library you would enjoy to play with. I hope you do and if you have some free feedback is always appreciated. [thram-stateless](https://www.npmjs.com/package/thram-stateless) (I ran out of ideas for the name)

Thanks and have a happy life 😃

**Comment by kentcdodds** [comment]
Hi @Thram!

To be clear, @reactions/component has moved to [@reach/component-component](https://ui.reach.tech/component-component) :)

Your library looks interesting. My first impression though is that it seems like unnecessary abstraction. I feel like @reach/component-component is flexible enough for me to do what I'd like.

That said, mixing it with context is interesting. If it's working for you, then I'm glad! Good luck with it!
