### ISSUE TITLE
I want to contribute to OS but I don't know where to start

### ISSUE THREAD

**Issue by JeffBaumgardt** [kentcdodds/ama#465]
Let me start off with I'm not a good technical writer so my documentation skills are very lacking, so it's best for me to stay away from docs unless they are non-existent.

I've been wanting to get more involved in contributing and I try to answer questions in Discord the best I can, when I can.

Where should I start?

**Comment by d3lm** [comment]
Are you looking for contributing to a specific library or a library written for a specific framework? There are many open source projects that are happy to get you started to contribute to their project. 

If you know Angular for example, [MachineLabs](https://github.com/machinelabs/machinelabs) would be a great project. I have also created a library [ngx-drag-to-select](https://github.com/d3lm/ngx-drag-to-select), also written in Angular, that has some open issues you could work on. There's plenty possibilities. My advice is to reach out to one of the maintainers of a library of choice and ask how you can contribute. They will be more than happy to help you, at least I would be, and I am also super grateful for all contributions.

My two cents to this question.

**Comment by kentcdodds** [comment]
Hi Jeff!

Have you read my blog post to answer this question? http://kcd.im/what-oss

Feel free to ask any follow up questions you have.
