### ISSUE TITLE
What do you think about "render prop data source components"?

### ISSUE THREAD

**Issue by kevinwolfcr** [kentcdodds/ama#467]
Hi Kent!

As I am always trying to update and optimize my architecture, I came up with this pattern that I call "render prop data source components". It is based on the container/presentational pattern but using render props.

Basically I can have a "TodoData" component and have the data/methods on its render function, with an use case like this:

```jsx
<TodoData>
{({ todos, addTodo, removeTodo }) => (<div>Presentational component</div>)}
</TodoData>
```

You can also pass callbacks like `<TodoData onTodoAdded onTodoRemoved />`.

And we can make use of composition thanks to libraries like [react-adopt](https://github.com/pedronauck/react-adopt).

I think this can be a powerful pattern because you can make use of all the component lifecycle on your "data source component", for refetching, polling, etc.

What do you think?

**Comment by kentcdodds** [comment]
Yup, I love it <3 These patterns are a great mechanism for separation of concerns 👌

**Comment by kevinwolfcr** [comment]
Just to follow up. Have you seen any library implementing this pattern?

**Comment by alexkrolick** [comment]
There are several: https://github.com/jxom/awesome-react-headless-components
