### ISSUE TITLE
Is a tree of React Elements returned by the `render` function of components referred to as Virtual DOM in React

### ISSUE THREAD

**Issue by react-datagrid** [kentcdodds/ama#469]
Is a tree of React Elements returned by the `render` function of components referred to as Virtual DOM in React?

**Comment by hedgerh** [comment]
React's Virtual DOM is made up of React elements.

> An element is a plain object describing a component instance or DOM node and its desired properties. [[source]](https://reactjs.org/blog/2015/12/18/react-components-elements-and-instances.html#elements-describe-the-tree)

The virtual DOM describes the entire tree of React elements that you `render` from all of the components in your app.

Here was a good article I found that explains the virtual DOM: http://reactkungfu.com/2015/10/the-difference-between-virtual-dom-and-dom/

It's also interesting to read the code overview/implementation notes for React to get a deeper understanding of how it works.  I think the Implementation Notes describe what you're interested in the most:

Implementation Notes - https://reactjs.org/docs/implementation-notes.html

Codebase Overview - https://reactjs.org/docs/codebase-overview.html

Hope that helps.

**Comment by react-datagrid** [comment]
@hedgerh , thanks a lot for your elaborate answer! Good luck
