### ISSUE TITLE
How did you start teaching on egghead and frontend masters?

### ISSUE THREAD

**Issue by jsjoeio** [kentcdodds/ama#472]
I looked through the closed issues and didn't see this (forgive me if I missed it). I'm interested in teaching others (through tutorials & courses). I started a YouTube channel and I've also written a few Medium articles. 

How did you end up teaching and creating courses for both [egghead.io](egghead.io) and [Frontend Masters](https://frontendmasters.com/)?

**Comment by kentcdodds** [comment]
Hi @jsjoeio!

I just wrote about this in my newsletter (which I think you're subscribed to): https://buttondown.email/kentcdodds/archive/03761505-8609-404c-a5b7-5367013292bf

That will hit my blog in 1.5 weeks :)

I hope that helps. (Also, welcome to Egghead 😉)
