### ISSUE TITLE
Using render props in controlled components (what to pass in render functions)?

### ISSUE THREAD

**Issue by bananatranada** [kentcdodds/ama#476]
Hi Kent, love what you're doing for the community.

I ran into a slightly strange situation with render props when using it inside a controlled component.

For stateful components, it makes sense to pass in whatever state that may be useful for render props because they're private. However, in controlled components, I'm not sure if I should provide anything that they themselves already have. That is, a prop they passed in. Do I need to pass that back to the developer? I understand that for calculations or modifications we definitely should. But for everything else that they already have, what should we do?

I ask because I like to create these so called helper render props, so developers don't always have to provide them. There are cases where they don't necessarily know the props that the container component passed in.

Thanks!

**Comment by kentcdodds** [comment]
Hi @bananatranada,

In downshift we do provide some things to the children callback that are given to us from the developer just as a convenience. This is especially useful if someone refactors their callback to exist outside the closure of their component's render method. It's mostly upside with very little downside. So I don't mind doing it. I'd recommend it :)
