### ISSUE TITLE
How do you start your day as a developer? 

### ISSUE THREAD

**Issue by LBWright** [kentcdodds/ama#478]
When I start work in the morning, I just don't have a good routine.
Do you do some reading first? Do you jump immediately into code? How do you sit down and focus when you first start your day?

**Comment by kentcdodds** [comment]
Hi @LBWright,

I hit my email/twitter/etc. and help people in open/inner source projects I'm leading. I actually spend a lot of my day doing that. But that's how I get started. Eventually I get to actually code some stuff up, but I spend a lot of time helping other people be productive.
