### ISSUE TITLE
How to use the SPA concept with server side programming languages like Java.

### ISSUE THREAD

**Issue by SanthoshRaju91** [kentcdodds/ama#479]
Hello @kentcdodds 

Before submitting this question, I read via the issue list to check whether this question is not duplicated. And in the process, I read some of your amazing answers and spent some time in couple of Youtube videos which you have linked. 

I just want to say, thank you so much for everything that you do, I have thanked you many a times via twitter, whenever you release an awesome newsletter or tweet something that is really helpful. 
Sorry Sir, I just couldn't stop thanking you enough for the amazing things that you do for the community.

My question is about using React with a server side programming languages like Java / SFDC / SAP. 

I work in a consulting firm and usually the client would send out a requirement to build an application using Java / SFDC / SAP, which limits us to bring some of the useful feature in modern Web application features like code splitting or least using eslint to these projects.

So we are trying to figure out a way of using React with programming languages, but we couldn't figure how we can bind the model (Java based variables in JSP syntax) to view in React. So we have thought of an approach of using the local storage to store all of the models and reference them back in React view.

It would be really helpful if you could share some of your thoughts/advice on this, or if you have/know of some resources/standards that is being already used to build applications using such tech stack.

Again thank you in advance for answering this question.

**Comment by kentcdodds** [comment]
Hi @SanthoshRaju91,

I'm afraid that my experience with any other language/platform other than JavaScript and Node is extremely limited. Sorry. Good luck.

**Comment by santhoshRaju9122** [comment]
No problem @kentcdodds, thank you for responding.
