### ISSUE TITLE
How many hours you build a program in a one day?

### ISSUE THREAD

**Issue by dikiaap** [kentcdodds/ama#48]

**Comment by kentcdodds** [comment]
Hi! Thanks for the question. Just to make sure I understand correctly, are you asking how many hours I spend programming a day?

**Comment by dikiaap** [comment]
yeah :smiley:

**Comment by kentcdodds** [comment]
Depends on the day. For example, my weekends are mostly spent with my family so I don't get a lot of coding done most of the time on Saturdays (2-3 hours max). I'm an active [Latter-day Saint](https://mormon.org) (aka Mormon), so my Sundays I generally don't spend much of any time coding.

During the week, I generally spend at least 5-6 hours coding at work (other time is spent in meetings and other activities). Then in the evenings I'll put in another 2-5 hours depending on the night.

If I have a side-project, those numbers are much bigger. But that hopefully answers your question. Thanks for the question!

**Comment by dikiaap** [comment]
Inspire to split time. Thanks for description and answer my question.
