### ISSUE TITLE
Code sharing between projects, how to manage?

### ISSUE THREAD

**Issue by weyert** [kentcdodds/ama#480]
First of all I would like to thank you for all your insightful videos and your projects such as testing libraries. I am day-by-day extending the test coverage of my project. Thank you, Kent.

I am currently working on a charity project were I am having two React/CRA projects which I would like to share code with each other. For example, I would like to share components such as a component which renders details of a profile. The main reason why I would like to share the code is to ensure that both CRA applications will display the same details.

If I understand it correctly, I could make a npm package and use it. Only this sounds really inconvenient to continuously push a new version to the git repo, run yarn install while working on the project. How do you share code between projects? How do you handle this while developing approach? Do you have any tips regarding this? 

Oh yeah, I prefer to not publish the npm package in the registry as I think it's not useful for other people :)

**Comment by hedgerh** [comment]
Publishing code to npm is one way to handle it.  It does add extra overhead, but you could possibly set up tooling to automate a decent amount of it.  I can go into this more if you'd like.

The second approach, if these are part of the same charity project, would be to create a "monorepo," where both projects live in the same git repo.  You'll be able to import directly from a common folder in the project.  You can also set them up to share the same deployment pipeline.

Check out [lerna](https://github.com/lerna/lerna) and google around for monorepos.  Lerna links to [this babel writeup about why it uses a monorepo structure](https://github.com/babel/babel/blob/master/doc/design/monorepo.md).

Maybe Kent or someone else has a better writeup on monorepos.

**Comment by weyert** [comment]
Thank you, @hedgerh. Yes, the two applications are part of the same project. Maybe I should get in a bit more details what my exact problem. I am having a client facing CRA application which has some components for displaying profile details and some order like details. My second CRA application is basically the dashboard of administrative application for the team at the charity. 

I would like to reuse the components for displaying an order or a profile from the client facing application to avoid code duplication. That's why I would like to share this components between these two projects, currently I am having them in separated git repositories on BitBucket.

I am not sure if you want to have dashboard and the 'frontend'/client facing app all in the same mono repo?

**Comment by alanrubin** [comment]
Hi @weyert a monorepo normally uses the same git repository to store all the projects in a standard folder structure so to be able to share code between them. I had this same question, tried monorepo with lerna as well but ended up going with "yarn workspaces" which is a far simpler solution to the issue with much learning. You can google for it, the idea is that you have packages folders where you can store your projects under the same git repository and is able to reference them between one and the other. There are another solutions to the problem as well and there are a couple of startups working on it - for example https://bitsrc.io/.

In your case it seems "yarn workspaces" is the easiest way to start with.

**Comment by kentcdodds** [comment]
Hi @weyert. Yeah, this is tricky. I'd suggest a monorepo, though I've heard those are tricky with CRA but I've never tried it.

Good luck.
