### ISSUE TITLE
What tips would you give for an effective pair programming session with an intern or anyone?

### ISSUE THREAD

**Issue by ankurkaushal** [kentcdodds/ama#481]
One of the things we don't really often do with our intern on the team is have more frequent pair programming sessions. So today, I scheduled a weekly pair programming session with him that would last about 30 minutes. As someone who doesn't really do pair programming sessions that often, what suggestions would you give? Especially with an intern, what should I keep in mind?

**Comment by kentcdodds** [comment]
Hi @ankurkaushal,

Honestly, I don't do pair programming all that often. But I'd say it's probably a good idea to let them drive as much as possible and don't be afraid of silence. Let them take time to process what it is you're doing. Be open to questions. You'll feel like they're slowing you down a bit, but they're probably also helping you focus and they can challenge your assumptions in ways that make you question your abstractions in a good way.

You probably already did the pair programming session, but I hope this helps anyone reading.
