### ISSUE TITLE
How do you & Airbnb keep your mobile app as simple as it is when business grows?

### ISSUE THREAD

**Issue by FateRiddle** [kentcdodds/ama#482]
Hi, you must be involved in the discussion of how Airbnb app looks and functions, thus I asked this question.

I'm working for a travel company Fliggy in China (so feel at ease, we won't cross path as competitor any time soon :D), and I always marvel at how simple Airbnb is.

Every app starts simple, but then gets complicated by the day, and almost all the travel/hotel apps in China look the same, complex and give me headaches.

But also I understand the reason behind it: 1. demands from users, and 2. everyone wants to start something, so they'll look good on KPI.

My questions are:
1. How do you think Airbnb manage to stay simple when company grows so big? And which do you think is the most crucial factor?
2. When and why do you turn down a demand, what is your principle here(be it from product manager, designer or user)?

p.s. If you don't care more questions, I've read article about airbnb giving up on RN, so have you thought about leaving Airbnb and join us in China? I mean, clearly you've got nothing to do now, right? 😄

**Comment by kentcdodds** [comment]
Hi @FateRiddle,
I actually don't work for Airbnb so I don't think I'm qualified to answer your question. Sorry.
