### ISSUE TITLE
How do you produce your live YouTube videos?

### ISSUE THREAD

**Issue by jchiatt** [kentcdodds/ama#487]
Hey Kent! I've been trying to figure out how you go live on YouTube and also have the pre-show music/splash screen. Can you point me to any tools you use to live stream? Thanks!

**Comment by artisologic** [comment]
I also wonder about this, especially about how you do to put your face video overlay on top?

**Comment by brentjanderson** [comment]
Wirecast is one of the best tools for this sort of thing, especially on Youtube. I don't know what Kent uses, but I have used this and it's fantastic: https://www.telestream.net/wirecastplay/landing.htm

That link is for their YouTube-only version ($10 to remove their watermark). Their more expensive variations are suitable for professional production.

**Comment by kentcdodds** [comment]
I've been using [OBS](https://obsproject.com/) for a few years and love it 💯

**Comment by kentcdodds** [comment]
Oh, and the pre-show splash screen was built in JS. I just recorded my screen for a few minutes with this as full-screen: https://codesandbox.io/s/z3nm3zyx

Then I added music by Ken Wheeler :)

**Comment by jchiatt** [comment]
Thanks Kent! Exactly what I was looking for.

**Comment by thall1961** [comment]
Me too!  Thanks!
