### ISSUE TITLE
3x Video Speed??

### ISSUE THREAD

**Issue by pertrai1** [kentcdodds/ama#490]
What do you use to watch videos at 3x speed? I tried video speed controller for Chrome but it is not working on any of the videos that I am watching

**Comment by egoarka** [comment]
this script works perfectly on any page having videos 
`document.querySelector('video').playbackRate = 3`

**Comment by pertrai1** [comment]
@egoarka I just tried that on frontendmasters course and the video could not keep up

**Comment by pertrai1** [comment]
@egoarka it is working now. 2.5 seems to be a good speed for my connection.

**Comment by kentcdodds** [comment]
What @egoarka showed is basically what I do. I also use https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk
