### ISSUE TITLE
Responsive design: Role of a designer and a developer

### ISSUE THREAD

**Issue by rajatvijay** [kentcdodds/ama#491]
So when we are making a new page from a design and the requirement is to make it work on both mobile and desktop screens, how do the designer and developer interact:

1. The designer gives 2 designs:
One for the `md` screen view
Second for the `xs` and `sm` screen view

2. The designer gives only 1 design and its the developer's job to make it work using "Responsive Web Design"

**Comment by hedgerh** [comment]
1 without a doubt.  I never follow this procedure, but your developers should be making things work in mobile from the start.  You will run into headaches if they don't consider the mobile design from the start.

Don't ever leave your developers to do design work, which is what you're doing when following path #2. It costs way more to have a developer spend 2-100 hours trying to figure out how to make something look versus having someone that is specifically trained to design UIs make it look the way it should.

Dream scenario: I get designs from a designer and develop the website without any guesswork, and with as little back and forth with the designer as possible.  You should strive for this, in my opinion.  I typically need to have a back and forth with the designer about behaviors of things, but I shouldn't be having to decide things like typographic hierarchy.

**Comment by kentcdodds** [comment]
I agree with @hedgerh here 👍
