### ISSUE TITLE
can you explain the 3 common build variations of libraries? 

### ISSUE THREAD

**Issue by dadamssg** [kentcdodds/ama#492]
The [3 common build variations](https://unpkg.com/downshift@2.2.3/dist/) being: 
- es
- commonjs
- umd

I understand the es build retains `import`/`export` syntax and is capable of being tree shaken. Useful for module bundlers(webpack, rollup). Use `module` in the `package.json` file for this build.

I understand commonjs uses `require()`, useful for when not using a module bundler(testing). Use `main` in the `package.json` file for this build. 

I understand umd supports commonjs and amd syntax. It can be used in the browser via `<script />` tag.

Why have both a umd build _and_ a commonjs build? Couldn't the umd build be used as the `main` in `package.json`? 

Can you demystify the purposes of each of these build variations?

**Comment by kentcdodds** [comment]
Hi @dadamssg :)

> Why have both a umd build and a commonjs build? Couldn't the umd build be used as the main in package.json?

Technically yes, but I figure since it's so easy to have both, may as well have both. The UMD is really only intended for use in the browser and the cjs is optimized for a CJS environment. 🤷‍♂️
