### ISSUE TITLE
Difference between 'End-to-end' and 'Integration' tests

### ISSUE THREAD

**Issue by brightpixels** [kentcdodds/ama#494]
Am confused by the difference between 'End-to-end' and 'Integration'. Sometimes I think they are being used interchangeably and sometimes I think they mean completely different things. For example, when taking about Cypress.io, it's presented  as an 'end-to-end' tool, but when you run the command 'cypress open', a folder called 'integration' is created with some examples that to me look like 'end-to-end' tests. So here am thinking it's must be used  interchangeably. However, when you are discussing the 'pyramid' or 'trophy' diagrams on how much tests to do for the various types of tests,  there is a separate labels for  'end-to-end' and 'integration' which makes me think they are two separate things. Am confused.

**Comment by cylim** [comment]
From my understanding,

End-to-End(E2E) Testing is UI testing that runs thru the services User Interface to perform every critical action(use case).

Integration Testing is testing between different services. e.g. Connection between API Server and App, Connection between all third-party services.

E2E can cover parts of the Integration Test.

**Comment by kentcdodds** [comment]
Hi @brightpixels,

I focus mostly on the UI, so when I'm talking about integration tests, I'm basically testing a component and I only mock HTTP requests and animation libraries. I leave everything else in there as-is. Including things like redux/react-router/etc.

With E2E I don't generally mock anything at all.

I hope that's helpful.

**Comment by kentcdodds** [comment]
Oh, and with the cypress thing, I actually don't like that they call that file integration and I rename it in [my course material](https://github.com/kentcdodds/jest-cypress-react-babel-webpack/blob/5fa4979c82f2139f998cdaffe68fba9ef1d11979/cypress.json#L3) because Cypress tests are e2e for me.
