### ISSUE TITLE
Render props and the tradeoff between flexibility and ease-of-use

### ISSUE THREAD

**Issue by mplis** [kentcdodds/ama#495]
The other day, I had to add a new prop to one of my team's common components to support a slightly new use case. The situation felt very similar to the one you described in [your React Rally talk](https://www.youtube.com/watch?v=AiJ8tRRH0f8) this year, so my first thought was that it'd be great if this component utilized render props so this new use case could be supported without having to modify the component at all.

However, we have a bunch of engineers that don't have a ton of React or JavaScript experience, but are occasionally tasked with making changes to the UI and the current components are pretty easy for them to use. Render props allow for a ton of flexibility, but they do push more responsibility onto the caller so I think it'd be a hard sell asking everyone to become familiar with this pattern.

Do we have to make a tradeoff between flexibility and ease-of-use when considering using render props? Or is there a way to expose easy-to-use components while providing the ability to handle various use cases?

---

I'll propose one idea I was thinking of. Have a headless component that's used by the regular component and export both. The regular component is easy to use, while the headless component could be used when there's a new use case to support. If that new use case becomes very common, then the team could consider changing the regular component to support it (e.g. adding a new prop, etc) or creating a new, specialized version of the regular component (e.g. `<FancyToggle />`). Thoughts?

```jsx
export class HeadlessToggle extends React.Component {
  state = {
    on: false
  };

  toggle = () => {
    this.setState(({ on }) => ({ on: !on }));
  };

  render() {
    const { toggle } = this;
    const { children } = this.props;
    const { on } = this.state;
    return children({ on, toggle });
  }
}

export const Toggle = () => {
  return (
    <HeadlessToggle>
      {({ on, toggle }) => (
        <button onClick={toggle}>{on ? "On" : "Off"}</button>
      )}
    </HeadlessToggle>
  );
};
```

**Comment by kentcdodds** [comment]
Between you and me... and everyone watching this repo... React is going to come out with something soon that will be even easier/more flexible than render props. So hang tight with what you have now and look forward for the next couple weeks :)

Please don't ask me for more details. I'm probably not supposed to even say as much as I have! 😬 

Good luck!

**Comment by mplis** [comment]
@kentcdodds Now that hooks are released (which I'm assuming is what you were alluding to earlier), I was hoping to revisit this question. While I do like the hooks API, I still feel like I'd have the same problem as I originally outlined.

I still feel there's a tension between wanting to expose components with simple API's that cover the majority of use cases while allowing enough flexibility to handle one-off/rare use cases when they come up without having to extend the component API.

Maybe hooks end up being easier to use and teach than render props, but I still don't want everyone who has to make a toggle component in our app to have to consume a `useToggle` custom hook and build the toggle markup themselves, especially if most of the use cases are the same. People will simply want a `<Toggle />` component.

---

I'm spitballing here a little, but what about having the custom hook expose the majority-use-case component? Something like this:

```js
const useToggle = () => {
  const [on, setOn] = useState(false);

  const toggle = () => setOn(!on);

  const Toggle = () => {
    return (
      <div>
        <div>{on ? "On" : "Off"}</div>
        <button onClick={toggle}>Toggle</button>
      </div>
    );
  };

  return { on, toggle, Toggle };
};
```

Then, everyone consumes `useToggle`, but most of the time, they'll just make use of `Toggle` and render that component. If someone needs a custom toggle component, then they can use `on` and `toggle` to build their own.

**Comment by kentcdodds** [comment]
Yeah, you could definitely do that. Personally I would leave it at simply:

```javascript
function useToggle(initialValue = false) {
  const [on, setOn] = useState(initialValue)
  const toggle = () => setOn(!on)
  return [on, toggle]
}
```

I just find it very unlikely that the Toggle component you have there is generic enough to be useful. You could however also implement the prop getters pattern to help people with common use cases:

```javascript
const callAll = (...fns) => (...args) => fns.forEach(fn => fn && fn(...args))

function useToggle(initialValue = false) {
  const [on, setOn] = useState(initialValue)
  const toggle = () => setOn(!on)
  const getTogglerProps = (props = {}) => ({
    'aria-expanded': on,
    tabIndex: 0,
    ...props,
    onClick: callAll(props.onClick, this.toggle),
  })
  return {on, toggle, getTogglerProps}
}

function App() {
  const {on, getTogglerProps} = useToggle()
  return (
    <div>
      <div>{on ? "On" : "Off"}</div>
      <button {...getTogglerProps()}>Toggle</button>
    </div>
  )
}
```

This strikes a good balance between reusability and usefulness I think.

Also, those 12 lines of code basically replace https://github.com/kentcdodds/react-toggled which is pretty legit :)

**Comment by mplis** [comment]
Thanks for the response! I saw that you recently got back from a long trip and it's probably a huge pain catching up on all your notifications so I appreciate you taking the time to respond.

One part I wanted to respond to was:

> I just find it very unlikely that the Toggle component you have there is generic enough to be useful

That particular Toggle component probably isn't that useful, but I was using it as a stand in for any useful-in-most-scenarios component. For an open source component library, that kind of component probably doesn't exist, but I imagine it's pretty common for an internal component library, like the one my team uses, especially when people on the team have a wide range of React/JS experience.

I do like the prop getters pattern, but it is another pattern that I'd have to teach. The difference between someone on my team being able to do this

```js
const SomeComponent = () => {
  const { Toggle } = useToggle()
  return <Toggle />
}
```

and having to do this

```js
const SomeComponent = () => {
  const { on, getTogglerProps } = useToggle()
  return (
    <div>
      <div>{on ? "On" : "Off"}</div>
      <button {...getTogglerProps()}>Toggle</button>
    </div>
  )
}
```

is pretty big, especially if the latter is line-for-line the same in multiple places throughout our app.

**Comment by kentcdodds** [comment]
Right, but I'm saying that this:

```javascript
const SomeComponent = () => {
  const { Toggle } = useToggle()
  return <Toggle />
}
```

Is more confusing and unnecessarily complex than this:

```javascript
import { Toggle } = from './toggle'

const SomeComponent = () => {
  return <Toggle />
}
```

...

**Comment by kentcdodds** [comment]
So if you don't need rendering flexibility that prop getters and hooks give you, then don't use hooks 🤷‍♂️

**Comment by mplis** [comment]
Ahh I see now. Exposing the component via the hook doesn't really make sense.

I think I had tunnel vision a bit when I said this earlier:

> but I still don't want everyone who has to make a toggle component in our app to have to consume a useToggle custom hook and build the toggle markup themselves

The answer is they don't. I think can get the balance I want using my original solution, which was to export both a headless component and a simple component that consumes the headless component, except now I just replace the headless component with a custom hook.
