### ISSUE TITLE
Why is using `import { Component } from 'react';` incorrect?

### ISSUE THREAD

**Issue by ewolfe** [kentcdodds/ama#496]
In one of your youtube videos (I can't remember which one) you said importing the component via `import { Component } from 'react';` was _technically_ incorrect. Can you expand on that?

**Comment by cylim** [comment]
I am not sure about React packages. It seems like a tree shaking topic for me, correct me if I am wrong.

Previously if we import function/component from some library, it can't handle the tree shaking for the first way, which mean you had included all files that export to the `package` into your bundle even you are not using it.

For example, if a `package` you used is 1mb
``` js
import { Component }  from 'package' // 1mb goes to your bundle
import Component form 'package/Component' // 100kb goes to your bundle
```

**Comment by SenhorLion** [comment]
I think it's _technically incorrect_ because `Component` is not a named export from React, but a "property" on the React object (looking at the source):

```JavaScript
var React = {
  Component: Component,
  /* ... */
}
```

There is only one export, `react`.

**Comment by tommmyy** [comment]
If you are using React, you need to import it as whole anyway... then `import React, { Component } from 'react';` is the correct import.

**Comment by kentcdodds** [comment]
The issue is that technically a CJS module (like react) cannot be consumed via ES module name imports. It works thanks to how Babel compiles modules, but it's technically incorrect. That's all I was saying. Learn more: https://kentcdodds.com/talks/#more-than-you-want-to-know-about-es6-modules
