### ISSUE TITLE
Buying a couple of seconds from one of your videos

### ISSUE THREAD

**Issue by Pazgirrl** [kentcdodds/ama#499]
Dear Kent, 

My name is Susi Paz and I am researching videos for my client to present at their conference in November 2018.  Could we use a couple of seconds of one of your videos in a short film we are producing for the event?  I have a budget and can pay for any usage you allow us my email is: Susi@SusiPaz.com .  Please do get back to me as it would be a privilege to feature your work.  

Kind regards, 

Susi

**Comment by kentcdodds** [comment]
Thanks, we'll continue this via email.
