### ISSUE TITLE
What does your phone homescreen look like? 

### ISSUE THREAD

**Issue by sindresorhus** [kentcdodds/ama#5]
Screenshot please. It tells a lot about a person. [Mine for example.](https://github.com/sindresorhus/ama/issues/64)

**Comment by kentcdodds** [comment]
![screenshot_2015-07-05-16-13-05](https://cloud.githubusercontent.com/assets/1500684/8513740/7463e72a-2334-11e5-9f81-695d2b4235bc.png)

**Comment by kentcdodds** [comment]
You're right, it does say quite a bit about me :-)

**Comment by benoror** [comment]
Wonderful family, congrats! BTW how is that widget called?

**Comment by kentcdodds** [comment]
Thanks! We're expecting another boy in September! :D

I use [Better DashClock](https://play.google.com/store/apps/details?id=com.betterapps.dashclock&hl=en)

**Comment by benoror** [comment]
Triple congrats then :smile: !!! Thanks!
