### ISSUE TITLE
Is React fast enough to be used for voice assistant hybrid apps?

### ISSUE THREAD

**Issue by jorgecas99** [kentcdodds/ama#502]
We are currently building a voice assistance hybrid app in Ionic and are quite disappointed with the performance benchmarks. Not only the app is slow but it lags when user interact with the UI. 

What would be the ideal stack to improve speed and user experience. Am positive than GraphQL and a good cache mechanism is fundamental for round trips but am also curious what the front end should be and whether React can assistance in this matter. Any info will be greatly appreciated. Not many people are doing this so there are too many resources when it comes to architecture to look at.

**Comment by jorgecas99** [comment]
Thanks @jbstewart based on the reading I have done all points to React Native, I was curious as to how I can locate people with voice assistance experience in github that would be willing to work on this project (and get paid). The first person that came to mine was @kentcdodds . I think experience is everything and my employer understands that. Any leads will be much appreciated. Thanks

**Comment by kentcdodds** [comment]
Hi @jorgecas99!

I think it's fast enough. I have very little experience with React Native personally though. Good luck!
