### ISSUE TITLE
Question about hooks and render props

### ISSUE THREAD

**Issue by bheberer** [kentcdodds/ama#503]
Hey Kent, with the introduction of react hooks I've been seeing that render props my not be as useful when it comes to reusing log between components anymore, but am I correct in assuming it's still a viable pattern when it comes to creating more flexible components? I.E., giving the consumer of the component more control over what's rendered.

**Comment by kentcdodds** [comment]
Hey @bheberer,
If you're able to constrain your component to only support a version of react which supports hooks then I would suggest to do so. Hooks can do everything that render props can do (and more) while providing a more elegant API.

That said, if you'd like to support both APIs (while still constraining your components to a version of react which supports hooks), you could try this: https://americanexpress.io/hydra/

I hope that helps! I'm pretty excited about hooks :)

**Comment by bheberer** [comment]
Thanks for the response! Definitely helps, I'm excited as well.
