### ISSUE TITLE
Front End masters  Testing Workshop

### ISSUE THREAD

**Issue by sukumarvaddi** [kentcdodds/ama#504]
Kent,
      In the Testing-workshop Project, there is a file called workshop-setup.js in scripts folder from which you use a function called verifySystem in verify.js. My question is if there is a separate project from which you built workshop-setup.js to include it in Testing-workshop Project. If so, is it on the Git hub? If it is on Git hub, please point me to that project. If not, how did you do it?

**Comment by kentcdodds** [comment]
Yup: https://github.com/kentcdodds/workshop-setup 😄
