### ISSUE TITLE
For Enterprises, should you build an internal Component Library or use Material/Ant/etc with your SPA's

### ISSUE THREAD

**Issue by dnbr2002** [kentcdodds/ama#506]
I realize this is a bit broad but the repo is AMA.  :)

So, in the past our agency has been mostly local server based applications.  Java is most of the code base so we have JSP pages.  There is some .Net so there is ASPX pages there.  There's a lot of cobol and green screen as well but that's not relevant to this question.  So to support a standard look and feel as well ensure high levels of accessability and 508 compliance, templates were created for JSP as well as individual components which the server apps could selectively use.  This was deemed our User Experience Framework (UEF).  This was done quite a few years ago.  Pretty basic bootstrap stuff.  

Now the agency is going through a modernization journey.  Moving towards the cloud and micro service architecture in a containerized PaaS environment.  With that we have begun to use SPA's.  Mainly Reac (Im a React guy) and Angular at this point.  There are no templates but the UEF has being trying to evolve into a reusable component library much like a Material or Ant where you would install the UEF npm package and import the components you want to use.  They've been really slow to adapt and I've seen some of the early stuff and it really doesn't compare to the quality I've seen in highly supported external libraries.  They look great out of box.  It feels like we are reinventing the wheel a bit.  So long story short.  

1. Are we weighing ourselves down with unnecessary work maintenance with this internal component lib to serve our modern JavaScript apps?  
2. What do you all do at PayPal?  
3. What have you seen at other enterprises? 

 I think the agency I work for would like to have some customization to external component libs.  Essentially if you could have your own internal Material where you setup specific fields they  way they should be across your agency so there is consistency with look and feel as well as 508 and accessibility so developers don't have to redo that work each time.  I've seen [bitsrc](https://bitsrc.io/), maybe there's potential in using that to customize external material elements for reuse internally in a agency?   

Anyhow that's my question.  Thanks so much for everything you do @kentcdodds !

**Comment by kentcdodds** [comment]
Hi @dnbr2002!

Right now I'm literally working on building a component library for PayPal. I think that is really common and recommend it if you want to have a distinct look. You will make your engineers faster.

It is really a bummer that you're doing the same thing that's already available in open source, but generally those are hard to skin to look like your company's style. There are some components (like `downshift`) which you could use in your company's component library.

Also, I'm really excited about [React Hooks](http://kcd.im/hooks-and-suspense) which will encourage building more composable building blocks that could be open sourced without enforcing a look and feel. So you can benefit from the work of OSS without having to sacrifice the look you need. That's coming soon and I expect we have a lot to look forward to there.

Good luck!

**Comment by dnbr2002** [comment]
Ok good information.  We are using Stencil component compiler.  I guess we'll keep heading down the path. I just fear we will never make anything that is going to look as good as material or ant.  Considering there's just some basics we need to enforce like specific field types and accessibility pieces, it seems like if you could just take a component lib, then taylor it for your use and lock it down.  Like a material you buy license too essentially.  Nothing like that I guess.  :(
