### ISSUE TITLE
Getting started with testing

### ISSUE THREAD

**Issue by anaibol** [kentcdodds/ama#507]
I've been listening to your Javascript testing course and your talks. I didn't really get yet the difference between integration testing and e2e testing, but I am learning a lot!
I was wondering how to start implementing tests on an existing application, putting what I learn on practice with useful tests.
There is already static testing with eslint / prettier, not flow yet.
I am used to learning from real-world applications, but it's not easy to find real and big applications with available source code with React and the full suite of tests (Cypress, Jest, Flow, etc..). This way I could see how people separate different kinds of tests.
Do you know if there open source apps to learn from? How would you get started concretely on an existing app?

Many thanks!

**Comment by anaibol** [comment]
I was taking a look at https://github.com/kentcdodds/testing-workshop
And I see that using Cypress for e2e testing and Jest for unit testing would mean that your integration tests are common to the client and server apps, right?

![screenshot_20181109_161628](https://user-images.githubusercontent.com/3210177/48283326-fa195380-e43a-11e8-8bf4-4502962b7034.jpeg)
![screenshot_20181109_161457](https://user-images.githubusercontent.com/3210177/48283332-fab1ea00-e43a-11e8-9704-cbe227da01f8.jpeg)

**Comment by kentcdodds** [comment]
Thanks for the help @hedgerh!

I hope that helped you @anaibol. You may also be interested in my lightning talk about this: http://kcd.im/wheel
