### ISSUE TITLE
How to get better on child parish work

### ISSUE THREAD

**Issue by flpStrri** [kentcdodds/ama#508]
I also do parish work with boys (13-16 y/o) but I feel my methodology is not working with them, I work too much on the "idea" level and not on the "experience" one. Since you also do this kind of work, would you recommend me anything to make it better?

**Comment by kentcdodds** [comment]
Hi @flpStrri!

Just to make sure we're on the same page. :) I teach 9 year old children in Sunday school once a week for an hour. I have a team-teacher, so I teach a lesson every other Sunday.

In my church we have a curriculum with really great outlines for the lessons I teach. Here's this Sunday's lesson: [Daniel in the Lions’ Den](https://www.lds.org/manual/primary-6-old-testament/lesson-42?lang=eng).

Maybe that'll give you an idea of what I do. I hope that's helpful!
