### ISSUE TITLE
Using react-testing-library for complicated user flows

### ISSUE THREAD

**Issue by mdavid88** [kentcdodds/ama#509]
Hey Kent, love the react-testing-library, it really gels with the way we want to do testing where I work. I have a question about how far to take it before you're into E2E land.

Let's say we're making a booking engine for an airline. SPA, react-router, redux. The first route is a complicated form that you put all your search criteria in, click search, and get taken to a list of available flights and you make your selection. This is great. Instead of having to dispatch a whole bunch of redux actions or manipulate state precisely to see that list, I can just have react-testing-library act on the form as a user.

But how far do you take it? What if there are many more steps in the flow, and you want to test the last route. Because each route is driven heavily by state set in previous routes (departure/arrival city, date of departure/return, number of passengers, etc.), it's hard to supply the correct state at any given step in the flow without being tied to implementation details. So do we get react-testing-library to go through the flow for each of our bigger tests, from start to desired route?

This is a pretty broad question, but hopefully you get where I'm coming from. Examples of testing are generally small and digestible, it'd be nice to hear your thoughts on what to do when the state you're trying to test requires quite a bit of user interaction to get to.

**Comment by kentcdodds** [comment]
> So do we get react-testing-library to go through the flow for each of our bigger tests, from start to desired route?

You definitely could do that. I would actually think that it'd be a good idea to have one test that goes through that entire flow once (just the happy path). Typically I would do that with Cypress, though you can do that with jest and react-testing-library if you prefer.

> it's hard to supply the correct state at any given step in the flow without being tied to implementation details

This is the tricky thing with testing. As soon as you don't test exactly as the end-user is using your product you're getting into implementation details (even mocking out a credit card processor is implementation details). We make these tradeoffs for practicality. So I would suggest have one test that gets you most of the way there, then cover your edge cases with smaller more focused tests.

I hope that's helpful!

**Comment by mdavid88** [comment]
Very. Thanks for all the work you're doing!
