### ISSUE TITLE
How to get by with enzyme for now?

### ISSUE THREAD

**Issue by mplis** [kentcdodds/ama#510]
For those of us that don't have the option to migrate our testing suite from `enzyme` to `react-testing-library` (yet), is there a subset of the `enzyme` API we could stick to in order to avoid testing implementation details?

I don't have much experience with either library (yet), but a couple rules I'm thinking of would be:

1. Use `mount` instead of `shallow`
2. Only pass CSS selectors to `find` and only select for `data-testId` (ideally I'd query by text like `getByText`, but it's not clear to me how I'd do that in `enzyme`)

Anything else I should keep in mind? I'm definitely looking for good-enough-for-now while I work on trying to improve our testing practices.

**Comment by kentcdodds** [comment]
Hi @mplis!

What you have there is pretty good 👍

I would challenge your assumption:

> don't have the option to migrate our testing suite from enzyme to react-testing-library

You don't have to migrate the entire testbase from one to the other. You can use both in the same codebase. Writing all new tests with react-testing-library and only updating old tests as you have time/come across them. In fact, you can use both libraries in the same file or even the same test.

Another experiment I just tried is to use create a custom render method that uses enzyme to mount a component and then dom-testing-library to get you the queries: https://codesandbox.io/s/54z5kkvx4x

It works fine, but.... I don't know why you wouldn't just use react-testing-library instead :)

So my recommendation:

```
npm install --save-dev react-testing-library
```

And then start using it in new test files. You can migrate over time (or never get off enzyme, it's really no big deal).
