### ISSUE TITLE
How do you make those code transition animations?

### ISSUE THREAD

**Issue by dkovacevic15** [kentcdodds/ama#512]
I wanna get better at presentations, and love the way you style your slides -- simple, clean, beautifully animated, just really up my alley.

I figured out you're using slider.js for the slides, but in some places you animate moving code, like the Simply React talk, and can't find how to do it.

Thanks!

**Comment by kentcdodds** [comment]
Hi!

You're talking about [these slides](https://simply-react.netlify.com/#0)? That's [mdx-deck](https://github.com/jxnblk/mdx-deck) ([I blogged about it a while back](https://blog.kentcdodds.com/mdx-deck-slide-decks-powered-by-markdown-and-react-bfc6d6af20da)). It's pretty neat! Good luck!

... hold it....

I think you may actually be asking about [this version](https://slides.com/kentcdodds/simply-react). For that one I'm simply using slides.com for most of it. The moving code is actually a video recording, but I explain how I did it in [this video](https://www.youtube.com/watch?v=3AaghqS3W4Y&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u).

I hope that helps! Good luck!
