### ISSUE TITLE
paypal-scripts vs kcd-scripts

### ISSUE THREAD

**Issue by joeycozza** [kentcdodds/ama#515]
- How much more "involved" is paypal-scripts versus your kcd-scripts?
- Does paypal-scripts handle a local dev server? 
    - If so, what was the decision there?
- Is paypal-scripts mature at this point? Is it in maintenance mode, or is there still active development on it?

Thanks for all your awesome content.

**Comment by kentcdodds** [comment]
Hi @joeycozza :wave:

> How much more "involved" is paypal-scripts versus your kcd-scripts?

Way more. It supports full applications with a client and server.

> Does paypal-scripts handle a local dev server?

Yes. For applications it runs the backend server with nodemon and the frontend with regular webpack. Then there's a runtime helper that proxy's requests to the backend server to the webpack server. We keep them separate like this so they can be restarted independently.

> Is paypal-scripts mature at this point? Is it in maintenance mode, or is there still active development on it?

Pretty mature except I decided to switch it from supporting flow to typescript (I'll write more about this in the future). So I've been working on it a lot in the last week or so. Many apps at PayPal use it and it will actually be the default tool for all new apps at PayPal soon.

Thanks for the questions!
