### ISSUE TITLE
Would you come to Honduras and teach a bunch of great devs to code better?

### ISSUE THREAD

**Issue by bsommardahl** [kentcdodds/ama#516]
I live in Honduras and work with an amazing team of devs who want to make the world a better place through clean code. We often struggle in JS and need some guidance on testing and best practices. We can't all come to the USA and besides, it would be scary expensive. Would you, instead, come to Honduras? We'd take really good care of you and get you back to your family quickly. We'd even send your wife flowers for lending you to us for a couple days. What do you think?

**Comment by cefeboru** [comment]
Please!

**Comment by kentcdodds** [comment]
Hi @bsommardahl!

I'm honored to be invited! Thank you! I'm afraid that travel is very difficult for me right now (as much as I'm sure my wife would appreciate the flowers).

I am however planning on doing some remote workshops this year (as mentioned in [2018 in review](https://buttondown.email/kentcdodds/archive/ca78f624-8ed7-463f-addd-a0d039d4dc3b)), so maybe you good Honduras friends could join me in those?

Thanks!
