### ISSUE TITLE
Why don’t you like destructuring custom `this` methods?

### ISSUE THREAD

**Issue by ScriptedAlchemy** [kentcdodds/ama#519]
Following our twitter chat. I’d love to understand why your preference is against destructuring normal methods or methods that return JSX off of ES6 classes `const {myCustomThing} = this;`

For context - here’s out chat. This is, in my case related to React. 
But i also extend the question to if it were just normal ES6 classes.

Would you still not prefer destructuring the `this` instance directly and instead use `this.myCustomthing`? 

I want to understand your preferences to get a glimpse into how your mind operates.

https://twitter.com/scriptedalchemy/status/1076535458291564544?s=21

Educate me. I won't follow anyone blindly, but I want to learn more from those like you.

**Comment by kentcdodds** [comment]
Answered in today's dev tip! https://www.youtube.com/watch?v=n-bqy1WUphs&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u
