### ISSUE TITLE
Do you use commands to automate (minor or major) tasks?

### ISSUE THREAD

**Issue by marceloramires** [kentcdodds/ama#52]
I'm very fond of creating command line tools for anything, like tricky git commands, building, deploying, running unit tests, starting/stopping services, etc.

Do you use any? if so, could you list the ones you like the most?

**Comment by kentcdodds** [comment]
Yeah, I try to automate common tasks. For most things I just use aliases. You can see all of mine in my [dotfiles](https://github.com/kentcdodds/dotfiles) (look at the `.bash_profile`). I also use [hub](https://github.com/github/hub) and [autocompletion](http://code-worrier.com/blog/autocomplete-git/). Then in my projects (both work and open source), I'll generally write scripts to automate tasks. I leverage [npm scripts](https://docs.npmjs.com/misc/scripts) quite a bit for this.

Oh, and I also use [snippets](https://github.com/kentcdodds/dotfiles/tree/master/.janus/vim-kentcdodds-snippets/snippets) in vim (and I used to in WebStorm) to create unit tests, angular modules, etc. I'm thinking about looking into [plop](https://www.npmjs.com/package/plop) to make it a little more extensible and less editor-focused (so other team members can use them too).

For my library [angular-formly](https://github.com/formly-js/angular-formly), I use several forms of automation to make contributing and publishing easier. What's really nice about that I don't have to do much to maintain the library anymore. I pretty much just merge pull requests and it gets released automatically.

At work, I developed our continuous integration solution that tests, builds, and deploys our master branch to four environments. It's a combination of bash scripts and npm scripts and is pretty powerful. For example, we even test, build, and deploy all pull requests and we also deploy each build twice (once for the actual app, and another as a storage mechanism which helps identifying when bugs entered the system much easier than a git bisect).

Automating stuff is important to me. I've actually been meaning to write a blog post with this premise: Let's say you have a task that takes 30 seconds, and you will only do it 10 times in your whole life. Even if it takes 30 minutes to automate it (6x the amount of total time the task would take), you should still automate the task. I'll save my reasoning for the blog post :-)

Thanks for the question!

**Comment by marceloramires** [comment]
Thanks! Very interesting answer. Didn't know some of these tools you mentioned, I'll take a look at them.

Funny that you mentioned the automation time x total usage time paradigm. I've always wondered that myself. I've definitely already spent more time automating some tasks than I'll spend performing them in my entire life, and always feel a bit stupid afterwards. Looking forward for the blog post.

**Comment by kentcdodds** [comment]
If you're interested in how I've automated angular-formly watch my series on egghead.io: [How to Write an Open Source JavaScript Library](https://egghead.io/series/how-to-write-an-open-source-javascript-library)
