### ISSUE TITLE
Self-Teaching the Scientific Approach

### ISSUE THREAD

**Issue by anthonybronkema** [kentcdodds/ama#523]
As someone without a CS degree, I feel like I’m spending most of my time learning to problem solve and think like a programmer. What advice do you have? 

Thank you for all you’ve done and continue to do for the community!

**Comment by kentcdodds** [comment]
Hi @anthonybronkema! I've answered this on [3 minutes with Kent](https://www.briefs.fm/3-minutes-with-kent/70).

Thanks!
