### ISSUE TITLE
Apollo link state or Redux?

### ISSUE THREAD

**Issue by o-t-w** [kentcdodds/ama#524]
In his blog post [Redux - Not Dead Yet!](https://blog.isquaredsoftware.com/2018/03/redux-not-dead-yet/) a Redux maintainer writes:

> I'd agree that data fetching via GraphQL, and especially with Apollo, will likely reduce or eliminate your data-fetching related Redux code. And again, if that's all you were using Redux for, you probably wouldn't need Redux after moving all the data-fetching handling into Apollo. I'll even go so far as to say that apollo-link-state could probably handle most of your other client-side state logic, and I think Apollo ships with a DevTools setup of its own. The Apollo team has been doing some pretty neat work, and while I don't like seeing people switch away from Redux, ultimately we all want to build great apps that help our users. But, as with context, I'd say there's definitely use cases where Redux is going to work better than GraphQL + Apollo, and possibly without requiring as much buy-in throughout your architecture. This is especially true if you need to do more than just fetch data or update a couple local state values, like persisting user data through page reloads or implementing complex workflow logic.

Have you tried both? For people learning state management for the first time, which one would you invest your time in (assuming they are using GraphQL already)?

**Comment by kentcdodds** [comment]
Sorry, I've never tried Apollo link state before, so I'm afraid I can't speak to this.
