### ISSUE TITLE
Why did you stop using vim keybindings?

### ISSUE THREAD

**Issue by jgierer12** [kentcdodds/ama#531]
In your recent streams and courses, I noticed that you aren't using vim keybindings for VS Code anymore. Is that just for the course to make it easier to follow the cursor, or did you stop using it entirely? If so, what's the reason for that?

**Comment by kentcdodds** [comment]
Here's your [audio-answer](https://www.briefs.fm/3-minutes-with-kent/75) :)

**Comment by jgierer12** [comment]
Thanks a lot Kent!

I had the same experience with Vim, used it for a month or two but quickly got fed up with all the configuration and lack of GUI perks. So I switched back to VSCode with [VSCodeVim/Vim](https://github.com/VSCodeVim/Vim) and I like it so far. It's a good compromise between the two editors. But I can definitely see where you're coming from, some things are a bit annoying with the vim extension.
