### ISSUE TITLE
KCD Scripts Walk through

### ISSUE THREAD

**Issue by adeelibr** [kentcdodds/ama#532]
Hello,

Thank you for all the knowledge you share via your blogs & podcasts. 

You once said in one of your podcasts, that you have hundreds of libraries & it's very hard to update each library manually. So you have automated the process by using kcd-scripts. Where you update kcd-scripts and all of your libraries are updated based on that.

Can you kindly do a walk through on how the internals of kcd-scripts work.

<hr />

Also can you kindly without using kcd-scripts create a react library that uses css-in-js stuff & walk through with publishing it in any of your podcasts. If you can in your precious time.

Thank you. Cheers. 
I love your content sir. :)

**Comment by kentcdodds** [comment]
Hi @adeelibr!

You're in luck! I've actually already done a walkthrough: https://www.youtube.com/watch?v=ZWfY-v1DCTE&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

Wahoo!

> Also can you kindly without using kcd-scripts create a react library that uses css-in-js stuff & walk through with publishing it in any of your podcasts. If you can in your precious time.

I'll keep this one in mind, but I don't have any plans for this one. It's a tricky problem and I've not really done it in a way that I like yet so I'm probably the wrong person to ask. Thanks!
