### ISSUE TITLE
State Initialization for Arrays

### ISSUE THREAD

**Issue by alexwendte** [kentcdodds/ama#534]
In React, if you have a state value `resources` and `resources` will be updated by your api data on mount, do you usually initialize `resources` to `undefined` or `[]`?

I am using Typescript, and I am finding it very annoying to always check `resources && resources.map( ... )`. However, it makes sense to me that the value is truly undefined until the api initializes the value with data, whether there are no `resources` `[]` or multiple `resources` `[{...}, {...}]`.

It would make sense to me to initialize the value to `undefined` so that Component can easily tell whether the data is still loading or not vs simply not having any items in the array. It is just kind of annoying and not concise to have to continue to check whether `resources` is defined or not.

What do you normally do, and would you recommend? Thanks Kent!

**Comment by kentcdodds** [comment]
Hi @alexwendte,
I would initialize that to an empty array personally. If you need to know whether the data has loaded yet or not then I suggest adding another separate state variable for tracking that.

I hope that helps!
