### ISSUE TITLE
React theming: Context vs CSS custom properties

### ISSUE THREAD

**Issue by o-t-w** [kentcdodds/ama#535]
When it comes to theming, what can be achieved using the context API that cannot be achieved with CSS variables?

Also, in what situations do you need to use the context API for theming? In some examples I see I can't understand how it is superior to just doing `import theme from './theme'` Importing and exporting already offers a way to pass things around the app without needing prop drilling.

**Comment by kentcdodds** [comment]
Well, for one [css variables are not supported in older browsers](https://caniuse.com/#feat=css-variables). I think that's probably the biggest thing. I've never used css variables so I can't really speak to how easy they are to use in a codebase.

> In what situations do you need to use the context API for theming?

You'd need it if you can dynamically change the theme at runtime. It could also be useful if you're making reusable components and people can provide their own theme by passing it to the context provider. But if you're just building an app and you can't dynamically change the theme, then feel free to use a singleton theme object.
