### ISSUE TITLE
Declaring object as props of context provider in render method

### ISSUE THREAD

**Issue by mjangir** [kentcdodds/ama#536]
Hi Kent,

Thanks for awesome react advance pattern series on frontend masters. I just have one confusion in compound components with the following code:

```
<ToggleContext.Provider
        value={{
          on: this.state.on,
          toggle: this.toggle
        }}
      >
        {this.props.children}
</ToggleContext.Provider>
```
By making this an object that we declare inside the render method, the value is changing every single time its re-rendered. And so you made it like below:

```
<ToggleContext.Provider value={this.state}>
        {this.props.children}
</ToggleContext.Provider>
```

I wanted to know how does it make a difference as what I think is, The main render method will never be called until and unless anything in this.state is changed. Kindly elaborate a bit.

Thank you so much.

**Comment by mjangir** [comment]
Hey Kent,

Sorry! Actually you answered that question in the next immediate video that context provider checks its **value** prop and declaring new object each time in renders creates new variable in memory. And it doesn't do like a shallow compare.

I got that.

Thanks a lot!

**Comment by kentcdodds** [comment]
Glad you figured it out!
