### ISSUE TITLE
How do you switch between folders and extensions in setup of your vscode? i have your config

### ISSUE THREAD

**Issue by lockround** [kentcdodds/ama#539]

**Comment by kentcdodds** [comment]
Hi @lockround! Answered on [DevTips with Kent](https://www.youtube.com/watch?v=IHMkIdmvD9c&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u)

**Comment by lockround** [comment]
Thanks you so much!! 
awesome as always...
:100:
