### ISSUE TITLE
How did you "level up" your JavaScript skills?

### ISSUE THREAD

**Issue by ivosantiago** [kentcdodds/ama#54]
Sometimes I start to look outside of my daily job and it is:
a) hard to pick the next thing in JS to learn (I'm currently working with AngularJS 1).
b) even if I pick something how do I really level up my skills? Are books/projects/talks the best way?

What was your path learning (and improving) JavaScript?

Thanks a lot

**Comment by kentcdodds** [comment]
Hi @ivosantiago! Thanks for the question! My answer to [this question](https://github.com/kentcdodds/ama/issues/41) is probably what you're looking for. Specifically with your questions:

a) Pick something. There's a lot of goodness out there. Experiment with a few things that look remotely interesting to you, then pick one and build something with it.
b) Build something. Also, be aware of your learning style (mentioned in my other answer).

Learning and improving my knowledge of JavaScript is an ongoing thing. I think that most people think I understand JavaScript better than I really do :smile:. If you're a book person though, I highly recommend @getify's [You Don't Know JS](https://github.com/getify/You-Dont-Know-JS) series :-) Also his workshops on [Frontend Masters](https://frontendmasters.com/) are fantastic.

Finally, staying current and being aware of the coolness is fun and helpful too. See the answer to [this question](https://github.com/kentcdodds/ama/issues/17) for more about what I do to do that :-)

Cheers!

**Comment by ivosantiago** [comment]
Thanks A LOT @kentcdodds !! I really appreciate your answer. :smile:
