### ISSUE TITLE
Adjusting Testing Trophy for Greenfield vs Mature project

### ISSUE THREAD

**Issue by krulletc** [kentcdodds/ama#540]
Thanks for the great presentation via Applitools. 

Does the Testing Trophy that you demoed in the podcast change based on if this is a greenfield vs a mature project?  If so, how would you change it?

**Comment by kentcdodds** [comment]
Hi @krulletc!

I answered this on [my podcast](https://www.briefs.fm/3-minutes-with-kent/72). Thanks!
