### ISSUE TITLE
Impostor Syndrome and self doubt

### ISSUE THREAD

**Issue by ritchieanesco** [kentcdodds/ama#546]
Hi Kent

Thanks for answering my question. I’ve been in the industry for 10+ years and it’s only recently that I’ve began doubting myself as a developer. Have you or know someone who has experienced imposter syndrome? If so how did you/they overcome it? 

Thanks again for all the things you do for the community.

**Comment by kentcdodds** [comment]
Hi @ritchieanesco!

Here's your [audio answer](https://www.briefs.fm/3-minutes-with-kent/79) (transcript is part of the episode description).

**Comment by ritchieanesco** [comment]
Thank you for spending the time to respond! Really appreciate your thoughts and glad to know that I’m not alone in this.
