### ISSUE TITLE
How to release open source projects under your account while working for a company

### ISSUE THREAD

**Issue by kyhy** [kentcdodds/ama#548]
Hello Kent!

I enjoy following all of your open source work and devtips videos. I noticed that a lot of the newer open source projects that you have `react-testing-library` and various babel plugins were under your account rather than Paypal.

I have a few projects that I would like to release under my account as I'd like to maintain them. I would rather not open it under a company as I don't want these projects to be de-prioritized and be canned.

Do you have any advice?

Thanks!

**Comment by kentcdodds** [comment]
Hi @kyhy!

Here you are: [#77](https://www.briefs.fm/3-minutes-with-kent/77)

**Comment by kyhy** [comment]
thank you Kent!
