### ISSUE TITLE
Explain the problem outlined in tree-shake-css

### ISSUE THREAD

**Issue by ewolfe** [kentcdodds/ama#549]
Overe [here on your repo "tree-shake-css"](https://github.com/kentcdodds/tree-shake-css/commit/eac898f00b6e6b2de059281678e0b0323b216eb5#r31981760) you said:

> You'll notice that `app1.js` is only importing `a` from `./lib` which is a file that imports both `a` and `b`. So the end result is the css for both a and b even though we're only using stuff from `a`.

Would you mind explaining this is happening? 😀

**Comment by kentcdodds** [comment]
Hi @ewolfe 👋 

Thanks for asking! Here you go: https://www.youtube.com/watch?v=Q_F-c0LEp4I&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u
