### ISSUE TITLE
Your opinion about A.I.

### ISSUE THREAD

**Issue by janhesters** [kentcdodds/ama#550]
Hi Kent, first of all thanks for answering my questions 🙏🏻

I would like to ask you yet another philosophical one:

What do you think about A.I. and the implications for humanity?

Your view on it is of particular interest to me because on the one hand you are a programmer and in the other hand you are religious (judging from your answer to what is happiness).
Do you believe in a utopian future that A.I. will be like a benevolent god?
Do you believe in a dystopian future and feel like A.I. might doom us?
Do you think it is even able to reach human level intelligence?

Thank you as always 😊

**Comment by kentcdodds** [comment]
Thanks @janhesters!

[Here's my answer](https://www.briefs.fm/3-minutes-with-kent/76)
