### ISSUE TITLE
PP Scripts and building your own.

### ISSUE THREAD

**Issue by chrislaughlin** [kentcdodds/ama#554]
You talk a lot about PP scripts and I assume this is something like react scripts for CRA. How did you get started building out this scripts package and do you have any good guides on how to start/build something like this. I feel that it would be useful not just for my work but also for my personal projects. 

Thanks 👍

**Comment by kentcdodds** [comment]
Hi @chrislaughlin 👋 

I've actually created a walkthrough video [here](https://www.youtube.com/watch?v=ZWfY-v1DCTE&t=0s&index=69&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u). Feel free to ask other questions if you have more specific questions that the video doesn't answer.
