### ISSUE TITLE
Github branch workflow

### ISSUE THREAD

**Issue by samAbeywickrama** [kentcdodds/ama#555]
Hey Kent,

If you could do a youtube video on github branch workflows, that would be great.  

I finished your "How to Write an Open Source JavaScript Library" on egghead. Thank you so much for the valuable content. leant a ton. 🤘😄✌️ .

**Comment by kentcdodds** [comment]
Hi @samAbeywickrama!

[Here's your video answer](https://www.youtube.com/watch?v=Ouu_FBog9Y4&index=2&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u&t=0s)
