### ISSUE TITLE
When is the next meetup group where you will be presenting?

### ISSUE THREAD

**Issue by run-time** [kentcdodds/ama#56]
curious if I could attend and meet you in person

**Comment by kentcdodds** [comment]
Hi @run-time! I'm still working on convincing my wife to let me go to tomorrow's [Elm meetup](http://www.meetup.com/Utah-Elm-Users/). If I can't make it to that one I think the next one I might show up at is [UtahJS](http://www.meetup.com/UtahJS/) in Orem or [ReactJS](http://www.meetup.com/ReactJS-Utah/). We'll see. I'd be happy to do lunch sometime though :-)

**Comment by run-time** [comment]
Sweet!  Hope you can make it.  I'm here right now trying to figure out how to add a div element around the Hello World Elm example and failing miserably.

**Comment by kentcdodds** [comment]
I'm definitely going to be at [ProvoJS](http://www.meetup.com/ProvoJS/) as a panelist with @djsmith42 and others. So I'll probably see you there. I may be at the next UtahJS on Jan 7th. I also plan to be at the [IE8 farewell party](http://farewell.ie8.lol/) :-)

**Comment by kentcdodds** [comment]
Hey @run-time, I'm going to be at [UtahJS Orem Meetup](http://www.meetup.com/UtahJS/events/229159374/?rv=cr2&_af=event&_af_eid=229159374&https=off) and I'll be speaking at [UtahJS SLC Meetup](http://www.meetup.com/UtahJS/events/230106879/) :+1:
