### ISSUE TITLE
Your thoughts about CSS in JavaScript?

### ISSUE THREAD

**Issue by gothbarbie** [kentcdodds/ama#560]
I've come to really enjoy working with `styled-components`. 

I know some people feel that CSS and JavaScript should be separated, but since we're already writing HTML with JSX, why not use the flexibility of JavaScript when we write our CSS as well?

**Have you tried any CSS-in-JavaScript tool and what are your thoughts about it?** Any obvious drawbacks that you see? Or is it more a matter of familiarity and personal taste? 

What I personally enjoy is that you can keep the camel-case style of CSS while having the flexibility of using props for different scenarios, as well as easily expand upon existing styles for when you need variations: 

```
const Button = styled.button`
  background-color: #ccc; 
  // other default styling
`
const BlueButton = styled(Button)`
  background-color: #00F;
`
```

**Comment by kentcdodds** [comment]
Hi @gothbarbie!

Thanks for the question. Here's your answer: https://www.briefs.fm/3-minutes-with-kent/80

And here's the YouTube video I referenced: https://www.youtube.com/watch?v=R1_nGU0x3Wk&list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf
