### ISSUE TITLE
Why is import name aliasing different from object destructuring aliasing?

### ISSUE THREAD

**Issue by harrysolovay** [kentcdodds/ama#562]
Hi Kent,

Was wondering if you had any thoughts on why this:

```js
import {SomeModule as AnotherName} from './some-module'
```

isn't this:

```js
import {SomeModule: AnotherName} from './some-module'
```

It seems strange that it would follow a different syntax than object destructure renaming.

Hope this is the right forum for such a question. It is "ask me anything", after all ;)

Thanks!

**Comment by kentcdodds** [comment]
Hi @harrysolovay,

This was a great question for my daily livestream: https://www.youtube.com/watch?v=4keUSxNw-KE&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

**Comment by harrysolovay** [comment]
@kentcdodds sweeeet. Watching it now :)
