### ISSUE TITLE
How do you test for mobile?

### ISSUE THREAD

**Issue by janhesters** [kentcdodds/ama#563]
Hi again Kent,

I love React Testing Library and Cypress Testing Library.

The React app I'm currently writing is a PWA using service workers and should be used via desktop as well as on mobile.

How do you test for mobile? Specifically, how do you test behaviour when the apps window size is below a certain threshold?

Greetings from Germany,
Jan

**Comment by kentcdodds** [comment]
Another great question @janhesters! Here's your answer: https://www.briefs.fm/3-minutes-with-kent/83
