### ISSUE TITLE
is Enzyme worth using with jest-dom

### ISSUE THREAD

**Issue by johnstonmatt** [kentcdodds/ama#564]
I understood enzyme as a way to evaluate the output of a component depending on its props, does jest-dom solve this problem independently? Is Enzyme just the jquery-like syntax as sugar?

**Comment by kentcdodds** [comment]
Hi @johnstonmatt! Here's your answer: https://www.briefs.fm/3-minutes-with-kent/82

**Comment by johnstonmatt** [comment]
wow, you are very quick, and very helpful! Thanks @kentcdodds, consider me converted :D
