### ISSUE TITLE
How to convert JS function to React class or functional component?

### ISSUE THREAD

**Issue by guylepage3** [kentcdodds/ama#568]
Taken from the tweet https://twitter.com/guylepage3/status/1091334300702859264

I see a need to import my traditional `.css` file styles into React and then simply pass classnames to components as you've done in your Egghead.io "Style React Components with className and In Line Styles" React course. https://egghead.io/lessons/react-style-react-components-with-classname-and-in-line-styles

After using virtually all the CSS-in-JS tools out there. this is the one concept that makes the most sense for scalable styling of an app. It allows for structured theming while providing the flexibility of CSS-in-JS. Hands down makes the most sense.

My ask is how to properly convert what you've executed in the course section into a React class or functional component?

Here's a Codepen fork if you'd like.
https://codepen.io/guylepage3/pen/omZMVM?editors=0110

Thx.

**Comment by kentcdodds** [comment]
Hi @guylepage3!

Thanks for the question. I hope this is helpful: https://www.youtube.com/watch?v=ljnrvPMjaVs&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

**Comment by guylepage3** [comment]
Thanks @kentcdodds.. 

Also here's a less effective method for others.. https://codepen.io/guylepage3/pen/zeZXeM
