### ISSUE TITLE
Understanding other people's code

### ISSUE THREAD

**Issue by miguelc1221** [kentcdodds/ama#57]
hey, i started coding 7 months ago and have come a long way with lots of practice, i can build full stack apps(react/redux/express) and learn more each day.I want to start contributing to open source on github but i have problems understanding other peoples code.I understand prototypal inheritance, classes etc. but still have a hard time understanding what is happening when i look at the code that make up some of the libraries i use.  My question is , do you have any tips on getting better at this ?

**Comment by kentcdodds** [comment]
Hmmm... I've been thinking about this question a lot today and I still can't think of a good answer for you. So I'll reach out to the interwebs to see what others can say...

I can definitely tell you that it's extremely valuable to read other people's code. You'll learn a lot from them (and it's one of the things I cite for [how getting into open source has been awesome for me](https://medium.com/@kentcdodds/how-getting-into-open-source-has-been-awesome-for-me-8480cd756a80)).

I'll reach out to twitter and see what other people think :-)

**Comment by mvolkmann** [comment]
I can't provide a good answer on how to get better at reading code that other people have written, but I can comment on why it is difficult. These are some common things people do in their code that make it difficult to read:

1) write functions/methods that are too long and do more than one thing
2) select poor names for functions/methods, parameters, variables, ...
3) format code in a way that differs from the way most people that use the language do
4) fail to add comments when something tricky/advanced is going on

**Comment by brenoc** [comment]
The best way to understand a code is to debug it. Add tons of breakpoints, tweak something, break it, see which functions are called and so on.

A good way to check if understood everything: add a new test.

**Comment by mvolkmann** [comment]
Come to think of it, I guess I do have some real advice. Make sure you understand some key features of the language the code is written in. For JavaScript I would include these: Array methods like map, filter, reduce, some, and every, Function methods like bind, call, and apply, and increasingly ES6 features like arrow functions, the spread operator, and others. If you aren't familiar with those and you are reading code that uses them, that will really slow you down.

**Comment by kentcdodds** [comment]
+1 @mvolkmann, that's great advice. Learn the language so you're not surprised when people are using features of it you're not familiar with.

**Comment by benoror** [comment]
This may sound counter-intuitive but for me the best way to understand other people's code is to start contributing and hacking around ASAP.

The earlier you start debugging and submitting simple fixes, the sooner you'll understand the inner-workings.

My advice: Don't take it too seriously, you don't need to read the whole codebase like it was a book, instead get your hands dirty and iterate over it.

**Comment by benoror** [comment]
+1 @mvolkmann Can confirm, author's neatness and discipline makes a big difference! (cc @kentcdodds :wink:)

**Comment by johnbrett** [comment]
Hey @miguelc1221, congrats, that's a long way to come in 7 months :)

I find you hit a point when learning to code that you can understand the language features quite well, but still struggle with a developers intent with using those features - they vary a LOT :) The problem with codebases is they're rarely written to be read, they're written to serve a purpose like an application, so often the best way to digest them is to try add a feature or test rather than just scan the code base. 

To accelerate the learning process, I find one the best approaches is to find examples and re-implement them with the tools you know and understand, then compare your version with the original example. You'll start to spot design patterns and things you might not have considered in your own implementation.

One other piece of advice I'd give is if you use a OSS project regularly which has a good community, try participate. This can initially just be watching issues and responding when you might have the answer, but then investigating bugs or fixing small bugs, to adding features. You'll learn loads from seeing beginners and more experienced devs discuss different approaches to solving problems. I took this approach as part of the [hapijs](https://github.com/hapijs/hapi) community and it has been one of my biggest sources of learning in the last year!

**Comment by kentcdodds** [comment]
@johnbrett 

> One other piece of advice I'd give is if you use a OSS project regularly which has a good community, try participate.

Totally +1 :D

**Comment by kentcdodds** [comment]
Closed, but people can feel free to continue the discussion :-)

**Comment by learningjs** [comment]
Great advises here, thanks to all, especially to @miguelc1221 for asking this question. 

Vital assertion: I can state that I am at a beginning level, so I will likely change my mind in the foreseeable future:

basically, the thing that helps me the most is to understand the conventions that are being used. If I do not understand, I just ask for enlightenment. If enlightenment is not enough, I then know that I surely have yet to grasp the underlying concepts (which in turn, is not always obvious)  :)

**Comment by miguelc1221** [comment]
Thanks a lot for all the responses!

@johnbrett I relate a lot to what you said,"...understand the language features quite well, but still struggle with a developers intent with using those features". The advice you gave is something i have been thinking about as well, and will defiantly take that approach. @kentcdodds Thanks for taking the time and helping me out, its why i love this community.

**Comment by johnbrett** [comment]
No problem @miguelc1221. If you happen across any of my repos on here, feel free to an raise an issue if you just want clarification on any of the code or why something has been done a certain way, I'll probably learn something in the process too :)

**Comment by popthestack** [comment]
One thing I do to understand code I don't understand is to refactor it. For example, if it's a long function I'll extract parts of it into new functions. The act of breaking it down often helps me get what it's doing. If a particular portion doesn't make sense I may tweak it to see how the output changes.

**Comment by kentcdodds** [comment]
Before you do that, write tests. You don't know what you could break especially if you don't understand it. But I agree with you!

**Comment by gh-amistry** [comment]
I recently tried going head-first at reading the code for https://github.com/facebook/react, and.... had no idea where to start :) Would anyone have some tips to at least find a starting point to read? Thanks!

**Comment by valera-rozuvan** [comment]
Do note that reading code is actually a lot harder than writing code! Please refer to this wonderful article by **Coding Horror** https://blog.codinghorror.com/when-understanding-means-rewriting/ .

**Comment by vitkarpov** [comment]
> Would anyone have some tips to at least find a starting point to read? 

I found very useful this docs:

- https://facebook.github.io/react/contributing/design-principles.html
- https://facebook.github.io/react/contributing/codebase-overview.html
- https://facebook.github.io/react/contributing/implementation-notes.html

You can make a simple test app and try to "stride" every function call during the reconcile process. Also, try to build your own Virtual DOM, it's not so hard (there's few articles about it)
