### ISSUE TITLE
How do you keep sustainable inspirations as a full-time educator?

### ISSUE THREAD

**Issue by chengjianhua** [kentcdodds/ama#574]
I just read your email _🚨 Big Announcement: I’m a full-time educator! 👨‍🏫_. I'm curious that is that means you quit your job in PayPal?

If so, out of the first line of development in challenges brought by the various company businesses will reduce your educating materials? I believe that most people want to get good educations with valuable knowledge, and the experiences people care are coming up from real problems met in real environments.

If not, how can you keep sustainable inspirations? And get them from where? It is hard, and I admire that you can take such a fantastic decision.

Thanks for the chance to ask this question! 🤗 @kentcdodds

**Comment by kentcdodds** [comment]
Hi @chengjianhua! That's a great question. Here's the answer: https://www.briefs.fm/3-minutes-with-kent/91

**Comment by chengjianhua** [comment]
> Hi @chengjianhua! That's a great question. Here's the answer: [briefs.fm/3-minutes-with-kent/91](https://www.briefs.fm/3-minutes-with-kent/91)

I have listened to it, thanks~ 🙏 You're a genius, AMA is a good approach to collect inspirations.
