### ISSUE TITLE
Data fetching - on load vs on demand?

### ISSUE THREAD

**Issue by moshekatz** [kentcdodds/ama#577]
Hi there!
I'm wondering when to use one over the other (or maybe a combination of both)?

### Things to consider:

1. Handling a lot of requests (I guess with some sort of caching)
2. The data doesn't change very often, and even if it does - it's ok to wait for a page refresh

#### Fetching on load:

- (-) slows down initial load
- (-) handling race conditions for some use cases (therefore probably introducing additional async API)
- (+) after a single request, I can access the data synchronously through cache (most use cases)

```js
// onLoadApi.js
const cache = {};

/* ...fetching logic to fill the cache... */

const get = key => cache[key];
const getAsync = key => /* reading from cache or waiting for the response */

export { get, getAsync }

// usageOnLoad.js
import { get, getAsync } from './onLoadApi'; 

const value = get('key');
const otherValue = await getAsync('otherKey');
```

#### Fetching on demand:
- (+) no effect on initial loading
- (-) accessing the data asynchronously in all use cases
- (+) no need for multiple API's, always returns a Promise

```js
// onDemandApi.js
const cache = {};

const getAsync = key => /* reading from cache or fetching from server */

export { getAsync }

// usageOnDemand.js
import { getAsync } from './onDemandApi'; 

const anyValue = await getAsync('key');
```

**Comment by kentcdodds** [comment]
Hi @moshekatz!

Here's your [audio answer](https://www.briefs.fm/3-minutes-with-kent/88)!
