### ISSUE TITLE
Not a question, but feedback about your streams

### ISSUE THREAD

**Issue by janhesters** [kentcdodds/ama#578]
Hi Kent,

First of all let me say I love your content 🎓. You taught me a lot and I'm very grateful for that. This is (I hope) constructive feedback.

I think you might want to reconsider wether you do long (~ longer than 20 minutes) streams on YouTube. Think about it:

Most of your viewers are probably programmer between 25 and 35. People who work full time jobs and, like you, have family. These people are probably not able to dedicate hours to watching videos.
Yesterday you made three great streams, but they were all about an hour long. While struggling to find the time to watch them I thought to myself: "I'm probably not the only one who has trouble watching these streams today. Many people would like to see this, but miss it because it is just to much."

I know you have egghead courses which are designed to be dense. I just wanted to give you this feedback so you might want to consider to make your YouTube videos similarly organised and dense. Because while just doing streams might be tempting because they don't require much planning or editing it will likely hurt your reach and cause people to miss out on your awesome content.

Again thank you for your work,
Jan

**Comment by jLouzado** [comment]
As Pascal wrote:
> I'm sorry I wrote you such a long letter; I didn't have time to write a short one. [ref]

IMO this question reads like a complaint along the lines of "OMG this is _too much_ content, please produce less".

I know that probably wasn't your intention @janhesters but it sorta comes across as ungrateful considering that the content is free. As you said, the denser videos are available in egghead and elsewhere and they're behind a paywall at the places where Kent has chosen to do so. 

P.S. that being said, that "Migrate Posts from Medium To Markdown" series was hella long. 😅 

[ref]: https://quoteinvestigator.com/2012/04/28/shorter-letter/

**Comment by janhesters** [comment]
@jLouzado I'm sorry. To be clear, I'm super thankful for Kent's content and he elevated my programming skills to another level 🙏

**Comment by mamachanko** [comment]
If Kent had more time he would make shorter videos.

**Comment by ultrox** [comment]
@janhesters I feel you, I loved shorter videos as well, I simply don't watch them now. From Kent point of view those long videos make sense as its almost free to him, he just record what he's doing,   simply its just low density/low quality content and so far away from what Kent was about, 'curated' content.

**Comment by kentcdodds** [comment]
Hey friends 👋

What you're saying: "The free stuff you make is too long"

What you mean: "The free stuff has a lower value per minute ratio than I want."

@jLouzado is totally correct here. It takes time to increase the value per minute ratio. WAY more time than producing the content.

@ultrox is totally right too. Producing longer videos is basically free (especially the [Coding with Kent](https://kcd.im/coding) series. Less so the [DevTips with Kent](https://kcd.im/devtips) one).

When I'm going to put a ton of work into increasing the value per minute ratio, I need to be paid for my time. Which is why things like [testingjavascript.com](https://testingjavascript.com) and [my remote workshops](https://kentcdodds.com/workshops/) cost a premium. A lot of the stuff available there you can find spread over dozens of hours of my free content if you really need to. But if you value your time and want a higher value per minute, you'll pay me for curating it all and keeping things brief.

For me, it's: "Make the free content without taking time (which I don't have) to increase the value per minute. Or don't make the free content at all." I choose to make the free content. If I take the time to increase the value per minute, it wont be free anymore.

I hope that's helpful insight :)

**Comment by janhesters** [comment]
Thank you for the response 🙏🏻 Thought I feel like (for me at least) you missed the point.

Just to clarify my position: I love Kent's free videos on YouTube. I love what he does. I bought his premium products and I'll continue to support him (and my skills 🤓) that way 📈 What follows can easily be confused with: "You (Kent) should make the high value per minutes video free _for me_ because I'm lazy and cheap." This is not what is being said here. If you understood it this way, you missed my point.

My point is:

You (Kent) might want to consider making (more / any) high value per minute videos on YouTube for free **for you** because they will increase your reach and therefore your income as well as your impact. Short to the point videos a highly shareable and your target demographic (programmers) are short on time."

I do understand that Kent's thought process:

> "Make the free content without taking time (which I don't have) to increase the value per minute. Or don't make the free content at all."

holds true either way.

Again, I love Kent's content and is work and I just wrote this comment to re-iterate my point because I felt like I wasn't understood. And I understand that it won't change the fact that Kent does not have time 😄

**Comment by ultrox** [comment]
@janhesters It look like you are afraid to miss something of a value in those free videos which will be impact-full on you(I used to have this feeling), but as you said you are buying Kent's premium content feel free not to watch longer videos or free content at all, as you'll be able to pay for it in denser format. 

This is what I learn to be true from Kent and totally understand the point of long videos which I don't like, and I wait for his curated content I'm going to pay. 

From marketing side of things I would argue this is not good strategy mostly over the point of people who are attracted from long vs short videos as new audience, but this is up to Kent to work out on his own.

**Comment by kentcdodds** [comment]
Thanks for clarifying Jan. I think I did misunderstand you. I'll take your suggestion and that of @ultrox into consideration 👍

**Comment by ritchieanesco** [comment]
@janheaters Why not contribute by adding markers in the video to help people (like yourself)  find the content they need?

**Comment by janhesters** [comment]
@ritchieanesco Good idea! 🙏 

@ultrox Well, for me the feeling was less FOMO (though it's there), and more like: "Wow, this video by Kent looks interesting... Gosh, it's 60 minutes 😦 I bet other people feel the same. Let's give Kent some feedback 🤗 "

**Comment by ritchieanesco** [comment]
Yeh understand about the feedback but maybe this is where we can also do our bit to help Kent out with all his free work. Let us know @kentcdodds!

**Comment by jLouzado** [comment]
Apologies for the misunderstanding @janhesters , thank you for clarifying. 🤗

**Comment by kentcdodds** [comment]
People can definitely help out by doing things like adding comments to the youtube videos where the key takeaways are in the video. There are all kinds of ways to take my lower value-per-minute offerings and curate them :)
