### ISSUE TITLE
Semantic-release, commitizen and PRs

### ISSUE THREAD

**Issue by ValentinH** [kentcdodds/ama#58]
Hi,

I have been watching your course about how to write a good library and I would like to setup semantic-release and commitizen for a project I'm maintaining on Github. However, there is still a point that there is not totally clear to me.

When working on a new feature, I often create a PR as soon as I get a first commit and suffix it with "WIP" so I can discuss about the implementation and my choices with other users. When the PR is ready to merge there is often more than one commit so I have 2 questions:
- should I rebase/squash everything to keep only one commit like "feat(featureA) - implement featureA" (I think this is probably the best practice).
- If I want to do the above process, how would you do it with semantic-release/commitizen (the rebase process actually).

Thanks by advance,
Valentin

**Comment by kentcdodds** [comment]
Hi @ValentinH! Thanks for the question!

So yes, I would recommend that you [rebase](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history)/[squash](http://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit) everything so your commit history represents the actual changes that were made when it gets into master. I don't believe in that scenario you'd be able to use commitizen. And that's ok. It's not too difficult to write a [conventional changelog commit](https://github.com/ajoslin/conventional-changelog/blob/master/conventions/angular.md) by hand.

Good luck!

**Comment by ValentinH** [comment]
Thanks for the answer! I'll set it up soon I think :)
