### ISSUE TITLE
Am I using Hooks right?

### ISSUE THREAD

**Issue by igor-ribeiro** [kentcdodds/ama#580]
Hi Kent, thank for your awesome content!

I'm building a slider with arrows to show the next content, and the arrows need to show only when needed (if there is items to see). I did it and I'm just curious if I'm doing it right, like, using Hooks right.

https://codesandbox.io/s/zxwzmx7yo3

Thank you again.

**Comment by kentcdodds** [comment]
Here's the link to the video! https://www.youtube.com/watch?v=Mf--BTZq47E&t=0s&index=2&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

**Comment by igor-ribeiro** [comment]
Thank you so much, Kent. I would be awesome if the person who asked could participate to explain also. Anyway, thanks again!

**Comment by igor-ribeiro** [comment]
Just as a follow up, I though it would be OK to read value from DOM on `useLayoutEffect`, because that's what I understood from the docs, but I understood your explanation. I was just trying to find a case to `useLayoutEffect`.

https://reactjs.org/docs/hooks-reference.html#uselayouteffect

> Use this to read layout from the DOM and synchronously re-render.

**Comment by kentcdodds** [comment]
I think this is the key:

> and synchronously re-render.

You were reading layout from the DOM, but you didn't need to synchronously re-render.

**Comment by mettjus** [comment]
Hi all, and thanks Kent for the awesome teaching!!
@igor-ribeiro I elaborated on it to try to find a cleaner/simpler solution, also considering the index-based approach proposed by @kentcdodds, which is what I'd choose myself. Maybe you find it interesting/useful, maybe not... https://codesandbox.io/s/52x927q82x
