### ISSUE TITLE
Properly reacting to changes in nested objects.

### ISSUE THREAD

**Issue by arthurtyukayev** [kentcdodds/ama#581]
Lets say you have a form with a state that's shaped like this:
```
let initialState = {
  contact: {
    firstName: null,
    lastName: null,
    email: null,
    address: null,
  },
  billing: {
    card: null,
    expire: null,
    code: null,
}
```
While a solution would be to use `useState` in your component to update that data, a better solution would be `useReducer`, however let's say you want to validate the the email, card, and address using external services.
What would be the best way to React to those changes with `useEffect` since they're all nested within  the their own objects?

**Comment by kentcdodds** [comment]
Hi @arthurtyukayev,

Here's your answer! https://www.youtube.com/watch?v=dIPvgHEM-2s&index=2&t=0s&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u
