### ISSUE TITLE
How did you create new projects at Paypal

### ISSUE THREAD

**Issue by havenchyk** [kentcdodds/ama#583]
Hi Kent!

I recently read one of your emails and there were next lines

> At PayPal, you create a new app by clicking a few buttons in a web UI which will create your GitHub (enterprise) repo and setup CI, deploys etc. etc. The GitHub repo it creates for you is based on a repo called the "sample-app."

Could you please explain/show how that worked in details? Did you use Docker/Jenkins? Of course if it's not under NDA :)

Best regards,
Uladzimir

**Comment by kentcdodds** [comment]
Hi @havenchyk!

I actually never used (or even saw) the tool myself 😬 I just updated the repo that was the template for new projects. I didn't personally use docker, but I know that we do use docker AND jenkins in our CI and deploys.

But I no longer work at PayPal so I can't investigate this further 😅
