### ISSUE TITLE
Rationale (source) how getLabelText came to be

### ISSUE THREAD

**Issue by ultrox** [kentcdodds/ama#585]
Hey Kent, 
You said in your fem-2018 course about testing react application you wrote it without getByLabelText and similar utils, and some user motivated you to move include them. I was looking at your first blog post about it [here](https://blog.kentcdodds.com/introducing-the-react-testing-library-e3a274307e65) but it seams you already included those at the time you wrote it, so I was unable to find that discussion. Can you direct me to it on top of you head?

**Comment by kentcdodds** [comment]
Hi @ultrox!

Here's the full story: https://github.com/kentcdodds/react-testing-library/issues/16
