### ISSUE TITLE
Writing framework agnostic tests

### ISSUE THREAD

**Issue by iAziz786** [kentcdodds/ama#586]
Hey Kent,

I was wondering what is your views about the writing framework agnostic tests?

For example, hypothetically, A company might be writing there web app with Vue.js but since the release of hooks they got interested in React and wants to rewrite their application to React progressively.

How do you approach writing tests for these kinds of situation, in which they don't have to rewrite their entire tests for the new framework?

Apart from `react-testing-library`, I haven't used other libraries from [testing-library](https://testing-library.com/). How well testing libraries APIs matches with each other so moving tests to other frameworks is easy?

Thanks!
Aziz

**Comment by kentcdodds** [comment]
Hi @iAziz786!

I think I answer your question pretty well here: https://blog.kentcdodds.com/react-is-an-implementation-detail-and-course-faq-ee73b028745e
