### ISSUE TITLE
When and why useState is more benefic than useReducer?

### ISSUE THREAD

**Issue by tolotrasmile** [kentcdodds/ama#587]
Hi Kent.

Congratulations on the new design of your website kentcdodds.com.

Looking at the source code of your website, in the [Subscribe](https://github.com/kentcdodds/kentcdodds.com/blob/master/src/components/Forms/Subscribe.js) component , you used useState hooks to handle the state of this component.

My question is, is not it more optimized to use a useReducer here instead of several useState? If not, why?

I asked myself this question by referring to your Egghead lesson [here](https://egghead.io/lessons/react-simplify-a-component-reducer-with-the-react-setstate-hook?pl=react-hooks-and-suspense-650307f2)

**Comment by sapegin** [comment]
This post may be useful: [useReducer, don't useState](https://matthamlin.me/blog/2019/february/why-you-should-useReducer/).

**Comment by kentcdodds** [comment]
Thanks for the question @tolotrasmile! I made it today's newsletter!

Here it is: https://kentcdodds.com/blog/should-i-usestate-or-usereducer

**Comment by tolotrasmile** [comment]
Big thanks for your answer @kentcdodds, it's awesome. I really like this question: "When do I use one over the other?" :) Thank you.

**Comment by alexkrolick** [comment]
@kentcdodds other than the "aesthetic" reasons in the linked posts, `useReducer` is safe when states depend on each other, but `useState` can end up with stale closures. A good rule of thumb (I think this was from Sebastian or Andrew on the React team) is to use reducers whenever states need to "reset" together or state changes depend on other state values.

- https://twitter.com/sebmarkbage/status/1088238204229017601
- https://twitter.com/sebmarkbage/status/1062126253044428800
- https://github.com/reactjs/rfcs/pull/68#issuecomment-439314884
