### ISSUE TITLE
How to reuse a test setup with `afterEach(cleanup)`

### ISSUE THREAD

**Issue by janhesters** [kentcdodds/ama#588]
Hi Kent,

In [question 570](https://github.com/kentcdodds/ama/issues/570) (which you can close, since I found the answers for all my problems, though this is in a way a follow up) I asked about why a second `.toBeInTheDocument()`in my test would fail, even though it shouldn't.

Turns out the reason for it is that `afterEach(cleanup)` unmounts the component.

As a refresher, here is a simplified version of the tests:

```js
import React from "react";
import { render } from "react-testing-library";
import ContactList from "../components/ContactList";

describe("Contact List", () => {
  describe("given no contacts", () => {
    const { getByText } = render(<ContactList />);

    it("displays 'Name' in the header", () => {
      const actual = getByText(/name/i);
      expect(actual).toBeInTheDocument();
    });

    it("displays 'No Contacts'", () => {
      // 🔴This test fails ...
      const actual = getByText(/no contacts/i);
      expect(actual).toBeInTheDocument();
    });
  });
});
```

I got the tests working by moving `const { getByText } = render(<ContactList />);` from the "global" `describe` to each `it`.

My question now is: Is there a way to reuse the setup for tests and still enjoy the benefits **(X)** of `afterEach(cleanup)`? Or is it okay to call it over and over again because tests should be verbose?

I think people often stumble over tests where they want to test several things with a shared setup.

Thanks as always,
Jan

[> **(X)** Failing to call cleanup when you've called render could result in a memory leak and tests which are not "idempotent" (which can lead to difficult to debug errors in your tests).](https://testing-library.com/docs/react-testing-library/api#cleanup)

**Comment by kentcdodds** [comment]
Hey @janhesters! I think I answer this well in this blog post: https://blog.kentcdodds.com/test-isolation-with-react-6962d3f13d1f
