### ISSUE TITLE
How to compile hooks with babel?

### ISSUE THREAD

**Issue by damiano-carradori** [kentcdodds/ama#589]
Ehy Kent, I'm trying to write a library using the react hooks, but I got this error when I compile the module and I try to use it from another project:
<img width="787" alt="schermata 2019-02-11 alle 23 35 39" src="https://user-images.githubusercontent.com/13188995/52598441-00620600-2e56-11e9-9586-a4f6572dd0b8.png">

Any idea of what I can do to solve it?😫

PS: you can find the code here https://github.com/damiano-carradori/react-forms-crane/tree/HOOKS

**Comment by puemos** [comment]
Hey @damiano-carradori 
1. make sure that you have the correct version of `react-dom` dependency on the `demo` app.
2. maybe you should add it to the `peerDependencies`

**Comment by damiano-carradori** [comment]
I got it!! The problem is with `npm link`, because the linked module is trying to use the `react` module from its `node_modules` that is different from the one on the testing application. In order to solve it you have to remove the `node_modules` folder from the linked package.
