### ISSUE TITLE
What kind of music to you normally jam out to while coding?

### ISSUE THREAD

**Issue by darkfadr** [kentcdodds/ama#59]

**Comment by kentcdodds** [comment]
I generally jam out to music on Pandora with a mix of radio stations by the following artists:
 - Owl City
 - Lindsey Stirling
 - Ellie Goulding
 - Ingrid Michaelson
 - Sara Bareilles
 - Colbie Caillat
 - Michael Buble
 - Josh Groban
 - Phillip Phillips
 - Madilyn Paige

Sometimes I'll go with some classical, Piano Guys, Aaron Copeland, Broadway Musicals (genre), Film Scores (genre), or Solo Piano (genre).

During the holidays it's been Christmas stations on Google Music. Good stuff :-)

Thanks for asking!
