### ISSUE TITLE
Is devops  equivalent to L3 engineers

### ISSUE THREAD

**Issue by sourcecodebits** [kentcdodds/ama#60]
What are the roles played by devops? Are they the escalation engineers?

**Comment by kentcdodds** [comment]
That's a great question. Unfortunately I have very little experience in the world of devops. I'm afraid I'm not the one you should be asking! Good luck finding your answer. Feel free to post any resources you discover!

**Comment by Cycododge** [comment]
DevOps is a mindset rather than a role or department. To be the most successful everybody must be on board, because it is a significant cultural change. ( http://devana.rs/blog/devops-is-a-culture-not-a-job-description )

**Comment by sourcecodebits** [comment]
Thanks for steering me into that direction.Unable to open the above link,but quick search sends me to the wiki https://en.wikipedia.org/wiki/DevOps good info.

**Comment by joshtoo** [comment]
@Cycododge - While I completely agree, the reality of life as the "DevOps Engineer" in my experience would be easily summed up as the Swiss Army Knife on the Development Team. We are usually strong Systems Engineers, well versed in the CI / build / release process while being able to cover dev positions for a bit more bandwidth when needed.
