### ISSUE TITLE
How did you develop your code style

### ISSUE THREAD

**Issue by ultrox** [kentcdodds/ama#602]
Hey Kent, 
I was reading your code quite a bit, mostly your node stuff(kcd-scripts, dom-testing-library), and I can't but wonder how did you develop your code style. 

You are using very small functions initial and building more complex but also small functions out of your small functions :D. And then you start. 

 Also I notice you use a lot packages from sindresorhus, I assume he had a lot of influence on you, at least initially, as this reminds me little bit on what he dose.

It seams like you are using functional programming by composing all those small function but without more advanced concepts, like (compose left/right). I would appreciate a resource.

**Comment by justsml** [comment]
![display](https://user-images.githubusercontent.com/397632/54485131-0a05d180-4839-11e9-993d-d49d44ef2321.gif)

❤️ @kentcdodds 

Seriously though, @ultrox brings up a great question! 

While Kent can elaborate on his approach to this design question, I did a related talk last year on the virtue of tiny functions called [Heroic Refactoring](https://www.youtube.com/watch?v=X79oCNqandc&feature=youtu.be&t=51m44s) .

I'm doing a follow up talk next month (Apr. 18th, 2019) on the many benefits of this technique and how it fits into the larger scope of other "refactoring" goals/techniques. 

Check the page here [Denver NodeJS Meetup](https://www.meetup.com/Node-js-Denver-Boulder/events/nprrhpyzgbxb/) to RSVP or get the stream link. (Details will be added within the week.)

**Comment by ultrox** [comment]
I would still love to get answer to the question even though I recognized it later on, at least to me this reminds me on functional style with all those partial functions, and naming conventions used are very much what Zakas was mentioning on his grate book 'Maintainable Javascript'. 

@justsml I love the name 'Heroic Refactoring' :), will watch the talk now, thanks!
