### ISSUE TITLE
Need to incrementally create a kcd-scripts at my company, any advice?

### ISSUE THREAD

**Issue by jLouzado** [kentcdodds/ama#609]
Two Part Question:
1. What do I need to know to be able to write a `kcd-scripts` like project from scratch.
1. There are several projects at my company at various levels of upkeep, maturity of dev-setup, etc.
    - Do I first work on slowly bringing existing projects onto some kind of internal `kcd-scripts` (which I'm guessing needs to be done manually), or
    - do I create a project generator that atleast sets up new projects properly?

**Comment by kentcdodds** [comment]
Hi @jLouzado!

Here's your answer: https://www.briefs.fm/3-minutes-with-kent/94

Good luck!

**Comment by ultrox** [comment]
video Kent mentiond https://www.youtube.com/watch?v=ZWfY-v1DCTE

**Comment by jLouzado** [comment]
Sorry, by `Generator` I meant something like `create-react-app` that bootstraps a project to depend on `react-scripts`.

Do you have something similar like that for `kcd-scripts` @kentcdodds or do you manually require the package?

**Comment by kentcdodds** [comment]
Yes, I do: https://github.com/kentcdodds/generator-kcd-oss
