### ISSUE TITLE
How do you choose your next goal?

### ISSUE THREAD

**Issue by phillipdodd** [kentcdodds/ama#610]
Have you ever had times, maybe right after having accomplished a particular tech goal, that you aren't sure what your next goal is/should be?

If so, what advice would you give to someone in a similar situation? My enthusiasm is still there, I am just having a difficult time knowing where to channel it next!

**Comment by kentcdodds** [comment]
Hi @phillipdodd!

Here's your answer: https://www.briefs.fm/3-minutes-with-kent/93
