### ISSUE TITLE
npm bug?not sure

### ISSUE THREAD

**Issue by nellysattari** [kentcdodds/ama#612]
Hi all,

When I use "npm i  lib-name <local-folder-path>" the result looks different from the "npm i lib-name". 
So when I run my webpack I will get this error :
Error: Couldn't find preset "babel-preset-env" relative to directory "D:\\local-folder-path"

I don't understand why the result should be different?? And what is the solution?

Regards,
Nelly

**Comment by nellysattari** [comment]
By the way the app I installed uses Babel 7 tand the other one which used the library applied on older version of Babel

**Comment by kentcdodds** [comment]
Hi @nellysattari,

I honestly have no idea. I use a mac and it doesn't make a difference if I have extra whitespace around things in a command. I'm not sure how things work on Windows. Good luck.
