### ISSUE TITLE
What technology are you using in your new blog?

### ISSUE THREAD

**Issue by SteveALee** [kentcdodds/ama#614]
Hi Kent

In your latest email to subscribers you described why you finally moved your blog from Medium (good plan).

Your message left me keen to know what tech you used? From your comments on time spent I guess there was quite a bit that you rolled yourself or significantly configured.

I'm thinking of trying vuepress for some solid vue experience to ballance React. That or ReactStatic.

**Comment by kentcdodds** [comment]
Hi @Steve!

[Here's your answer!](https://www.briefs.fm/3-minutes-with-kent/92)

**Comment by SteveALee** [comment]
Thank you! Gatsby docs should get even better now Marcy Sutton is on the outreach team. MDX looks useful too.

Gotta love egghead!!!!
