### ISSUE TITLE
Type Checking for React Custom hooks

### ISSUE THREAD

**Issue by NaviMarella** [kentcdodds/ama#616]
Hi Kent,

How do we do type checking for custom react hooks ??

Most of the projects use PropTypes library, and adoption for React-Typescript by the community is not at expected scale. 

Do you any suggestions for type checking hooks.

**Comment by kevinwolfcr** [comment]
PropTypes library is for testing component props.

If you have properly set up Flow or TypeScript, then you can typecheck your functions as you would do with any regular function.

```typescript
interface CounterHook {
  count: number
  increment: (step: number) => void
  decrement: (step: number) => void
}

function useCounter(initialCount: number = 0): CounterHook {
  const [count, setCount] = useState(initialCount)
  const increment = (step: number = 1): void => setCount(count + step)
  const decrement = (step: number = 1): void => setCount(count - step)

  return {
    count,
    increment,
    decrement,
  }
}
```

**Comment by kentcdodds** [comment]
Hi @NaviMarella!

I recommend using TypeScript as @iamkevinwolf suggests, but if you want some runtime type checking with prop types, here's one way you could do it: https://twitter.com/kentcdodds/status/1148593489304858630
