### ISSUE TITLE
Is it possible to make nested menus in dropdown with downshift

### ISSUE THREAD

**Issue by Guria** [kentcdodds/ama#617]
Hey, Kent.
First of all, thank you for all your great work and especially for downshift-js.
I have a need to build an accessible dropdown with nested menus.
And I'd like to hear your thoughts and advice on it before I started to dig into trying to implement it with downshift myself.

Here is example:
![image](https://user-images.githubusercontent.com/36270/53486394-02f16c00-3aa2-11e9-9097-f6df9582b0b3.png)

Would be really appreciated for any kind of feedback.

**Comment by kentcdodds** [comment]
Yes, I believe this should be 100% possible with downshift. :)
