### ISSUE TITLE
Avoid re-rendering whole List

### ISSUE THREAD

**Issue by qiandongyq** [kentcdodds/ama#619]
I have a list of lessons
```javascript
const initLessons = {
	"lesson 1": {
		name: "lesson 1",
		checked: true,
		status: {
			isFinished: false,
			// something else
		}
	},
	// reset of lessons
}
	
```

I want to able to toggle `checked` value and `status.isFinished`.
There are have three Components related to this.

```javascript

const reducer = (state, action) => {
  switch (action.type) {
    case "TOGGLE_ONE_CHECK":
      return {
        ...state,
        [action.payload.name]: {
          ...state[action.payload.name],
          checked: !state[action.payload.name].checked
        }
      };
	default:
		return state;
  }
};

const [lessons, dispatch] = React.useReducer(reducer, initLessons);

const toggleChecked = (name) => dispatch({ type: "TOGGLE_ONE_CHECK", payload: name })

const Screen = React.memo(()=> <LessonList lessons={lessons} toggleChecked={toggleChecked}/>)

const LessonList = React.memo(() => 
		<div>
			{_.map(lessons, (lesson, index) => {
            return (
              <Lesson
                lesson={lesson}
                key={index}
				toggleChecked={props.toggleChecked}
              />
            );
          })}
		</div>
	);

const Lesson = React.memo((props) => <Lesson toggle={() => props.toggleChecked(props.lesson.name)} />)
```

**The problem is the every time I change checked value of one of item in the list. It re-rendering whole list.**

Sorry for my English and thanks for the help

**Comment by kentcdodds** [comment]
> The problem is the every time I change checked value of one of item in the list. It re-rendering whole list.

Can you explain why this is a problem? Why is it a problem that the whole list lis re-rendered?

**Comment by qiandongyq** [comment]
@kentcdodds There isn't problem now, but I want to see if there is a way to avoid re-rendering whole list if there is only one item in the list is changed value. Just curious and maybe some performance boost? 

Thanks for quick reply

**Comment by kentcdodds** [comment]
Typically I wait for performance to be a problem before I worry too much about it. How many items are in the list?

**Comment by qiandongyq** [comment]
There are around 90 items in the list. If the way I implement is ok, then I won't worry for now. Thanks for the help

**Comment by kentcdodds** [comment]
Well, it looks like the code you're giving me is incomplete so I can't really speak to that, but if it works then I would say go with it. Don't worry so much about performance until it's a problem. In the 3.5 years that I've been building apps with React, I've not once had a performance problem that needed `shouldComponentUpdate`, `React.memo`, or `PureComponent`.

Good luck!
