### ISSUE TITLE
Can you show us a picture of your current setup?

### ISSUE THREAD

**Issue by deezahyn** [kentcdodds/ama#62]
I'm looking forward to your dual 27" monitor setup!  Glad you figured it out.

**Comment by kentcdodds** [comment]
I'm still actually waiting for some things to arrive for my setup to be complete. I'll probably do a video walkthrough when I get it all set up :-)

**Comment by kentcdodds** [comment]
![img_20160102_203452](https://cloud.githubusercontent.com/assets/1500684/12077156/568f721a-b190-11e5-8fff-a3d060386632.jpg)

Here's what it looks like so far though :-)

**Comment by deezahyn** [comment]
sweet setup @kentcdodds !

**Comment by kentcdodds** [comment]
Video coming soon :-)

![img_20160106_164405](https://cloud.githubusercontent.com/assets/1500684/12158374/aa85683a-b496-11e5-9a24-f82c9af7af93.jpg)

**Comment by kentcdodds** [comment]
The video will be here when it's finished uploading. https://youtu.be/r8hU2wpZifY

Let me know if you have any further questions :-)

**Comment by deezahyn** [comment]
I'm digging it! Probably going to get a dual monitor setup as well.  Thanks @kentcdodds
