### ISSUE TITLE
Advanced Prop Validation and Throwing Errors

### ISSUE THREAD

**Issue by akatechis** [kentcdodds/ama#621]
Hi Kent, I just recently stumbled on this series of videos on Youtube, and love the small, digestible format.

I have a question re: best practices around prop validation and throwing errors during a component's render. Suppose I have a `PageLayout` component that expects to receive exactly 2 children (a left and right side of the page that it will render into its own surrounding markup).

Is it Ok for this component to throw an error when rendering? I don't expect to let these things into production (famous last words). Is there a better way of handling these sorts of issues?

https://codesandbox.io/s/jjx8j3748y

Thanks!

(also, as an aside question, is it Ok for a component to pull apart the `children` array like that?)

**Comment by kentcdodds** [comment]
Hi @akatechis!

Here's your answer: https://www.youtube.com/watch?v=mJS6kSq0Wog&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u
