### ISSUE TITLE
Do you think we should always useCallback on custom hooks?

### ISSUE THREAD

**Issue by kevinwolfdev** [kentcdodds/ama#623]
Hi Kent!

I want to know what are your personal position on always returning callbacks with `useCallback` from custom hooks.

### The problem
I was creating a test hook, a `useCounter` one

```javascript
function useCounter() {
  const [count, setCount] = useState(0);
  const handleDecrement = () => setCount(c => Math.max(c - 1, 0));
  const handleIncrement = () => setCount(c => Math.min(c + 1, 25));

  return {
    count,
    handleDecrement,
    handleIncrement
  };
}
```

Having this component hierarchy:

```
App (uses 5 useHook's)
|- Counter
|-- CounterButton (-)
|-- CounterButton (+)
|- Counter
|-- CounterButton (-)
|-- CounterButton (+)
|- Counter
|-- CounterButton (-)
|-- CounterButton (+)
|- Counter
|-- CounterButton (-)
|-- CounterButton (+)
|- Counter
|-- CounterButton (-)
|-- CounterButton (+)
```

When I started doing `console.log` on the render of `Counter` and `CounterButton` components, I'd noticed that when I changed the value of any counter, for example the first one, it caused the re-render of all the other `Counter`s and the `CounterButton`s within them, even when using `React.memo`, because when `App` was re-rendering, each of the callbacks returned by `useCounter` was being re-declared.

### The solution

I did implemented `useCallback` for those callbacks, which accomplished my desired behaviour, slightly modifying the `useCounter` hook.

```javascript
function useCounter() {
  const [count, setCount] = useState(0);

  const handleDecrement = useCallback(
    () => setCount(c => Math.max(c - 1, 0)),
    []
  );

  const handleIncrement = useCallback(
    () => setCount(c => Math.min(c + 1, 25)),
    []
  );

  return {
    count,
    handleDecrement,
    handleIncrement
  };
}
```

### THE QUESTION

So my question for you is: **Do you think we should _always_ `useCallback` on custom hooks?**, or do you see it as an early optimisation? My concern is that if `Counter` component where more complex, then the user will start to experience some performance issues, because of the lot of re-renders.

https://codesandbox.io/s/qzkn0zwjvq

**Comment by DevanB** [comment]
I'd be curious to @kentcdodds to also answer what `useCallback` is also in this response. I've seen him use it in some of this latest blog posts, but I don't _get_ what it is, yet. 😄
