### ISSUE TITLE
YT Live stream request - interesting situation with setInterval and hooks

### ISSUE THREAD

**Issue by ChaituKNag** [kentcdodds/ama#624]
Hi Kent,

This is in response to your Twitter [post](https://twitter.com/kentcdodds/status/1102647400915582981?s=20) that you posted on 5th March 2019.

I am raising this AMA just to remind you about my request for a quick live-stream on which approach/solution that you finally chose for this particular situation (You mentioned about useReducer in the thread).

Your original post was this:

> So I've got an interesting situation I wonder how you all would solve this problem: 
> (link: https://codesandbox.io/s/p35qwvr6rq) 
> codesandbox.io/s/p35qwvr6rq
> 
> The issue is that sometimes the setInterval callback (which updates the lapse time) is getting called _after_ the handleClearClick callback sets the lapse time to 0.

![kent-ama-request](https://user-images.githubusercontent.com/13428505/53896278-b38add00-4059-11e9-8f94-b592f52fce86.png)

**Comment by kentcdodds** [comment]
Done! https://www.youtube.com/watch?v=Vi_46Io0UZc&index=2&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u&t=0s
