### ISSUE TITLE
What's the difference?

### ISSUE THREAD

**Issue by LBWright** [kentcdodds/ama#626]
I see a lot of your workshops around Youtube, Frontend Masters, Egghead, and now your Testing Javascript Course.

What is the difference between your Testing Javascript course and some of your other content? Why should I pay $200 for the course?

I ask this because I love your testing material and would really like to purchase the course but it would need to be justified to my wife (if I purchase personally) or my boss (if the company will do it for me).

**Comment by kentcdodds** [comment]
Hi @LBWright! Here's your answer: https://www.briefs.fm/3-minutes-with-kent/95
