### ISSUE TITLE
How to write E2E tests for serverless applications?

### ISSUE THREAD

**Issue by janhesters** [kentcdodds/ama#629]
Hi Kent 👋🏻

[Serverless](https://medium.com/@dabit3/full-stack-development-in-the-era-of-serverless-computing-c1e49bba8580) is a small but rapidly growing field. But because it's new, there isn't that much information out there. Since you are one of the loudest and most credible voices out there when it comes to testing, here is my question:

I'm building a serverless web app with React powered by AWS Amplify. I'm writing my E2E tests using Cypress. Up until now I only wrote container components and mocked the state. I wrote tests to ensure everything works fine.

Now I connected my containers with logic. I added auth and a GraphQL backend (`amplify add auth` & `amplify add api`). I now face two problems:

1. The tests don't even start, because the user is logged out. In the cypress docs it says that going through the log-in steps using the UI is bad practice. You should instead make a direct request with credentials to log you in. So I looked at the network tabs when logging in and found out that Amplify makes 4 different requests to the cognito servers, none of which I understand (since the payload seems to be hashed). How would you automate login when using AWS Amplify with Auth, so that you do not have to go through the steps using the UI?
2. Furthermore the docs say you should seed data, so that you control the state your application is in during the tests. How would you seed your data or control your state using AWS Amplify? I think it would be bad to constantly add or create resources during your tests, wouldn't it?

How would you write E2E tests for serverless applications?

Thank you very much 🤗

**Comment by kentcdodds** [comment]
Hey @janhesters! Great question. I'll help with what I know: [Episode 96](https://www.briefs.fm/3-minutes-with-kent/96)

**Comment by janhesters** [comment]
@kentcdodds Thanks for answering! I will write shorter questions in the future so you will have it easier to read 🤗 

PS: Jan is pronounced as the 'y' in 'yes' 😉
