### ISSUE TITLE
angular project: add angular to package dependencies?

### ISSUE THREAD

**Issue by JohnnyTheTank** [kentcdodds/ama#63]
If I publish an angular tool, should I add „angular“ to dependencies in bower and npm?
For example this this repos: https://github.com/JohnnyTheTank/angular-vimeo-api-factory

The same with bootstrap for this repo: https://github.com/JohnnyTheTank/bootstrap-block-grid

I think I should add "angular" or "bootstrap" to dependencies, but I'm not sure. What is the right way?

Thanks for your help :)

**Comment by kentcdodds** [comment]
I updated [my blogpost](https://medium.com/@kentcdodds/how-to-distribute-your-angularjs-module-e04d4dd58ddc#.1n8dmocqo) to my recommendation for that. Ignore bower. Don't trouble yourself with it. Good luck! :+1: Thanks for the question!
