### ISSUE TITLE
How did you become a member of the TC39 Committee?

### ISSUE THREAD

**Issue by jsjoeio** [kentcdodds/ama#630]
I know you are a member and have been for a while.

I'm curious though - what's the story behind that? How did you get involved? What are your intentions for being involved?

And maybe a follow-up question, if someone were interested in helping JavaScript as a language progress forward, what advice would you give? :)

**Comment by kentcdodds** [comment]
Hi JSJoe! Here's my answer: https://www.briefs.fm/3-minutes-with-kent/98

Note, I don't think that I mentioned this in the audio, but I'm no longer a member of TC39 because I'm no longer employed by PayPal.
