### ISSUE TITLE
Testing axios interception with react-testing-library

### ISSUE THREAD

**Issue by visarts** [kentcdodds/ama#631]
I have an Interceptor component that sits around and monitors axios calls, updating headers based on user info, amongst other things. But the old tests were using enzyme, and now that it's been refactored to be a functional component using hooks, all those tests are failing with little recourse. I could post some of the old tests here but I'd like to know your methodology to approach a component like this, and what should be tested and how. Thanks so much!

https://codesandbox.io/s/w66v095r47

**Comment by kentcdodds** [comment]
Hi @visarts! Here's your answer: https://www.youtube.com/watch?v=YJKtzS1jGsI&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

**Comment by etienne-dldc** [comment]
@kentcdodds Did you know you can freeze a sandbox ? That way if you edit it and change it it will create a fork instead of saving it 😎 
![Screenshot 2019-03-18 at 22 19 17](https://user-images.githubusercontent.com/14336608/54564431-15d5cd00-49cc-11e9-93e9-935da75db3e0.png)

**Comment by kentcdodds** [comment]
Oh! That's fantastic. Thank you!!
