### ISSUE TITLE
Is it okay to process data in useEffect()?

### ISSUE THREAD

**Issue by janhesters** [kentcdodds/ama#632]
Hi Kent,

first the TL;DR (so that you can summarize it quickly and don't have to stumble while reading it out loud, in case you answer it publicly):

Is it okay to process data in `useEffect`, if I make sure the effect only runs when the data changes by providing the data as a dependency? Like this:

```js
function MyComponent() {
  const [obj, setObj] = useState(initialObj);

  useEffect(() => {
    setObj(processedData(data));
  }, [data])
}
```

Now the long version why I ask this question:

I recently started using [`react-apollo-hooks`](https://github.com/trojanowski/react-apollo-hooks). Contrary to `react-apollo` this library does NOT expose a `onCompleted` handler. The API is pretty intuitive (see below). I need to process the result of a query, so here is what I planned on doing:

```js
function ContactList() {
  const [contacts, setContacts] = useState([]);
  // Yes, weirdly this package exposes objects and not arrays 😅
  const { data, error, loading } = useQuery(queries.listContacts);

  useEffect(() => {
    if(!error && !loading) {
      setContacts(
        // Replaces all `null` values in list of objects with empty strings
        replaceNillInArrayWithEmptyString(data.listContacts.items)
      );
    }
  }, [data, error, loading])
 return (
  // ...
  )
}
```

I don't know if this is okay. It feels kinda hacky. 

In any case, thank you as always! 🔥📈 🎓

**Comment by kentcdodds** [comment]
Here's the answer to your question: https://www.briefs.fm/3-minutes-with-kent/97

**Comment by janhesters** [comment]
@kentcdodds Thank you very much! 😊

**Comment by janhesters** [comment]
@kentcdodds Btw, great pronounciation 👌
