### ISSUE TITLE
How to `useContext` with a Functional Comonent as Provider

### ISSUE THREAD

**Issue by httpJunkie** [kentcdodds/ama#644]
# Refactoring Class based Provider to Functional Component

I have been watching your [Simplify React Apps with React Hooks](https://egghead.io/courses/simplify-react-apps-with-react-hooks) series on EggHead along with other videos about how to use React Hooks with the Context API. After I thought I had most of the concepts understood, I built a demo to help reinforce my learning. I created a mostly functional component filled demo using Hooks to consume context in my many functional components in the demo.

In my own attempt to turn the class-based provider into a functional component and switch it from using `this.state` and `setState` to instead utilize Hooks and `useState`, I ran into a kind of chicken and egg scenario. 

Below is a StackBlitz demo showing a working example, but my provider is a class-based component:

[StackBlitz: react-usecontext-class-provider](https://stackblitz.com/edit/react-usecontext-class-provider?file=index.js)

I have tried myself to convert that class-based provider component to a functional one and I'm stuck, my context doesn't know about my attempt to create a `changeTeam()` function to modify state. Here is a demo showing where I got stuck with this refactoring:

[StackBlitz: react-usecontext-functional-provider](https://stackblitz.com/edit/react-usecontext-functional-provider?file=index.js)

When we click on the button that is supposed to update the state using Hooks understandably it doesn't know what `changeTeam()` function is.

## Error:
    context.changeTeam is not a function

**Comment by arackaf** [comment]
Your setState call is wrong - it's overwriting tons of state it shouldn't be. Change to the functional style. 

```js
changeTeam: (team) => setProfile(profile => ({ ...profile, team: `Kendo${team}`}))
```

**Comment by httpJunkie** [comment]
`setProfile`, but who's keeping track, that worked perfectly. Thanks Adam!

**Comment by arackaf** [comment]
Right - for legacy reasons I'll sometimes refer to the update function of useState as `setState` - not sure if there's a more standard name for it
