### ISSUE TITLE
Would you go to ForwardWeb4 or ReactConf 2016? 

### ISSUE THREAD

**Issue by thejones** [kentcdodds/ama#65]
Assuming that you had purchased a ticket for ForwardWeb4 and a single day training session, but then you were selected to go to ReactConf 2016, which would you chose and why? Asking for a friend...

**Comment by kentcdodds** [comment]
Hi @thejones, thanks for the question.

I'm assuming you're talking about [ForwardJS](http://forwardjs.com/summit) and [React Conf](http://conf.reactjs.com/). I'm actually going to both of these conferences. If I'm not misunderstanding you, there's a week between them. Go to both of them! :D That's what I'm doing :D
