### ISSUE TITLE
Subscribing and unsubscribing from a Promise in React.useEffect

### ISSUE THREAD

**Issue by JulianG** [kentcdodds/ama#652]
Hi Kent,

I just finished watching [Safely setState on a Mounted React Component through the useEffect Hook](https://egghead.io/lessons/react-safely-setstate-on-a-mounted-react-component-through-the-useeffect-hook).

In this lesson we need to cancel a GitHub client request when the function component is unmounted to prevent setting state if the promise resolves afterwards.
Because the client doesn't provide a way to unsubscribe, the lesson uses another useEffect and useRef to keep a "mountedRef" boolean. Something like:

```js
const mountedRef = useRef(false)
useEffect(() => {
  mountedRef.current = true
  return () => (mountedRef.current = false)
}, [])
```

I think the same can be achieved in a simpler way:

```js
function App({ delay }) {
  const [state, setState] = React.useState("loading...");
  React.useEffect(() => {
    let subscribed = true; // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    client
      .fetchData(delay)
      .then(value => (subscribed ? setState(value) : null))  // <<<<<<<<<<<<<<<<<<<<
      .catch(error => (subscribed ? setState(error.toString()) : null));  // <<<<<<<

    return () => (subscribed = false);  // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  }, [delay]);
```

I made an example: https://codesandbox.io/s/3rzpk225qq

Do you see any problems with this implementation?

Thanks,
Julian

**Comment by kentcdodds** [comment]
Clever! (In a good way). I think that works just fine! 👍
