### ISSUE TITLE
Learning and Teaching 

### ISSUE THREAD

**Issue by tanvirraj** [kentcdodds/ama#653]
how do you learn so many things this quick and fast?
how you decide what you will teach 
when you decide what topic you will teach, 
what's your process 

i wants' to be a teacher like but don't know how to start 
i am working in react almost over a year and working very large application 
but every time I want to teach something it comes to my mind that 
there are already resource about that for learning 
and why people read my blog post or watch videos

**Comment by kentcdodds** [comment]
Thanks for the question @tanvirraj. I did my best to answer you [here](https://www.briefs.fm/3-minutes-with-kent/107). Good luck!

**Comment by tanvirraj** [comment]
@kentcdodds Thank you sooo much
