### ISSUE TITLE
React.cloneElement 

### ISSUE THREAD

**Issue by Alimudassar111** [kentcdodds/ama#656]
I was watching your FEM's advance pattrens course.I have confusion about the React.cloneElement. I heard that it just makes a new clone of the provided element and can pass some new props to the newely created element. 
const {children: Children } = this.props
React.cloneElement(Children, {
on: this.state.on
})

so can we no do it like <Children on={this.state.on}/>

Isn't it the same ?

lets say you have 3 childs....
const {children: Children } = this.props
React.Children.map(Children, (EachChild) => <EachChild on={this.state.on}/>)

are these both approaches doing same thing either directly passing props to component or by using colne Element.

Thanks a lot.

**Comment by kentcdodds** [comment]
Try it and see if you can figure out why it doesn't work 😉

**Comment by Alimudassar111** [comment]
Thanks, I figured it out. If I don't clone the element, all the props being injected on that component will be lost. besides this, it's fine ....
