### ISSUE TITLE
native-testing-library vs react-native-testing-library

### ISSUE THREAD

**Issue by sJJdGG** [kentcdodds/ama#660]
Hi Kent

Great work on testing-library.

I've noticed you recommend native-testing-library over react-native-testing-library as the recommended testing library for react-native especially considering that it looks like the community is moving toward RNTL and RNTL explicitly acknowledges your work as the inspiration.

Is there any specific reason about this?

Do you find RNTL different in API from what you think should be and NTL is the correct one in implementing those goals?

Overall which one do you recommend and why? What things do you find better in the other one and what things should be fixed/added to make it a right choice?

**Comment by kentcdodds** [comment]
When react-native-testing-library was created, I mentioned to the creators at Callstack that I wasn't happy with the shallow rendering capabilities or the `getByType` or `getByProps` APIs. They held firm and shipped those things anyway.

When native-testing-library came around, not only did it not include those things, but it also added some queries that were much more in the spirit of the *-testing-library philosophy. So I'm much happier with native-testing-library for that reason.

I'm currently in conversations with both authors to talk about consolidating, but for now I'm recommending everyone use native-testing-library. I'm really happy with it.

Good luck!

**Comment by sJJdGG** [comment]
Thanks!

Gonna use NTL for the time being and keep a close eye on RNTL for the mentioned changes.
