### ISSUE TITLE
Front end masters courses

### ISSUE THREAD

**Issue by Mhmdabed11** [kentcdodds/ama#665]
Hello Kent, I recently started watching react videos on fem and they are awesome, thank you ! Will you be giving any course soon explaining react advanced patterns with hooks?

**Comment by kentcdodds** [comment]
Hi @Mhmdabed11! I've already updated my material and gave it at React Amsterdam last week. It went great and I'm excited to do some more! I'm not sure whether I'll be able to make a trip out to get it recorded for Frontend Masters this year or not though. If you subscribe to https://kcd.im/news you'll definitely not miss any announcements about it though. Thanks!
