### ISSUE TITLE
How to reach the next level?

### ISSUE THREAD

**Issue by WendellAdriel** [kentcdodds/ama#672]
Hey, hello @kentcdodds.
I'm a huge fan of yours. I really like your tweets, articles, workshops, etc. First of all, I want to thank you for all the help in the Open Source community and all the resources you provide for everyone.

I'm sending this message to ask for help with something. I work with development since 2009, but I consider myself an ordinary developer, I'll explain better. I'm kinda good at what I do, but if I compare myself to someone like you, Evan You, Sarah Drasner, Dan Abramov, etc, I'm almost a baby with my first steps. I know how to build a product code, but sometimes I check issues in the React and Vue repos and I don't even understand a lot of things, so that's what I'm talking about. I'm on a diff level.

I love to work with code and the only thing I love most is teaching. I already led some workshops in companies I worked on and on some local meetups. One of my dreams is to someday be able to work as a core member of awesome Open Source projects, but I really don't know how can I get to this level. As I said, I don't see myself as an awesome dev, but I learn things fast and I'm curious and passionate.

Since you're an amazing person and someone that got into this world of teaching a lot of people and creating lots of great Open Source project, can you give tips on how can I level up my game?

Sorry for the huge message, btw.
Best regards,

**Comment by kentcdodds** [comment]
Hey @WendellAdriel! This is a great question. Here's the answer: [#111](https://www.briefs.fm/3-minutes-with-kent/111)

And here's the blog post I was talking about: [Solidifying what you learn](https://kentcdodds.com/blog/solidifying-what-you-learn)

**Comment by WendellAdriel** [comment]
Thank you so much @kentcdodds!!!
