### ISSUE TITLE
Can you please show how do you strongly type a react app with hooks?

### ISSUE THREAD

**Issue by otrebu** [kentcdodds/ama#674]
For example with createContext is quite annoying to have to declare the context twice.
I first create it with some place holders value and using an interface, so that I make it properly strongly typed.
But then in my provider I shape the context again, with its actual functionality.
And then obviously there is the interface for it.

This is a good article: https://levelup.gitconnected.com/usetypescript-a-complete-guide-to-react-hooks-and-typescript-db1858d1fb9c

But when showing the context it does something similar.

Thank you in advance!

**Comment by kentcdodds** [comment]
Here's how I solve it: https://twitter.com/swyx/status/1122280909301002242
