### ISSUE TITLE
What does the C in your middle name stand for?

### ISSUE THREAD

**Issue by janhesters** [kentcdodds/ama#675]
Hi Kent,

I was wondering this for a while, looked in your AMA and didn't find anything. What is your middle name? 😄

**Comment by kentcdodds** [comment]
Christopher

My older sister wanted my first name to be Christopher and she called me that for a long time when I was a baby, but eventually relented 😆

**Comment by janhesters** [comment]
@kentcdodds Thanks for the answer 😊
