### ISSUE TITLE
Allow us to unsubscribe from workshop notifications

### ISSUE THREAD

**Issue by janhesters** [kentcdodds/ama#682]
Hi Kent,

As you know I'm a huge fan of your content. I really enjoy your newsletter and I definitely want to know if you have new courses on egghead or self made ones like testingjavascript.com.

But, I have no interest in online workshops. I tried to update my convert kit profile after receiving one of your mails to disable mails about workshops, but I could only find a setting to update my email and my name.

Could you please add settings to convertkit so that we can choose for which type of contents we get mails?

Again, I love your video content and your blog. I just dislike the mails about the workshops.

Thank you 😊

**Comment by kentcdodds** [comment]
I'll give it some thought @janhesters  :)
