### ISSUE TITLE
Religion, Meetups, and Alcohol

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/ama#685]
I received this as an email from someone who prefers to be anonymous:

---

Hi Kent,

Pleasure meeting you! You're an absolute rockstar and inspiration.

As a practicing Muslim, living in accordance with my religion is priority `#1`, which I feel is something you can appreciate.

I also feel you appreciate developers trying to level-up their career, market, and work for themselves to generate wealth. Part of marketing is meeting people, which meetups are great for!

Unfortunately for whatever reason, 99% of meetups offer alcohol, which is forbidden in Islam to even be around. 

If I may ask you two questions:
1. Does your faith share this restriction?
2. If yes, how do you get around it? If no, how would you advise someone getting around it?

I'm shy to publicly ask this question, so anonymity's dearly appreciated. Thank you for the value you continue to provide. ❤

**Comment by kentcdodds** [comment]
Here's your answer: https://www.briefs.fm/3-minutes-with-kent/110

One thing that I would add is that if you do talk with them about this you could reference React Rally's reasons for not providing alcohol and suggest that it's about inclusion. It's also a way that they could save money on the meetup and maybe do other even cooler things with that money (like fly speakers in or do prize giveaways).

Here's what React Rally has said in previous emails to attendees about this subject:

> In an effort to make React Rally as inclusive as possible alcohol will not be served at the conference. We recognize that for a number of reasons people may find alcohol objectionable, and we want to avoid putting anyone in an uncomfortable situation. At the same time, we also acknowledge that many will want to partake in libations. There are many establishments surrounding the venue that you may enjoy.

Good luck!

**Comment by dieillusion** [comment]
Poor Muslim. How does he survive in this cruel world?

**Comment by kentcdodds** [comment]
That sounds like sarcasm and it is totally inappropriate and against the code of conduct: https://github.com/kentcdodds/ama/blob/master/CODE_OF_CONDUCT.md

Please apologize and refrain from this behavior in the future or you will find yourself blocked.
