### ISSUE TITLE
can we use react-testing-library with redux? Do you have an example for reference. I am seeing issue with reducers.

### ISSUE THREAD

**Issue by vinay0458** [kentcdodds/ama#687]

**Comment by kentcdodds** [comment]
Yes you can: [here's an example](https://codesandbox.io/s/github/kentcdodds/react-testing-library-examples/tree/master/?fontsize=14&module=%2Fsrc%2F__tests__%2Freact-redux.js&previewwindow=tests)

**Comment by kentcdodds** [comment]
In the future, please ask questions like this on [the community support site](https://spectrum.chat/testing-library) :)

**Comment by vinay0458** [comment]
Hi Kent,

Thanks for your reply!
You are Awesome.

Regards
Vinay
