### ISSUE TITLE
Would it be possible to use Formly for on Angular 2 using UpgradeAdapter?

### ISSUE THREAD

**Issue by ricsmania** [kentcdodds/ama#69]
Hi @kentcdodds 

I've read your answer about writing Formly for Angular 2 on #66, and I was wondering if it would be possible to use the current version of Formly and Angular 2 using UpgradeAdapter. I tried it on a simple application but couldn't get it to work. I have too little experience with Angular 2 to know whether I'm doing it wrong or if it's just not as easy as I think it is.

We are about to start a potentially very large Angular project, and we have to choose between version 1 and 2. If the UpgradeAdapter works for components like Formly, it would make our decision much easier.

So, do you think it would be viable to use it? If possible, could you provide a very simple working example?

Thanks!

**Comment by kentcdodds** [comment]
Hi @ricsmania,
Thanks for the question. Unfortunately, I don't have the know how for this and I'm afraid I don't have the time to dedicate to learning how. I definitely don't see myself doing anything with angular 2 any time soon, so I'm afraid I can't be of much help :-( Maybe I'll tweet about this and see if any of my friends could help. Good luck!

**Comment by joshtoo** [comment]
@ricsmania - I've been focusing on Angular2 for the past few months, @kentcdodds threw out a request on Twitter and i'm sure I can help but I'll need something a bit more specific. 

Assuming we aren't talking about a companies intellectual property, the most efficient way to do this would be for you to point me to the repo you are having issue with.

**Comment by ricsmania** [comment]
Hi @kentcdodds and @joshtoo and thank you very much for the help.

After a few hours of trial and error I got it to work: https://plnkr.co/edit/hXp4r9?p=preview

I know this is probably not the best way to do it. I forked a working ngUpgrade example and went from there. I'll try to convert it to Typescript now and use Angular 2 best practices.

@joshtoo if you could help converting this to Typescript or ES2015 and doing it the right way I'm sure you will come up with a much better solution than me. But I'll try to do it anyway as a learning exercise.

Thanks again!

**Comment by joshtoo** [comment]
@ricsmania - I'll take a look at the plunk in the morning. I work almost exclusively with TypeScript, unlike some I feel the benefits of static typing in large applications for outweigh the effort needed to learn the syntax of another super set.

**Comment by ricsmania** [comment]
@joshtoo thanks again for the help.

I got it working pretty easily with regular directives, but I wanted to use the new directive component syntax, and it just doesn't work. More details here: http://stackoverflow.com/questions/34860728/angular-2-upgradeng1component-not-working-unknown-provider
