### ISSUE TITLE
Application State and avoiding many "wasted renders"

### ISSUE THREAD

**Issue by dfmartin** [kentcdodds/ama#690]
I have read through your various recent articles around application state via hooks (great read BTW).  And I have started to put some of it into practice.  Right now it is just a feature context, but the entire app is within it.  However, there are only two parts that are "consuming" it (if I have understood that word correctly).  The problem I am running into is that when the state of that context changes it seems everything gets re-rendered according to React DevTools Highlight Updates putting blue boxes around everything.

Is this expected/generally ok?  What is the best way to investigate this?

For context (pun), I have a messaging feature in my application.  The main feature is not always visible - only if the user goes into the Message Center.  However, there is the icon for launching that feature.  The hope was to show the number of unread messages on that icon which is always visible, and the feature context is already grabbing that every 60s.  So, I thought why not use that by pushing the feature context up to the <App /> level and allow the button for the icon consume that state.  This is a rather dense data entry app, so when the user is not in the message center, it feels heavy to cause a re-render of these other portions of the app.

Thanks!

**Comment by kentcdodds** [comment]
Hey David!

Try putting the direct children of your context in a `React.memo` and let me know if that helps :)

**Comment by kentcdodds** [comment]
Something like this: https://codesandbox.io/s/93r1rr3v3w

**Comment by kentcdodds** [comment]
And here's the before: https://codesandbox.io/s/ryyqj2nl6n

**Comment by dfmartin** [comment]
Thanks for the response.  Unfortunately it did not work.  the problem for me is that the Provider needs to be too high up the component chain in order to encompass both the main menu of the application and an individual feature which means the direct child is the app itself.  At least it feels that way now.  I'd need to see if there is a better/different way structure things.  For now, since the menu icon needs only a small sliver of functionality from the context I may just have it work independent.

**Comment by kentcdodds** [comment]
Gotcha. Makes sense.

In that case I wouldn't worry about it. It's unlikely to be a performance problem. If it ever is, find out which components are rendering slowly and fix those and/or use `React.memo` on them. You should be good though :)

I hope that's helpful!
