### ISSUE TITLE
How to test a route change in a resolved promise

### ISSUE THREAD

**Issue by ritchieanesco** [kentcdodds/ama#696]
Hi Kent,

I completed your testing javascript which was awesome!

 I have a form when submitted will call an endpoint.  Should the submission succeed the user is redirected to a success screen (using reach router) else a failed screen.

I currently have a test that mocks out the api call (borrowed from your examples) but this means I can’t test if the user has been sent to the correct screen because I’m just returning a resolved promise and I’m not sure if it’s a good thing to duplicate code just for these tests.

Any suggestions?

**Comment by kentcdodds** [comment]
Great question @ritchieanesco. Could you give me a codesandbox showing what you have so far and I'll show you what I'd do.

**Comment by ritchieanesco** [comment]
I quickly put this together... hopefully it makes sense https://codesandbox.io/s/resolved-promise-callback-test-ws57c

**Comment by ritchieanesco** [comment]
Closing this issue as I’ve figured it out. For those interested Formik has a setStatus in its onSubmit handler that will trigger a render. I can use tis state to perform the redirect to either a success or error page.
