### ISSUE TITLE
Do you prep for live streaming?

### ISSUE THREAD

**Issue by frankcalise** [kentcdodds/ama#701]
When you're just working on some code such as [Adding tests to a React application](https://www.youtube.com/watch?v=sqCikjna2Lg), do you come up with a script or outline of what you want to do prior? Or do you just have an idea what you're going to explore for that day, hop on and say, this is what I'll be doing and organically go through the thought prcoess and everything however it occurs?

**Comment by kentcdodds** [comment]
Hi Frank,

I have two types of livestreams: [Coding with Kent](https://kcd.im/coding) and [DevTips with Kent](https://kcd.im/devtips). For coding I don't plan that one bit. It's basically me thinking "Hey, I'm going to work on some stuff and I don't mind people watching." For the DevTips it's much more focused on something specific I want to teach about something I learned recently or I want to answer something on my AMA.

I don't have as much time to livestream as much as I would like I'm afraid :-(
