### ISSUE TITLE
React Auth - handle 401 error?

### ISSUE THREAD

**Issue by dT-Nick** [kentcdodds/ama#703]
Hi Kent,

I read your blog post about [Authentication in react apps](https://kentcdodds.com/blog/authentication-in-react-applications), and I wanted to ask what your preferred method of dealing with a 401 Unauthorised error is (when the users token has expired and they're trying to fetch data).

Thanks!

**Comment by kentcdodds** [comment]
Hi @dT-Nick,

In that situation I automatically log the user out (and remove their token from local storage). When that happens, the app re-renders and the user is presented with the login screen. Not a lot needs to happen for this to work :)
