### ISSUE TITLE
When to know a React Context is properly applied with hooks

### ISSUE THREAD

**Issue by Ruffeng** [kentcdodds/ama#705]
Hi!
Recently I've been doing some playground with React.Context. Everything looks great, and I really like the concept. Thanks to that, I am not feeling chained to redux or Apollo link state anymore. I've bumped into a situation that I would like to discuss here and know the opinion of the community.

Let's say I have my context, for example for a Toggle Switch button( as the examples from Kent. C):
```javascript
const ToggleContextState = React.createContext()
const ToggleContextDispatch = React.createContext()

const ToggleProvider = () => {
  const [state, dispatch] = React.useState(false)
  const toggle = dispatch(!state)

  return (
    <ToggleContextState.Provider value={state}>
      <ToggleContextDispatch.Provider value={dispatch}>
        {children}
      </ToggleContextDispatch>
    </ToggleContextState>
  )
}

const useToggleContext = () => {
  const on = React.useContext(ToggleContextState)
  const toggle = React.useContext(ToggleContextDispatch)
  return { on, toggle }
}
```

Having this as a context. Let's say I have a situation like
```javascript
// Switch has been imported 

const onChange = () => {
  const { on ,toggle } = useToggleContext()
  // ... stuff that onChange applies
}
const Switch = () => (
  <ToggleProvider>
    <SwitchButton onChange={onChange} />
  </ToggleProvider>
)
```

So here it goes my question: How could I take advantage of `useToggleContext` inside the `onChange` method? 

Hooks has 2 unique rules, and one of them is just referencing this example:

```
Only call Hooks from React function components. Don’t call Hooks from regular JavaScript functions. 
(There is just one other valid place to call Hooks — your own custom Hooks. We’ll learn about them in a moment.)
```
I would have the necessity to invok the `useToggleContext` inside this method, son then i can `toggle()`. However, this is forbidden.

My next approach:  I do render prop components, so I receive the context and I can use it. Ok, I'll modify my example:

```javascript
const ToggleProvider = () => {
  const [state, dispatch] = React.useState(false)
  const toggle = dispatch(!state)

  return (
    <ToggleContextState.Provider value={state}>
      <ToggleContextDispatch.Provider value={dispatch}>
        {children(useToggleContext())}
      </ToggleContextDispatch>
    </ToggleContextState>
  )
}
...
const onChange = (toggle) => {
  // ... stuff that onChange applies
}
const Switch = () => (
  <ToggleProvider>
    { ({toggle}) => 
    <SwitchButton onChange={() => onChange(toggle)} />
    }
  </ToggleProvider>
)
```

That didn't work either, sending back an `undefined` context, so I can't invoke the toggle.

My last solution was to break into even smaller pieces and apply the context from there...
```javascript
const RenderSwitchButton = () => {
  const { on ,toggle } = useToggleContext() //=> This WORKS
  return <SwitchButton onChange={() => onChange(toggle)} />
}

const Switch = () => (
  <ToggleProvider>
    <RenderSwitchButton onChange={onChange} />
  </ToggleProvider>
)
```

So I hit a solution to avoid the problem I had and I kind of like it since it forces me to break the components into smaller pieces to invoke the context.

However, I am curious how a situation like this can be solved. I think scenarios like this are quite common, so I would like to know what would be the best approach to hit this.

Thank you!

**Comment by kentcdodds** [comment]
Hi @Ruffeng,

Just looking at your question now and your solution is _the_ solution. You absolutely have to render your component within the context provider, there's no getting around that. I can't think of any "better" way to do this and I'm actually pretty happy with it as it is anyway personally.

Good luck!
