### ISSUE TITLE
Can ES6 Symbol be used as unique keys in Reactjs???

### ISSUE THREAD

**Issue by Adnank122** [kentcdodds/ama#708]
For example, if I'm creating list items in a loop, can I do something like this?
```js
  <li key={Symbol()} > {Something here} </li>

```

**Comment by kentcdodds** [comment]
Hi @Adnank122,

That should work, but I'd recommend against it. See: https://egghead.io/lessons/react-use-the-key-prop-when-rendering-a-list-with-react

**Comment by Adnank122** [comment]
Thanks for replying @kentcdodds .
 I just found out about symbol data type and thought it might work as it always produces a unique value. usually, I use a library called CUID to generate unique keys. If it's not a bother, can you kindly elaborate a little bit?

**Comment by kentcdodds** [comment]
Did you watch the video I linked to? I don't think I can elaborate on that much more. [Maybe the docs will help](https://reactjs.org/docs/lists-and-keys.html)?

Also, I'm giving a workshop and will be teaching about this in a few weeks: https://kentcdodds.com/workshops/react-fundamentals

**Comment by Adnank122** [comment]
@kentcdodds 
Yes, I did. Also, I love your workshops. That's where I learned reactjs. I was just wondering about why it wouldn't be a good idea. I'm reading the docs on Symbol on MDN. Maybe I can find something there.
If I get it, I'll post it here.  
Thanks so much for getting the time to reply.

**Comment by kentcdodds** [comment]
Try using Symbol() with the example in my video and you'll see that it's no different from using the `index`.
