### ISSUE TITLE
Best practice for a new web project in Angular? Build, test and deploy what tools?

### ISSUE THREAD

**Issue by pedrolopix** [kentcdodds/ama#71]

**Comment by kentcdodds** [comment]
Hi @pedrolopix,
Thanks for the question. I would recommend that you check out [John Papa's Styleguide](https://github.com/johnpapa/angular-styleguide) for many of the best practices.

- **Building**: Check out [webpack](http://webpack.github.io/) (see my [egghead.io series](https://egghead.io/series/angular-and-webpack-for-modular-applications))
- **Test**: Check out [Karma](http://karma-runner.github.io/) and use [mocha](http://mochajs.org/) with [chai](http://chaijs.com/) (I demonstrate this as part of my series on egghead as well)
- **Deploy**: Really depends on what you're trying to build and your company. Many use AWS with CloudFront. For some of my projects I use [surge.sh](https://surge.sh/). In any case, you should be able to deploy your application as a bunch of static files to a CDN where it can be cached and served with lightning fast speed (as opposed to a custom server that serves the files).

Good luck! :+1:
