### ISSUE TITLE
Life and Emotions During Your Career as an Engineer.

### ISSUE THREAD

**Issue by royalgiant** [kentcdodds/ama#711]
Some follow up questions from https://github.com/kentcdodds/ama/issues/1:

Did you ever question yourself when it came to your ability to succeed as an engineer?

Did you ever have anxiety or felt nervous about the decisions you made. Can you name 1-3 memorable experiences that made you anxious and how you overcame that?

Did you have mentors that helped you grow into who you are now? If so, what in particular did they do that seasoned engineers could emulate for newer engineers? If not, how did you grow to this point where you are now?

Rejecting USAA with a family seemed scary and I would never do that. What crossed your mind in making that decision? 

My experience with programmers is that there's a lot of us who aren't as faithful or confidence or have a cup full of hope, which I think you have. Do you think you have that? If so, what did you do to cultivate that? 

Hahaha. I turned this into an interview... feel free to answer/not answer however you like ;)

**Comment by kentcdodds** [comment]
Hi @royalgiant!

Thanks for the questions. I answered them on my 3 minute podcast here: https://www.briefs.fm/3-minutes-with-kent/113

**Comment by royalgiant** [comment]
Thank you Kent,

This is amazing! One would not think that you'd have anxiety with speaking
seeing as how you seem so confident over Twitter, your blog, and your
podcast!

Really admire your faith, I think it's one of the things that people do not
realize how helpful it could be when they really think about how it fits
into their lives instead of following blindly towards a religion.

Best regards,

Donald Lee

Contact Number: +1 (205)835-3859
Connect with me on Linkedin: https://ca.linkedin.com/in/donaldlee50
Check me out at Github: https://github.com/royalgiant
Dancers! Drop us a line: https://m.me/1698913433763088?ref=dancingnomads
