### ISSUE TITLE
How to test a component that returns null in render function?

### ISSUE THREAD

**Issue by AntoniosProvidakis** [kentcdodds/ama#712]
Let's assume that a component returns null in render function, based on some prop.

What is the best way to use expect in order to ensure that component is not rendered?

Example:

```js
import React from 'react';
import { render, fireEvent } from '@testing-library/react';
import Pagination from '../Pagination';

it('should not render if totaPages is 0', () => {
  const { container } = render(<Pagination activePage={1} totalPages={0} />);
  expect(container.firstChild).toBeNull();
});
```

Is the above code enough?

Is it even needed to test such functionality?

Thanks.

**Comment by kentcdodds** [comment]
Hi @AntoniosProvidakis,

Depends on the component for [whether it's worthwhile](https://kcd.im/what-test), but that's a fine way to test it I think.
