### ISSUE TITLE
Replace Redux Saga/Thunk with Hooks?

### ISSUE THREAD

**Issue by sidferreira** [kentcdodds/ama#715]
I like the whole Redux idea, but I also like to use the minimum dependencies as possible.

Hooks and ContextAPI seem to offer a great replacement for most cases, but I still wondering about how to handle Side Effects in the pure-react solution.

How can to solve this?

**Comment by kentcdodds** [comment]
I definitely have thoughts here, but to be sure I address your question, could you give me an example of the kinds of side-effects you're doing with redux that you find particularly hard or unclear with going it with hooks alone?

**Comment by sidferreira** [comment]
@kentcdodds One good example is sync profile when the app is resumed, but wait for `CACHE_LOADED` action.

**Comment by sidferreira** [comment]
Another example is to request out data-provider component to check for updates if by any reason one item is missing (when you have multiple API endpoints)

**Comment by kentcdodds** [comment]
I have been a bit busy lately, but I saw this recently that might be helpful to you: https://www.youtube.com/watch?v=nUzLlHFVXx0

Especially watch toward the end. Let me know if that answers your question.

**Comment by tommmyy** [comment]
hm... If I overlook the style of how he composes the hooks (spaghetti style, no compose fn), I am still missing Redux enhancers and great Redux ecosystem.

**Comment by kentcdodds** [comment]
By all means, if you like redux and want to keep yourself in an existing ecosystem, feel free to stay there. As for myself, I never liked redux, so I'm thrilled that react has this kind of capability built-in.

**Comment by tommmyy** [comment]
and why you do not like Redux? I am sure you have a blog post about that somewhere :)

**Comment by sidferreira** [comment]
@kentcdodds This videos made me see that there's a small "change" in "Thinking React" with Hooks... And that's a GREAT change!

**Comment by kentcdodds** [comment]
@tommmyy, it's not redux by itself, but what people do with redux that bothers me. Inevitably people will put too much state in the global store and that results in maintainability and performance issues. Maybe this will help: https://kcd.im/state and https://kcd.im/colocation

@sidferreira, I'm glad that answers your question. Maybe one day I'll write a blog post about this, but for now, Michael's talk is basically what I would say. Thanks!
