### ISSUE TITLE
Update testingjavascript.com cypress tutorial to use latest versions of cypress-testing-library

### ISSUE THREAD

**Issue by snamoah** [kentcdodds/ama#716]
Hey Kencdodds,

Thanks for your tutorial on testing javascript applications using cypress on testingjavascript.com. I noticed however that the fourth video on installing cypress-testing-library is outdated as the package is deprecated in favour of `@testing-library/cypress`. I see that you have documented on the cypress-testing-library about its deprecation but would be great if that lecture could be updated with the new library.

Thanks, and keep up the good work!

**Comment by kentcdodds** [comment]
Am update is planned 😃
