### ISSUE TITLE
If i want be like you, where i have to start?

### ISSUE THREAD

**Issue by brutalcrozt** [kentcdodds/ama#72]
Like i need a map to find you dude :smiling_imp:

**Comment by kentcdodds** [comment]
Hi @brutalcrozt,
To be honest, I find your question disturbing and creepy. Considering that you've already contacted me several times through multiple mediums and I just haven't had the time to get back to you yet.

No, I won't be providing you with a map to find me.

As far as being like me. As flattering as that is, I'm really nothing special, but I can tell you the things that are core to who I am and maybe that will give you an idea of why I am the way I am (however you interpret that).

1. I'm a [child of God](https://www.lds.org/general-conference/1998/10/we-are-children-of-god) and a [covenant](https://www.lds.org/topics/covenant?lang=eng) keeping member of [The Church of Jesus Christ of Latter-Day Saints](https://lds.org) (aka [Mormon](https://mormon.org))
2. I'm a faithful husband, father, son, brother, Uncle, etc.
3. I'm a software engineer working hard to develop my skills so I can care for my family

This are the three things that define me more than anything else. Best of luck to you.

**Comment by brutalcrozt** [comment]
ok man thanks
