### ISSUE TITLE
Is there any reason why I shouldn't make the "react-hooks/exhaustive-deps" ESLint rule an error?

### ISSUE THREAD

**Issue by mplis** [kentcdodds/ama#724]
In the README for [`eslint-plugin-react-hooks`](https://www.npmjs.com/package/eslint-plugin-react-hooks), it tells you to add this to your ESLint config file:

```
"rules": {
  "react-hooks/rules-of-hooks": "error",
  "react-hooks/exhaustive-deps": "warn"
}
```

Is there any reason why I wouldn't want to make `react-hooks/exhaustive-deps` an error?

**Comment by kentcdodds** [comment]
99% of the time you shouldn't break that rule, but the rule isn't perfect, so sometimes the rule is wrong. I'm guessing that's why they suggest to use a warning.
