### ISSUE TITLE
What would you use?

### ISSUE THREAD

**Issue by ColadaFF** [kentcdodds/ama#73]
Hi kent,
I know about your position against the question "React or Angular", still, I have a question about that and a context that will help you understand why the question again.

The app I'm trying to create is about surveys, that can the configured(Surveys and questions) and some charts about the result of the survey.

I have the question about which one because all the react simplicity and the greatness with things like redux, I also been working on another projects with angular and angular-formly, which make forms really easy, as you already know, haha, but what would you use to build something like the app I described?

**Comment by kentcdodds** [comment]
Hi @ColadaFF!
Thanks for the question! I must say that I have yet to build much with React and I've certainly never built anything very form-heavy. If I had to do it today and I needed to move quickly and have a feature-full implementation, I'd totally use Angular 1.x. No brainer there.

But if I needed to maintain it long-term and I had time to do a proper implementation, I would look at other factors. Probably the biggest for me is the team. Who's working on the project? Do you think that they'd be effective working with Angular? Are they the kind of developers that think the way Angular encourages you to think? Do they need the guiding hand of Angular dictating much of how they accomplish their tasks?

Or are they the kind that like to have flexibility? Do they prefer functional programming? Do they think of modules as small, isolated pieces that you can put together like legos in the best way to accomplish the task at hand? This is more of a React mind-set.

I would really encourage you to consider the team as well as the technology. I'm sure there's a good foms library for React. So make sure you think of the kind of codebase you're looking to have and the kind of developers you'll have on the project.

Sorry for the non-answer. Good luck!

**Comment by siddharthkp** [comment]
> I'd totally use Angular 1.x. No brainer there.

lol, hi from 2019

**Comment by kentcdodds** [comment]
lol, Kent of early 2016 was an AngularJS wiz and a React newb 😅
