### ISSUE TITLE
Suggestions for Automated Cross-Browser Testing?

### ISSUE THREAD

**Issue by peterkrieg** [kentcdodds/ama#735]
Hi Kent,

I found this [issue](https://github.com/kentcdodds/ama/issues/276) which discusses a stack for automated cross-browser testing.  However, that was a couple years ago so I was wondering if you had any suggestions currently?  I would like to use cypress but as of now they don't support browsers other than chromium-based.

I'm considering [testcafe](https://devexpress.github.io/testcafe/) but curious what other thoughts you have.

Thanks in advance!

**Comment by kentcdodds** [comment]
Thanks for the question @peterkrieg! Here's your answer: https://www.briefs.fm/3-minutes-with-kent/115

**Comment by peterkrieg** [comment]
thanks for taking the time to answer @kentcdodds !  Very helpful, I appreciate it.
