### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by jdsandifer** [kentcdodds/ama#736]
The link to "Hi, thanks for reaching out to me 👋" seems to point to a nonexistent Medium article (410 error).

It should probably point to the [blog](https://kentcdodds.com/blog/hi-thanks-for-reaching-out-to-me) or [kcd.im/no-time](kcd.im/no-time).

**Comment by kentcdodds** [comment]
Thank you!

**Comment by jdsandifer** [comment]
You're welcome! Thanks for sharing all your great content.
