### ISSUE TITLE
What syntax highlighting library do you use for easy to read code?

### ISSUE THREAD

**Issue by DavidWells** [kentcdodds/ama#74]
I need a solid way to display some modern ES6 JS in the browser for some posts I'm writing.

Do you know of a good library to use that works with ES6 + JSX

Thanks!

**Comment by kentcdodds** [comment]
Hi @DavidWells,
Thanks for your question! I've never actually done this (last time I did something like this was before I did much ES6/JSX). So, what I would do is find somewhere that does something that you're looking to do and ask them how they do it (like @wesbos's blog).

I can tell you that it's most likely that [highlight.js](https://highlightjs.org/) can probably do what you want it to (and I wouldn't be surprised if that's what @wesbos is using).

**Comment by wesbos** [comment]
I use prism - it has very good ES6 highlighting.

**Comment by kentcdodds** [comment]
Thanks @wesbos! I knew I could count on you :clap:

**Comment by DavidWells** [comment]
@wesbos does it handle JSX too? Trying to find an example on your site

**Comment by wesbos** [comment]
Yep  - only recently thought. 

https://github.com/PrismJS/prism/pull/479

**Comment by DavidWells** [comment]
Awesome! Thanks @kentcdodds + @wesbos .

Got some posts coming soon =)
