### ISSUE TITLE
Prop Drilling vs. Context

### ISSUE THREAD

**Issue by KennyHammerlund** [kentcdodds/ama#741]
I have 4-5 layers of components that all use the same prop. Because they are used in every component down the tree I did not use a context. I feel like I could use a context and HOC on each component to keep the code cleaner but I think the only benefit would be to remove the prop drilling. 

basically I would be able to change 
`<EndTurnButton playerMatchHelper={playerMatchHelper} scoreboardHelper={scoreboardHelper} />`
to 
`<EndTurnButton  />`
for a couple components in each layer. Is there any benefit to using the context approach besides  this?

**Comment by kentcdodds** [comment]
Hi @KennyHammerlund,

I wouldn't say it's worthwhile. Adding context is adding implicit abstraction which comes at a cost. The benefit of avoiding prop drilling just 5 levels wouldn't be worth the cost to me.

**Comment by kentcdodds** [comment]
Good luck!
