### ISSUE TITLE
How to minimize the overlap between unit/integration tests and UI/e2e tests?

### ISSUE THREAD

**Issue by DanielStoica85** [kentcdodds/ama#743]
Let's say you are working on app which has it's frontend built with React. For your React components, you use jest and react-testing-library to write unit and integration tests. For your UI/E2E tests you use Cypress. 

How do you organize your tests in such a way so you don't test the same functionalities twice?

**Comment by kentcdodds** [comment]
Hi @DanielStoica85,

I personally don't worry too much about a little overlap. But maybe this will help https://kcd.im/trophy

Good luck!
