### ISSUE TITLE
Internal Component library testing

### ISSUE THREAD

**Issue by Shadowlauch** [kentcdodds/ama#750]
Hellot,

We are currently developing a small internal component library, that is mostly without styling (except "functional" styling). So in that sense the html we create in the library is part of the public API that the developer consumer use to style the components. Would you test the whole HTML structure of a component to make sure that "contract" is honored?

Thanks!

**Comment by juandiegombr** [comment]
Hello!

I was going to ask mostly the same.

We have a project for all the base components (Buttons, inputs, selects... ) All those components need to behave as we expect but also they need to be visually as we expect. We have a brand design with different themes for different products, so the styles are very important. We use plain CSS to style them.

What approach would you use to test them visually? It is possible do it with testing-library?

Thank you!

**Comment by mayteio** [comment]
We use storybook for visual testing. You can go one further with tools like;
- [`storyshots-addon`](https://github.com/storybookjs/storybook/tree/master/addons/storyshots)
- [`jest-image-snapshot`](https://github.com/americanexpress/jest-image-snapshot)

Or paid services like (Chromatica)[https://www.chromaticqa.com/]. [Further reading](https://storybook.js.org/docs/testing/automated-visual-testing/).

**Comment by kentcdodds** [comment]
Hi there @Shadowlauch,

I answered this on my 3 minute podcast :) Here you go: https://www.briefs.fm/3-minutes-with-kent/120
