### ISSUE TITLE
React effect creates a new event handler on update

### ISSUE THREAD

**Issue by aganglada** [kentcdodds/ama#752]
It it a normal behaviour for an effect with a custom event handler to attach and de-attach on every state change?

I've made this [codesandbox](https://codesandbox.io/s/patient-sunset-dfozv) in which you can see on every click on the checkbox, the event attaches and de-attaches when the piece of state changes.

Am I missing something or this is the normal behaviour? 

Thanks in advance.

**Comment by kentcdodds** [comment]
Hi @aganglada :)

Here's a good solution: https://codesandbox.io/s/agitated-dewdney-6qp5r

Also, I livestreamed this :) https://www.youtube.com/watch?v=L59rOas2AYE&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u

**Comment by aganglada** [comment]
Thank you @kentcdodds you are amazing!
