### ISSUE TITLE
Testing Folder File Structure

### ISSUE THREAD

**Issue by DzoYee** [kentcdodds/ama#754]
How do you structure your project as far as tests go?

I usually keep my frontend jest tests right next to my component. For example we have component.js and then component.test.js.

One issue I run into is knowing whether that component is a component unit or component integration test. It gets free hairy when you need to quickly find out which of it's child components it is testing. 

I'm curious how you structure e2e tests as well.

**Comment by kentcdodds** [comment]
Hi @DzoYee,

Great question. I answered it on [my podcast](https://www.briefs.fm/3-minutes-with-kent/118).

Enjoy :)
