### ISSUE TITLE
What is you opinion on my createSharedState React RFC

### ISSUE THREAD

**Issue by mucsi96** [kentcdodds/ama#755]
Hi Kent,

I am your follower and very impressed with your React knowledge. I would like to ask your feedback on my first [React RFC](https://github.com/reactjs/rfcs/pull/130). I think it could be very valuable for the whole React community. How do you see it from your perspective?

**Comment by kentcdodds** [comment]
Hi @mucsi96,

Interesting idea. I left feedback on the PR.
