### ISSUE TITLE
Testing workshop part 1 is blocked ;(

### ISSUE THREAD

**Issue by nicksp** [kentcdodds/ama#757]
Hey @kentcdodds 👋

I was about to start going through the testing workshop you gave at Paypal but realized part 1 was blocked 😞Any up to date content replacement or mirror link at least?
https://www.youtube.com/watch?v=w6KCDFssHFA

**Comment by kentcdodds** [comment]
Hi @nicksp,

I don't know. Maybe YouTube blocks it for you based on where you're from? I'm sorry about that.

You could buy a license to TestingJavaScript.com instead. It's a LOT more valuable anyway.

**Comment by nicksp** [comment]
> Maybe YouTube blocks it for you based on where you're from

Does it work for you? I tried it under VPN using different countries and it's the same blocked content ;(

**Comment by kentcdodds** [comment]
It does work for me.

![image](https://user-images.githubusercontent.com/1500684/69577266-44f50300-0f8b-11ea-8dc7-0be4e0f924b8.png)

**Comment by nicksp** [comment]
Cheers, I'm probably gonna check out the testingjavascript.com 😛 Looks like a solid resource.
