### ISSUE TITLE
What are two habits that really good engineers have which novices should begin to cultivate?

### ISSUE THREAD

**Issue by joshmanders** [kentcdodds/ama#76]
One of the biggest hurdles of my career was cultivating good habits. Being a self taught programmer in the days of horrible tutorials, I cultivated a lot of bad habits that were hard to kick.

**Comment by kentcdodds** [comment]
Hi @joshmanders,

Finally getting to this question! I don't know if I could say that I have any real habits. But here are a few things that I tend to do that have served to be useful for me:

- Surround yourself with people smarter than you and ask them questions. Often people are more willing to do this if they know it could benefit more people, so I often do this over a Hangout On Air where the conversations are made available later. You can find my conversations like this here: http://kcd.im/tech-chats. Obviously that's not all the conversations I've ever had with people like this. Talk with people about stuff a lot. Be willing to have your opinion challenged and changed. Have an open mind.
- Learn by doing what I describe in #41 
- Give freely. I recently heard @jsonmez [on SE-Radio](http://www.se-radio.net/2015/12/se-radio-episode-245-john-sonmez-on-marketing-yourself-and-managing-your-career/) say that 90% of what you create you do for free and charge for 10% of it. I don't really do that exactly (I do have a day job), but I certainly spend a lot of time doing things for free. This has had a huge, positive impact on my career.

There are a few few things that I do regularly that have been good things for me in my (very short) career. :-)

Thanks for the question!

**Comment by suhasdeshpande** [comment]
Great stuff @kentcdodds .. +1:
