### ISSUE TITLE
React hooks: passing a Functional component as a callback to Array.prototype.map

### ISSUE THREAD

**Issue by tearingItUp786** [kentcdodds/ama#763]
Howdy Kent

I ran into an issue where if I provided a function that used hooks in its implementation and returned some JSX to the callback for `Array.prototype.map`. The error I received was `React Error: Rendered fewer hooks than expected`. [This article gave me the solution I was looking for but not a very detailed explanation](https://medium.com/@jonchurch/how-to-fix-react-error-rendered-fewer-hooks-than-expected-e6a378985d3c)

Here's an example of what I'm talking about although this probably won't break; I just wanted to clarify for you.

```jsx
  function Foo({ val, key }) {
    const [cool, updateCool] = React.useState(false);

    return <button key={ key } onClick={ () => updateCool(!cool) }>{ val }</button>
  }

  function App() {
    const values = [ {val: 1, key: 1}, { val: 2, key: 2 }, { val: 3, key: 3 }]

  return (<div>
      { values.map(Foo) } {/* broken */}
      { values.map(obj => <Foo {...obj} />) } {/* works */}
    </div>)
  }
```

**Comment by tearingItUp786** [comment]
For those of y'all interested in the answer, check out @kentcdodds blog post here: https://kentcdodds.com/blog/dont-call-a-react-function-component

**Comment by kentcdodds** [comment]
Thanks @tearingItUp786! I forgot to come back here to provide the link myself 😅

I hope it was helpful!
