### ISSUE TITLE
Extract methods from components or not, for proper testing?

### ISSUE THREAD

**Issue by jamesfromvenice** [kentcdodds/ama#764]
1. If a component has a method that is **not** dependent on the parent function per se', do you break it out (same file) to a separate function ie..

```
function whatever () {
  const [whatever, setWhatever] = useState(0);
  const upperCaseAndMerge = (arg) => arg.join('').toUpperCase(); // MOVE THIS OUT ?

 return .....
}
```

would you move that method out like so?

```
function joinAndUpper = (arg) => arg.join('').toUpperCase(); 
function whatever () {
  const [whatever, setWhatever] = useState(0);
  const upperCaseAndMerge = joinAndUpper(arg);

 return .....
}
```

2 My second question sorta is relevant to the first, when testing "joinAndUpper", don't we need it "outside" so we can test that function in isolation? 

What would be your strategy here? Do you leave methods that don't need to be tested sitting in component and those you do, put outside?

**Comment by kentcdodds** [comment]
Hi @jamesfromvenice,

Here's your answer: https://kentcdodds.com/blog/why-i-avoid-nesting-closures

Thanks!
