### ISSUE TITLE
Logic inside component vs outside component

### ISSUE THREAD

**Issue by dericgw** [kentcdodds/ama#767]
With the new Suspense API, _some_ use of hooks and things like GraphQL, it seems like there is a push to handle most logic inside of components. In the past on medium and larger apps, I have used some other state management library like MobX to keep a clear dileniation of business logic and kept most all logic outside of components. I like how clean this feels and it makes testing really easy. How do you feel about having a ton of business logic inside of components? Is that where we're headed? Surely I'm not the only one who finds this kinda gross feeling?

**Comment by kentcdodds** [comment]
Hi @dericgw!

I think the beauty of hooks is that you can put that logic into a custom hook and then it's separate from the components that use the hook :)
