### ISSUE TITLE
Do you pass an object or its properties in props?

### ISSUE THREAD

**Issue by raphaelbadia** [kentcdodds/ama#769]
Hello,

Let’s say that you retrieved a list of users and want to map over it with a `<UserRow />`, displaying first name, lastname and a dozen of other properties.

would you write it this way : `<UserRow user={user}/>` or would you write explicitly each property as prop ?

According to https://stackoverflow.com/questions/52621169/react-props-should-i-pass-the-object-or-its-properties-does-it-make-much-diffe , it’s important to  pass the props individually, but I would love to know your take on this 
Thanks !
🙏

**Comment by kentcdodds** [comment]
Hi @raphaelbadia,

I don't really have a strong opinion on this, though I typically would just pass the user object itself as a `user` prop.

Sorry that's not very helpful. Good luck!
