### ISSUE TITLE
Set up Real Project with Fetching Data

### ISSUE THREAD

**Issue by hd4ng** [kentcdodds/ama#770]
Hi, I am new to the real React project. In the past, when learning, I get the data from firebase which provides all functions for fetch, update, and refetch data. And now with the real React project, I don't know how to set up Fetching Data yet.

My project is using REST API so that I try to use Fetch and Axios. But I see the code for getting data from that are duplicated a lot. And when update new data, I don't know how to refetch data again, and which way to make the performance good.

Could you give me some advice? Thanks.

**Comment by kentcdodds** [comment]
Hi @hd4ng,

Look into react-query 👍
