### ISSUE TITLE
Mocking different values from a module with Jest

### ISSUE THREAD

**Issue by connorkatz** [kentcdodds/ama#772]
Wondering if there is a way to mock different values (not functions) from a module without resorting to using require.

I have a module that I am importing that gets some values from the window #legacysoftware

In different tests I want to mock different values so that I can ensure my code behaves correctly with different values

I found this  https://medium.com/trabe/mocking-different-values-for-the-same-module-using-jest-a7b8d358d78b

But it recommends using require which just feels odd.

Wondering if there is a way to do this without using require?

**Comment by kentcdodds** [comment]
Hi @connorkatz,

What they're suggesting is actually a good way to go about it.

What I normally do though is separate these things into different test files. That allows me to use imports. But that's not why I do it. I find that it's easier for my brain if I can see all the mocks used by a given file at the top of the test file and not worry about some other test in that file changing the mock on me.

Good luck!
