### ISSUE TITLE
Why can't you pass a function to a function and set that function to a new one?

### ISSUE THREAD

**Issue by TransmissionsDev** [kentcdodds/ama#774]
See more here: https://spectrum.chat/testingjavascript/general/why-does-the-jest-spyon-function-accept-a-string-key-and-a-module-instead-of-the-function-itself~e885567b-9f3a-417d-8619-bc0a56154d19

Thanks Kent!

**Comment by kentcdodds** [comment]
Hi @TransmissionsDev,

I think [this](https://spectrum.chat/testingjavascript/general/why-does-the-jest-spyon-function-accept-a-string-key-and-a-module-instead-of-the-function-itself~e885567b-9f3a-417d-8619-bc0a56154d19?m=MTU3ODE1MDM5OTg0NQ==) is a good answer :)
