### ISSUE TITLE
Intelligent Code Completion for @testing-library/react

### ISSUE THREAD

**Issue by hd4ng** [kentcdodds/ama#775]
Hi Kent, right now I am using create-react-app to setup my project. Is there any way to display Intelligent Code Completion for @testing-library/react in the non-typescript project?
For example: `toHaveTextContent` or `toHaveAttribute`?
Thanks

**Comment by kentcdodds** [comment]
Hi @hd4ng,

If you update to the latest version of @testing-library/jest-dom, you should get autocomplete out of the box thanks to this: https://github.com/testing-library/jest-dom/issues/123

Woo!

**Comment by hd4ng** [comment]
Oh yeah. Thank you
