### ISSUE TITLE
Where do you get your images?

### ISSUE THREAD

**Issue by davidgumzchoi** [kentcdodds/ama#777]
I love all your front end development work, but I also love the micro animations you choose, stock images, and especially the icons, svgs you use in your personal website and svg images like the icons for Testing JavaScript.

I'd love some insight into where you get these images and/or how you learned to create these images. Thanks!

**Comment by kentcdodds** [comment]
Hi @davidgumzchoi,

All of that is done by the good folks at egghead.io. Specifically @vojtaholik and @MaggieAppleton. They're brilliant!
