### ISSUE TITLE
Testing React hooks components with useEffect

### ISSUE THREAD

**Issue by lior-gutweter** [kentcdodds/ama#778]
Hi Kent,

We have a technical debt about testing React components which include hooks.
We have a standard component that first presents a loading sign, then make an ajax call in `useEffect`, update the result with useState, and at last renders the result.

You can see an example [here](https://codesandbox.io/s/cool-goldberg-32sb1). I used `setTimeout` to simulate a long ajax call.

With react-testing-library, you can render the component and wait until the relevant data is fetched and displayed. My colleagues insist they want to test the component separately when the state already contains the fetched data.

They argue that otherwise the tests will take much longer and that we don't need to test React hooks internal implementation. 

I don't know a way that it can be done. With class components you could call `setState` while in functional component you cannot. I am also not sure which approach is better.

Any thoughts?

**Comment by kentcdodds** [comment]
Hi @lior-gutweter,

The recommendation for unit/integration testing code like this is to mock the module that's making those requests (or to mock the mechanism that makes the request (like `window.fetch`)). Here's an example of mocking the module (doesn't work in codesandbox but it does locally): https://codesandbox.io/s/cool-butterfly-7oy0h

Good luck! :)
