### ISSUE TITLE
How did you register your personnal email ?

### ISSUE THREAD

**Issue by MattixNow** [kentcdodds/ama#779]
Hey Kent I saw that you have a personalized email address with the domain names kentcdodds.com, with which service did you create this email and do you have any advice for creating a personalized email.

Bye

**Comment by kentcdodds** [comment]
Hi @MattixNow,

This is a pretty common practice and there are a lot of tutorials online to show you how to do it. I glanced at this one and it looks ok: https://thedigitalnonprofit.com/use-gmail-own-domain-free/

Good luck!

**Comment by MattixNow** [comment]
Thanks a lot !
