### ISSUE TITLE
How, in your own work, do you test components that provide data rather than UI?

### ISSUE THREAD

**Issue by mayteio** [kentcdodds/ama#781]
Hey Kent, firstly thanks for all your awesome content - testing javascript in general (8 years developing at the time) was daunting and a mystery to me. Your paradigm of __"Test how the user interacts and sees, not how it's implemented"__ was a lightbulb moment for me because I could never relate to testing for a computer when humans use our products! I now feel extremely confident testing UI (which helps a lot with imposter syndrome as a developer 😉)

Doing my best to stick to the paradigm, I find myself testing a context provider that is responsible for authenticating a 3rd party service and providing the resulting class/object to the rest of my app (specifically, [Pusher](https://pusher.com/) via [@harelpls/use-pusher](https://www.npmjs.com/package/@harelpls/use-pusher). _All_ the code is implementation specific (authenticate against our identity provider, hitting a lambda to authenticate that against pusher and providing the resulting object). So my question is:

**How, in your own work, do you test components that provide data rather than UI?**

Cheers from Australia!

**Comment by kentcdodds** [comment]
Hi @mayteio,

Great question. I answered it via audio: https://www.briefs.fm/3-minutes-with-kent/117

Thanks!

**Comment by mayteio** [comment]
Unreal, thanks mate. All good with the wildfires, Melbourne got a bit smokey but we've had good rain recently and seems to be *somewhat* calming down.

Awesome Brief! What I took away from that was that if I am interacting with a third party or service, the only way to really test my components is to mock those (either in cypress or stubbing out a server with responses). 

So in my case, I need to mock the lambda response for authentication and mock the PusherChannel to run tests (either in cypress or creating a stubbed server).
