### ISSUE TITLE
How do you know tests are good quality?

### ISSUE THREAD

**Issue by krulletc** [kentcdodds/ama#782]
Hi Kent,

I've been through your Testing Javascript course (it's awesome!), but I wonder how you know that tests are really good and not missing areas, especially in a larger collaborative project.  I know just looking at code coverage helps, but it can also have issues if people are chasing a high coverage number.  Do you use any tools like mutation testing (e.g. Stryker) or do you rely on good code reviews or maybe there's something else?

**Comment by kentcdodds** [comment]
Hi there @krulletc! Great question. I answered this on my 3 minute podcast here: https://www.briefs.fm/3-minutes-with-kent/119

I referenced this post: [kcd.im/what-test](https://kcd.im/what-test)

Good luck!
