### ISSUE TITLE
How did you start streaming on youtube?

### ISSUE THREAD

**Issue by slim-hmidi** [kentcdodds/ama#784]
First of all, I want to congratulate you for the great work and videos that you make.
Then, I want to ask you and I hope that my question is not a duplicate:
How was your experience at the beginning when you started streaming and making videos online?
Are there any person that encouraged you or inspired you to make like him?
What are the tips that you can give for anyone wants to make his own youtube channel and making videos?
Thanks and hope that you will see my question.

**Comment by kentcdodds** [comment]
Hi @slim-hmidi!

Good question. I answered on [my 3 minute podcast](https://www.briefs.fm/3-minutes-with-kent/123) :)

**Comment by slim-hmidi** [comment]
Thanks a lot.
