### ISSUE TITLE
Copy rights check!

### ISSUE THREAD

**Issue by uwehlzcu** [kentcdodds/ama#786]
Hello Kent - I trust you're well.

I was browsing courses on educative.io platform and stumbled upon a react patterns course which is its content is very similar to your egghead react patterns course. attached the course url
https://www.educative.io/courses/react-in-patterns

BR,

**Comment by kentcdodds** [comment]
Thanks for the ping @uwehlzcu, but I don't think there's anything in there that I could claim copyright on. It looks like pretty original material :)
