### ISSUE TITLE
Auth + serverless

### ISSUE THREAD

**Issue by MattixNow** [kentcdodds/ama#789]
What's the best way to authantificate a user to his `<service>` account and get some data from this `<service>` ?
Example :
Auth on my app with spotify and get your music stats.

What's the best hosting way for the auth server ? Can i "serverless" my app ?

**Comment by kentcdodds** [comment]
Hi @MattixNow,

Great question. [I answered it on my podcast](https://www.briefs.fm/3-minutes-with-kent/125).

Here's the blog post I referenced: https://kentcdodds.com/blog/super-simple-start-to-serverless

Good luck.

**Comment by MattixNow** [comment]
Thanks a lot for your reply !
