### ISSUE TITLE
Open source project idea

### ISSUE THREAD

**Issue by lopter-sigyn** [kentcdodds/ama#79]
One of the Github Social Impact team members told me about your article First-timers-only and I was so grateful to see someone doing something to help bring more new developers into the industry.

Following your lead the next steps I'd like to see are github sponsor a hackathon, with the help of angelhack, where hacker like you can bring their knowledge for procedures to create and build upon a main project/page repository reference. 

Additionally, completion of certain coding challenges reflected in repositories with a code similar to your first-timers-only (think Free Code Camp as an example) would give credentials to github profiles on knowledge demonstrated by the owner of said profile.

If you look at the repository of Gods of Mayhem - I've found repositories with lesson plans, documentation, tutorials, I could go on.  - it just seems there has to be a way to bring the knowledge contained on github together to form the core of what can grow into how we keep the idea of free software development alive and help entry-level developers level up. Here are the format examples:

Elementary OS - website as a github page template for the creation of a collaborative project
Launch School - the intro class for those serious about getting employed in the industry
Cook Systems - an example of how businesses looking to hire quality talent can help build a better product/community
Epic Games - a company who is giving people the opportunity to be involved in their evolution
Codeship - could somebody please have a proper class on the use of this product in the development cycle? Please use Kevin of Launch School's manor of explanation

There are so many examples that fit different learning styles and needs its really something that just needs categorization and standardization, not complication and conformity.Then end-goal being when a person wants to complete an assessment for a position, or present themselves for hire, they can get the information they need to know what skills are necessary to complete said assessment. Additionally, they would then also have the proper knowledge to have commits to active open-source projects and/or find an opportunity to change their life (i.e Cook Systems).

I dream of an open-source game studio, complete with an HR section - that's where you do the assessments to demonstrate your skills. A training department, that's where you would learn how to do you the position you are interested in, get clear instructions for setting up your dev environment and finally production where you would collaborate and push code.

Sigh, I hope this isn't all over the place. All I mean to say is if we make it easier for companies who are TRYING to promote open-source participation to follow a standard others can understand. I think the world of coding will benefit.

I look forward to hearing your thoughts on this effort of mine. I really appreciate your openness to listen and be involved.

**Comment by kentcdodds** [comment]
Hi @lopter-sigyn!

Thanks for reaching out. I'll be honest, I'm not entirely certain I understand what you're trying to accomplish, but anything that's working hard to make it easier for new people to get started gets a :+1: from me! Sounds like you've got some good ideas. Keep up the hard work!

I would also like to mention that I recently finished recording a new free series for egghead.io that is in the review process right now which will be called: "How to Contribute to an Open Source Library on GitHub" which I think will mesh with what you're trying to accomplish quite well :-)

Have a nice day!
