### ISSUE TITLE
What are your thoughts about Next.js?

### ISSUE THREAD

**Issue by kevinwolfdev** [kentcdodds/ama#798]
Now that Next.js [announced static site generation improvements](https://nextjs.org/blog/next-9-3), what are your thoughts about it vs Gatsby?

**Comment by justincy** [comment]
In addition, it seems that you (Kent) prefer CRA. Why? I'd like to how you feel about CRA vs Next.js vs Gatsby.

**Comment by justincy** [comment]
I think he's already answered this: https://github.com/kentcdodds/ama/issues/680

**Comment by kentcdodds** [comment]
Yup :) Thanks @justincy!
