### ISSUE TITLE
Hi Kent asking for a favor to AngularJS Guatemala community

### ISSUE THREAD

**Issue by diegochavez** [kentcdodds/ama#80]
Man first of all, i want to say thank you about the great work you are doing on the Angular Formly project is awesome, and other good stuff you working on! 

Let me tell you, I'm  asking for a favor to the most influencer AngularJs developers all over the world to encourage the AngularJS Community on my country Guatemala, which is a small country in central america, I have big dreams to put the community on the map. So i'm asking for a favor, i have organized a Meetup the 20 of this month, i was looking if you could share us a video message to encourage Guatemala AngularJS Community to stay close and start to build great stuff. could be a small video but with a big message :+1: thanks for your time Kent. 

Best,

Diego Chavez
AngularJS Guatemala Meetup.

**Comment by kentcdodds** [comment]
Hi @diegochavez!

I would be happy to! You say it's on the Saturday, the 20th of February? What time (and timezone) would that be? Why don't you send me a calendar invite and any other information you have (how long do you want me to talk, how do you want me to connect, etc.): kent@doddsfamily.us

Thanks!

**Comment by diegochavez** [comment]
Thanks @kentcdodds email sent :+1:

**Comment by kentcdodds** [comment]
Looking forward to this. I could definitely do a live video hangout at the beginning or end of the event. Let me know what you'd prefer :-)

**Comment by diegochavez** [comment]
Thanks mate that's awesome!, i'll send you an email about that.
Best,
