### ISSUE TITLE
using javascript classes and design patterns with react components

### ISSUE THREAD

**Issue by weiklr** [kentcdodds/ama#806]
Hi Kent,

What are your thoughts about using javascript classes and design patterns such as builder design patterns for complex data objects along side with React components? 

It seems that React revolves around functional programming concepts, with callbacks and closures, and I not sure if it's a good practice to do so?

**Comment by kentcdodds** [comment]
Hi @weiklr,

I'm not a huge fan of classes or those patterns and I'm really happy to see React moving toward more functional principles.

I've written about something related to this in the past: https://kentcdodds.com/blog/classes-complexity-and-functional-programming

Hope that helps :)
