### ISSUE TITLE
GRIFITI wrist pads, which material?

### ISSUE THREAD

**Issue by ccalvarez** [kentcdodds/ama#812]
Hi Kent!
I am about to buy the [GRIFITI wrist pads](https://www.amazon.com/dp/B00AJE771W/?tag=kentcdodds-20), but found that they're available in two materials:

- Black Nylon

- Smooth Skin Rubber

Which one do you recommend?  

Thanks!

**Comment by kentcdodds** [comment]
Hi @ccalvarez! I have the Black Nylon and like them. They do get a little dirty and the nylon is starting to peal off, but it's fine. Still works and it's comfortable.
