### ISSUE TITLE
What that syntax mean ?

### ISSUE THREAD

**Issue by kuzyo** [kentcdodds/ama#820]
Hey, Kent
Saw in you bookshelf repo strange syntax for me - `listItems ?? []`, `onSuccess?.(listItems)`. Could you please explain what is it and how it works ? Thanks

```
function useListItems({onSuccess, ...options} = {}) {
  const {data: listItems} = useQuery({
    queryKey: 'list-items',
    queryFn: readListItems,
    onSuccess: async listItems => {
      await onSuccess?.(listItems)
      for (const listItem of listItems) {
        setQueryDataForBook(listItem.book)
      }
    },
    ...options,
  })
  return listItems ?? []
}
```

**Comment by hexrcs** [comment]
They are the [nullish coalescing operator `??`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) and [optional chaining operator `?.`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) added in ES2020.

**Comment by kuzyo** [comment]
@hexrcs Thanks. Glad to know.
