### ISSUE TITLE
Null vs Empty fragment?

### ISSUE THREAD

**Issue by karangarg45** [kentcdodds/ama#822]
Hi Kent,

In react if you want to render nothing either you can return null from the component or you can render an empty fragment.

Is there any disadvantage of using `<React.Fragment/>` over `null`.What are your thoughts on this? I think using `React.Fragment` is more explicit and shows developer's intent

**Comment by kentcdodds** [comment]
I don't think there's any real observable difference here. Given that it's all about your preference and for me, I prefer to render `null` when I want nothing rendered. Fragments are intended to encapsulate children and if I saw an empty fragment I would be confused why it's there 🤷‍♂️
