### ISSUE TITLE
Add Version Numbers to Library Documentation API's

### ISSUE THREAD

**Issue by JimmayVV** [kentcdodds/ama#823]
Hi Kent!

I had a question about something I was wondering if you've ever considered before.

My question is, have you considered adding some form of information to the documentation within your libraries (for instance @testing-library/react) to let the users know which versions of your library support it?

A big one I'm thinking about is the `screen` query. I think it would be great if you could mention which version of the package first shipped the feature, so that users like me who are not on the bleeding edge can know what needs an update to use, and what doesn't. Obviously we can look at release notes, and the source code, but I think there'd be value in trying it out.

Just a thought! Thanks!

Jimmy

**Comment by kentcdodds** [comment]
Hi @JimmayVV,

That's a good idea. Could you open an issue on the docs repo? https://github.com/testing-library/testing-library-docs

Might be a great contribution opportunity :)

**Comment by JimmayVV** [comment]
> Hi @JimmayVV,
> 
> That's a good idea. Could you open an issue on the docs repo? https://github.com/testing-library/testing-library-docs
> 
> Might be a great contribution opportunity :)

Yes sir, done! Thanks for thinking it's not a bad idea :D
