### ISSUE TITLE
React Profiler showing more commits, expected less

### ISSUE THREAD

**Issue by kuladeepu** [kentcdodds/ama#825]
Hi Kent,

While profiling my component SettingsBody(https://gist.github.com/kuladeepu/3ed38b8366da35047e07c15da543cf10) it is showing 15 commits.

Each TextInput component of Profile component committed at different level
but iam expecting a single commit of entire Profile component in mount phase.

While in updating phase, profiler showing desired number of commits. 

And also please review my code.

Thank you

**Comment by kentcdodds** [comment]
Hi @kuladeepu, 

I tried to answer your question a bit https://youtu.be/d84fhj7FMuQ?t=186

Unfortunately I can't give you too much insight without a running example 😬

**Comment by kuladeepu** [comment]
Hi @kentcdodds 
Here's the Flamegraph https://kapwi.ng/c/dUjPpzhE (mount SettingsBody).

**Comment by kuladeepu** [comment]
Thank you.
I attached the flamegraph.
https://github.com/kentcdodds/ama/issues/825#issuecomment-694652775

**Comment by kentcdodds** [comment]
Hi @kuladeepu,

I'm afraid that's still not enough for me to say what's going on. Sorry.
