### ISSUE TITLE
Live streams on demand.

### ISSUE THREAD

**Issue by dT-Nick** [kentcdodds/ama#826]
Hi Kent,

I've noticed you've moved your Coding with Kent streaming over to discord. Just curious if you plan to make that content available on demand anywhere? I find it super useful and most of the time can't make it to a live stream due to time zone differences.

Cheers

**Comment by kentcdodds** [comment]
Yeah, I may figure out a way to record this stuff, but I don't want to increase friction for me to live stream

**Comment by dT-Nick** [comment]
> Yeah, I may figure out a way to record this stuff, but I don't want to increase friction for me to live stream

Okay cool, understandably so. Hopefully you can come up with a solution.
