### ISSUE TITLE
What's your process to record educational videos?

### ISSUE THREAD

**Issue by niksumeiko** [kentcdodds/ama#827]
Do you write scripts in advance? Or how do you explicitly remember what to say and, more important, what to code/show when recording a single video or multiple videos in a row?

**Comment by kentcdodds** [comment]
Hi @niksumeiko!

Here's the answer! https://kentcdodds.com/blog/how-i-record-educational-videos (I know that video embed is broken right now but the link above works fine, and it's not that important anyway).

Hope it's helpful.
