### ISSUE TITLE
Opinion of ClojureScript?

### ISSUE THREAD

**Issue by austingardner** [kentcdodds/ama#828]
Hey Kent, 

Keep up the good work! I'm a huge fan, and react-testing-library has made testing our app so much easier! 

I was just wondering about your opinion of ClojureScript, which can be used with libraries like Reagent which allows you to use React components in ClojureScript. 

- Austin

**Comment by kentcdodds** [comment]
Hi @austingardner,

I answered this during office hours today: https://www.youtube.com/watch?v=ph_dQoIKzoY
