### ISSUE TITLE
[Life/Family/Work Balance ]¿How do you manage your time?

### ISSUE THREAD

**Issue by matiasfha** [kentcdodds/ama#830]
Hi Kent!. As everyone acknowledge you are a terrific educator and a productive content creator and code creator/maintainer but also you are a father of 4 kids!!! (clap clap clap).

I'm also a father and engineer.  And also started my content creation journey not so long ago and is sometimes overwhelming so my questions is as follow.

¿How the heck do you manage your time to be as productive as you are and also to have a life?
What kind of systems or habits do you think help you to keep on track with all the things you do in the different aspects of life?

(I mentioned this before in a twitter thread. I think that this is a very good topic for at least a blog post xD)

**Comment by kentcdodds** [comment]
Thanks for your kind words! This is a great topic for a blog post! In fact, I've written about it already! https://kcd.im/productivity 😉
