### ISSUE TITLE
How do I pass values from a hook into a component rendered by a test?

### ISSUE THREAD

**Issue by hanhanhan** [kentcdodds/ama#831]
Should I?
Can I?

https://stackoverflow.com/questions/62732303/how-do-i-pass-values-from-a-hook-into-a-component-rendered-by-a-test

It seems like a trade off between either mocking the hooks props, or going up the tree to call render, then querying for the component to be tested.

Is there anything better?

**Comment by kentcdodds** [comment]
Hi @hanhanhan,

I have two blog posts that you might appreciate :)

- https://kentcdodds.com/blog/react-hooks-whats-going-to-happen-to-my-tests
- https://kentcdodds.com/blog/how-to-test-custom-react-hooks

I hope those help. Good luck!
