### ISSUE TITLE
What were the features you were missing in buttondown?

### ISSUE THREAD

**Issue by vvo** [kentcdodds/ama#835]
Hi there, I just started to use buttondown (for https://nextjsnews.com/), mostly because I knew you used it at some point. Now I see you moved to another platform (https://convertkit.com/) and I am just wondering: at which point, for which features did you move? Thanks!

(Also saw https://twitter.com/_benmccormick/status/1084977748471435267 but was curious about the details)

**Comment by kentcdodds** [comment]
Hi @vvo,

I answered this during office hours today: https://www.youtube.com/watch?v=ph_dQoIKzoY
