### ISSUE TITLE
JSDOM doesn't dynamically provide the clientHeight

### ISSUE THREAD

**Issue by mjangir** [kentcdodds/ama#837]
Hi Kent, first of all, many many thanks for your huge contribution to the dev community and special thanks for enlighten us on testing in JavaScript.

I'm having a problem with dom testing. I've a text truncate component in React which dynamically calculates the client height of its div when a new text is appended. In browser, we get the client height properly on each line append. But since I'm using jest (which comes with jsdom as a dom manipulation library), my component doesn't work properly as jsdom doesn't actually render the dom elements in document and hence clientHeight is not calculated.

Could you please help me a bit. Thank you Kent.

**Comment by kentcdodds** [comment]
Hi @mjangir,

Yeah, there's pretty much no reasonable way to test this kind of thing with jsdom (you can do [some mocking](https://github.com/downshift-js/downshift/blob/01b7dad511d73a2aff5c09792ee9b983ae668bb9/src/__tests__/utils.scroll-into-view.js#L84-L115), but it's pretty imperfect), so I suggest using Cypress for testing those kinds fo things.

Good luck!
