### ISSUE TITLE
3-Part Question: How Do You Create A Podcast?

### ISSUE THREAD

**Issue by ajsnetiker** [kentcdodds/ama#84]
**Part 1:** Do you need specific "podcast software" to record and export the audio, or is a program such as GarageBand sufficient enough?

**Part 2:** How do you add an episode to iTunes?

**Part 3:** How do you maintain your feed so iTunes can display a list of _all_ available episodes?

**Comment by kentcdodds** [comment]
Hi @ajsnetiker! Thanks for the question :-D

**Part 1:** Part of the reason that my podcast is on Google+ Hangouts on Air is because I don't have to do anything special to record the podcast. It automatically goes up to YouTube immediately afterward. Then I download the MP4 and pull the audio off of that. But if you're not keen to do a live show and would prefer to do editing, you might ask @cmaxw or @ladyleet what they do for that. I was just on @ladyleet's show, Modern Web, and we all just recorded our sound on our individual computers using QuickTime, then sent the file to her.

**Part 2**: I use a service called [podbean.com](http://www.podbean.com/). It's not too expensive and it provides everything I need to be able to [submit the podcast to iTunes](https://www.youtube.com/watch?v=pXc7WCq_25c).

**Part 3**: That happens automatically after you add your podcast RSS feed to iTunes.

Good luck!

**Comment by ladyleet** [comment]
Hi @ajsnetiker ! :) I use garage band and I use podbean and publish to itunes through that. ;) Just set up itunes after I switched over to podbean after I saw that @kentcdodds was using it :) Was on soundcloud before but podbean is way better.

**Comment by kentcdodds** [comment]
Another thing to think about is a new service that I'm starting to really love: [briefs.fm](https://briefs.fm). I've got [a podcast](https://www.briefs.fm/3-minutes-with-kent) on there :-) It's a unique approach to podcasting and I think it's pretty neat.

**Comment by ladyleet** [comment]
@kentcdodds haha one thing at a time for me! haha :)

**Comment by ajsnetiker** [comment]
:+1: Thanks @kentcdodds and @ladyleet! 

Using briefs.fm sounds like a good place to start. I'm not 100% sure what I want to do yet, but I had an idea pop into my head that could work out and might make the learning process easier for people. I'm trying to make more of a contribution rather than sitting back and hitting 'apply' trying to land a job, so I have something to show for the gap between full-time jobs. That's why I started looking into conferences, where I found @kentcdodds in the first place! I'll let you know what I end up doing.

**Comment by kentcdodds** [comment]
Note: briefs.fm is a bit of a different kind of podcast. It's like twitter where other podcasts are like a full blogpost (or pamphlet). I like it a lot though, so enjoy!

**Comment by ajsnetiker** [comment]
That sounds perfect! I want to start out slow, but again my goal is mainly to do it so people know my name and to make a contribution. I just went to your site and see you use Medium for your blog, and I intend to do the same thing and already have enough for my first article. I was about to add WordPress to my site, but Medium believes in creating a value network and it's much more high-trafficked than my website will ever be.

On a radio show, someone once said "I don't care what you do, just be the best at it." And that's my goal. I'm inspired every time somebody wins an award, or knows enough to be a speaker at a conference just like you, @kentcdodds, or when YouTubers find a way to get tons of followers. That's my goal - and everybody like you who got there **distributes content**. in one way or another. To make a career mean anything, it takes more than knowing a programming language and a computer, so that's what I'm doing.

Thanks again for the advice .. you've been an awesome contact to have, and again that's exactly why I started looking at conferences to begin with!

I'm sure when you think about it, a majority of developers _are_ just great programmer and employees of company XYZ, but that just makes my chances even better. I may never even be as great as many people, but if more of them know who I am then I'll at least have the opportunity to learn.

**Comment by kentcdodds** [comment]
Good luck to you in your goals there @ajsnetiker. I just gave [a talk](https://github.com/kentcdodds/talks#zero-to-60-in-software-development-how-to-jumpstart-your-career) at ForwardJS you might find interesting. The video recording should go up pretty soon hopefully.

It's all about providing value to the community. You give to the community, and they give back to you. Good luck!

**Comment by ajsnetiker** [comment]
Thanks @kentcdodds . I have an appointment to talk to Ben tomorrow to get set up with briefs.fm, who actually found this thread earlier. I'm also signed up with a free PodBean account to try it and I'm about to do a test and see what happens.
