### ISSUE TITLE
What resources do you use to keep up to date on the direction of the industry?

### ISSUE THREAD

**Issue by blackjackkent** [kentcdodds/ama#853]
Hullo! 

I'm interested in becoming active in the talk/workshop scene for web development (and React in particular) as I really enjoy teaching other people and demonstrating new technologies. However, I've noticed that the people who are very successful in this area seem to be very much on top of all the cutting-edge developments and know what's coming and are able to talk about it early - for instance, you mention in an answer to another question on here that you were reading the Webpack docs when it was still in a very early stage.

What sort of resources do you find most valuable for staying up to date and figuring out what subjects are most useful for your audience?

Thanks so much!

**Comment by kentcdodds** [comment]
@blackjackkent,

The trick with being on the cutting-edge is you're often working with stuff that's not well documented and no tutorials exist. So I spend a lot of time looking at the source code and making demos/experiments. I'm afraid I don't really have specific resources to use other than GitHub 🤷‍♂️

As for:

> figuring out what subjects are most useful for your audience?

I don't. I focus on what interests me. More on this: https://twitter.com/kentcdodds/status/1318772932844285953

I hope that helps!
