### ISSUE TITLE
Thank you so much and question about setting up a project.

### ISSUE THREAD

**Issue by yanisurbis** [kentcdodds/ama#86]
I want to start with a dollop of gratitude for everything you've done for JS community (repos, medium posts, egghead series, JSAir podcast, youtube screencasts and performances); it's so vital and significant. I mean, I've never seen in my life such kind and supportive people. I think you should probably give a speech at some conference (TED would be great) about what makes JSC so great, how it encourages learning, innovate education and what another can do to create such.

And the question is: Where can I find information how to set up and manage open source projects. In the last episode of JSAir, you talked about how beneficial is to have ESLint and how it helps. Today earlier I've found great repo (https://github.com/joebew42/study-path), It's answering some of the questions, but it probably can be improved (there is no word about app architecture). Do you have any suggestions? 

P.S.: I am not a native speaker, so please sorry for typos.

**Comment by kentcdodds** [comment]
Hi @yanisurbis,
Thanks for your question and your kind words!

For getting a new project started, I have a free series of lessons on Egghead.io: http://kcd.im/write-oss

For managing the project long-term, I'm giving a talk at [Space City JS](http://spacecity.codes) this year about that. Will be available later.

And you might also be interested in [this](https://medium.com/@kentcdodds/introducing-how-to-contribute-to-open-source-be67917eb704)

Good luck!
