### ISSUE TITLE
Javascript Logging Library in browser

### ISSUE THREAD

**Issue by sarod** [kentcdodds/ama#87]
Hi Kent,

I find that angular $log is quite limited and I always end up in one of the following situation:
* spending lot of time commenting out log statements.
* being drown in logs

Coming from a java background I would like to find something equivalent to log4j to be able to enable logging only for parts of my app.

What strategy do you use for logging?
Do you have a goto logging library or maybe a list of recomendations? Do you use directly angular $log?
If using $log how to you handle the enablement of logs for a particular service or controller?

Cheers
-Seb

**Comment by kentcdodds** [comment]
Hi @sarod,
Thanks for the question. I actually don't do Angular anymore. But on my last project, I used a custom logger abstraction that I created called [`echo-logger`](https://npmjs.com/package/echo-logger) which worked out pretty well for me, but I don't know whether I'd recommend anyone else use it.

Honestly, I don't have a good recommendation for you. You might consider just continuing using `$log` and disabling it in production or something: http://stackoverflow.com/a/15582227/971592

But anytime you're looking for a good library, I recommend you check out [libraries.io](https://libraries.io/) it's awesome.

Good luck!
