### ISSUE TITLE
How did you get so active in the community in a short time? 

### ISSUE THREAD

**Issue by lukeschunk** [kentcdodds/ama#91]

**Comment by kentcdodds** [comment]
Hi (again) @lukeschunk! Thanks for the question :-)

You might want to take a look at #89. It's pretty related. You may consider hitting the "Subscribe" button because I plan to post a link to my talk recording there when it's been uploaded.

Let me know if you have any other questions :-)

**Comment by kentcdodds** [comment]
My talk was published. Hope it's helpful to you :-) https://youtu.be/-qPh6I2hfjw
