### ISSUE TITLE
What is your opinion on AVA vs Wallaby?

### ISSUE THREAD

**Issue by thelambdaparty** [kentcdodds/ama#95]
Hi Kent!

Wanted to know your opinion as you have more experience with AVA.

Does AVA have advantages over Wallaby (+ Mocha)? 

I was very impressed with the performance of Wallaby, and setup was much easier than with Karma, worked out of the box with Webpack, Mocha and Babel. By what i read AVA is also very fast.

Thanks!

**Comment by kentcdodds** [comment]
Hi @thelambdaparty,
Thanks for the question. Honestly, I haven't set up Wallaby yet :-/ But I imagine that you may be able to get them to work together (somehow?).

Honestly, AVA is about more than just performance (it is crazy fast and that's cool) but there are a lot [more benefits](https://github.com/sindresorhus/ava/tree/8d47119458e83d3899683ad3ea3a4c1c01b7dd49#why-not-mocha-tape-tap) to using AVA over other frameworks.

When I start looking into Wallaby, I'll try to make it work with AVA. If I can't then I wont use Wallaby :-(

Thanks!

**Comment by ArtemGovorov** [comment]
@kentcdodds @thelambdaparty Here you go http://dm.gl/2016/04/26/wallaby-sublime-electron-ava/#ava-support

**Comment by kentcdodds** [comment]
This. Is. Amazing!!! Thank you @ArtemGovorov! I'll definitely be giving it a try now!

**Comment by kentcdodds** [comment]
@ArtemGovorov, I tried last week with Atom and it said `ava` wasn't supported. Do I need to wait for an update?

**Comment by ArtemGovorov** [comment]
@kentcdodds It should automatically update in Atom (normally after a few minutes). Try [forcing the update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), this should help. If there's still some error message, please let me know.

**Comment by ArtemGovorov** [comment]
@kentcdodds I have also put this sample repo together that may be helpful: https://github.com/wallabyjs/ava-sample
