### ISSUE TITLE
How Do I Submit a PR to Fix a Specific Issue?

### ISSUE THREAD

**Issue by geirman** [kentcdodds/ama#97]
Let's say I'm reviewing the issues of an interesting github repository and I find one I'd like to fix. I follow your [outstanding egghead.io tutorial](https://egghead.io/lessons/javascript-introduction-to-github), make my code change, prepare the PR, and submit it. How do I marry that PR to the Issue so that anyone reviewing the issue will see that a PR was submitted to fix it?

**Comment by kentcdodds** [comment]
Thanks for the question! You can reference issues using `#5` for example. You can even have those issues closed automatically when the PR is merged: https://help.github.com/articles/closing-issues-via-commit-messages/
